### ISSUE TITLE
Bug in iron-query-params.html

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1]
There is a bug in iron-location/iron-query-params.html because of which `app-location` does not accept any query-parameters. I fixed this by substituting this:

```
       paramsObject: {
          type: Object,
          notify: true,
          value: function() {
            return {};
         }
```

by this:

```
       paramsObject: {
          type: Object,
          notify: true
         }
```

But it can be overwritten again with the next bower-install until the Polymer team have fixed this. So just to be aware that if query parameters are not accepted, this is most likely the case.

**Comment by SamaneriVimala** [comment]
Bug seems to have been resolved in Polymer 2.0
