### ISSUE TITLE
Dhammapada translations

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1005]
https://discourse.suttacentral.net/t/english-translation-of-chinese-dharmapada-t211/9477/5?u=vimala
https://discourse.suttacentral.net/t/english-translation-of-chinese-dharmapada-t211/9477/10?u=vimala

Various early Dhp translations, including in Latin, are available on Archive.org

**Comment by SamaneriVimala** [comment]
Some of them are being done by Ayya Kathrin.
Sabbamitta is doing the Latin.

**Comment by SamaneriVimala** [comment]
Ayya Kathrin has done French, Portuguese and Catalan.

**Comment by SamaneriVimala** [comment]
More DHP translations reported by Volker.
https://discourse.suttacentral.net/t/chinese-tibetan-dharmapadas/8545/29?u=vimala
