### ISSUE TITLE
Error referencing suttaplex-page

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#1015]
Somehow there is a 404 error for a “elements/static/suttaplex.page”. It is referenced from the sc-static-page-selector. I've seen this problem before. What happens is that you are on a static page and you want to go to a suttaplex. So it starts to look for that from the page where it is at rather than from the top and cannot find it there.

**Comment by SamaneriVimala** [comment]
Done

**Comment by SamaneriVimala** [comment]
Same error for Search ... still to do.

**Comment by sujato** [comment]
Is this still current? I'm not sure what error I'm looking for. @SamaneriVimala

**Comment by SamaneriVimala** [comment]
@sujato there was a 404 error in the console. In the front of the site itself you could not see anything.
You can still see the error in the console when you go from a static page like the homepage to a suttaplex page via the menu on the main, live, site (which has not yet been updated).

**Comment by SamaneriVimala** [comment]
Anyway, 404 error has been fixed.
