### ISSUE TITLE
Make universal SC reference looker-upper

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1019]
Okay, so we used to have a cool widget on D&D that would convert a reference to a SC link, complete with info and stuff. That has broken on the upgrade, and should be reintroduced. But why don't we do it by INCREASING THE AWESOME!?!  :100: 

So the bible peeps have this thing:

https://labs.bible.org/NETBibleTagger/

Throw the js on your site, and when anyone writes a bible reference, it will pull in the exact quote for that passage. Neat, huh? Pretty much the same thing that we do/did, but it can be used anywhere.

So, why not do the same thing, but leverage the power of web components? We can build it out of LitElement so it's not dependent on polymer. Then anyone can just throw it into their forum or whatever and bingo presto! It will pull up refs, quotes, and stuff for SC.

If only we have an element that brings together all the information in a portable way …. Hey! We do, it's called a suttaplex! So the widget can call up a suttaplex. Optionally, if a segment is specified with a #, it can include the text for that segment.

**Comment by Aminah-SC** [comment]
Splendid! What specific steps does bring this into fruition require?

**Comment by sujato** [comment]
I'm not really sure, we'll have to talk about it with the devas. But my understanding is that over time we will gradually rebuild all our elements on LitElement. Making a universal looker-upper gives us a chance to do this with the suttaplex, one of our most complex pieces of UI. I am thinking that we can use the same LitElement based suttaplex on our site, and, with some jiggery pokery, make it into a universal element.

How much work does this involve? Not a clue! So if one of our devas wants to take it on, great, otherwise we can see if Kuba or Hubert can do it.
