### ISSUE TITLE
Transcribing Hinuber Nepalese Cullavagga fragment

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#1025]
Myself and @sujato will transcribe the Nepalese Cullavagga fragment and then compare the two and this will be used as a showcase for other texts.

**Comment by sujato** [comment]
Note that Ven Sunyo has agreed to do the typing. He is going to Holland next week and will set up Atom there.

**Comment by SamaneriVimala** [comment]
I have typed it up, but not checked it. Also updated the Readme file.

**Comment by SamaneriVimala** [comment]
Check this in repro:https://github.com/sujato/bendall-cv
