### ISSUE TITLE
Segmenting of CullaVagga

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#1041]
Segment Cullavagga (and rest of the Vinaya) for Ajahn Brahmali to be able to do his translations directly in there.

**Comment by SamaneriVimala** [comment]
Sabbamitta (Mahavagga) and Tara (Culavagga) are working on this.

**Comment by SamaneriVimala** [comment]
HTML from IB Horner's files still needs to be added as well as the reference numbers therein.

**Comment by sujato** [comment]
consolidate
