### ISSUE TITLE
Pootalization of Ajahn Brahmali's Vinaya texts

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1044]
**Note: the issues re the Vinaya pootlization are out of date with the current state of the project, so I consolidate them here.**

### Stage One: Get everything on Pootle

A large part of initial work was done by Vimala, subsequently by Sabbamitta and Tara. 

For details see ongoing discussion thread:

https://discourse.suttacentral.net/t/notes-on-the-segmentation-of-pali-vinaya-with-brahmalis-translation/10665/1 

- Bu-vb and Bi-vb are done
- Kds are about half-way.

### Stage Two: Adapting to new JSON format

Once everything is on Pootle, I will take it offline and work over the files for consistency. At least two different approaches to creating them have been used, so I will make it all consistent, accurate, and complete.

Once the PO files are nice, we can transform them to the new JSON standard.

### Stage three: review text in Bilara

While a good deal of proofing and correcting is being done during the work, further proofing and ongoing work will be needed. This will be in Bilara, not Pootle.

**Comment by Aminah-SC** [comment]
@SamaneriVimala just to note, I closed #900 you asked me to open as this Epic is more current, but in case any of the tasks from that ticket are still relevant I'll duplicate them here:
* add texts to Pootle
* test texts on site after uploading
* test links in texts
* teach Ajahn how to make changes in Pootle
