### ISSUE TITLE
Dutiya-Parakkamabābhu Cullavagga transcription

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1050]
I have made a proposal for the digitization of the 13th century manuscript of the Cullavagga that sits in the Colombo National Museum. 

Currently the files live on my personal repo: https://github.com/sujato/cullavagga

Since it will be a collaborative project with SC as one partner, when the time comes we will create a dedicated repo for this.

**Comment by Aminah-SC** [comment]
Note from a dev meeting: diff checking should be part of this project.

**Comment by sujato** [comment]
This project is still ongoing, typing is nearly half way through. There's no real need to keep it as an issue here though, so I'll close it.
