### ISSUE TITLE
"Rockhill" search query results duplication   

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1061]
A search for "Rockhill" returns two listings for each varga of Rockhill's translation of Udānavarga. One correctly links to the text (eg. https://suttacentral.net/uv-kg10/en/rockhill), one leads to an outdated link and gives an "Internal Server Error" (eg. https://suttacentral.net/xct-uv10/en/rockhill).

Additionally, a search for "Udānavarga" leads to peculiar results.

**Comment by SamaneriVimala** [comment]
Hi @Aminah-SC . Sorry I did not make myself clear. This is not the issue. The issue I wanted to make a ticket for was the search results that only show "udanavarga". The duplication is only a result of the database not having been restarted when the filenames where changed. So best to put it on the agenda for next meeting so as to remind him that he does that with the next site update. In any case, I checked the search results and this issue has been solved on the master branch together with the changes I made there last week. I will update it to staging today.
