### ISSUE TITLE
Find languages

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1078]
One of the hard problems—arguably *the* hard problem—that SC tries to solve is *findability*. We’ve got so many texts, how do you get what you want?

A specific example of this is, how do you find translations in your language? This is a bad problem with the current UI. It’s not too bad if you’re using English, or some other well-represented language, and if you stick to well-known collections. But what if you are looking in a language with only a few texts? Or if you want to explore some of the more obscure corners.

Here I propose some UX improvements to address this.

## “Languages” Page 

Provide a more informative UI for the user to see what languages and translations are available on SC. Currently people get very confused. If we say, "we have translations in 40 languages", they think, "we have translated the entire canon into 40 languages", which of course is very far from the truth. This page will let them see an overview of what is there and what is missing.

https://github.com/suttacentral/suttacentral/issues/1080

## "Language" Pages

Note the use of plural! These give a more detailed overview of the texts that have been translated in any of our languages.

https://github.com/suttacentral/suttacentral/issues/1243

## Add all languages to "choose language" dropdown

Keep the current implementation of language choosing (for now), but add all languages to it.

https://github.com/suttacentral/suttacentral/issues/1249

## "Choose Language" prompt

Since a user may not know they have the option to choose another language, we can prompt them at an appropriate time. This is done via a one-time popup modal, which is activated only when there is an indication from the user that they may want to use a language other than English.

https://github.com/suttacentral/suttacentral/issues/1184

## Yellow Brick Road 

Provide in the sidebar an explicit indication of where the user can find translations in their own language.

https://github.com/suttacentral/suttacentral/issues/1079

## Rollout l10n

In addition, I will include under this epic the rollout of l10n for completed languages, namely Chinese and Portuguese.

https://github.com/suttacentral/suttacentral/issues/1166

**Comment by SamaneriVimala** [comment]
Like on the old site we had something like https://legacy.suttacentral.net/fa, which would tell you immediately the one translation in Farsi we have.
