### ISSUE TITLE
Yellow Brick Road

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1079]
https://github.com/suttacentral/suttacentral/issues/1078

As in “follow the”. The idea behind this is that we highlight menu items in a distinctive way to guide a user to their destination.

Let us use a "grren dot" (see below).

![c16185560475db2e8502400a6242915615368391](https://user-images.githubusercontent.com/6112010/42686032-445efbce-86c7-11e8-9e0e-85490be8ec4c.jpg)

So this is how it works. Let’s say you’re a Klingon. You’ve been a dedicated soldier of the Klingon empire, but lately you just haven’t been feeling it. Why do we have to have this incessant war with the Federation? Can’t we find peace somehow? So you come to SC looking for a little intergalactic harmony. And yes! We have the Discourse on Loving Kindness in Klingon. But how would you know that? You follow the Yellow Brick Road!

![follow_the_yellow_brick_road_by_ashlee751-d4xsqlo](https://user-images.githubusercontent.com/6112010/42686044-4ad6b62c-86c7-11e8-8727-385e42d6be82.jpg)

Let us follow the journey of our hero on their path. They choose "Klingon" for their site language. In the sidebar, we see that "sutta" has a "green dot" on the expander.

![screenshot from 2018-12-14 21-01-22](https://user-images.githubusercontent.com/6112010/49997549-fbafdb80-ffe5-11e8-961a-987491dd0df9.png)

This is neat, I think, because it clearly indicates the action required. There's something exciting under the green dot—namely, suttas in Klingon translation! Click on the green dot and you see this.

![screenshot from 2018-12-14 21-02-16](https://user-images.githubusercontent.com/6112010/49997669-4fbac000-ffe6-11e8-82d6-036c1a588ed5.png)

More green dots! The original green dot has vanished, as it is no longer needed, and two more are revealed. There are Klingon translations in the "long" and "Linked" sections. Click one of them!

![screenshot from 2018-12-14 21-02-40](https://user-images.githubusercontent.com/6112010/49997751-8395e580-ffe6-11e8-97d1-8540e7f495a9.png)

Clicking the "Long", it expands that section. The green dot on "Linked" remains unchanged. Here the green dot appears on the sidewards arrow rather than the downwards expander, but the message is clearly the same. Click it!

![screenshot from 2018-12-14 21-08-12](https://user-images.githubusercontent.com/6112010/49997828-bcce5580-ffe6-11e8-8bc2-e10edf8faa13.png)

Now we're at the lowest level, so there are no more arrows or expanders on the right. But still, there is a green dot, which now is plain green. (I know it looks different than the other dots, this is just my poor graphics skills; it should be the same, just lacking an icon.) 

![dorothy-and-toto-for-the-lovely-mackenzie-3-toto-the-wizard-of-oz-17564699-500-400](https://user-images.githubusercontent.com/6112010/42686095-74e25458-86c7-11e8-9bfa-0cb1624fcf50.jpg)

At each level, the highlight is displayed at the *lowest level* that contains translations in your language. Thus it is always leading you on to go towards the texts that you can read.

**Comment by sujato** [comment]
Just you wait until the second part of my thrilling two-part series!

**Comment by SamaneriVimala** [comment]
Sorry, I'm a Vulcan and don't understand Klingon-logic. Looking forward to the sequal: Yellow Brick Road - The Final Frontier.

**Comment by sujato** [comment]
basic implementation is done, further details for other issues.

**Comment by sujato** [comment]
I am re-opening this issue as there is still critical functionality missing. Essential functions to be fixed before launch:

- Submenus must show green dot
- Previous level dot must disappear when you open the next level

Both of these as per spec and examples above.
