### ISSUE TITLE
Create compact view

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1082]
The current view uses rather a lot of space for each sutta, especially in the suttaplex lists. For power users, or just people who like information-density, having a more compact view would be better.

I propose we do this by making some simple adjustments to the suttaplexes, viz:

- Remove "blurb".
- Remove space between suttaplexes
- Make main suttaplex title smaller (same size as title for parallels).
- Maybe squeeze some padding.

These changes should be pretty simple, and allow displaying maybe twice as many suttas per screen. 

## UI

Add as option to the Settings dialog.

**Comment by SamaneriVimala** [comment]
Been playing around with this a bit. 

![screenshot from 2018-07-17 11-29-07](https://user-images.githubusercontent.com/7444824/42808972-b8fa5ede-89b4-11e8-8b6e-ac1fd7cec83a.png)

The suttaplex on the sutta-pages remains the same as it was. 
I have not added a button for this yet. Should be pretty simple to add: it only has to swap classes.
Let me know what you think. Uploaded to test-list-view branch.

**Comment by sujato** [comment]
Oh, very nice, it's pretty much exactly what I was thinking. Having the refs on the Title line saves even more space!

Maybe take out the "Translations" and "More" badges? Currently they are a little cramped, and a "compact" user is not likely to need these.

And keep the titles in Serif font, they will stand out better. But apart from that, I'd be happy to roll this design as a feature.

I'm not thrilled about putting any more icons in the toolbar, as it is way too crowded on mobile screens already. In fact I'd like to take some icons away (lotus Home icon, I'm looking at you!).

By "Settings", I was thinking of my proposed Unified settings dialog, I should have made that clear:

https://github.com/suttacentral/suttacentral/issues/1081 

If we go ahead with that, we should put the compact view setting there.

If we don't do the Unified Settings dialog, or if that takes some time to get implemented, we can put compact view selector next to the theme chooser on the toolbar vert-menu.

**Comment by SamaneriVimala** [comment]
I had a look at the settings-menu proposal. I like that but will take some time to implement so not for now. 
I will put it in the vert menu but are the two icons i used for it okay?

**Comment by SamaneriVimala** [comment]
Okay, done this. Please have a look at the new design (for now, until #1081 ) has been implemented.

**Comment by sujato** [comment]
I agree, we can implement this now and leave the new setting UI for later.

It's looking good, may I request a couple of changes:

1. I asked for the -subheading size for the titles, but on seeing it, it's too small. Let's go for the next size up, `--paper-font-title`.
2. For the UI, in MD, when toggling between two states, use a toggle switch, the same as the theme chooser. And the "Toggle menu vew" should be "Toggle compact view". Incidentally, we should change the text on the theme chooser. So the two become:
  - Toggle dark theme
  - Toggle compact view

**Comment by SamaneriVimala** [comment]
It didn't take as long as I expected. When does anything actually work the first time you try it? Anyway, it did in this case. I also changed the display a bit for use on mobile phones because I got tired of the parallels-icon falling off my screen all the time. (Passana also reported this before)
