### ISSUE TITLE
Blank Home page

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1085]
Intermittent bug reported by some users:

https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/320

**Comment by SamaneriVimala** [comment]
Seems to have something to do with Sentry? Seems a bit odd. Maybe deactivate Sentry and see if the bug re-appears.

**Comment by Aminah-SC** [comment]
Pending launch of the P3 site on Production. No action required for now.
