### ISSUE TITLE
Suttaplex display bug on mobile screens. 

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1089]
Sutta info spills out of their cards on mobiles as per below:

![screenshot_2018-07-26-19-04-01](https://user-images.githubusercontent.com/36522678/43277613-737d93c8-9100-11e8-9727-bfd6417ecb89.png)

**Comment by SamaneriVimala** [comment]
Only seems to happen in compact view so will have to look at that.
