### ISSUE TITLE
Swath preprocessor for Thai

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1103]
@sujato commented on [Mon Jul 17 2017](https://github.com/suttacentral/legacy-suttacentral/issues/207)

As per this Discourse thread, we should use Swath to preprocess all Thai text. 

https://discourse.suttacentral.net/t/smart-word-analysis-for-thai/5833/3

**Comment by sujato** [comment]
Closing, because when implemented it did not offer a meaningful improvement and in some cases of Pali names made the breaks worse.
