### ISSUE TITLE
Pack it and shake it

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1105]
Two basic aspects:

- Basic setup
- Advanced setup

-------------------------

Mentioned by Hubert as one of the key advantages of P3, use of a bundler such as Rollup or WebPack allows the app to be cleanly packed and supports tree-shaking. Hopefully this will result in smaller bundles and a faster app.

There are a bunch of similar libraries, we should use whatever the devs think is best.

The goal should be to reduce code size as much as possible.

**Comment by Aminah-SC** [comment]
As per a team meeting on 19/11/18 it was decided that neither of these steps were best suited to this project.

We already have something that is basically equivalent to Webpack, from Polymer (which already bundles things, although it does have limited build options). Also Webpack will become less relevant going forward. However, we could _possibly_ use Webpack for just the import libraries.

Tree-shacking is typically used for apps built with eg. Angular or React, but SC more or less uses what it has and doesn't have so much code to remove (in cases where stuff could be removed they're written in). However, may be worth checking.

**Comment by sujato** [comment]
Note that the decision recorded by Aminah above was later reversed and we went ahead with webpack.
