### ISSUE TITLE
Search UI should show last search term in text field

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1112]
See comment here: https://discourse.suttacentral.net/t/search-improvements/10175/24

This is a problem I have also noticed and it should be fixed. 

> In the results, show the search field with the previous search text filled out, with a button to resubmit. Right now you have to go back up, click the icon in the header, and re-type your search. IMHO that’s a really confusing path, and when you don’t get the results you want it’s extra-discouraging to find that your search isn’t in the field and has to be copy-pasted. Having this field at the top of results also gives you a perfect place to add documentation and/or filtering tools.

Currently when you enter a search, the search field retracts and the search item disappears. This is an example of an anti-pattern that arises because of not responding to explicit user requests.

Instead, keep the search field open when a search is entered, and retain the search term in the field. Then if someone wants to change the spelling or enter a new search, it is right there already.

The search field should only close if a user requests it, or if they go to a new page.

- **Keep search field open with search term retained when a search is entered.**

**Comment by ihongda** [comment]
![Peek 2019-06-14 21-25](https://user-images.githubusercontent.com/4037966/59512340-19092800-8eeb-11e9-945b-e87278e748d0.gif)
