### ISSUE TITLE
404 pages are soft 404

### ISSUE THREAD

**Issue by olastor** [suttacentral/suttacentral#1152]
Entering a invalid url like https://suttacentral.net/abc123 shows a page with a "Page not found" title and "null" in the browser title. The returned status code is 200, which indicates a success. 

I'm not familiar with the frameworks you're using and if it is possible to set the status code to 404 (since it is a web app). But if it is, it might be a good idea to set a real 404 status code on these pages. 

This is probably not a problem, but it could be relevant for SEO, I think there are cases where such "soft 404" pages could have a negative impact on the Google indexing or ranking.

See:
  - https://support.google.com/webmasters/answer/181708?hl=en
  - http://www.ppctag.com/soft-404-pages-harmful-google-ranking-solution/

**Comment by sujato** [comment]
Good point, thanks for the suggestion.

**Comment by robertmusil** [comment]
It's actually not possible to do hard-404 in SPA

**Comment by sujato** [comment]
okay thanks, well, leave it then
