### ISSUE TITLE
Develop a set of specifications for updating HTML texts to current HTML5 spec

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1161]
We should develop a set of specifications for updating our HTML texts to use the current recommendations for HTML5, while ensuring that the CSS and JS plays nicely.

The HTML spec should be pretty settled on everything by now (when Ven. Sujato was doing the original texts, things like "article" and so on were still very much up in the air).

- First we'd go through the various tags and usages, and determine which needed updating.

- Then we could do it using regexes and push it to Github.

**Comment by Aminah-SC** [comment]
[A list of unique tags found in sc-data/html_text](https://drive.google.com/open?id=1yY2I1ld-q_52jjLq2N2tsbLdumD7vV0U)

([full list](https://drive.google.com/file/d/1VpjadKkAtx2NTNG7N0tYZGYcB4UT785d/view?usp=sharing) - generated with "grep -P -ohr "<.*?>" | sort --unique > ~/Projects/SC/SChtmlTags.txt")

**Comment by Aminah-SC** [comment]
Ven. @sujato 

I've now done a preliminary sweep through `/sc-data/html_text`, pushed to a new branch `html-clean` and opened a pull request it you wanted to have a glance before merging. 

The following have been amended:

```
<!-- gaiji, … -->
<!doctype html>
<!DOCTYPE HTML>
</ p>
</a">
</A>
</blockquotes>
</br>
</H3>
</P>
<504>
<</h1>
<</p>
<a  href="…">
<a class="…" id="…" id="…">
<a href="…"  target="_blank">
<a href="…" target="_blanc">
<a href="…" target="blank">
<a href="…" target='_blank'>
<a href="…" target=blanc>
<A HREF="…">
<a href='http://a-buddha-ujja.hu/Info/Balint-Gyongyi'>
<a href='http://www.accesstoinsight.org/tipitaka/kn/thag/thag.08.01.bodh.html' rel='nofollow'>
<a href=http://obo.genaud.net/dhamma-vinaya/pts/mn/mn.080.horn.pts.htm target="_blank">
<A id="…" class="…">
<A NAME="…">
<a title=’Pali: cetana’>
<blockquote clas="gatha">
<blockquote class="…"<p>
<br />
<br/>
<bR>
<BR>
<div  id="…" lang="…">
<H3>
<hr/>
<lI>
<meta author="…">
<meta charset="utf-8"/>
<meta charset="utf-8">
<meta charset="utf8">
<meta>
<P>
<section class="…"  id="…">
<span <span class="…">
<span class="…" >
<span class="…" title=">
<span class="…" title='…>
<span claass="…">
<span clas="…">
<span style="“text-decoration:" underline>
<table  class="…">
<|blockquote>
```
There were a few other items that seemed obviously not quite right, but I had a question mark over how they were to be handled so have left them for the time being. They are marked with an indent and "??????" in the new whittled down list of unique tags found in `/sc-data/html_text`: 
[SChtmlTags-swp2.txt](https://github.com/suttacentral/suttacentral/files/2574030/SChtmlTags-swp2.txt). They are as follows with the relevant file/s given (line no. correspond to the .txt):

fr/lzh/sutta/lzh-nbs/t1670b/t1670b2.50.html
_Line 45:_ `<2.50 is missing in the English text. The following is included in 2.49 there>`


vi/pli/sutta/sn/sn18/sn18.22.html
vi/pli/sutta/sn/sn18/sn18.21.html
vi/pli/sutta/sn/sn1/sn1.37.html
vi/pli/sutta/sn/sn2/sn2.8.html
_Line 51:_ `<a class="…" id="…" pi>`


fr/lzh/sutta/lzh-nbs/t1670b/t1670b2.65.html
_Line 80:_ `<again 2.65 is missing in the English text. The following is included in 2.64 there.>`

fr/lzh/sutta/lzh-nbs/t1670b/t1670b2.45.html:
fr/lzh/sutta/lzh-nbs/t1670b/t1670b2.19.html:
_Line 110:_ `<end of chapter 2>`
_Line 111:_ `<end of first chapter>`
_Line 93:_ `<chapter 2>`
_Line 94:_ `<chapter 3>`

es/pli/vinaya/pli-tv-bu-pm.html
de/pli/sutta/kn/ja/ja313.html
de/pli/sutta/kn/ja/ja313.html
de/pli/sutta/kn/ja/ja313.html
_Line 112:_ `<font face="Times New Roman">` (used to wrap "ā" character, or troll :smiling_imp:)


pli/vinaya/pli-tv-kd/pli-tv-kd10.html
_Line 159:_ `<span a="…`

pli/vinaya/pli-tv-kd/pli-tv-kd17.html
_Line 160:_ `<span ag="…`

pli/vinaya/pli-tv-kd/pli-tv-kd1.html
_Line 161:_ `<span ariyasaccan="…`

pli/vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pc/pli-tv-bi-vb-pc42.html
_Line 162:_ `<span asa="…`

pli/vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pc/pli-tv-bi-vb-pc35.html
_Line 163:_ `<span bhikkhuvibha="…`

pli/vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pc/pli-tv-bi-vb-pc35.html
pli/vinaya/pli-tv-pvr/pli-tv-pvr17.html
_Line 166:_ `<span class="…" dissati=""…`

pli/vinaya/pli-tv-pvr/pli-tv-pvr16.html
_Line 169:_ `<span class="…" id="…" itip="" kesuci="" ni="" pariv="" potthakesu="" title="…">`

fr/lzh/sutta/lzh-nbs/t1670b/t1670b2.28.html
_Line 194:_ `<The English text is missing chapter 2.28. All the following is included in 2.27 there>`

I'm guessing the Vinaya ones may just about to become moot.

**Comment by sujato** [comment]
Can we move this to Discourse? Github is hopeless for conversations!

**Comment by Aminah-SC** [comment]
Connected: https://github.com/suttacentral/suttacentral/issues/1400

**Comment by sujato** [comment]
Here is a current list of all PTS abbreviations (from uid_expansion). In the past we were somewhat promiscuous in allowing many different forms of PTS number, but this lead to ambiguities and errors. The forms given here are clear and unambiguous. We should make sure the updated texts use these, and all other forms are replaced. I have updated the refs in the various data files.

```
  {
    "uid": "pts-a",
    "acro": "PTS A",
    "name": "Pali Text Society Atthakathā"
  },
  {
    "uid": "pts-cs",
    "acro": "PTS cs",
    "name": "Pali Text Society section number"
  },
  {
    "uid": "pts-vp-pli",
    "acro": "PTS vp pli",
    "name": "Pali Text Society volume and page of the Pali text"
  },
  {
    "uid": "pts-vp-pli1ed",
    "acro": "PTS vp pli 1st ed.",
    "name": "Pali Text Society volume and page, 1st edition of the Pali text"
  },
  {
    "uid": "pts-vp-pli2ed",
    "acro": "PTS vp pli 2nd ed.",
    "name": "Pali Text Society volume and page, 2nd edition of the Pali text"
  },
  {
    "uid": "pts-vp-en",
    "acro": "PTS vp en",
    "name": "Pali Text Society volume and page of the English translation"
  },
  {
    "uid": "vnp",
    "acro": "PTS verse number ",
    "name": "Pali Text Society verse number"
  },
```

**Comment by chansikpark** [comment]
> We should make sure the updated texts use these, and all other forms are replaced. I have updated the refs in the various data files.

Bhante, there's a discrepancy that I noticed while rebuilding the database. Namely, `uid_expansion.json` is used in the data loader and due to a duplicate key, the loading fails. The duplication is on the uid "vns" which both "Vinayanidānasūtra" and "SC verse number" use.
