### ISSUE TITLE
Suttaplex redesign: v2.0

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1162]
# Suttaplex 2.0

## Introduction

Please find here the latest and greatest version of the infamous SC Suttaplex! 

[suttaplex-2.1.zip](https://github.com/suttacentral/suttacentral/files/2604316/suttaplex-2.1.zip)

The suttaplex is in many ways the heart of SC, and contains within it the bulk of our content. The first version of the suttaplex managed to pack all this information together in a usable way, but in hindsight was hampered by an overly-literal interpretation of Material Design. The information is not particularly clear to new people. For example, the texts were confusingly represented partly by buttons and partly in a dropdown, with nothing to distinguish a root text from a translation.

One thing I have noticed is that many people do not understand even basics of our field: the difference between a root text and a translation, for example. Or the fact that a Pali text can have multiple editions.

The SC motto is "Early Buddhist texts, translations, and parallels". The new design implements this very literally, showing each of these as distinct sections.

![suttaplex-2 1](https://user-images.githubusercontent.com/6112010/48843862-508b7800-edd3-11e8-828a-bd23b16e6e29.png)

## What stays the same

The main title, "nerdy row" (with reference data, etc.), and "blurb" all stay exactly the same.

(Note, however, that there are some stylistic problems with the nerdy row: the vertical and horizontal spacing has gotten all out of wack.)

## What changes

The old version had an "action bar" at the bottom of the suttaplex. This is gone, and the parts of it are elsewhere.

The "share" icon has been moved to the top right corner. Otherwise it is the same (the demo is an approximation). 

Next to this is a "volume" icon, indicating audio. This is a link to the appropriate sutta on voice.suttacentral.net. It is worth considering whether to implement palying audio directly in our interface. However, it involves a number of complexities, and at this time It think it's preferable to direct a user to a site dedicated to the audio experience.

If there is a "difficulty" icon, it appears to the left of the "share" or "volume" icon.

There are no buttons or dropdowns (apart from the "share" icon).

## Headings

The various sections are indicated with `<h2>` headings. Each of these begins with a dynamically-generated number. The number and chief "thing" are bolded, the remainder is regular. They are italics to distinguish them stylistically.

## The "Read" list

All texts are represented in what is called a "list" in MD. Note this is not the same as a list in HTML.

The items in the "read" list have three main elements:

1. A "open book" icon on the left. This gives some space and heft to each icon, as well as supplying some color to the card.
2. The "creator" of the text. In root texts, the creator is the edition, in translations it is the translator. Use the full version of the name. 
3. Publication details, consisting of:
   1. The language (preceded by the language icon; the demo just uses the same icon for each one.)
   2. The publication date.

This gives a more dignified and clear representation of each text. The language is explictly stated, and reinforced by the icon. 

The publication date is added where we have it. The reason for this is that generally people prefer to read more modern translations. Currently we don't have the publication date in a data format, so we should create this. If we don't have it, just leave it out.

In addition to this, there are a few stylistic flourishes:

- colored background on hover
- ripple effect on click (not in demo)
- arrow on hover (not sure if this is needed)
- animated ease in/out for hover

## The parallels

![suttaplex-2 1-parallels](https://user-images.githubusercontent.com/6112010/48843868-55e8c280-edd3-11e8-9881-26e69548c274.png)

The parallels tables are mostly similar to how they were before. The main difference is that the dropdown with direct access to texts is removed. This simplifies the logic and reduces the data. Instead, each cell of the table is a link to the main thing represented by that cell.

- In the left column, clicking the cells takes you to the text or relevant portion thereof. Of course, the text itself is already available from the "read" list. The real value added here is the link to portions of the text in the case of sectional parallels.
- In the right column, clicking the cell takes you to the suttaplex for that text. In other words, if the cell is MA 106, the link target is simply `/ma106`.

In addition, there are a few small style tweaks: background and corners are adjusted for a softer look.

The "relationship" icons remain unchanged (these are faked in the demo).

Note that the styling of the parallel cells is similar to the "read" items: title in black serif, secondary info in grey sans-serif, with similar hover effects and rounded corners.

## Compact view

![suttaplex-2 1-compact](https://user-images.githubusercontent.com/6112010/48843880-5d0fd080-edd3-11e8-9209-2d1cc0b786e4.png)

On SC we currently have a compact view for the suttaplex list. This is retained, although the functionality is different due to the limitations of this primitive demo. Clicking the main title hides all but the title and nerdy row. 

In fact, what should also happen is:

- The main title font size is reduced.
- The title and nerdy row go on the same line.
- The first translation is visible by default.

For the demo, the compact view is toggled per suttaplex. But in production, as with the current site, the compact view is toggled for all the suttaplex items. Currently this toggle is in the main toolbar, but it would make better sense to put it at the top of the suttaplex list.

The behavior should be this:

- The view as shown is default.
- When a user toggles compact view, it implements compact suttaplexes universally and remembers the choice.
- When in compact view, click on the title area of the card and it reveals the full view as normal. (Note, this excludes the two icons, which function as normal in compact view; however this does not work properly in the demo.)

## Grid view

![suttaplex2 1-grid](https://user-images.githubusercontent.com/6112010/48844363-95fc7500-edd4-11e8-96c9-3e6fe914b7af.png)

Due to the wonders of modern CSS, it is trivial to implement a grid view as well as a list view. 

This is useful for users with wide screens. One of the disadvantage of the new suttaplex design is that it uses more vertical space: about twice as much space per suttaplex. This can be mitigated for users with wide screens if they can choose a grid view. On a 14" laptop screen, I can see 4 suttaplexes per row.

I propose we implement a grid view. Like the compact view, this would be activated with a toggle at the top of the suttaplex list page. 

We can even get an ultra-dense view by using both grid and compact.

![suttaplex-2 1-compact-grid](https://user-images.githubusercontent.com/6112010/48844455-d6f48980-edd4-11e8-967e-1f0339af2b71.png)

## The demo

This is implemented in pure HTML and CSS, and pushes the limits of such an approach. 

I have used the details/summary elements extensively, actually too much. I would, however, hope that they can be used in production for the "read" list and the parallels. It's probably not a good idea to use them for the dropdown menu or compact view toggle.

In general, we should try to use native HTML/CSS wherever possible. The suttaplex is quite complex, and loads considerable data. If we can reduce the size it is good.

One advantage of using a JS disclosure widget is that we could animate the opening and closing. It'd be nice, and better MD. In the old version we abandoned animation because of iron-list. But maybe we could bring animations back? Unfortunately it is not possible to animate the details/summary widget, at least not in any sane manner.

I would consider this an advantage of a JS approach, but by itself it's not enough to justify it. If there are other good reasons to use a JS widget, then we can add in animation. 

One thing to bear in mind: I would like ultimately to implement the suttaplex as a universal web component. That is, we can make a publicly-available component that people can drop into a site, and it will enable suttaplexes there; a bit like the oneboxes on Discourse. This is another reason it's best to reduce the code size and minimize the dependencies, even if they are used elsewhere on SC.

Note that for the parallels (i) icon, the demo uses details/summary, whereas the production site uses paper-tooltip. The current site also uses details/summary in the nerdy row, in a different context: not for the (i) icon, but for expanding the reference publication details in certain cases. It's always been a bit weird to use both a tooltip and a clickable widget, so I propose we use details/summary for both, and  remove paper-tooltip as a dependency in the nerdy-row. 

## Colors

I have implemented the colors in accordance with me proposed color scheme changes. 

## Naming things

In the demo, I use `tx` for "text" and `ll` for "parallel".

## Production

It is important in the suttaplex to **only get information when requested by the user**. This is because the amount of data in the extra translations and parallels can be quite extensive, many tens of thousands of pieces of data. Most of these things are used quite rarely, and we should not penalize the many for the sake of the few. 

So when the "more translations" or "parallels" are clicked, only then get the data.

The same thing applies with the "share icon", specifically for the "copy table" and "cite" functions. These contain the entire parallels data, so this innocuous and rarely-used icon can contain a huge amount of data. Again, only fetch the data when the user actually requests it. (The "copy link" is not such a problem, as it merely has the ID.)

**Comment by sujato** [comment]
The redesign is live on staging, and mostly it looks terrific. There are a few details of implementation that need to be sorted, let me make a list here.

The following are bugs.

2. In the “nerdy row”, there is a bug in the implementation of the “title” attribute. It should say “SuttaCentral ID”.
3. The `<h3>` headings need to include singular/plural versions for the words “translation(s)”, “edition(s)” and “parallel(s): “1 translation …”, “2 translations …”, etc.
5. The parallels should have a color on hover, similar to the texts and translations.
6. The dark theme doesn’t play nicely with the hover colors. Probably this can be fixed by redefining them as rgba.
7. For the segmented translations, i.e. mine (and soon others!), we should say “English & Pali” instead of just “English”.
9. Compact view does not work.

The following are improvements to be made.

1. Use HTML summary/details instead of divs for expandable sections.
1. Also use summary/details in the nerdy row for the info icon (i) (`<sc-sutta-note>`). Style and behavior should be exactly the same as the `.nerdy-row-summary`. The (i) icon displays by default, the information is revealed on click. 
1. This means we can virtually remove paper-tooltip as a dependency. Let’s finish it off by using a “title” attribute on the “difficulty” icon.
1. Refactor using LitElement.

Note that the `.nerdy-row-summary` and the `<sc-sutta-note>` both appear only occasionally. I think the `<sc-sutta-note>` only appears in parallels (as it discusses relations), while the `.nerdy-row-summary` may appear either in the main nerdy row or the parallels. An example of them both in the parallels is: https://staging.suttacentral.net/dn1. An example of `.nerdy-row-summary` in the main nerdy row is https://staging.suttacentral.net/up3.050. 

The following improvements depend on external factors.

1. “Audio” icon has no target. This awaits the release of voice.suttacentral.net.
8. Dates for translations will be added pending the markup of the data.

**Comment by robertmusil** [comment]
### Cannot reproduce
- [ ] In the “nerdy row”, there is a bug in the implementation of the “title” attribute. It should say “SuttaCentral ID”. 

### Done
- [ ] The \<h3\> headings need to include singular/plural versions for the words “translation(s)”, “edition(s)” and “parallel(s): “1 translation …”, “2 translations …”, etc. 
- [ ] On mobile, the “tx-icon” icon is squashed. Actually the icon should be pure SVG and not need the CSS circle.  
- [ ] One minor stylistic detail: we should remove italics from the \<h3\> headers. They were in the mockup, but currently our fonts do not support bold + italic. This will change next year when we introduce variable fonts. 
- [ ] Use HTML summary/details instead of divs for expandable sections.
- [ ] Also use summary/details in the nerdy row for the info icon (i) (<sc-sutta-note>). Style and behavior should be exactly the same as the .nerdy-row-summary. The (i) icon displays by default, the information is revealed on click.
- [ ] This means we can virtually remove paper-tooltip as a dependency. Let’s finish it off by using a “title” attribute on the “difficulty” icon.
- [ ] Refactor using LitElement.

### To be discussed

- [ ] The dark theme doesn’t play nicely with the hover colors. Probably this can be fixed by redefining them as rgba.
- [ ] For the segmented translations, i.e. mine (and soon others!), we should say “English & Pali” instead of just “English”.
- [ ] Compact view does not work.

**Comment by sujato** [comment]
Here I will note various things that come up with the latest iteration of the suttaplex redesign. Please feel free to split any of these into separate issues if you like, I am just noting them in one place for my own convenience.

- [] In `<h3>` headings, “parallel(s)” still shows plural form for “1 parallels”. Eg https://staging.suttacentral.net/mn47
- [] Font styling is not applied correctly. In SC, all text that appears on the screen must be fully defined with the appropriate mixins. The font styles and sizes have been carefully calibrated to display correctly with the different fonts and languages, etc. In the new suttaplex, font size is applied inconsistently and incorrectly; see the old suttaplex for the correct version. In brief, there are only 3 font sizes that apply in the suttaplex card.
   1. Main title (`font-size: var(--paper-font-headline_-_font-size);`) (Note that currently in staging, font size of the title is specified twice.)
   2. Primary text, including blurb, `<h3>` headings, `.tx-creator`, etc. (`var(--sc-paper-font-body_-_font-size)`) (Currently in staging, this is not specified at all)
   3. Secondary text, including nerdy row, `.tx-publication`, etc. (`var(--paper-font-body2_-_font-size)`)
- [] Related: `.suttaplex-nerdy-row` defines font-weight twice.
- [] `.tx:after` uses a font glyph for an arrow. Redefine this to use an appropriate `iron-icon`.
- [] In certain cases, a translation is mistakenly appearing as a root text. See eg. https://staging.suttacentral.net/dhp. This occurs in cases where a three-letter ISO code is used for a translation.. Normally we use two-letter codes for translations and three letter codes for root texts. However there are certain cases where use of three-letter codes for translations proved unavoidable. See here for a case where texts are said to be the root: https://staging.suttacentral.net/kp9. We need a more reliable means of detecting the root text.
- [] Compact view is not complete; see the discussion in the initial spec, and we will discuss it further.
- [] We can forget about having a distinct color for the original text icon; just use the primary color for all of them.
- [] The (i) icon in nerdy row is still using `paper-tooltip`, it should use details/summary. Eg. https://staging.suttacentral.net/dn1
- [] In the Vinaya parallels (and possibly elsewhere), we are correctly giving the expanded form of the ID in the parallels. However there is a quirk in that for Chinese and Tibetan we are displaying the full names "Literary Chinese" and "Classical Tibetan". These are correct, but not appropriate for the context, which should just say "Chinese", "Tibetan".
- [] In the left-hand column of the parallels tables, we are mistakenly applying text-transform and letter-spacing in `.root-link`. These are a hangover from when these were in a button. As a general rule, these styles are only applied to buttons.
- [] We should consistently inform users of what is *not*. See https://staging.suttacentral.net/ma7. Here, it correctly says "0 parallels in ancient texts". However, there are no English translations, or to put it more generally, no translations in the user's language. But this is not indicated: it just misses out that field. It should say "0 English translations". Similarly, if there are no translations in other languages, it should say so.
- Related: Saying "**2 more translations** in modern languages" is incorrect when there are no translations in the user's language. Let's reword these fields to say:
   - **0 translations** in English
   - **2 translations** in other modern languages

**Comment by sujato** [comment]
A nice touch with the suttaplexes is that when a long list is loading, it shows the vagga and section titles before the actual cards have loaded. That gives you an overview, which is then filled out by the content. I don’t know if this was deliberate or not, but I like it!

**Comment by Aminah-SC** [comment]
Just in case it's relevant, I've closed #1188 as I understand all the info to implement the publication date detail is now there.

**Comment by sujato** [comment]
Note that this issue also pertains to suttaplex:

https://github.com/suttacentral/suttacentral/issues/1214

**Comment by sujato** [comment]
Excellent, almost all the issues are complete. The only outstanding issue is the clean language switch, which I will put in a new ticket.
