### ISSUE TITLE
Fix uid errors

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1165]
The following errors were highlighted by a local build:

```
ERROR:root:Text uids do not match menu uids for (en): an4.304, an6.170, an7.618, an7.645, an8.148, an9.113, an10.229, an10.233, an10.240, an10.267, sn12.93, sn48.137, sn48.147, sn50.67 
ERROR:root:Text uids do not match menu uids for (pli): an4.304, an6.170, an7.618, an7.645, an8.148, an9.113, an10.229, an10.233, an10.240, an10.267, sn12.93, sn48.137, sn48.147, sn50.67
ERROR:root:Text uids do not match menu uids for (zz): zz1, zz2, zz3
```

**Comment by SamaneriVimala** [comment]
zz cannot be changed but the others need changing in pootle so it will have to be fixed in Bilara (I checked and this date this has not been done yet).

**Comment by SamaneriVimala** [comment]
@Aminah-SC - this seems to be fixed now (except for the zz but we cannot change that ... it should give an error as the zz pages don't appear in the menu)
