### ISSUE TITLE
Mentions are not mentioned

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1171]
Reported by Ayya Vimala:

>I just noticed a flaw in our SC design: mentions are not mentioned at all.
>So for instance I have in the parallels list:
> "mentions": ["sn6.9#2","ne37#53"]
>
>But this is neither with sn6.9 nor ne37.

They suggest: 

>Thing to do is to check Arango first to see if they are in there. If they are not, you have a backend problem. If they are, it is either the frontend or the serving of the data to the frontend.

**Comment by SamaneriVimala** [comment]
The main problem here is that the methodology is not correct. The way the data is read and stored is not properly used and some decisions need to be taken about that by Bhante @sujato .

There problem appears for Mentions and Retellings in a similar way but not entirely the same.

**Retelling**
See for instance dn19. There is a retelling in cp5 but there is no icon to show it.
At cp5 the retelling is not mentioned at all.

**Mentions**
See for instance sn6.9 and ne37 as above.

So several questions here for both:

1. What icon and title attribute have to be used for Retelling A --> B (So in this case, what should it look like at dn19?) and for Menion A --> B (at sn6.9)
2. What icon and title attribute have to be used for the opposite (So in this case at cp5 and ne37)

**Comment by sujato** [comment]
Thanks Ayya for the comments, I am just getting around to looking at this. The first thing to do is to make sure the data is loading correctly. Can you please specify exactly what the error is on the back end so @blake-sc can fix it?

**Comment by SamaneriVimala** [comment]
I can very easily change it in the backend and have Blake check my changes in the PR. 
But what I would need to know is how they need to change in the backend based on how the frontend will use the information. So if you can answer the questions above I can proceed.
