### ISSUE TITLE
2018 UPGRADE: COOL NEW STUFF

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1174]
There are a bunch of proposals for doing some cool new things with SC. These can be launched as each feature is ready.

This is the 3rd and final key stage of [SuttaCentral Upgrade Roadmap 2018](https://github.com/suttacentral/suttacentral/issues/1091) to be begun after the completion of the "[Wackamole](https://github.com/suttacentral/suttacentral/milestone/4)" bug fixing mission.

> I will note the current state of each of these (2/1/2019), and group them as "done", "high priority", "minor", and "not yet".

### Audio Support

> Implemented on suttaplex cards. No need for further work at this time.

Some of our friends are making audio files from reading the Suttas. [We can do some cool stuff here.](https://github.com/suttacentral/suttacentral/issues/961)

- Aggregate the audio files on our own servers, ensure a consistent quality, URL, and so on. (Blake?)
- Implement a UI in our suttaplex cards for reading suttas. (STXnext)
- Set up podcasting.
- Set up audio suttas on demand via Alexa, Google Home, Siri, etc.

### Find languages

> Critical update, should be the focus of Cool New Stuff

We have begun the process of localizing the site, and translation teams in Indonesian and Chinese are well under way. However this brings us to one of the problems that we are yet to solve: how are you to find where translations are in your language?

Here I propose [a number of features to assist with this](https://github.com/suttacentral/suttacentral/issues/1078).

### "Books"

> This is a long-standing and much-requested feature, and the coding is almost ready. Let us make this a priority.

A long term desideratum has been the export translations to [PDF for printing](https://github.com/suttacentral/suttacentral/issues/960) and EPUB. In fact much of the back end for this is in place. Let us ensure that this is complete and robust.

### Use Adaptive Tab Bars on (mostly) all pages

The static pages use Adaptive Tab Bars to navigate among a set of related entities at the same hierarchical level. We can extend this UI pattern to other kinds of pages to improve consistency.

https://github.com/suttacentral/suttacentral/issues/1238

### Make universal elements

> We should definitely try to make this work, at least for Bilara and Discourse. But there needs to be a discussion first.

One of the promises of web components is that they can be just dropped in and work anywhere. The lightness of LitElement should make this better than ever. We can look at cases where SC’s elements can be used, not just on SC, but anywhere. Candidates include:

1. Suttaplexes: use SC reference IDs (MN 1, etc.) to call up the relevant suttaplex card (similar to former functionality on Discourse) https://github.com/suttacentral/suttacentral/issues/1019
2. Pali/Chinese lookup

We could use these on Discourse (our forum) and our translation software Bilara, and make them available to other sites. Ideally, any blog, sutta site, discussion forum or whatever could just include the web component and leverage the same functionality.

### Refactor how to get "Home"

Some tweaks in how the Home page is accessed.

https://github.com/suttacentral/suttacentral/issues/1239

### Move "forum" link from toolbar to vert-menu

https://github.com/suttacentral/suttacentral/issues/1240

### Swath preprocessor

Makes Thai text look pretty.

https://github.com/suttacentral/legacy-suttacentral/issues/207

### Table of Contents

https://github.com/suttacentral/suttacentral/issues/914

### Stop sidebar from hating sujato

https://github.com/suttacentral/suttacentral/issues/995

### Flip vert-menu animation

https://github.com/suttacentral/suttacentral/issues/993

### Improve toolbar for static pages

https://github.com/suttacentral/suttacentral/issues/929

### Improving site metadata and documentation via RDF

> So far, no progress on this, we do not anticipate doing it this cycle.

With BDRC, [we have agreed to move towards supplying metadata for texts, etc. via RDF](https://github.com/suttacentral/suttacentral/issues/1028). Two aspects:

1. Put data in RDF format according to the BDRC schema. Start with the new texts created by SC.
2. Implement the data in our UI.
   - Use for texts in the metadata fields.
   - Use for “Language” pages (see next).

A volunteer, Anders, is looking into this. We anticipate it will take some time, and it may well be not ready for this cycle. We wouldn’t expect STXnext to do the RDF part, only the UI.

### <s>Create unified Setting dialog</s>

> Probably trash this one favor of adaptive tab bar proposal, but it needs discussion.

[One settings dialog to rule them all.](https://github.com/suttacentral/suttacentral/issues/1081)

### Improve handling of references

> It looks like we probably won't get around to this one.

Our complex sets of interrelated references make up one of the most powerful yet difficult areas for SC. A number of improvements have been proposed.

1. [Use standoff references in segmented texts](https://github.com/suttacentral/suttacentral/issues/1056).
2. [Simplify front end handling of references by creating three classes for references](https://github.com/suttacentral/suttacentral/issues/1055)
3. Fix incorrect reference handling in certain cases.

Also see:

https://github.com/suttacentral/suttacentral/issues/1013

https://github.com/suttacentral/suttacentral/issues/966

https://github.com/suttacentral/suttacentral/issues/713

### Support comparison of multiple editions of root texts

> Not a strong priority

We are currently engaged in digitizing the oldest Pali manuscripts, from the [9th](https://github.com/sujato/bendall-cv) and [13th](https://github.com/dpcv) centuries. In addition, there are multiple editions of the texts in Pali, Chinese, and Tibetan. Over time, we can add more of these to the site, implementing a convenient way to compare them.

These texts will be segmented. They can be displayed through the Textual Information dialog, which will show them segment by segment as with the translations. In addition, we can implement a diffing library to shows differences between editions.

**Comment by sujato** [comment]
Most of these issues are completed. I will close the epic, as it is no longer a meaningful part of our development process, although some issues remain as stand-alone.
