### ISSUE TITLE
Scrape pali sanskrit and chinese verses to find parallels

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1178]
https://discourse.suttacentral.net/t/adding-new-parallels-to-suttacentral/11300/9?u=vimala

**Comment by SamaneriVimala** [comment]
Written Python program to go through the verses. It is scraping all verse lines and compares them with other texts in the same language. Found quite a few new Sanskrit parallels so far but still a lot of work to go through the whole lot.

**Comment by SamaneriVimala** [comment]
Depends on issue #1215 first.
