### ISSUE TITLE
Research performance issues

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1180]
Performance audit:
* Lighthouse
* Chrome tools 
* manual investigation

**Comment by Bosmanfrx** [comment]
For every update in Redux we save current redux state in localStorage. We should rewrite this `subscribe` to something more sane (as middleware) and only write necessary records to localStorage. During performance testing disabling it sped up site navigation by a factor of 2

**Comment by Bosmanfrx** [comment]
Lighthouse audit seems to be little bugged in recent Chrome version, so this is mostly manual analisys.

1. Fonts we download from Google CDN are not deferred and thus are render-blocking.
2. We can slightly improve our load time by deferring the rest of scripts.
3. It seems that we have massive DOM node count. It's partly fault of `iron-iconset-svg`. We are loading 525 icons into DOM and producing about 1400 DOM nodes. A lot. But I'm not sure if we can do anything with that.
4. We can introduce lazy-loading for images on static pages. It'll let us shave about 500 kb from initial load size for homepage
5. For time being - 500ms seems like hard limit for our bootstrap process. It probably can be improved a bit by rewriting to LitElements.
6. `_addChevronHighlightListeners` touchstart listener could be passive. It'll help a bit with scrolling.

**Comment by sujato** [comment]
I have run Lighthouse audit, here is the data:

[staging.suttacentral.net-20181214T073433.zip](https://github.com/suttacentral/suttacentral/files/2677698/staging.suttacentral.net-20181214T073433.zip)

And some screenshots. These focus on the performance issues, I have left the a11y and other issues off.



![screenshot from 2018-12-14 07-41-52](https://user-images.githubusercontent.com/6112010/49967423-e8b1f280-ff76-11e8-94ae-3e74bf7b4969.png)

![screenshot from 2018-12-14 07-42-28](https://user-images.githubusercontent.com/6112010/49967434-f2d3f100-ff76-11e8-812d-1457c1ada633.png)

See below, we are serving two versions of our Regular font! We need to check and make sure we only serve the latest version of each font. 

![screenshot from 2018-12-14 07-43-27](https://user-images.githubusercontent.com/6112010/49967445-fbc4c280-ff76-11e8-88e3-1797830753b2.png)

![screenshot from 2018-12-14 07-45-30](https://user-images.githubusercontent.com/6112010/49967460-0717ee00-ff77-11e8-9e46-552ea110072d.png)

![screenshot from 2018-12-14 07-45-40](https://user-images.githubusercontent.com/6112010/49967476-0ed79280-ff77-11e8-8e2f-8698b1f895fd.png)

![screenshot from 2018-12-14 07-45-58](https://user-images.githubusercontent.com/6112010/49967489-1ac35480-ff77-11e8-817f-acce5da1de08.png)

![screenshot from 2018-12-14 07-46-15](https://user-images.githubusercontent.com/6112010/49967506-24e55300-ff77-11e8-8a5b-b14fa7fd7e39.png)

![screenshot from 2018-12-14 07-46-25](https://user-images.githubusercontent.com/6112010/49967517-2e6ebb00-ff77-11e8-9a38-ac1afd1bc391.png)

**Comment by sujato** [comment]
And for your convenience, here is a side-by-side of production and staging, so you can see that certain of the issues have already been addressed in the production site.

![screenshot from 2018-12-14 09-53-33](https://user-images.githubusercontent.com/6112010/49972617-5b769a00-ff86-11e8-8030-b97f0a1b3992.png)
