### ISSUE TITLE
SuttaCentral Voice Icon in Suttaplex redesign 

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1189]
Resulting from a meeting (30/11/18) with Robet, Karl and Aminah we outlined the following specs for linking SC with SCV as a first step towards integration:

* SC would link to SCV by making a search call (eg. "mn1"). Once on SCV users can set options to their own tastes (eg. reader, or translation).  
* Only the "search" and "lang" parameters from Karl's [URL Format](https://github.com/sc-voice/sc-voice/wiki/URL-format) will be used. 
* For the time being, only segmented texts would have active audio icons (otherwise the icon will be greyed out with a tooltip noting there is no audio available yet).
* Links will open in a new tab.

**Comment by Aminah-SC** [comment]
A meeting needs to be set up with Karl to figure out linking to the sutta audio.

**Comment by sujato** [comment]
Thanks so much. 

My only question would be, why a greyed out icon? It seems to me that would be okay if we intend to imminently support it, but we don't. Moreover, what of all the other languages? We will probably never get around to covering them all. So it seems to me better to simply have the icon for segmented texts, and not have it in other cases. Or am I missing something? @robertmusil

**Comment by robertmusil** [comment]
We decided to omit the icon if there's no segmented texts.
