### ISSUE TITLE
Update/Replace browser detection when serving application bundle

### ISSUE THREAD

**Issue by janlat** [suttacentral/suttacentral#1197]
Research:

In production, we serve 2 different versions of the application bundle: one for modern browsers, and one for older ones, with new JS features transpiled down to something they can understand.

Decision which one to use is based on reading user's browser version, which is not the most reliable way of doing this, and also requires keeping the config up to date with browser updates.

Proposed solution: try using `<script>`'s `nomodule` attribute. If that doesn't work for us, just update the config.

Modern browsers are defined as how Google define LIT-element (IE and Edge are not of concern).

**Comment by Aminah-SC** [comment]
This ticket will lead to the creation of a new implementation ticket.

**Comment by janlat** [comment]
New ticket: #1229
