### ISSUE TITLE
Vol/page data missing from suttaplex nerdy row in Vinaya when there is a translated title

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1214]
#### Description:

The nerdy row should include vol/page data where available (which it usually is). But sometimes in the Vinaya the vol/page data is missing.

The issue seems to be connected with the type of information present in the nerdy row: specifically, when there is no translated title, the vol/page info appears, but if there is a translated title, the vol/page info disappears.

I noticed this bug in the context of the Vinaya. It doesn't seem to happen in the suttas. But I haven't researched widely.

#### Steps to reproduce:

Here is a typical Vinaya suttaplex list:

https://staging.suttacentral.net/pli-tv-bu-vb-pc

Up to no. 50, the texts have translated titles and no vol/page info. After that, they have no translated titles and the vol/page info appears.

(Note that the reason some have a translated title and some do not is simply because the underlying text is incomplete, so this is expected.)

#### Expected behaviour:

Vol/page is displayed regardless of whether there is a translated title or not.

#### Screenshots:

![screenshot from 2018-12-16 18-29-49](https://user-images.githubusercontent.com/6112010/50051127-c085e780-0160-11e9-8ffb-c7cc87f0b4fd.png)

![screenshot from 2018-12-21 17-31-38](https://user-images.githubusercontent.com/6112010/50328311-b8ee8600-0546-11e9-859f-aed0a8395ea2.png)

#### Scope

So far I have only noticed this in the Pali Vinaya. But the site should be checked to ensure it is not happening elsewhere.

**Comment by robertmusil** [comment]
Cannot fix on this end, the api replies:

`http://localhost/api/suttaplex/pli-tv-bu-vb-pc50?language=en`
```json
[
    {
        "acronym": null,
        "volpages": null,
        "uid": "pli-tv-bu-vb-pc50",
        "blurb": "If, while staying with an army, a monk goes to see the army in action, he must confess the offense.",
        "difficulty": null,
        "original_title": "Uyyodhika",
        "root_lang": "pli",
        "type": "text",
        "translated_title": "The training rule on battles",
        "translations": ['...'],
        "parallel_count": 40,
        "biblio": null,
        "num": 104
    }
]
```
`http://localhost/api/suttaplex/pli-tv-bu-vb-pc51?language=en`
```json
[
    {
        "acronym": null,
        "volpages": "Vin iv 108",
        "uid": "pli-tv-bu-vb-pc51",
        "blurb": "A monk who consumes alcohol must confess the offense.",
        "difficulty": null,
        "original_title": "Sur\u0101p\u0101na",
        "root_lang": "pli",
        "type": "text",
        "translated_title": "",
        "translations": ['...'],
        "parallel_count": 41,
        "biblio": null,
        "num": 105
    }
]

```

Please note that the first one doesn't have `volpage` and the second one has it, thus it's not displayed for the first one and it is for the second one.
