### ISSUE TITLE
Color rework for dark theme for suttaplex

### ISSUE THREAD

**Issue by robertmusil** [suttacentral/suttacentral#1217]
#### Added value:
Dark theme colors need to be discussed and picked so they look nice on suttaplex. Also slight adjustments could be made to the normal colors.

#### Acceptance criteria:
- [ ] Colors changed accordingly
- [ ] The parallels should have a color on hover, similar to the texts and translations.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
We should be able to achieve this by simply adding one color to the mixins:

`--sc-primary-color-light-transparent: rgba(255,203,97,0.3);`

Use this for hover on the suttaplex cards.
