### ISSUE TITLE
Staging serves extra unnecessary font

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1221]
#### Description:

Staging is currently serving an unnecessary font, Noto Sans. This is not served on production. 

#### Steps to reproduce:

Load a page. Make a cup of tea while downloading the useless font!

#### Expected behaviour:

Only load necessary fonts. For Latin-like languages, that should normally be just the Skolar (reversed as raloks in our font naming system!)

#### Screenshots:

![screenshot from 2018-12-18 10-05-44](https://user-images.githubusercontent.com/6112010/50121414-d1437400-02ac-11e9-8732-fd112edf02a6.png)

**Comment by robertmusil** [comment]
Fixed on #1211
