### ISSUE TITLE
Parallels with unusual texts not showing

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#1228]
Jaina, Hindi and other parallels for which we have no menu items like the Mūlasarvāstivādivinaya no longer show up in the lists of parallels.
For instance, we have in parallels.json:

"parallels": ["thag16.4#vns786","mn82#47","Uttarādhyayanasūtra 4#3"]

https://staging.suttacentral.net/thag16.4

But only the first parallel (between Thag 16.4 and MN82) shows up and the Uttarādhyayanasūtra is no longer there. This used to be there so something must have changed in the programming so they no longer show.

**Comment by sujato** [comment]
This is still current.

**Comment by SamaneriVimala** [comment]
This indeed needs to be loaded into ArangoDB. I will have a look and will have Blake check the code.

**Comment by sujato** [comment]
This is fixed, but has created a minor UI problem: even though these texts are just a reference, with no linked text, the cell still highlights on hover as if it were linked. i'll make a separate issue for this.
