### ISSUE TITLE
Missing Pali text in segmented translations

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1236]
#### Description:

In some cases the translation abbreviates the root text, and not every segment is translated. However, when the "root and translation" viw is enabled (side by side or line by line) then the user must be able to see the root text in full.

This does not work in every case, as sometimes there is Pali text missing.

This problem is not specific to staging, it is present on production as well.

#### Steps to reproduce:

- Got to https://suttacentral.net/sn56.14/en/sujato
- Enable side by side or line by line view.
- The root text displays next to the translated portions only.
- Go to https://staging.suttacentral.net/sn56.14/pli/ms 
- You can see there is substantially more Pali text.
- The Pali text is complete on Pootle: https://pootle.suttacentral.net/en/sn/translate/sn56/sn56.014.po
- And on Github: https://github.com/suttacentral/sc-data/blob/master/po_text/pli-en/sn/en/sn56/sn56.014.po

#### Expected behaviour:

Side by side or line by line view will always display the full root text, regardless of whether a particular segment has been translated or not.

#### Screenshots:

![screenshot from 2018-12-23 10-21-05](https://user-images.githubusercontent.com/6112010/50379372-9078a000-069c-11e9-8073-a8368e259f25.png)

**Comment by sujato** [comment]
This bug is still not fixed.

**Comment by ihongda** [comment]
![2019-04-05 18-20-21屏幕截图](https://user-images.githubusercontent.com/4037966/55621413-ff9f7d80-57cf-11e9-9b48-7f044654ba51.png)

I found the cause of the bug and wrote the preliminary solution code. It looks like it's working, but it needs further optimization.

**Comment by ihongda** [comment]
![aaa屏幕截图](https://user-images.githubusercontent.com/4037966/55635032-528a2c80-57f2-11e9-8643-e1dab396be8c.png)

Done.
I will optimize the code and submit it.

**Comment by sujato** [comment]
Thanks this is fixed.
