### ISSUE TITLE
Different dictionary results in staging and production

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1237]
#### Description:

Search for the same term yields different results in staging and production. We have not made any deliberate changes to this, so there is a bug on staging.

#### Steps to reproduce:

https://staging.suttacentral.net/define/gocara

https://suttacentral.net/define/gocara

#### Expected behaviour:

Staging and production return identical results

#### Screenshots:

![screenshot from 2018-12-25 16-28-21](https://user-images.githubusercontent.com/6112010/50413276-2b6ea700-0862-11e9-8834-c6258234742a.png)

**Comment by robertmusil** [comment]
@Bosmanfrx do you know anything about it?

**Comment by Aminah-SC** [comment]
@janlat will rebuild to see if this fixes the issue and will report back.
