### ISSUE TITLE
Re-create woff and woff2 files for Skolar and other fonts

### ISSUE THREAD

**Issue by saukap** [suttacentral/suttacentral#1241]
#### Description:
While investigating #1204 it was found that the woff and woff2 files that were generated for the Skolar Devanagari fonts, although valid files,  were not rendering most ligatures properly. Once the OTF file was converted using the tools mentioned below, the text rendered well.

#### Steps to reproduce:

The steps in #1204 

#### Fix:
We need to re-generate the woff files from the Skolar otf/ttf files and possibly others.

1. Use this [woff converter](https://github.com/samboy/WOFF)
2. Use this [woff2 converter](https://github.com/google/woff2)

**Comment by sujato** [comment]
We made a decision some time ago to keep it simple and focus just on woff2. Our fonts are complicated enough!
