### ISSUE TITLE
ja541 is not displayed on the site

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1242]
Reported [here](https://discourse.suttacentral.net/t/fixing-html-on-legacy-texts/11242/33?u=aminah).

**Comment by SamaneriVimala** [comment]
Same problem with JA499

**Comment by SamaneriVimala** [comment]
Some observations about this:
This is in the root text only.
This is a frontend issue. The text has been loaded correctly and is there but there is a "display:none" on the `<sc-simple-text>` element that should not be there.

**Comment by sujato** [comment]
Appears to work
