### ISSUE TITLE
Future Stuff (> Jan 2019)  

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1245]
This is a list of issues originally defined within the scope of the [SuttaCentral Upgrade Roadmap 2018](https://github.com/suttacentral/suttacentral/issues/1091) under the [Wackamole](https://github.com/suttacentral/suttacentral/issues/1173) and the [Cool New Stuff](https://github.com/suttacentral/suttacentral/issues/1174) sub epics, but will now be taken up in a future development cycle.

## Bugs

#927 
#1208 
#1234 

### Improving site metadata and documentation via RDF

With BDRC, [we have agreed to move towards supplying metadata for texts, etc. via RDF](https://github.com/suttacentral/suttacentral/issues/1028). Two aspects:

1. Put data in RDF format according to the BDRC schema. Start with the new texts created by SC.
2. Implement the data in our UI.
   - Use for texts in the metadata fields.
   - Use for “Language” pages (see next).

A volunteer, Anders, is looking into this. We anticipate it will take some time, and it may well be not ready for this cycle. We wouldn’t expect STXnext to do the RDF part, only the UI.

### People and Projects

RDF-based improvement of presentation of people and projects.

https://github.com/suttacentral/suttacentral/issues/1244

### <s>Create unified Setting dialog</s>

> Probably trash this one favor of adaptive tab bar proposal, but it needs discussion.

[One settings dialog to rule them all.](https://github.com/suttacentral/suttacentral/issues/1081)

### Adaptive tab bar everywhere

Use the "adaptive tab bar" as per the static pages, but apply it everywhere to get contextual settings and the like. Make the interface cleaner and more consistent across views.

https://github.com/suttacentral/suttacentral/issues/1238

### Reconsider how to get Home

Some tweaks and adjustments to the "Home" navigation, fro when we switch to MWC.

https://github.com/suttacentral/suttacentral/issues/1239

### Improve handling of references

Our complex sets of interrelated references make up one of the most powerful yet difficult areas for SC. A number of improvements have been proposed.

1. [Use standoff references in segmented texts](https://github.com/suttacentral/suttacentral/issues/1056).
2. [Simplify front end handling of references by creating three classes for references](https://github.com/suttacentral/suttacentral/issues/1055)
3. Fix incorrect reference handling in certain cases.

Also see:

https://github.com/suttacentral/suttacentral/issues/1013

https://github.com/suttacentral/suttacentral/issues/966

https://github.com/suttacentral/suttacentral/issues/713

### Support comparison of multiple editions of root texts

We are currently engaged in digitizing the oldest Pali manuscripts, from the [9th](https://github.com/sujato/bendall-cv) and [13th](https://github.com/dpcv) centuries. In addition, there are multiple editions of the texts in Pali, Chinese, and Tibetan. Over time, we can add more of these to the site, implementing a convenient way to compare them.

These texts will be segmented. They can be displayed through the Textual Information dialog, which will show them segment by segment as with the translations. In addition, we can implement a diffing library to shows differences between editions.

### Markup navigation in supertitles

Make the segmented text supertitles reflect the same hierarchy as the sidebar: Then:

1. Linkify them
2. Extract the translations for the sidebar

https://github.com/suttacentral/suttacentral/issues/1322

https://github.com/suttacentral/suttacentral/issues/1139

### Remove infinite scroll from search, and review search UI

This might wait until we get the chance to review search fully.

https://github.com/suttacentral/suttacentral/issues/1231

https://github.com/suttacentral/suttacentral/issues/1112

### Update HTML markup

https://github.com/suttacentral/suttacentral/issues/1161

https://github.com/suttacentral/suttacentral/issues/1160

**Comment by sujato** [comment]
I'm going to close this, as many issues have been completed, others are speculative. We should probably have a more narrow focus in our epics!
