### ISSUE TITLE
Add all languages to choose language dropdown

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1249]
#### Added value:

Currently the choose language dropdown in the toolbar vert-menu lists only English and Polish. It should list all languages available on SC.

The reason for the change is that formerly the advantage of choosing a language was minimal, but once the Yellow Brick Road is working it will be much more useful. Also in some cases the localized UI is now available.

In addition to this, change the icon to use the "translate" icon:

https://material.io/tools/icons/?icon=translate&style=baseline 

#### Acceptance criteria:

Select language works and activates the Yellow Brick Road, changes the default translations, and displays localized UI where applicable (Chinese and Portuguese).

#### Method of demonstrating completion:

Test the change widely in the navigation and UI.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by blake-sc** [comment]
Currently there is an existing languages endpoint /api/languages when called with http://localhost/api/languages?all=true it returns a list of all languages and whether they are root or not. From what I can tell it should be sufficient to either use ?all=true or remove the behaviour and always return everything and filter based on the is_root property
