### ISSUE TITLE
font-synthesis is not working in FF for Chinese l10n

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1262]
#### Description:

In non-latin scripts, italics are rarely used. Yet browsers still synthesize faux italics, which look bad and can become unreadable.

The CSS `font-synthesis` property is the correct fix for this:

https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis 

It currently only works in FF and Safari.

We have implemented this in `sc-text-styles.js`, yet it is not working on the site.

#### Steps to reproduce:

Open staging. Change language to Chinese. See the main site subtitle in italics. 

#### Expected behaviour:

No italics appear anywhere on the site in the defined languages.

**Comment by ihongda** [comment]
![2019-04-02 23-33-07屏幕截图](https://user-images.githubusercontent.com/4037966/55415604-e1ebd180-559f-11e9-8696-e0bd70979bde.png)

It looks OK.
1. "Subtitle class" did not assign "lang" attributes before.
2. There seems to be something problem with "sc-text-styles.js". when I loaded it in "sc-static-page-selector.js", I made an error(Index page cannot load properly),I'll checked it later.

**Comment by ihongda** [comment]
![深度截图_选择区域_20190809234324](https://user-images.githubusercontent.com/4037966/62791745-61fee680-bb00-11e9-881d-b33f13f41042.png)

It seems that the chrome browser also implements "font-synthesis"

**Comment by sujato** [comment]
I'm not sure what is happening at your end, but I don't believe it is the case that Chrome has adopted font-synthesis. The MDN docs still state that it is not supported in Chrome, and this is in fact the case on my machine: on the left is Firefox, right is Chrome.

![Screenshot from 2019-08-10 09-04-18](https://user-images.githubusercontent.com/6112010/62813411-fe030f00-bb4d-11e9-95c4-9d8b13cd7d3f.png)

**Comment by ihongda** [comment]
It is  not working in chrome browser v74,v76,v77 on another machine. I think it may be caused by "Linkify the site title" this time. I will go back to confirm again.:smile:
