### ISSUE TITLE
Go through Sentry and debug

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1281]
#### User story

So far we have concentrated on just getting Sentry working. But we should actually use it for what it is meant to be used for.

#### Feature description

Fix each bug on staging as reported by Sentry starting from the point after SDK is working and the sidebar update has been pushed.

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

All bugs reported by Sentry are fixed. 

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by robertmusil** [comment]
This should be close no? Sentry isn't even used on master

**Comment by sujato** [comment]
I think it is still active? I have entries from a few days ago, on staging. 

https://sentry.io/organizations/suttacentral/issues/2200918792/?project=358981&query=is%3Aunresolved

Do you know who has access to our sentry?

**Comment by ihongda** [comment]
Sentry is not currently used.
Are we going to redeploy?
