### ISSUE TITLE
Replace image on Home page

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1284]
#### User story

One of the images on the Home page should be replaced (upon recommendation by Chinese user that the text is not suitable). The image to be replaced is "becomingone", which is for the "What's here" page. replace it with "returninghome", which is included with the "squooshed" images:

https://github.com/suttacentral/suttacentral/issues/1287

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

"becoming one" is gone, "return home" is there.

Squoosh as per #1287

#### Pre milestone planning check:
- [x] Small enough to completed in a milestone.
- [x] Dependencies marked
- [x] No external dependencies block the PBI from being completed.
- [x] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
This is still not fixed. Pening PR https://github.com/suttacentral/suttacentral/pull/1417

**Comment by sujato** [comment]
Still not fixed. It's been since April to update a simple image.

**Comment by ihongda** [comment]
Sorry, I've neglected this. Let me deal with it.

**Comment by ihongda** [comment]
![深度截图_选择区域_20190914111638](https://user-images.githubusercontent.com/4037966/64902822-3cf22a80-d6e1-11e9-9644-a7fe47447c03.png)

**Comment by ihongda** [comment]
I saw the latest code, Blake dealt with the problem two days ago.

**Comment by sujato** [comment]
The problem is not dealt with until it is live on production and in front of the eyeballs of our readers!
