### ISSUE TITLE
R&D a plan for setting up a SC podcast

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1294]
### Task

We need to determine how best to set up a SC podcast and outline a proposal, or list of possible options to that end. 

This D&D thread can house relevant discussion: https://discourse.suttacentral.net/t/a-suttacentral-podcast/11852

### Outcome

An agreed plan of action for setting up a podcast.

**Comment by sujato** [comment]
doesn't look like it's going to happen.
