### ISSUE TITLE
Use LitElement, remove Polymer 

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1310]
## Update

Track this via the Milestone.

## Status as of Nov 2020

The text pages and many other elements have been rewritten in LitElement, however several elements remain to be changed. We should make a list of remaining elements.

I'll be making a list and adding items to the remove polymer milestone.

## LitElement replaces Polymer

Polymer, together with its system of libraries and components, is being replaced by LitElement. We must go through the entire code base and remove all dependencies on Polymer and legacy elements and ensure they are replaced with modern alternatives.

The general policy should be to produce code that is:

- valid and semantic
- fast and light
- reliable on modern browsers
- based on web standards

Where possible, use just HTML and CSS. Use modern vanilla JS where necessary. Import web components where they make sense. At all costs, avoid heavy and unnecessary dependencies. Evaluate each change and only add the minimum code necessary. Aim to produce clean, semantic HTML.

## MWC elements

The Polymer team is updating from Polymer/paper to Material Web Components (mwc) based on LitElement.

There are several versions of this, the one we want is "Material Components Web Components"

https://github.com/material-components/material-components-web-components

This is the obvious choice for updating, and in many cases it may be the correct one. Note, however, that the official MWC elements have been somewhat compromised by their reliance on "old-school" upstream CSS in BEM, etc. The polymer team is working to improve this, but it means that as of now, MWC components are significantly larger than they need be.

An optimized version of the MWC components is being developed, but is not yet published.

https://captaincodeman.github.io/mega-material/ 

These are super-small!

Thus we should take a flexible approach to replacing elements on a case-by-case basis:

- Use MWC
- Use other third-party libraries 
- Build our own

**Review all imported web components and completely remove dependency on legacy Polymer components and other outdated components.**

There's a good list of component libraries here.

https://open-wc.org/faq/component-libraries.html 

Not all components have been directly replaced by mwc. In some cases the components are no longer necessary, as the web platform has evolved. For example:

- `neon-animation`: [deprecated](https://www.polymer-project.org/blog/2017-07-12-an-update-on-neon-animation), use CSS keyframe animations, CSS transitions, or the Web Animations API. The latter is polyfilled with `web-animations-js`, but given our limited animation requirements, we should see if this can be removed as well.
- `iron-flex-layout`: From [its own repo](https://github.com/PolymerElements/iron-flex-layout): "this is an old element, that was written before all modern browsers had non-prefixed flex styles. As such, nowadays you don't really need to use this element anymore, and can use CSS flex styles directly in your code."

**Use platform features directly where possible. Use web components for features not available in the platform.**

Candidates for removal include:

-  @polymer/app-layout": "^3.0.0"
- @polymer/app-route": "^3.0.0"
- @polymer/app-storage": "^3.0.0"
- @polymer/iron-a11y-keys": "^3.0.0"
- @polymer/iron-ajax": "^3.0.0"
- @polymer/iron-collapse": "^3.0.0"
- @polymer/iron-flex-layout": "^3.0.0"
- @polymer/iron-form": "^3.0.0"
- @polymer/iron-icon": "^3.0.0"
- @polymer/iron-iconset-svg": "^3.0.0"
- @polymer/iron-image": "^3.0.0"
- @polymer/iron-location": "^3.0.0"
- @polymer/iron-media-query": "^3.0.0"
- @polymer/iron-meta": "^3.0.0"
- @polymer/iron-overlay-behavior": "^3.0.0"
- @polymer/iron-pages": "^3.0.0"
- @polymer/iron-scroll-threshold": "^3.0.0"
- @polymer/neon-animation": "^3.0.0"
- @polymer/paper-button": "^3.0.0"
- @polymer/paper-card": "^3.0.0"
- @polymer/paper-checkbox": "^3.0.0"
- @polymer/paper-dialog": "^3.0.0"
- @polymer/paper-dialog-scrollable": "^3.0.0"
- @polymer/paper-dropdown-menu": "^3.0.0"
- @polymer/paper-icon-button": "^3.0.0"
- @polymer/paper-input": "^3.0.0"
- @polymer/paper-item": "^3.0.0"
- @polymer/paper-listbox": "^3.0.0"
- @polymer/paper-menu-button": "^3.0.0"
- @polymer/paper-progress": "^3.0.0"
- @polymer/paper-radio-button": "^3.0.0"
- @polymer/paper-radio-group": "^3.0.0"
- @polymer/paper-spinner": "^3.0.0"
- @polymer/paper-styles": "^3.0.0"
- @polymer/paper-tabs": "^3.0.0"
- @polymer/paper-toast": "^3.0.0"
- @polymer/paper-toggle-button": "^3.0.0"
- @polymer/paper-tooltip": "^3.0.0"
- @polymer/polymer": "^3.0.0"

**Comment by ihongda** [comment]
In the past two weeks, the following SC components have been rewritten:
1. sc-text-options.js
2. sc-page-dictionary.js
3. offline-page.js
4. sc-settings-menu.js
5. sc-static-page-selector.js
6. sc-drawer-layout.js
7. sc-pli.js
8. sc-lzh2en.js

the following components have not been rewritten:
1. sc-page-search.js
2. sc-text-page-selector.js
3. sc-text-page.js
4. sc-simple-text.js
5. sc-segmented-text.js
6. stripe-card.js
7. donate-now-page.js
8. donation-success-page.js

Because there is a large gap between litelement and polymer, for example, there is no two-way binding, no observer and computed parameters for attributes, and the way to bind data is also different, so an important point of rewriting is to rewrite the corresponding polymer code by using the method of litelement, and it takes a lot of time to test to ensure that the modified component and the behavior before modification are exactly the same.

As for the replacement of paper components, I don't think this is a big problem. When the current polymer SC component is rewritten with litelement, if there is a suitable litelement component that can be used, (I hope it is a complete set of components with better compatibility), it won't take too long to replace the current paper components.

**Comment by ihongda** [comment]
So far, I have rewritten all the SC components except the donation related pages. Next, I will carefully test and gradually submit the code. The next step is to find a suitable component to gradually replace the paper component.

**Comment by sujato** [comment]
For donations, have a look at this:

https://github.com/bennypowers/stripe-elements

**Comment by sujato** [comment]
To replace iron-icons, if the official material icons, based on ligature font, are not ideal, we can use the following, which supply both svg and js versions:

https://github.com/Templarian/MaterialDesign
