### ISSUE TITLE
Unify structural data for sidebar, suttaplex lists, and supertitles

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1322]
## User story

A user wants to be able to get somewhere by clicking what's on the page, without necessarily having to go through the sidebar every time.

In addition, a user wants to see the navigation in their own language as much as possible, with fallbacks where that is not available.

## What is a supertitle?

The "supertitles" are found above the main `<h1>` title in the text pages. 

![supertitle](https://user-images.githubusercontent.com/6112010/64742225-cc130d00-d53e-11e9-90a8-79d870c8cf80.jpg)

These give some information about the location of the sutta within the larger collection. Many of our source texts, including the Mahasangiti Pali edition, include such details in their source files. We adopted it from such examples. However it was done in a deliberately loose way: there is no plan or consistency in how they are used, it just depends on the source.

In fact, the supertitles should not belong in the text files at all. They pertain to navigation and collection structure, not to the actual sutta. We should, therefore, remove the supertitles from the hard-coded texts, and keep just the sutta title there.

**Supertitles should be handled as part of the structural data, rather than text data.**

> Note: The supertitles in **legacy texts** are complex and inconsistent, for example, they frequently include both translated and original text titles. Thus we shall, as usual, leave these and focus on the segmented texts.

## Overview

1. Create data in bilara giving original text and translation of structure.
2. Apply this data to all navigation elements, including:
    - sidebar
    - supertitles
    - suttaplex lists
3. Apply root title or translated title as appropriate.
4. Make supertitles into navigable links, so that clicking on, say "Middle Discourses" takes you to `/mn`, i.e. the suttaplex list for that section.

### 1. Create data in bilara

Currently information on the names of texts and text-structures are handled like this.

- Translated text titles are extracted from the `<h1>` element on text pages.
- Root titles are, I think, taken from sc-data/structure/division. In any case, they are *not* taken from /structure/sutta.json.
- Other structural details are found in sc-data/structure/division.

The data in sc-data/structure/division is kept in the following form, eg.

```
[{"_path": "mn", "name": "Majjhimanikāya", "type": "division", "num": 2, "child_count": 3},
{"_path": "mn/mn-mulapannasa", "name": "Mūlapaṇṇāsa", "type": "div", "num": 1, "child_count": 5},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga", "name": "Mūlapariyāya Vagga", "type": "div", "num": 1, "child_count": 10, "display_num": "1-10"},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga/mn1", "name": "Mūlapariyāya Sutta", "type": "text", "num": 1},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga/mn2", "name": "Sabbāsava Sutta", "type": "text", "num": 2},
```
(I dislike this data structure, see #1487)

Note that the "_path" is not, as one might expect, the URL; the URL contains only the last element of the "_path".

The "name" as given here is usually in the root language. Sometimes it is in English, when there is no equivalent. 

I propose that we create sets of `division` files for bilara, which would have something like the following form.

#### root

```
{
  "mn": "Majjhima Nikāya",
  "mn/mn-mulapannasa": "Mūlapaṇṇāsa",
  "mn/mn-mulapannasa/mn-mulapariyayavagga": "Mūlapariyāya Vagga",
  "mn/mn-mulapannasa/mn-sihanadavagga": "Sīhanāda Vagga",
```
#### translation/en/sujato (or whatever)

```
{
  "mn": "Middle Discourses",
  "mn/mn-mulapannasa": "Root Fifty",
  "mn/mn-mulapannasa/mn-mulapariyayavagga": "The Chapter on the Root of All Things",
  "mn/mn-mulapannasa/mn-sihanadavagga": "The Chapter on the Lion’s Roar",
```

To ensure that we do not have duplication and conflicts, we should delete the corresponding data from both /sc-data/structure/division and the bilara-data text files. That is to say, all information on the names of structural elements should be kept only in the bilara division files.

sc-data/structure/division would then look like this:

```
[{"_path": "mn", "type": "division", "num": 2, "child_count": 3},
{"_path": "mn/mn-mulapannasa", "type": "div", "num": 1, "child_count": 5},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga", "type": "div", "num": 1, "child_count": 10, "display_num": "1-10"},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga/mn1", "type": "text", "num": 1},
{"_path": "mn/mn-mulapannasa/mn-mulapariyayavagga/mn2", "type": "text", "num": 2},
```

Text files would have the supertitle elements removed, so that:

```
{
  "mn9:0.1": "Majjhima Nikāya 9 ",
  "mn9:0.2": "Sammādiṭṭhisutta ",
  "mn9:1.1": "Evaṃ me sutaṃ—",
```

would become:

```
{
  "mn9:0.1": "Sammādiṭṭhisutta ",
  "mn9:1.1": "Evaṃ me sutaṃ—",
```

One advantage this gives us is that the sutta title will then consistently be consistently numbered `0.1`. Heck, we could even call it `mn9:title`.

### 2. Apply data to sidebar, supertitles, and suttaplex

Currently the supertitles do not match the structure of texts in the sidebar. For example, in DN, the sidebar has nikaya → vagga → sutta, but in the text we just have nikaya → sutta. Likewise, in MN the sidebar has nikaya → pannasa → vagga → sutta, but the text just has nikaya → sutta.

**Ensure that supertitles in segmented texts reflect the same structure as the sidebar.**

### 3. Apply root title or translated title appropriately

For the supertitles, the root text or translation should obviously be applied to the root or translation accordingly.

In the sidebar and suttaplex list, it is a little more complex. As a general rule it would be best to apply the translated title in the users chosen language (English by default.) However, there are a number of considerations that make this more complex than it might at first appear.

- In some cases it is tricky to see how a translation would work in the sidebar, as we cannot meaningfully distinguish between, say, Majjhima Nikāya and Madhyamāgama. They both mean :"Collection of Middle-Length Discourses" or more concisely, "Middle Discourses".
- The sidebar is space-constrained. 
- Sometimes users may be more familiar with the original titles.

Hence I propose this:

**In the Suttaplex lists, use both translated and root titles.** This will make the structural titles agree with the suttaplexes themselves, which already do this. It would look something like this.

![suttaplex-structure](https://user-images.githubusercontent.com/6112010/64743606-fd420c00-d543-11e9-9174-3c2de36eae97.jpg)

**In the Sidebar, use translated title, but give option to force the use of root title.** The cases where retaining a root title are necessary will vary by language. In some languages it will be possible to easily distinguish Majjhima Nikāya and Madhyamāgama, in other cases not.

Thus we would have a configuration file, eg. `en/root-in-sidebar.json` where such cases were noted on a per-language basis. Only exceptions are noted, otherwise the default is to use the translated title.

```
{
  "mn": "yes",
  "ma": "yes",
}
```

### 4. Make supertitles into navigable links

We add two features to the supertitles:

1. Each supertitle has a class name that is the slug version of the Pali for that structural level. 
    - Use the Pali names because it then remains the same in text and translation, and is a meaningful and useful markup to have in any case.
2. Each supertitle has a link with the name of that level as used in the sidebar. 

Use the `<nav>` element, which will allow us to differentiate between the navigable supertitles and the legacy supertitles. Everything inside the `<nav>` is inserted dynamically.

We will then end up with something like this, using DN as the simplest example. 

    <header>
        <nav>
            <ul>
                <li class="nikaya"><a href="/dn">Long Discourses</a></li>
                <li class="vagga"><a href="/dn-silakkhandhavagga"><The Chapter on Ethics</a></li>
            </ul>
        </nav>
        <h1>The Supreme Net</h1>
    </header>

Or a more complex case:

    <header>
        <nav>
             <ul>
                <li class="nikaya"><a href="/sn">Linked Discourses</a></li>
                <li class="vaggasamyutta"><a href="/sn-khandhavaggasamyutta">The Collection on Aggregates</a></li>
                <li class="samyutta"><a href="/sn22">“Linked Discourses on the Aggregates”</a></li>
                <li class="pannasaka"><a  #href="/sn22-mulapannasaka">The Root Fifty</a></li>
                <li class="vagga"><a href="/sn22-nakulapituvagga">The Chapter on Nakula’s Father</a></li>
            </ul>
        </nav>
        <h1>Nakula’s Father</h1>
    </header>

**Comment by ihongda** [comment]
![深度截图_选择区域_20200105190632](https://user-images.githubusercontent.com/4037966/71778978-0cffc780-2fef-11ea-8727-8c34d8e9900f.png)

A simple style breadcrumb style supertitle
I will try more styles

**Comment by ihongda** [comment]
![深度截图_选择区域_20200105214332](https://user-images.githubusercontent.com/4037966/71780991-7c33e680-3004-11ea-99c3-513ff94bd6b6.png)

**Comment by sujato** [comment]
This issue has been partly progressed or changed, so I will close it here.
