### ISSUE TITLE
Add Vietnamese translations of the Pali Nikayas

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1337]
D&D's purifiedpalisutta has shared his Vietnamese translations of the Pali Nikayas:
https://discourse.suttacentral.net/t/alternative-vietnamese-translation-of-the-pali-nikayas/11908/ which can be added to SC after allowing a little time for corrections and edits.

**Comment by sujato** [comment]
Meanwhile there is still this outstanding: https://github.com/suttacentral/legacy-suttacentral/issues/160
