### ISSUE TITLE
Variant readings display bug in legacy texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1342]
Variant readings are found in Sanskrit texts. Note that Pali variants in segmented texts are handled differently and are not part of this issue.

Let us take `avs100.html` as example. Here is how variants are marked up.

    <span class='var' title='Speyer: veṣṭhitaḥ'>veṣṭitaḥ</span>

When "highlighting" is applied, CSS takes care of showing these items, and the content appears on hover.

So far so good!

The only tricky bit is to **make sure everything related to processing these is removed from the JS files.** If it's all nicely organized this shouldn't be an issue, but it must be carefully checked. Don't leave messy useless code cluttering up the files!

I believe the relevant JS is in `sc-simple-text.js` and `sc-segmented-text.js`. But don't trust me, check and make sure it is completely removed from everywhere.

This also affects `<span class="corr">`. Eg in DA 1, `<span class='corr' title='[尸→尼]'>尼</span>` displays like this:

![Screenshot from 2020-10-29 09-03-51](https://user-images.githubusercontent.com/6112010/97501754-eec3e780-19c5-11eb-8088-3009510bc505.png)

**Comment by sujato** [comment]
This is a FF bug, they display fine in Chrome.

**Comment by SamaneriVimala** [comment]
Yes and no. They display fine in Chrome on my one machine and not the other ... Both running Ubuntu 18.04. Interesting.
I know it is not that important if we are switching to segmented texts, but it is a nuisance if you are working with verse parallels (of course on the machine where it is not working). So I will have a quick look to see if I can figure it out.

**Comment by SamaneriVimala** [comment]
Scratch that. The problem in Chrome has disappeared. It was just still in cache but emptying that it disappeared. So yes, only on FF.

**Comment by SamaneriVimala** [comment]
Problem has re-appeared in Chrome too. Should be solved with when the segmenting is all done. Variables only appear in pali texts.

**Comment by ihongda** [comment]
![屏幕快照 2019-10-08 上午11 50 25](https://user-images.githubusercontent.com/4037966/66366170-28dcd880-e9c2-11e9-85aa-335f7a0bb5b0.png)

Bhante, I see different display behaviors in different browsers, such as the one above in the opera browser. Is this correct?

**Comment by sujato** [comment]
Well, that is kind of correct, although it's not formatted 100%.

Still, as per the latest version of the ticket, we should get rid of any element at all. Just keep the HTML as it is, and color the span, that is all we need.

**Comment by ihongda** [comment]
Ok, I'll look at what's causing the different display behavior and fix it.

**Comment by ihongda** [comment]
![屏幕快照 2019-10-08 下午1 25 47](https://user-images.githubusercontent.com/4037966/66369932-e1aa1400-e9d0-11e9-9375-d1600c70f11b.png)

Changed the relevant style, leaving only the color.

**Comment by ihongda** [comment]
It looks like the problem has been solved :)

**Comment by sujato** [comment]
Just to note, in avs100, which I used as the original example, the text markup was faulty. I have corrected it.

Apart from that it seems as if the errors have been fixed.
