### ISSUE TITLE
On current iOS sidebar scroll is broken

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1348]
As per issue described here:

https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/372

Both safari 12 and Chrome 71 on iOS 12.1.2.

Using the sidebar, it is impossible to scroll and see the other collections.

**Comment by SamaneriVimala** [comment]
Also iOS 12.14 
https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/401?u=vimala

**Comment by sujato** [comment]
sidebar has been removed
