### ISSUE TITLE
Certain search terms are not returned in dictionary results

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1351]
## Description:
https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/378?u=sujato

> I have found a couple of words that have entries in the PTS Pali English Dictionary, but whose definitions are not found using SuttaCentral: jāta and pūra. I don’t know whether this is relevant, but in both cases there are very similar entries (same Roman letters, different diacritics) on the previous page of the PED. In both cases the Pali to English popups work, providing the correct short definition and link. See, for example, mil5.5.1 and an4.103.

## Steps to reproduce:

https://suttacentral.net/search?query=p%C5%ABra

https://suttacentral.net/search?query=j%C4%81ta

## Expected behaviour:

Words that are in the dictionary get returned in search results.

## To do

Determine if this is front or back end!

**Comment by SamaneriVimala** [comment]
Closing this ticket because the issue has been solved with the last update. I changed a few things to the loading some time ago and it is now life.
