### ISSUE TITLE
Some vol-page info in suttaplex nerdy row show in jeans-&-tshirt form

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1353]
## Description:

The nerdy row contains ID information for the sutta. This is sometimes displayed using the "jeans-&-tshirt" form of the ID (in `uid_expansion`, the `uid`), whereas it should be displayed in the "suit-&-tie" version (in `uid_expansion`, the `acro`).

I believe this was created when we fixed https://github.com/suttacentral/suttacentral/issues/1214

## Steps to reproduce:

examples:

https://suttacentral.net/pli-tv-bu-vb-pj

https://suttacentral.net/an3-patipadavagga 

https://suttacentral.net/an5-sammutipeyyala

## Expected behaviour:

**All IDs display in `acro` aka "suit-&-tie" form. A user never sees the `uid` form, except in the URL.**

## Screenshots:
![screenshot from 2019-02-06 09-39-42](https://user-images.githubusercontent.com/6112010/52309188-73e9ba80-29f3-11e9-9999-3e478768ceea.png)

**Comment by chansikpark** [comment]
The `volpages` attribute returned by the query for suttaplex list is populated by the `volpage` attribute from the corresponding `root` collection object or from the first non-null `volpage` attribute of any corresponding objects from `html_text` or `po_strings` (see [queries.py](https://github.com/suttacentral/suttacentral/blob/20307d3d3c04765d53f9d00ee52f6a46bf3eee21/server/server/common/queries.py#L260)).

In the case of 'an5-sammutipeyyala', `an5.272` has a non-null `volpage` in the `root` collection whereas `an5.273-285` only has a non-null `volpage` in `po_strings` (in the entry for Pali). It's the same situation for the other two cases listed.

It would seem that there are at most four ways to address this:

1. Populate the `volpage` attributes in `root`.
2. Populate the `volpage` attributes in `po_strings` in "suit-&-tie" form.
3. Create a database mapping from "jeans-&-tshirt" form to all the possible "suit-&-tie" forms.
4. Implement some fail-safe mapping from "jeans-&-tshirt" to "suit-&-tie" in [views.py](https://github.com/suttacentral/suttacentral/blob/20307d3d3c04765d53f9d00ee52f6a46bf3eee21/server/server/api/views.py#L433).

Looking into how the data loading process handles `volpage` attributes in `root` and elsewhere to see if there's some logical place for the first method. Eg: sc-data/structure/sutta.json seems to have all the suit-&-tie volpages

(Hi all, first comment!)

**Comment by sujato** [comment]
Thanks so much!

A couple of points:

- Indeed, "nerdy" data should aim for completeness and accuracy, so alternative refs should be displayed if present.
- We are actively thinking and working towards segmented translations in Chinese and Sanskrit, so Pali-only is undesirable.

**Comment by chansikpark** [comment]
Confirmed fixed on staging:

![Screenshot from 2019-11-27 13-14-23](https://user-images.githubusercontent.com/16063972/69693210-fa54c180-1117-11ea-9b95-3ec2fd38859a.png)
![Screenshot from 2019-11-27 13-14-45](https://user-images.githubusercontent.com/16063972/69693216-ffb20c00-1117-11ea-8047-3768a408ff43.png)
![Screenshot from 2019-11-27 13-15-04](https://user-images.githubusercontent.com/16063972/69693220-02146600-1118-11ea-858d-bd665a8c8197.png)
