### ISSUE TITLE
Vagga titles copped off on the sidebar (Firefox )

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1363]
#### Description:

In Firefox, the last vagga title gets chopped off in longer vagga lists. This has been found to be so for SN1.71-81, SN45.171-180 and AN1.616-627 in a non-exhaustive search (so there may be other instances).   

#### Steps to reproduce:

* On the sidebar click eg.:
  * Sutta
  * Numbered
  * Aṅguttaranikāya
  * Ekakanipāta
* scroll down to 616-627

#### Expected behaviour:

The title should not be cut off.

#### Screenshots:

![image](https://user-images.githubusercontent.com/36522678/52595647-3dbe9780-2e46-11e9-9390-049bf85c7f01.png) 
![image](https://user-images.githubusercontent.com/36522678/52596070-55e2e680-2e47-11e9-9dde-158c7213e009.png)

**Comment by sujato** [comment]
sidebar has been removed
