### ISSUE TITLE
Some translated texts not visible in menu

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1370]
When you choose for instance English as the site language, some of the translations are no longer shown in the dropdown for the translations menu.

Issue was reported here:
https://discourse.suttacentral.net/t/site-localisation-issues/11963/11

For instance here:
https://suttacentral.net/kp9
According to the html files there are a total of 27 translations of this file. Only 23 are shown.
Missing ones are:
Japanese
English (Amaravati Sangha)
Saarlaendisch
Klingon

Note that 3 of those are the languages that use a 3-letter code instead of a 2-letter code. That does not explain why the Amaravati one is not shown any more but maybe there the author code is wrong somewhere.

**Comment by SamaneriVimala** [comment]
Amaravati bug was fixed.
