### ISSUE TITLE
Dictionary word not appearing in the dictionary lookup results

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1371]
Issue was reported here:
https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/386

The word `nīvaraṇa` exists in various dictionaries but does not appear in the search as a dictionary entry and it appears empty here:
https://suttacentral.net/define/n%C4%ABvara%E1%B9%87a

The lookup works fine.

Check the Arango entry for this. Maybe a formatting error somewhere that bugs it up.

**Comment by SamaneriVimala** [comment]
I cannot see why but this entry is not loaded into Arango DB. 
In fact, if I look at NCPED, it has a total of 13483 words while Arango only has 13030 words from that dictionary. 
Same with other dictionaries. DPPN has 1367 entries and in Arango only 996.
The word 'aṅga' appears in all dictionaries but only 2 are shown.
