### ISSUE TITLE
Display bug on selected language for dropdown using pseudo-icons

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1373]
### Description:

See sujato-work branch

https://github.com/suttacentral/suttacentral/issues/1368

Using psuedo-icons on language dropdown menu, the "selected" language has a display bug. It is the wrong color and position, then corrects itself when something (eg the scrollbar) is clicked.

### Steps to reproduce:

Run sujato-work branch locally, inspect language dropdown.

### Expected behaviour:

All language icons look the same.

### Screenshots:

![screenshot from 2019-02-19 11-04-14](https://user-images.githubusercontent.com/6112010/52981828-47dc2980-3436-11e9-8d69-d9489423c14a.png)

**Comment by ihongda** [comment]
I seem to have fixed this bug, but I have to test it on more browsers.

[http://dhammaisland.com/files/LanguagesMenu.png](url)

**Comment by ihongda** [comment]
I seem to have fixed this bug, but I have to test it on more browsers

![LanguagesMenu](https://user-images.githubusercontent.com/4037966/55269734-afa55000-52d1-11e9-8e83-f8152f1d77a3.png)
