### ISSUE TITLE
Typo in definition of Tathāgato

### ISSUE THREAD

**Issue by earcanal** [suttacentral/suttacentral#1378]
#### Steps to reproduce:

1. Browse [SN 22.58](https://suttacentral.net/sn22.58/pli/ms#5)
1. Hover over the word **Tathāgato**
1. Definition reads: "**tathāgata**: one who has gone so; the Enlighten One. (adj.)

#### Expected behaviour:

Definition should read: "**tathāgata**: one who has gone so; the Enlightened One. (adj.)

#### Screenshots:

![enlightened_one](https://user-images.githubusercontent.com/1086888/53356902-605fae80-3924-11e9-9bc1-6c3193a424c8.png)

**Comment by sujato** [comment]
Thanks, I have pushed this correction, it will show up in due course.

Note, however, that the lookup tool is still using our legacy dictionary, from Buddhadatta's Concise Pali-English Dictionary (CPED). In due course, this will be updated with the more accurate and complete New Concise Pali English Dictionary (NCPED), corrected according to Margaret Cones' Dictionary of Pali.
