### ISSUE TITLE
Quotehanger not working in segmented texts

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#1381]
<h2>Description:</h2>
The quotehanger is not working on segmented English translations. Quotes at the start of a line show as part of the regular text and not before it. There is a proper name for such quotes but I forgot :-(

<h2>Steps to reproduce:</h2>
Go to any segmented English text. For instance https://suttacentral.net/dn1/en/sujato. Turn off all settings so you just see the English (although the same happens when the pali is turned on, just easier to see it without).

<h2>Expected behaviour:</h2>
The quotes have to be before the line

<h2>Screenshots:</h2>
Segmented translation:

![screenshot from 2019-03-02 08-36-03](https://user-images.githubusercontent.com/7444824/53678967-868ba280-3cc6-11e9-9f4a-b6255f463e71.png)

HTML legacy translation of the same text:
![Screenshot from 2019-03-02 08-36-28.png](https://images.zenhubusercontent.com/5ab1657e4b5806bc2bcbaac1/8bdfb7f2-c971-4151-9147-dd36cfa586cf)

**Comment by sujato** [comment]
I'd rather get rid of quotehanger. It has been fun and all, but in the days of :

- CSS grids
- segmented texts
- rtl texts
- CJK texts

and stuff, I think it's just too complicated to get it right. Better use CSS:

https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation

It has 13% browser support, oh well, maybe it'll get better!
