### ISSUE TITLE
Re-generate PO files for Thig and Thag

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1388]
## Description:

The PO files for Thig and Thag were generated from the incorrect HTML files. The files used were an older version that have incorrect numbers for verses, and also omit some data.

See https://github.com/suttacentral/suttacentral/issues/1345. Hopefully this will resolve that issue, or at least make a start on it.

We have to re-generate the PO files, keeping the English translation intact, but incorporating the correct source HTML files.

https://github.com/suttacentral/sc-data/tree/d230d84d9f4a9f661f7c3afe928b3b317c695682/html_text/pli/sutta/kn/thag

https://github.com/suttacentral/sc-data/tree/d230d84d9f4a9f661f7c3afe928b3b317c695682/html_text/pli/sutta/kn/thig

**Comment by SamaneriVimala** [comment]
I have partly corrected some things in the po files in sc-data so as to enable me to work but it's too much to find out all problems. Best is to re-segment the whole lot from the latest html files that were known as above.

**Comment by SamaneriVimala** [comment]
Blake has sent me the segmented po files with the corrected thig/thag in pali only. I will merge with the current English po files and make new ones as well as Bilara files.

**Comment by sujato** [comment]
Don't worry about Bilara files. Just make the correct PO files. All the bilara files are out of date and are just dummy text.
