### ISSUE TITLE
Update SC's social sharing image

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1400]
#### User story

_[I just tried to share a sutta on a Facebook page and saw that the social sharing image is just a png screenshot of the website.](https://discourse.suttacentral.net/t/could-you-set-a-new-social-sharing-image-for-suttacentral/12454)_ This doesn't look so great and also means no meta info is scraped & shared and that makes me sad.

#### Item description

We should update the image, perhaps with something like this:

![image.png](https://images.zenhubusercontent.com/5a91e3ac4b5806bc2bc83eec/e4836afe-26bc-4932-81a2-fa78b2a2a2c8)

We should also assign the generic og (open graphic) meta tag properties used by social sharing platforms and, if necessary, platform-specific tags as well. See the following for more on og here:

http://ogp.me/
https://www.aira.net/open-graph-social-media-traffic/

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

- [ ] social sharing image has been updated
- [ ] relevant meta tags have been added to sutta `<head>` eg:

    ```
    <meta property="og:title" content="SUTTA TITLE">   
    <meta property="og:description" content="SUTTAPLEX BLURB">
    <meta property="og:image" content="PATH/SOCIAL SHARING IMAGE.png>
    ```

Has been tested on:

- [ ] Discourse
- [ ] Pinterest
- [ ] FB
- [ ] LinkedIn
- [ ] Twitter
- [ ] Whatsapp

**Comment by ihongda** [comment]
So far, the tests on Facebook and Twitter have been successful:

![facebook-og](https://user-images.githubusercontent.com/4037966/55967441-e3f31600-5cac-11e9-8139-393eca39605b.png)

![Twitter-og](https://user-images.githubusercontent.com/4037966/55967450-eb1a2400-5cac-11e9-8292-2955ab7961f9.png)

But in LinkedIn, the description is not shown:

![linkedin-og](https://user-images.githubusercontent.com/4037966/55967554-18ff6880-5cad-11e9-8230-1a9c41567493.png)



In WhatsApp, the picture needs to be changed to square:

![Whatsapp-og](https://user-images.githubusercontent.com/4037966/55967664-43512600-5cad-11e9-9ebb-6bc190984470.png)

**Comment by sujato** [comment]
Hongda, that's looking really good. How about I ask Rina, our graphics person to see if she can tweak the design of the image a little. We should use the SC fonts, etc. But these are fine to use in the meantime.

**Comment by ihongda** [comment]
Bhante, we need two specifications of pictures, **rectangle and square.** at present, we still lack one square.

In addition, I will test it in:  
- Quora, 
- Weibo (a Chinese  social media platforms similar to Twitter), 
- 知乎(a Quora-like knowledge Q&A platform).

**Comment by ihongda** [comment]
I have submitted the code, and when it is updated to staging, I will test it again to confirm that the effect is satisfactory.

**Comment by KingofDucks** [comment]
![20190521_SocialMediaBanner_Facebook](https://user-images.githubusercontent.com/50226962/58100770-a2e21000-7c21-11e9-99e8-639231db3484.jpg)

How's about this? Also if there is any other social media image you need, let me know. https://sproutsocial.com/insights/social-media-image-sizes-guide/

**Comment by ihongda** [comment]
Hello KingofDucks, that's looking really good! 
I will use this image instead of the previous image to test.

**Comment by ihongda** [comment]
Twitter:
![twitter](https://user-images.githubusercontent.com/4037966/58179766-68d54480-7cdb-11e9-866c-d807a85796fe.png)

Facebook:
![facebook](https://user-images.githubusercontent.com/4037966/58179820-83a7b900-7cdb-11e9-8a18-9f5ce78f28c0.png)

Linkin:
![linkin](https://user-images.githubusercontent.com/4037966/58179840-8c988a80-7cdb-11e9-94bb-ba369f302f75.png)

It seems that the proportion needs to be adjusted slightly. Let me try to see if there is an optimal proportion.

**Comment by ihongda** [comment]
Hello KingofDucks, Could you make a image of 1,200 x 630 for me?

**Comment by sujato** [comment]
Hey that's nice, the typography is looking good (and i don't say that lightly!)

**Comment by KingofDucks** [comment]
![20190527_SocialMediaBanner](https://user-images.githubusercontent.com/50226962/58423894-863e5000-80d9-11e9-8e00-9e71f85badce.jpg)
Hi Hongda, see if this one work.

**Comment by ihongda** [comment]
Hi Rina, The effect is perfect, great job!

Facebook:
![facebook](https://user-images.githubusercontent.com/4037966/58424726-a4e91a80-80ca-11e9-9a79-44efd7a3cb09.png)

LinkedIn:
![linkin](https://user-images.githubusercontent.com/4037966/58424737-aa466500-80ca-11e9-9b4b-d2d33b97dc00.png)

Twritter:

![twitter](https://user-images.githubusercontent.com/4037966/58424751-b3cfcd00-80ca-11e9-8564-e04885cfb444.png)

**Comment by KingofDucks** [comment]
Oh, I'm glad. If you need any other size, please let me know.
