### ISSUE TITLE
Error in counting number of English texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1410]
## Description:

On the language page on staging, the number of English texts is counted incorrectly:

https://staging.suttacentral.net/languages

Compare with current production:

https://suttacentral.net/languages 

(It is also correct on local hongda branch)

It is not just the total number of texts, but the texts per collection that are also incorrect. perhaps it has stopped counting the segmented texts?

https://staging.suttacentral.net/languages/en

(note SN and AN are too low.)

## Expected behaviour:

English texts are counted correctly.

## Screenshots:

![Screenshot from 2019-04-09 08-47-46](https://user-images.githubusercontent.com/6112010/55761927-5f35ab80-5aa4-11e9-912e-8ff7370991b3.png)

**Comment by blake-sc** [comment]
There is a good chance that this has something to do with load-data failing to load all the texts or something. It would be the first thing to rule out anyway.

**Comment by blake-sc** [comment]
So it turns out staging was running out of memory which causes the load-data process to stall partway through. I increased the swap size allowing it to complete. Issue seems to be fixed now.
