### ISSUE TITLE
Sort translations on "language" pages by root language

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1411]
## User story

Jim wants to know what ancient Chinese texts have been translated into English. He goes to 

https://suttacentral.net/languages/en 

But the list is unstructured and does not make it clear what the root languages are.

He is confused and sad, and considers taking up a new life as a florist.

## Feature description

Add another level of heading to the list of `<h2>Translations</h2>`. The new headings will be `<h3>`. The heading names the language, and underneath that are all the texts translated from that language. Like this!

### Pali

- Digha Nikaya
- Majjhima Nikaya
…

### Chinese

- Madhyamagama
…

### Tibetan

- Kangyur 
…

And so on.

## Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

- `<h3>` headings for all language names
- Texts arranged under appropriate headings.
- the number of texts counted does not change, just the arrangement.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by ihongda** [comment]
![深度截图_选择区域_20190417180449](https://user-images.githubusercontent.com/4037966/56279828-72e3b080-613b-11e9-8ffd-f623e5d91330.png)

Bhante, does this effect meet expectations?

**Comment by sujato** [comment]
Yes, that would be great.
