### ISSUE TITLE
When used dark theme, and change text settings, The text of toast is not easy to read。

### ISSUE THREAD

**Issue by ihongda** [suttacentral/suttacentral#1419]
When used dark theme, and change text settings, The text of toast is not easy to read：

![c](https://user-images.githubusercontent.com/4037966/56088556-37848000-5eb6-11e9-8950-e2368a9b86d1.png)

![b](https://user-images.githubusercontent.com/4037966/56088557-39e6da00-5eb6-11e9-8cff-3f7ef837fdcd.png)

![a](https://user-images.githubusercontent.com/4037966/56088559-3c493400-5eb6-11e9-9e01-c39900927484.png)

**Comment by sujato** [comment]
Let's leave this one for now, and check when we upgrade to LitElement.

**Comment by ihongda** [comment]
Okey,Bhante
I expect to start the work of upgrade to litElement this week.

**Comment by sujato** [comment]
works fine now
