### ISSUE TITLE
Ghost texts appear as if linked in suttaplex

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1422]
## Description:

In some cases we have texts that are in the parallels data, but we do not have actual texts for them, either on SC or in external source. Let us call these "ghost texts". 

In the parallels tables, normally when you hover over a cell, it shows as a different color (pale gold) to highlight the fact that it is clickable. Ghost texts are not clickable, yet the highlight still appears.

## Steps to reproduce:

https://suttacentral.net/thag16.4

Hover over "Uttaradhyayanasutra". it shows pale gold. 

## Expected behaviour:

Ghost texts in suttaplex should not change color on hover.

**Comment by ihongda** [comment]
![ghost1](https://user-images.githubusercontent.com/4037966/63696948-7821dc00-c84e-11e9-8430-7ac4bb0af493.gif)

**Comment by ihongda** [comment]
Hey Bhante, does this meet the requirements?

**Comment by sujato** [comment]
Yes, looks like it!

**Comment by sujato** [comment]
This is still not fixed on the site. **Code does not matter until it is in front of the eyeballs of the users!**
