### ISSUE TITLE
Add Ven. Pannobhāsa’s EN translation Snp4 (Bilara)

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1424]
Following on from discussion [here](https://discourse.suttacentral.net/t/request-for-ven-pannobhasas-translation-of-the-sn-a-akavagga-to-be-uploaded/12656/) Ven. Pāladhammika has forwarded a text copy of Ven. Pannobhāsa’s translation of the Aṭṭḥakavagga he has prepared to add to SC via Bilara when it is ready:

[snp4-en-pannobhasa.txt](https://app.zenhub.com/files/89286697/c7103fd1-2100-49ca-8e9b-7780066c23ab/download)

**Comment by sujato** [comment]
Pannobhasa is a nazi apologist, his work should be on SC.
