### ISSUE TITLE
Use cursor:pointer for .top-row in compact view

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1437]
Like it says, currently there is nothing to indicate the top-row is clickable in compact view, this would at least be something.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by ihongda** [comment]
![深度截图_选择区域_20190523204200](https://user-images.githubusercontent.com/4037966/58253526-40ad1a80-7d9b-11e9-9205-0da6dca90c7c.png)
