### ISSUE TITLE
Heal the sliced toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1448]
The static pages use a so-called "prominent" version of the toolbar, with extra height, and including the SC title and logo. When you scroll down, the "prominent" toolbar disappears and is replaced by a "standard" toolbar, as found elsewhere on SC. 

If you open up the Home page and scroll down, you'll see that the toolbar slices into two separate layers as it contracts. There's an unwanted shadow that meaninglessly divides the area. This sometimes creates unfortunate effects.

![Screenshot%20from%202019-06-05%2010-13-56|690x74](https://discourse.suttacentral.net/uploads/default/original/3X/1/4/149b10ce2b18fcbc4aa319bf3bf38d05113f9874.png) 

This is in fact just a leftover from the initial mockup, it was never meant to be like this. We just always had bigger priorities and never got around to fixing it.

The correct transition looks like this:

https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1d3jb571H-QqU8rMvcvksU1e8-Di0lgu0%2Ftopappbars-behavior-scrolling-prominent-to-regular.mp4

Per Material design Guidelines:

https://material.io/design/components/app-bars-top.html#behavior

The only difference is that we do *not* shrink the title as per the demonstration. Rather, we use the site name and logo on the prominent toolbar, and replace with the page title on the standard toolbar. (See next item).

- **The transition between the "prominent" and "standard" toolbar should be smooth, with no jank or artifacts at any point.**

**Comment by ihongda** [comment]
![Peek 2019-07-15 21-51](https://user-images.githubusercontent.com/4037966/61221332-e3a26500-a74a-11e9-9a41-bcbc18cc402f.gif)

**Comment by sujato** [comment]
This issue is still not solved. Remember, the point of this is that the toolbar must behave in a way that is *elegant and organic*. It must appear in all cases as a **seamless and integrated whole**, not as a bunch of parts clanging together and interfering with each other. The toolbar is the primary thing that people see on SC, and it must work 100% in all cases.

Here is a screencast that shows a number of problems:

![Screencast from 03-08-19 09_50_11(1)](https://user-images.githubusercontent.com/6112010/62404404-59298480-b5d7-11e9-91d8-efe47181b4b9.gif)

1. When you scroll down, the top part of the toolbar covers part of the site title. **The site title must never be covered or clipped by another part of the toolbar.**
2. This overlaps with #1449, the static page titles. Currently the static page title appears immediately as you scroll down. This is incorrect. **We must *never* have both the site title and the static page title visible at the same time.**
3. Similarly, when scrolling back up, the static page title appears, which is correct. However, the main site title reappears before the static page title disappears. This conflicts with the requirement in the original issue: **To transition between the site title and page title, fade the site title out and fade the page title in**. The static page title *must* disappear completely before the site title appears.
4. Another problem is that the animation of the top part of the toolbar (i.e. toolbarHeader) is different than that of the rest of the toolbar. It moves up and down as you scroll, in a way that is independent of the rest of the toolbar. This must never happen. It does not look organic. There is no need for any separate animation on toolbarHeader, it should just behave like the whole of the prominent toolbar is a single entity.
5. When you scroll up or down, the static page title frequently appears for a second, then scrolls itself out of view or disappears. It acts like it has a mind of its own. This must never happen. The behavior and appearance of everything on the screen must be purposeful and intentional. Look at it and ask, why is this movement happening? What does it convey to the user? Random or unnecessary motion confuses a user. We must convey to them a sense of clarity and predictability in the UI.

**Comment by sujato** [comment]
The issues are still not solved. The toolbar still behaves in unpredictable and odd ways. Some things have got better, others are worse. I feel like we should give up on the whole thing and start from scratch implementing it with the new mwc elements.

**Comment by ihongda** [comment]
Using the new MDC refactoring can solve the problem. I submitted another PR, which should temporarily improve some effects.

**Comment by sujato** [comment]
Thanks. While you're looking at it, can you fix the shadow effects? In MD, each element is supposed to have a realistic physical location compared to all other elements. On our page, we have, from back to front:

1. The basic background
2. The cards
3. The toolbar
4. The sidebar

But the toolbar has no shadow. Its shadow should place it between the cards and the sidebar. See the MD design site for reference:

https://material.io/components/

**Comment by ihongda** [comment]
Okay, Bhante, I'll have a look sometime :pray:
