### ISSUE TITLE
Add titles to standard toolbar on static pages

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1449]
Unlike say the suttaplex or text pages, the **standard toolbar** on static pages is blank. It should contain the title of the page. Thus for static pages:

### Prominent toolbar is unchanged. 

It appears at the top of the page, containing the site title and logo. It does *not* contain the page title (because you can see this on the page already.)

![prominent_toolbar](https://user-images.githubusercontent.com/6112010/60546694-364e4b00-9d61-11e9-9d68-26943f3cdf56.jpg)

### Standard toolbar appears when you scroll down, and contains the page title.

Currently the standard toolbar looks like this:

![standard_toolbar_notitle](https://user-images.githubusercontent.com/6112010/60546783-64cc2600-9d61-11e9-8662-75ca3362af50.jpg)

It must be changed to include the title of the page, like this:

![standard_toolbar_title](https://user-images.githubusercontent.com/6112010/60546800-71e91500-9d61-11e9-93e7-346815daba3d.jpg)

If you have a look at how Discourse does it on threads, we want something similar.

- **To transition between the site title and page title, fade the site title out and fade the page title in.**

**Comment by ihongda** [comment]
![Peek 2019-06-21 22-37](https://user-images.githubusercontent.com/4037966/59930343-53d40880-9475-11e9-8ca3-8855a2dd6477.gif)

**Comment by sujato** [comment]
As for capitalization: yes, it must be capitalized. But do not get a lowercase version and transform it, it will always create bugs. Use the same literal string as in the page `<h1>`.

Don't use the `<title>` attribute, it is not reliable at the moment. I will make a separate issue for this.

**Comment by ihongda** [comment]
![Peek 2019-07-03 21-16](https://user-images.githubusercontent.com/4037966/60594583-dd6dc980-9dd7-11e9-943c-208b3b2d6b83.gif)

Bhante, does this meet the requirements?

**Comment by ihongda** [comment]
Or:

![Peek 2019-07-03 21-23](https://user-images.githubusercontent.com/4037966/60595096-eb701a00-9dd8-11e9-8a43-83d2a42739d9.gif)

**Comment by ihongda** [comment]
![Peek 2019-07-15 19-51](https://user-images.githubusercontent.com/4037966/61214342-45a69e80-a73a-11e9-9271-62991f1ac30b.gif)

**Comment by ihongda** [comment]
Bhante, does this effect meet your requirements?

**Comment by sujato** [comment]
That's great!
