### ISSUE TITLE
Attach the Adaptive Tab Bar to the standard toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1450]
Static pages make use of an Adaptive tab Bar (ATB). These provide a group of related, hierarchically horizontal, pages that vary according to context.

>As a historical note, this idea was added in the late stages of the initial development. I like it and would like to extend the concept beyond just the static pages, applying them to text pages and maybe elsewhere, too. See proposal on #1238.

The ATB is currently affixed to the prominent toolbar. So if you scroll down, the ATB disappears. If you scroll up, the standard toolbar appears, without the ATB.

![Screenshot%20from%202019-06-05%2010-37-06|690x118](https://discourse.suttacentral.net/uploads/default/original/3X/9/9/993cd32832455adae4cd68b83954b9124d381457.png) 

The ATB should remain fixed to the toolbar regardless of whether it is in prominent or standard state. Adding the title also (as per #1449) we end up with something like this:

![Screenshot%20from%202019-06-05%2010-37-06|690x149](https://discourse.suttacentral.net/uploads/default/original/3X/e/a/ea17ffbad450a1728b9d60c407f254c8f23219f1.png) 

This has the advantage that when you are halfway down the page, you can scroll up a little, and the toolbar and ATB appear, so you can navigate between pages right there.

- **The ATB should be always attached to the relevant toolbar, and display when the toolbar displays.**

**Comment by ihongda** [comment]
![Peek 2019-09-19 21-47](https://user-images.githubusercontent.com/4037966/65249828-33c0ed80-db27-11e9-8cfc-c72de7130be1.gif)

The effect is not perfect, but basically usable.

**Comment by sujato** [comment]
Hmm, not really good enough. 

Can you explain to me why it is difficult to achieve this?

**Comment by ihongda** [comment]
The toolbar uses the paper app-header component, which has a scrolling effect, but ATB has no scrolling effect, So when I put them together, it's a little bit inconsistent, I think it's not a good choice to modify the app-header source code.

I'll try to add a scroll effect to ATB, another option is to display ATB at the most appropriate time.

**Comment by sujato** [comment]
I find this surprising, given that this is the most basic default use of Tab Bars in Material design:

https://material.io/components/tabs/#placement

Surely they must have built them to take this use case into consideration? The whole point of using these components was to adopt simple patterns that were already built in to what was there so we did not have to mess around with all this stuff. Just put the tab bar in the toolbar, done.

Even the basic examples for Material Web components use exactly this design pattern:

https://adopt-a-pup.glitch.me/

https://github.com/material-components/material-components-web/blob/master/docs/examples.md

**Comment by ihongda** [comment]
Bhante, thank you for your information.
In fact, toolbar and ATB are placed in two separate web components in SC, and of course we can try to plug the ATB into the appropriate place of the toolbar when we need it to see if I can get what we want. 😄

**Comment by sujato** [comment]
>  toolbar and ATB are placed in two separate web components in SC

Okay, well then that is the problem and it must be fixed. This is just poor architecture. The ATB is part of the header and must be included within it. 

Honestly I feel at this point we should throw away the existing code and just rebuild the entire header based on the MWC components. It's just been a series of problems trying to achieve what should be extremely simple, basic, default usability patterns. The animations ("heal the toolbar") are still not fixed. We are wasting time and effort getting the paper components working, let us just get rid of them and do it again.

**Comment by ihongda** [comment]
![Peek 2019-09-23 20-55](https://user-images.githubusercontent.com/4037966/65427287-8dd1f380-de44-11e9-96c7-201de5eb3a1e.gif)

**Comment by ihongda** [comment]
> > toolbar and ATB are placed in two separate web components in SC
> 
> Okay, well then that is the problem and it must be fixed. This is just poor architecture. The ATB is part of the header and must be included within it.
> 
> Honestly I feel at this point we should throw away the existing code and just rebuild the entire header based on the MWC components. It's just been a series of problems trying to achieve what should be extremely simple, basic, default usability patterns. The animations ("heal the toolbar") are still not fixed. We are wasting time and effort getting the paper components working, let us just get rid of them and do it again.

Agree, it's time to restructure toolbar's architecture.

**Comment by sujato** [comment]
Great, let's do that. 

As for the most recent example, it is better, but still too complex. The toolbar and the tab-bar are the same thing, they should animate and move together. There should be no separate animation applied to these elements, just to the header as a whole. So there is never a state where the tab bar is visible while the toolbar is not.

**Comment by ihongda** [comment]
![Peek 2019-09-25 22-28](https://user-images.githubusercontent.com/4037966/65610455-f4414800-dfe3-11e9-85b6-c1eaa6737829.gif)

Approaching the target！

**Comment by sujato** [comment]
Deprecate in favor of card-based navigation.
