### ISSUE TITLE
Linkify the site title/logo

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1451]
It's common practice to click on a site logo and/or title to get Home. However SC breaks this: the main site logo/title is not clickable. The entire area (including logo, main title, and subtitle) should be a single clickable area that takes you back to the Home page. This should be the same on every static page.

- **On static pages, make the site logo/title a link to Home**

**Comment by ihongda** [comment]
![Peek 2019-07-08 23-30](https://user-images.githubusercontent.com/4037966/60822668-82254800-a1d8-11e9-90a5-9f39ef33c1a1.gif)

**Comment by sujato** [comment]
The target area for the clickable title is width 100%. It should be restricted to the area of the visible title, logo, and subtitle only. Clickable blank space is an anti-pattern: a user expects that if nothing is indicated on the screen, that is a region that can be clicked, grabbed, swiped, etc. without activating anything.

The region that should be clickable is indicated in this screenshot.

![Screenshot from 2019-08-03 10-18-14](https://user-images.githubusercontent.com/6112010/62404553-81fe4980-b5d8-11e9-9f12-08b427638491.png)
