### ISSUE TITLE
Remove HOME from ATBs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1452]
Currently the Adaptive Tab Bars (ATBs) include a HOME tab. This breaks Material Design, which specifies that on a Tab Bar, each option should be part of a *horizontal* navigation hierarchy. HOME is of course going *up* in the hierarchy, not sideways. Thus we should remove it, and users can get home via the main site title or the sidebar. (See previous).

- **Remove HOME link from all ATBs**

**Comment by ihongda** [comment]
![深度截图_选择区域_20190709193450](https://user-images.githubusercontent.com/4037966/60884912-c9ffaa00-a280-11e9-9f2f-dbad20eec6ba.png)
