### ISSUE TITLE
Reduce horizontal padding for toolbar elements on small screens

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1453]
It's hard to read the page title on small screens, as there is insufficient horizontal space. For narrow screens, therefore, we should reduce the horizontal padding between the various elements, i.e. the icons and the page title.

**Comment by ihongda** [comment]
Before:
![深度截图_选择区域_20190709202326](https://user-images.githubusercontent.com/4037966/60887693-8d837c80-a287-11e9-882d-7a9df83eda3e.png)

Now:
![Uploading 深度截图_选择区域_20190709202340.png…]()

**Comment by ihongda** [comment]
![Peek 2019-07-09 20-26](https://user-images.githubusercontent.com/4037966/60887793-cd4a6400-a287-11e9-895d-072d2e0fa6f9.gif)

**Comment by sujato** [comment]
I’d reduce the padding between the search icon and the “three dots” icon, apart from that it should be fine. (As a principle, remember that spacing in material design must always be on a 4px grid.)

**Comment by ihongda** [comment]
Okay, Bhante, I'll adjust it again. :smile:

**Comment by ihongda** [comment]
![Peek 2019-07-24 18-23](https://user-images.githubusercontent.com/4037966/61786432-41683880-ae40-11e9-9a25-786d60a5c8dd.gif)

reduce the margin 8px between the search icon and the “three dots”.

**Comment by sujato** [comment]
looking good, but i'll have test it on staging to really be sure.

**Comment by ihongda** [comment]
I'll commit the code after a detailed test :smile:
