### ISSUE TITLE
Remove white lotus logo Home link from toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1454]
This is something was added quite late in the development cycle. We were concerned that there needed to be a more obvious Home link on all pages. So for the standard toolbar, i.e. *not* on static pages, we added a SC white lotus logo to serve as a Home link. 

Of course it is always possible to go home via the sidebar, and I now think adding the lotus was a mistake. Why?

- It's an extra thing and not really necessary
- It's not really obvious that it is a Home icon
- It makes the toolbar too busy (see previous item)
- It is common on modern apps to omit such a Home button: Gmail, for example, does exactly what i am proposing, just have "home" on the sidebar.

This change comes with a cost: some functionality is removed, and I assume some users would prefer it the way it is. But I think on the whole it should be an improvement.

Combining the last two items, here is the toolbar on narrow screens as it is (left) and with the proposed changes (right).

![toolbar-mobile|690x538](https://discourse.suttacentral.net/uploads/default/original/3X/e/b/eb889c8bf607c24270e09b916ba4637d1e482652.jpeg)

Currently for small screens we shrink the font-size of the page title. These proposed changes would occur at the same break-point.

- **Remove lotus Home icon and reduce horizontal padding of toolbar elements on narrow screens, using the same breakpoint as for reducing the font size.**

**Comment by ihongda** [comment]
![深度截图_选择区域_20190709193450](https://user-images.githubusercontent.com/4037966/60884870-ab011800-a280-11e9-83d9-8e228aec8d69.png)
