### ISSUE TITLE
Improve search field responsive behaviour

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1455]
There are currently some bugs in the search field. 

- On a narrow screen, if you open it, it makes the hamburger menu shrink away. At certain widths, it kind of half shrinks and leaves a ridiculous little thing behind.
- The search field also encroaches to the right for some reason, not just pushing out the vert-menu icon, but actually pushing out over the screen.

This all seems like bad CSS design. It should work like this.

On sufficiently wide screens, the search field simply opens and does not affect any other toolbar items. 

- Current status: ☑

![Screenshot%20from%202019-06-05%2016-24-05|690x34](https://discourse.suttacentral.net/uploads/default/original/3X/1/d/1d63be3d85507e28f09ee6ab8c9947de59046698.png) 

On medium width screens, open the search field and hide the page title. 

- Current status: ☑

![Screenshot%20from%202019-06-05%2016-24-33|690x46](https://discourse.suttacentral.net/uploads/default/original/3X/3/b/3b6d2f1597acd5758b3e2b9c7995b4d5dad877ff.png) 

On narrow screens, open the search field and hide everything else on the toolbar, so that the search field takes up all of the toolbar width. 

- Current status: ❎

![Screenshot%20from%202019-06-05%2016-25-31|690x445](https://discourse.suttacentral.net/uploads/default/original/3X/2/f/2f61be6c06e58177e552c6d3b9fc6446ce8ed345.png)

- **Ensure search field has correct behavior in all contexts and screen widths.**

**Comment by ihongda** [comment]
![Peek 2019-06-14 21-32](https://user-images.githubusercontent.com/4037966/59512842-24a91e80-8eec-11e9-800b-d896c4aa9e5d.gif)

when the windows innerWidth < 480, hide everything else,
the search field will takes up all of the toolbar width.

**Comment by sujato** [comment]
Okay, so on the example you show above, the functionality is correct, however, the animations are not smooth. It moves a bit to the left, then to the right. It doesn't convey a sense of confidence.

Moreover, on my screen the search bar is not centered as it is on the gif posted above. The X disappears to the right.

![ezgif-4-c6ba0ee11ab4](https://user-images.githubusercontent.com/6112010/68402133-d6b9df00-0148-11ea-9cd7-b6b4d204f169.gif)

Have a look at the Material design guidelines for animations:

https://material.io/design/motion/

And don't forget to *always* use FLIP for smooth animations:

https://aerotwist.com/blog/flip-your-animations/

https://medium.com/outsystems-experts/flip-your-60-fps-animations-flip-em-good-372281598865

**Comment by ihongda** [comment]
I'm sorry, I didn't respond in time. I will solve this problem the next time I submit the code.

**Comment by ihongda** [comment]
> It moves a bit to the left, then to the right.
---
This is due to the use of "cubic-bezier" animation.
https://developer.mozilla.org/zh-TW/docs/Web/CSS/transition-timing-function

I use "liner" instead.

**Comment by sujato** [comment]
Looks good. I noticed another bug, though. On Firefox, the `text-overflow: ellipsis` is not working. On long titles, the toolbar action icons are pushed to the right, off the page.

Screenshot has Firefox on the left (incorrect) and Chrome on the right (correct).


![Screenshot from 2020-01-17 17-34-52](https://user-images.githubusercontent.com/6112010/72589705-145c9480-3950-11ea-952c-71c9bf45d26f.png)

**Comment by ihongda** [comment]
Okay, Bhante, I will arrange the appropriate time for processing.
