### ISSUE TITLE
The next/previous sutta link doesn't show on sn35.32 and sn35.33-42

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1462]
#### Description:

The next sutta link does not show on sn35.32 in any version (root or translation), and the previous sutta link doesn't show on sn35.33-42.

#### Steps to reproduce:

* go to eg. https://suttacentral.net/sn35.32/en/sujato
* scroll to bottom of the page
* Behold! A blank space on the right corner. 

or 

* go to eg. https://suttacentral.net/sn35.33-42/en/sujato
* scroll to bottom of the page
* Behold! A blank space on the left corner. 

#### Expected behaviour:

There ought to be a link to next or previous sutta, in the blank space (as in eg. https://suttacentral.net/sn41.7/en/sujato).

#### Screenshots:

![image.png](https://images.zenhubusercontent.com/5a91e3ac4b5806bc2bc83eec/54651121-2c7e-4181-bfe3-256396f9a3a8)

![image.png](https://images.zenhubusercontent.com/5a91e3ac4b5806bc2bc83eec/83d52147-0585-4738-9ef5-2dbe6ea7dc4b)

**Comment by ihongda** [comment]
![深度截图_选择区域_20190706183406](https://user-images.githubusercontent.com/4037966/60755062-19de3700-a01d-11e9-9411-77e6af81fd11.png)




This should be the reason that the JSON returned by the corresponding API lacks the next Sutta info
[https://suttacentral.net/api/suttas/sn35.32/sujato?lang=en]

**Comment by Aminah-SC** [comment]
Thanks so much for finding that out!

**Comment by ihongda** [comment]
Find the cause of the problem. There is no problem with Python code. It is caused by the related error data in sc-data/structure/division/sutta/sn.json, the fix will be pushed later.

**Comment by sujato** [comment]
works now
