### ISSUE TITLE
<title> attribute on some static pages is not loaded

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1463]
## Description:

In certain of the static pages, the `<title.` attribute does not update correctly.

## Steps to reproduce:

See: https://suttacentral.net/donations

The title attribute is correct: `<title>SuttaCentral—donations</title>`

Now go to: https://suttacentral.net/offline

Title is incorrect: `<title>SuttaCentral—</title>`

It should be: `<title>SuttaCentral—offline</title>`

#### Expected behaviour:

The title attribute always includes the page title. Use the slug form as found in the URL. 

The offline page is only an example. Check and make sure this works correctly on all static pages.

**Comment by ihongda** [comment]
![Peek 2019-07-03 20-19](https://user-images.githubusercontent.com/4037966/60591014-08ecb600-9dd0-11e9-890d-638788ecd8ee.gif)

Fix pages that lack titles: Use offline page, Languages page, Downloads page.

**Comment by ihongda** [comment]
Bhante, I don't understand Polish and Portuguese. I use translation software to translate these words. Is that correct? :

Polish:
"OFFLINE": "UŻYWAJ OFFLINE",
"LANGUAGES": "JĘZYK",
"DOWNLOADS": "DO POBRANIA"

Portuguese:
"OFFLINE": "USO OFFLINE",
"LANGUAGES": "A LÍNGUA",
"DOWNLOADS": "DOWNLOADS"

**Comment by sujato** [comment]
Sorry about the slow response!

This issue is still current. The pages mentioned above are fixed, but other pages are not. In particular, the Guides do not have proper titles, eg. https://suttacentral.net/general-guide-sujato

We must ensure that *all* static pages will have a proper title in both the `<title>` tag and the main page title in the toolbar.

As for the Portuguese issue you mention, you can contact @Gabriel_L on the Discourse forum. More generally, with any questions about translations, ask Aminah, she has the relevant contacts.

**Comment by ihongda** [comment]
OKay, Bhante, I will carry out a comprehensive inspection on this issue.
