### ISSUE TITLE
Parallel check: SN 40.2 & SĀ 501

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/suttacentral#1466]
> SN 40.2 shows no parallels, but I believe SĀ 501 is a parallel to this sutta.
>
>_([D&D](https://discourse.suttacentral.net/t/please-report-any-errors-or-typos/9548/450))_

**Comment by thesunshade** [comment]
merged with https://github.com/suttacentral/suttacentral/issues/1489#issuecomment-1972230608
