### ISSUE TITLE
Add MD divider to suttaplex

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1475]
The information in the suttaplex is too dense and should be distinguished better. In material design the way to do this is using what they call a "divider":

https://material.io/components/dividers

This can be accomplished purely with CSS. Add something like:

```
border-top: 1px solid var(--sc-border-color);
    margin-top: var(--sc-size-md);
    padding-top: var(--sc-size-sm);
```
to `.section-details.main-translations`

**Comment by ihongda** [comment]
![深度截图_选择区域_20190903231206](https://user-images.githubusercontent.com/4037966/64185792-53f27a80-cea0-11e9-8060-3be867ae86a5.png)

Add four dividers to distinguish different types of information.

**Comment by ihongda** [comment]
![深度截图_选择区域_20190903231206](https://user-images.githubusercontent.com/4037966/64185792-53f27a80-cea0-11e9-8060-3be867ae86a5.png)

Add four dividers to distinguish different types of information.

**Comment by ihongda** [comment]
![深度截图_选择区域_20190905184554](https://user-images.githubusercontent.com/4037966/64335453-70f88c00-d00d-11e9-8339-b293c8b1de89.png)

add "divider" style to ".section-details.main-translations"

**Comment by sujato** [comment]
That looks great, thanks.

**Comment by sujato** [comment]
And again, this is still not visible on staging. It is IMPERATIVE that ALL completed changes be reliably and immediately pushed to staging. @blake-sc @ihongda
