### ISSUE TITLE
Yellow Brick Road (aka little green dots) give false positives based on sect

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1476]
The purpose of the yellow Brick Road (YBR) is to indicate where users can find translations in their own language. When translations are present, a green dot is added on the sidebar. The dot is added at the *lowest level that is visible to the user*, and thus acts as an indication where they may go next.

In some cases, a green dot appears at a higher level but disappears at a lower level. This should never happen: when you open a level with a green dot, the dot should move to the next level, and so on, until you arrive at the text itself.

I have observed this in the case of the Vinaya and Abhidhamma.

Take Abhidhamma as an example. here I use some flowers instead of a green dot!

With English as my chosen language, there is a green dot on the top level.

- **ABHIDHAMMA** 💐

Great, so we know there are English translations in there. Open that level:

- **ABHIDHAMMA**
- (pli) THERAVĀDA 💐
- (lzh) DHARMAGUPTAKA 💐
- (lzh) SARVĀSTIVĀDA
- (san) SARVĀSTIVĀDA

The green dot on "Abhidhamma" disappears, whih is correct. Green dots appear on "Theravada" and "Dhamaguptaka", indicating that both of these contain English translations.

Open "Theravada" and see several green dots, indicating translations, and if you click there you see that the translations are in fact found. yay!

But! Open "Dharmaguptaka" and there is no green dot. And in fact there are no English translations here. So the green dot on Dharmaguptaka is a mistake.

If you go to the Vinaya, you will see that the same thing happens in several cases. 

It seems to be the case that if a *school* has any translation in the Vinaya or Abhidhamma, *all* the top levels containing texts of that school are said to have translation.

Thus for the Dharmaguptaka, there are some translations of the Chinese text, and these are indicated correctly. But then there are *no* translations of the PGD text, yet the green dot is visible, but disappears when you open it, just like in the Abhidharma. 

The same applies to the Mulasarvastivada.

**Green dots should appear only when there is a translation included in that text, not on other texts of that school.**

**Comment by ihongda** [comment]
![深度截图_选择区域_20190903222014](https://user-images.githubusercontent.com/4037966/64181447-0aeaf800-ce99-11e9-8f0d-f1a413c142fd.png)

It seems that there is something problem with the data provided by the API.
when there is a translation not included in that text, ‘yellow_brick_road’still set to 'true'. 

 Let me examine it in detail.

**Comment by chansikpark** [comment]
I shall turn to this issue now.

**Comment by sujato** [comment]
Note, this issue is still current.
