### ISSUE TITLE
Taisho parallels table has missing column letters

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1477]
It seems the data in the parallels root in the parallels tables is getting corrupted somehow, the references to the Taisho have lost the internal letter representing the column. 

https://discourse.suttacentral.net/t/please-report-any-errors-or-typos/9548/518

The bug applies to `.parallels-root-id`. 

For example, see: https://suttacentral.net/t198/#t0183b17--t0184b02

```
<td class="parallels-root-cell parallels-table-cell paper-lift" rowspan="1">
                  <a class="root-link" href="/t198/lzh/#t0179b11--t0179c01">
                    <paper-ripple></paper-ripple>
                    <div class="parallels-root-id root" title="SuttaCentral ID">
                      T 198: 017911–017901
                    </div>
                  </a>
                </td>
```
Notice how the link has `t0179b11`, whereas the displayed number is "017911". 

Similarly, `t0179c01` becomes "017901".

Thus the column lketter is being somehow stripped.

**Column letter more be restored to parallel root IDs for Chinese texts.**

**Comment by ihongda** [comment]
As Ven. Vimala said, remove 'replace (/[a-z]+/g,'')' would yield normal results, but I don't know if it would affect other rules.

**Comment by ihongda** [comment]
![深度截图_选择区域_20190905211510](https://user-images.githubusercontent.com/4037966/64345113-4f55cf80-d022-11e9-91f6-2d4ce1c7ca7f.png)

**Comment by sujato** [comment]
I'm wondering why we get it right in the right-hand column, eg. "T ii 483c17" but not in the left?

**Comment by ihongda** [comment]
Because in the content of the left column 
some characters have been replaced, and the right column no replacement was made.

**Comment by sujato** [comment]
Okay, great.
