### ISSUE TITLE
Root parallels display poorly in Firefox

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1478]
The root parallel IDs appear in the left-hand column of the parallels tables. In cases where there is a long ID, this is not handled well in Firefox. See the screenshot with Firefox left, Chrome right. Text overflows the boundaries in Firefox.

![Screenshot from 2019-09-05 07-01-34](https://user-images.githubusercontent.com/6112010/64291259-13335800-cfab-11e9-9e95-56917445adc6.png)

**Display of long IDs in parallels roots in Firefox must be the same as Chrome, or at least, should look presentable.**

**Comment by ihongda** [comment]
![深度截图_选择区域_20190906192021](https://user-images.githubusercontent.com/4037966/64424392-876d1900-d0db-11e9-9a58-e256ef3b6f1a.png)

When fixd "Taisho parallels table has missing column letters #1477",  this problem has also been solved.

**Comment by sujato** [comment]
Still not fixed on staging. Once again, it is IMPERATIVE that when changes are made they are pushed to staging IMMEDIATELY. @blake-sc @ihongda
