### ISSUE TITLE
Root Pali text in DN does not display

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1479]
If you select the root Pali text in DN, there is no text and the console shows an error. Pali texts in other collections seem to work, but should be more fully tested.

Below see a screenshot, on the left is the Pali MS text for DN 4, on the right is the Sujato translation of the same page.

![Screenshot from 2019-09-05 16-25-12](https://user-images.githubusercontent.com/6112010/64317132-19045a00-cffa-11e9-91ad-4ddd2ca37657.png)

**All Pali text in DN (and all text everywhere for that matter) must display.**

**Comment by ihongda** [comment]
![深度截图_选择区域_20190905191201](https://user-images.githubusercontent.com/4037966/64337058-17925c00-d011-11e9-9e62-fd51f6301535.png)

Reasons have been found and repaired.

**Comment by sujato** [comment]
Excellent, thanks.
