### ISSUE TITLE
Add CSS hanging-punctuation support

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1481]
We have in the past supported hanging punctuation via a JS plugin called "quotehanger". it is, however, tricky to get it working right in every context. There is a proposed CSS property for doing this:

https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation 

Let us use this. It has 13% browser support (safari), so that's not nothing. Maybe it'll improve!

The following would probably do it:

    p, li {hanging-punctuation: first last;}

**Comment by ihongda** [comment]
Has been added to 'sc-segmented-text.js' and 'sc-simple-text.js'

Go to safari browser tomorrow to test the effect of'hanging-punctuation'.

**Comment by ihongda** [comment]
Has been added to 'sc-segmented-text.js' and 'sc-simple-text.js'
Go to safari browser tomorrow to test the effect of'hanging-punctuation'.
