### ISSUE TITLE
A Sutta-garden: page layout for segmented texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1483]
## Proposal

- Implement CSS design for new bilara-segmented texts.

 look at how to achieve various layout designs. These are all responsive, so to see how they work, download the attached folder and open sn1.1-new.html in your browser.

[sc-ux.zip](https://github.com/suttacentral/suttacentral/files/3600011/sc-ux.zip)

## Caveats

- This is about the segmented texts only, not legacy texts.
- I will discuss the tooltip in another thread.
- [See here for the distinction between "primary" and "secondary references.](#1055) (Note: not visible in latest design)
- This is about page layout, not UI, the buttons are only there to help showcase possible layouts.
- The CSS is obviously not production-ready, nevertheless it uses SC styles for the most part. **CSS must be refactored to apply per function, not per page**.

## Basic concepts

- Typography remains similar to currently.
- Verses are now indented rather than centered. It keeps things simpler.
- As now, the default view is a single language.
- Comments and Variant readings (collectively, "notes") are available via tooltip by default.
- User may enable references.
- Design of reference "chips" is the same regardless of position (unlike currently)
- The views labelled "Plus" show the Notes.
- Notes are in the margin where there is enough room, otherwise inline.
- Notes in margin may overlap. In this case, click to raise an obscured Note.
- Side by side plus view makes great use of a wide screen!
- In "Plus" views, each segment is on a new line.
- Unlike current site, segment lines are not vertically separated. Thus you get a better picture of the paragraphs. Each view is optimized for best vertical layout.
- Notes have icons + color to differentiate them.
- Current ability to show Pali segments with tooltip is removed. (*Not* the Pali lookup!)

## How?

The secret sauce is CSS Grids. These didn't exist when we did the original layout, and even when we made the revised site they were just starting to get mainstream. However they have 93% browser support these days. 

Grids are an extremely powerful layout tool, as they let you declaratively assign elements to grid columns and rows. So we can simply use CSS to tell the page how many columns, what goes in which column, and how wide it should be.

## UI

For the UI, see #1496

## To-do

- The overlapping notes are my main concern. Essentially this arises because they must be made `position:absolute` so that they can span multiple rows, otherwise long notes would force the grid to have big empty spaces. When clicking it raises the note, but this is currently done with CSS and thus is not sticky. It should be sticky, which is not possible in CSS and must be done in JS.
- More complicated, and probably best left for now, I wonder if we can use JS to detect a collision between two absolutely-positioned notes, and cut short the upper note, leaving, say, a [jagged bottom edge](https://stackoverflow.com/questions/24386147/jagged-edges-with-transparant-background-in-css) to indicate it has been truncated. Then click would raise and reveal the whole note. 
- Icons must be done properly, this is just for demo.

**Comment by ihongda** [comment]
![aaa](https://user-images.githubusercontent.com/4037966/70916851-4b8d0c80-2057-11ea-9b11-5f9b8fcb94b1.gif)

1. If the number of comments is greater than 1, recalculate the height based on the height of the previous comment and the next comment and top.

2. When the mouse is moved to comment, the original height will be restored, and when the mouse leaves, it will be reduced.

**Comment by sujato** [comment]
Great, that looks good.
