### ISSUE TITLE
Beyond the tooltip: a better dictionary lookup for text pages

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1485]
## 2-do

This feature is mostly complete, here is what remains:

- [x] Use proper icons.
- [x] Use proper typography mixins.
- [x] <s>Replace `<details>` with proper `<dialog>`. </s> It's good enough for now. the `dialog` element is still not widely adopted enough.
- [ ] Use updated JSON source #1508 
- [x] There is a bug, the bottom sheet opens automatically when you navigate to a text page. The bottom sheet should only open or close at the explicit request of the user.

***

Currently one of SC's killer features is the Pali or Chinese dictionary lookup. Enable it and you can hover over Pali or Chinese words on the page and get a definition.

https://material.io/components/tooltips/

## The Problems

1. **Touchscreens**: using tooltips on touchscreen is bad. This is more than 50% of our users!
2. **Positioning**: It's hard to get the position right in all contexts.
3. **HTML title attribute is bad**: this is the basic HTML way of putting a tooltip on, but it suffers severe accessibility issues and is especially poor for screenreaders. Also there is no way to style it or add functionality.
4. **Too much info**: MD guidelines say a tooltip should have just a short message, no more than a few words. But we put whole dictionary definitions in them.
5. **Too much functionality**: We add a link to full definitions, but this is hard to get to and not explained.
6. **No MWC**: the MWC does not have a tooltip candidate, and even the more advanced parent project lacks it.

## A better way: use MD "bottom sheet"

https://material.io/components/sheets-bottom/

A bottom-sheet is similar to a tooltip in that it appears for displaying transient information. However it differs in that it is attached to the bottom of the screen, rather than floating around, and contains rich information. Typically on a mobile a bottom-sheet might fill a third of the screen or so.

We can use this to display the dictionary lookup information. This will effectively be identical to the "dictionary preview" card that is displayed at the top of search results. 

https://suttacentral.net/search?query=idha

This means we can reuse components.

### Activate it

The sheet can called by first turning the lookup on, then highlighting a word.

- Interface is the same for desktop and mobile: just highlight a word.
- Lookup only works for a single word. If user highlight many words, only look up the first one.
- The sheet should be persistent: Once activated, keep it until dismissed by the user.
- Once activated, it can be pulled up or swiped up from the bottom of the screen.

### Navigate

User has prev/next arrows, similar to the prev/next arrows for suttas.

-  The "next" arrow is conveniently located by the user's thumb on mobiles.
- Touch target is large and static. Just keep clicking or tapping on the same spot to go through words.
- Interface is identical for desktop and touchscreen.
- Should also support keyboard navigation for desktop.

### Mockup

Here is a very rough initial design mockup.

![0c644533d5c58babe4f6a2806fdbd75f41bea56a](https://user-images.githubusercontent.com/6112010/64687320-9d108300-d4cd-11e9-8e28-66e24049da30.jpeg)

- Current term is identified by both color and border
- User can click to go to relevant /define/ page for full entries. (This is currently the case on the tooltip also, so the data is already there.)
- Bottom sheet can be dismissed by swiping or clicking a down-arrow (not shown)
- Bottom sheet is full width

## Implementation

- There is no bottom sheet in the MWC components, nor in the parent project. So in this respect it is no better than a tooltip. So we shall either have to find another source or roll our own.
- Height of dictionary section will vary depending on entry length, we will need to consider how to handle this. Perhaps we will have to have a fixed height allowing for say three lines, then scroll to see more; however, it will not often happen that a user needs to see more.
- Currently the lookup requires inserting `<span class="word">Evam</span>` on each word. On a text the size of the Mahaparinibbana Sutta, that's a heckton of DOM! Will this still be necessary?

**Comment by ihongda** [comment]
![GIF](https://user-images.githubusercontent.com/4037966/66381145-55591a80-e9eb-11e9-8a38-164c7b22c381.gif)

I found a react component with a similar effect, and if it meet the requirement, I'll try to implement it with lit-element.

**Comment by sujato** [comment]
Nice, yes, that's the basic idea. One difference is that we do not want a shim (i.e. the dark element covering the rest of the page). The user must be able to see and interact with the page as normal.

**Comment by ihongda** [comment]
Okey, Bhante, I got it.

**Comment by ihongda** [comment]
![Peek 2019-10-14 17-05](https://user-images.githubusercontent.com/4037966/66740144-fee55380-eea4-11e9-9352-f6a8e98ce195.gif)

I made a rough prototype, realized the basic functions, and then optimized the appearance.

**Comment by ihongda** [comment]
[class="word"  ] It needs to be keep at present, but the new text page should be able to be remove.

**Comment by ihongda** [comment]
![Peek 2019-10-16 21-28](https://user-images.githubusercontent.com/4037966/66923861-2f232280-f05c-11e9-9765-01b188471974.gif)

Adjusted effect.

**Comment by ihongda** [comment]
![深度截图_选择区域_20191017094907](https://user-images.githubusercontent.com/4037966/66971344-6d076180-f0c3-11e9-91ec-85e2538420fc.png)

**Comment by sujato** [comment]
This is looking great. I am trying to get my local SC working on my laptop, hopefully I can do that and test this. But we’re going to need to test it on mobile too.

**Comment by ihongda** [comment]
I will submit the code later 😄 

I wonder PC users are more likely to see dictionary text near words so they don't have to look away from the bottom of their eyes.
But paper-tooltip has some drawbacks and the experience is not very good.

**Comment by sujato** [comment]
I understand, but if it’s an issue, a PC user can always just scroll the text so that it is near the bottom of the page. So I don’t think it will be a huge problem. Still, that’s what testing is for, we never know what it will be like until we actually use it for real.

**Comment by ihongda** [comment]
Okey，Bhante，I got it.
I'll keep the code that calls tooltip for now, if needed, I'll consider writing a lighter tooltip component to experiment with.

**Comment by sujato** [comment]
I have updated the styles.

- Remove duplicated `${this.currentDefine}`
- Make it a fixed height so it doesn't make people dizzy.
- Add keyboard shortcuts for moving forwards and backwards.
- Add "Help" dialog. 
- Make matching highlights for term in text and in lookup.
- Use transition to animate opening and closing.

I will add remaining 2-do items to the main issue.
