### ISSUE TITLE
Import texts from html-clean5 to working branch

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1491]
The cleaned and updated HTML texts must be pulled and used when upgrading the text pages. This must be done at the start of the text pages upgrade process, so we have plenty of time for testing.

**Comment by ihongda** [comment]
Ok, I will draft a new html5 texts based on the data structure of Bilara.

**Comment by sujato** [comment]
No, that's not what we want, in fact it is the other way around!

The updated HTML texts are correct as-is. The task is to test whether the new markup causes any bugs when they are used on the site.

It is the bilara HTML markup that is outdated and must be updated. However I have assigned Aminah to this task, as she is the one who has been working on this.

**Comment by ihongda** [comment]
Okey, Bhante 😄

**Comment by ihongda** [comment]
After checking, compared with the previous version, html-clean5 has modified several places:

1. <div class ='hgroup'> is replaced by <header>, <p> is replaced by <ul>
2. Removed some CSS classes
3. <aside> is replaced by <footer>

I have adjusted the CSS style file.
