### ISSUE TITLE
Text page settings for ATB

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1496]
## Background

Currently the text setting are accessed via a modal dialog. This has the disadvantage that you cannot see the changes as you make them. It would be better if the user can see the changes as they are applied.

Here is an inspiration for this idea:

http://apadanatranslation.org/text/chapter-1/poem-001.html

Go to Tools/Features and you can select various options. You can see the changes immediately, and in addition, they are highlighted as they happen. Let us use a similar idea for SC.

## Design

To make this work, we want to minimize the vertical height of the settings menu. This is especially critical for small screens. Thus let us make a sheet with the various items *horizontally*, and you can scroll horizontally to see them.

The basic idea is this:

- In the text pages ATB there is a tab item "Settings"
- When you click this, it opens the setting dialog.
- For all other tab items, they simply open a new page. This does not.
- Instead, an overlay ("scrollable sheet") appears over the text page, below the Tab bar. This overlay is set to width 100%, absolute position, and scrolls horizontally.
- The items for selecting textual tools are listed horizontally on this sheet.
- You can still see the text that is not covered by the sheet.
- When you click, the change happens immediately.
- In addition, a brief splash of background color highlights the change.
- For the lookup tools, when you activate them, 
  - the *bottom sheet* appears, 
  -  the first word in the middle paragraph of the page is automatically selected, a
  - the relevant entry shown in the dictionary sheet.
- The "scrollable sheet" appears at the same elevation level as the tab bar/toolbar.

Here is a rough mockup.

![tab-tools](https://user-images.githubusercontent.com/6112010/64943442-15e95380-d8af-11e9-8092-195e467513d2.jpg)

Here are the source files. In the mockup, only the ref buttons work, the rest are just for show.

[tab-tools.zip](https://github.com/suttacentral/suttacentral/files/3615260/tab-tools.zip)

**Comment by ihongda** [comment]
There are currently several options to achieve:
1. Refactor the toolbar using the paper component
2. Rewrite toolbar with MDC
3. Rewrite toolbar with other components

I prefer the second option, but at present MDC only released the pre-release version 0.12, which is not suitable for production environments, but can try it.

**Comment by sujato** [comment]
I would say to go ahead with the MWC, it should be reasonably stable.

BTW, the naming conventions are confusing, as seems typical at Google! "MDC" is the abbreviated form of "Material Design Components", which is the parent project. The ones we want are "MWC", which applies "MDC" but uses LitElement. The actual name is "Material Components Web Components" (!) but the abbreviation is MWC.

https://github.com/material-components/material-components-web-components

**Comment by sujato** [comment]
- REFERENCE: only seems to work if "Pali" is activated
- NOTES: "none" is the same as "Tooltip on asterisk". Should have "Tooltip on asterisk" as default, and user can select "None" which hides the asterisk.
- "View original text with translation": Should have "Plain" by default
- mwc-form isn't respecting styles

**Comment by ihongda** [comment]
> * REFERENCE: only seems to work if "Pali" is activated
> * NOTES: "none" is the same as "Tooltip on asterisk". Should have "Tooltip on asterisk" as default, and user can select "None" which hides the asterisk.
> * "View original text with translation": Should have "Plain" by default

Thx, Bhante, I've adjusted the logic of the settings.

> * mwc-form isn't respecting styles
yes, it's a little bit of a hassle.

**Comment by sujato** [comment]
Actually, they have a theming guide now, the styles can be easily changed. I have made the chasnges and will push them through.

 The guide is still not published but you can read it here:

https://github.com/arthurevans/material-components-web-components/blob/7510d5df9e107109073a99242ee6371cfd8efc52/docs/theming.md

**Comment by ihongda** [comment]
> Actually, they have a theming guide now, the styles can be easily changed. I have made the chasnges and will push them through.
> 
> The guide is still not published but you can read it here:
> 
> [arthurevans/material-components-web-components:docs/theming.md@`7510d5d`](https://github.com/arthurevans/material-components-web-components/blob/7510d5df9e107109073a99242ee6371cfd8efc52/docs/theming.md)

Thx, Bhante, 
but it seems that we can't control some styles at will, Let me read the guide carefully:)

**Comment by sujato** [comment]
Hongda, can we make one addition to the top sheet? One more setting, using a switch:

```
<details><summary>Show highlighting</summary>
<p>Where applicable, highlight the text to show extra details about the structure.</p>
</details>
```
Then just an on/off switch. When you  turn it on, it puts `class='highlight'` onto the `<article>` That's it!

**Comment by ihongda** [comment]
> Hongda, can we make one addition to the top sheet? One more setting, using a switch:
> 
> ```
> <details><summary>Show highlighting</summary>
> <p>Where applicable, highlight the text to show extra details about the structure.</p>
> </details>
> ```
> 
> Then just an on/off switch. When you turn it on, it puts `class='highlight'` onto the `<article>` That's it!

Yes, of course, Bhante:)

**Comment by ihongda** [comment]
![alt](https://ibb.co/k05330J)

Bhante, Are we going to implement this feature? I think it's good for enhancing the user experience.

**Comment by ihongda** [comment]
[Highlight related structures](https://ibb.co/k05330J)

Bhante, Are we going to implement this feature? I think it's good for enhancing the user experience.

**Comment by sujato** [comment]
Sorry I missed this at the time. But yes, I think this is a good idea. not essential for launch, but if it's easy, then go ahead.
