### ISSUE TITLE
server error on download page

### ISSUE THREAD

**Issue by Yyatiko** [suttacentral/suttacentral#1501]
#### Description:

The link on the top of the page https://suttacentral.net/downloads are down: Server error.

It is impossible to download the The latest version of key translations on SuttaCentral.

Thank

**Comment by ihongda** [comment]
Hello Yyatiko, thank you for your feedback and we will deal with it as soon as possible. 😄

**Comment by ihongda** [comment]
Hello, Yyatiko, our engineers have solved the problem :smile:
