### ISSUE TITLE
Remove unnecessary social sharing images

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1513]
In client/img we have three social sharing images.

- social_image.png
- social_sharing.png
- social_sharing_image.png

Only one of these should be used, the others should be deleted. I believe the correct one is social_sharing.png,

**Determine which social sharing image is used and delete unused images**

Also, the image is not properly optimized. Here is a smaller file run through tinypng.com 

[tinified.zip](https://github.com/suttacentral/suttacentral/files/3689391/tinified.zip)

**Make sure that all images are fully optimized**

**Comment by ihongda** [comment]
Old Shared images have been removed in master branch and replaced with optimized images.
