### ISSUE TITLE
Loading legacy html texts into Arango is broken for Pali (at least)

### ISSUE THREAD

**Issue by chansikpark** [suttacentral/suttacentral#1518]
#### Description:

It appears that in the process of resolving #1094, a file containing mappings from Mahasangiti `ms` references to various other Pali editions was restructured (suttacentral/sc-data@d669d888eb6f87decab83f1a82ab1de348ad7c19 ff.). The file in question, `pali_concord.json`, is now made obsolete by `all_pali_concordance.json`.

However, `pali_concord.json` is still used by the `make load-data` task, specifically when determining the PTS volume-and-page references for legacy html texts in Pali. This results in the task failing when building the app from scratch, and ultimately a bunch of the texts aren't loaded. The code that uses `pali_concord.json` needs to be retired out of the main line (or made to fail more gracefully), or updated in line with the new structure.

#### Steps to reproduce:

0. Run data loading from scratch

1. Go to https://staging.suttacentral.net/bv

2. None of the texts are loaded:

#### Expected behaviour:

There should be "1 edition of the root text", multiple translations available, and there should be vol-page reference to a PTS edition.

#### Screenshots:

On staging, Buddhavamsa texts aren't loaded and have no vol-page references:

![Screenshot from 2019-10-09 18-13-32](https://user-images.githubusercontent.com/16063972/66468283-d9c99d00-eac0-11e9-9d23-6d948900bae7.png)

This is what their values should be:

![Screenshot from 2019-10-09 18-14-30](https://user-images.githubusercontent.com/16063972/66468449-201efc00-eac1-11e9-8d95-fbdc39696533.png)

**Comment by sujato** [comment]
Thanks, i will alert our developers right away.

**Comment by chansikpark** [comment]
Confirmed fixed on staging

![Screenshot from 2019-11-27 13-30-51](https://user-images.githubusercontent.com/16063972/69693855-27a26f00-111a-11ea-9477-47dd21275ef2.png)
