### ISSUE TITLE
Text images for Pali texts

### ISSUE THREAD

**Issue by chansikpark** [suttacentral/suttacentral#1535]
#### Description:

Text page images in the new site for Pali texts are (1) no longer viewable for segmented texts, (2) not viewable for some texts even though the images are available and (3) viewable for other texts only when "textual information" is toggled.

(1) No longer working (segmented texts):
- DN, AN, MN, SN

(2) Never worked (but images available):
- Kp, Pe, Pv, Vv, pli-tv-bu-vb-pj, pli-tv-bu-vb-pc, pli-tv-pvr

(3) Working (only after toggling "textual information" even if it was already on):
- Bv, Cnd, Cp, Dhp, Mil, Mnd, Ne, Ps, Snp, Ud, pli-tv-kd, 

(4) These are working perfectly:
- Thag, Thig

(Note: these were tested by checking the first text in each collection)

Also, the `sc-text-image` element uses an [old version](https://www.npmjs.com/package/viewerjs/v/0.10.0) of a third party image display library `viewerjs`. @sujato notes: "It is by no means mandatory or optimized. When we built this it just happened to be one that worked with a minimum of fuss so we went with it. But there may be a better option out there!"

Note that the legacy site hosts a [text file](https://legacy.suttacentral.net/text_images/contents.txt) containing a list of image file names that are available for display. This file is loaded into the `images` collection in Arango. The images themselves are also designed to be accessed from the legacy website ([qv](https://github.com/suttacentral/suttacentral/blob/28e0dbe821f68571f41b4dc8da96bb8ffd55b760/client/constants.js#L4)). The former has 29,239 lines while the Arango collection has 12,993 entries. Filtering logic can be found in [images_files.py](https://github.com/suttacentral/suttacentral/blob/master/server/server/data_loader/images_files.py#L16). The other ~16,000 images are from a Thai edition. (see #1536)

#### Steps to reproduce:

1. Navigate to a Pali text page (eg. https://suttacentral.net/dn1/pli/ms)

2. Enable the "View textual information" switch by clicking on the gear icon to access "Text settings".

![Screenshot from 2019-11-09 10-17-31.png](https://images.zenhubusercontent.com/5d38485218e9de29f0225184/c136b6d9-9861-4ecf-a52b-bf8af3c2a26e)

3. Note the lack of a direct means to view text images.

![Screenshot from 2019-11-09 10-18-11.png](https://images.zenhubusercontent.com/5d38485218e9de29f0225184/24bbf9bd-fb75-47fb-99f6-33f6912684be)

#### Expected behaviour:

A clickable book icon should appear adjacent to each of the "PTS-VP-PLI" markings. Once clicked, an image of the page from the corresponding PTS book featuring at least the beginning of the corresponding paragraph/section should be shown.

In the legacy site, when viewing Pali texts, after enabling textual information in the sidebar, a small book icon shows up next to each PTS paragraph/section marking that, once clicked, displays an actual image from the Pali Text Society's books of the page that features the beginning of the particular paragraph/section.

![Screenshot from 2019-11-09 09-36-32.png](https://images.zenhubusercontent.com/5d38485218e9de29f0225184/9f36dab2-2dbb-4dcb-860d-3577c12f540a)

![Screenshot from 2019-11-09 09-37-39.png](https://images.zenhubusercontent.com/5d38485218e9de29f0225184/24706a06-01ac-4808-9dc7-9f52fb05624d)

#### Related Issues:

 https://github.com/suttacentral/suttacentral/pull/513

**Comment by thesunshade** [comment]
I'm going to close this since it applies to the old version of the site.
