### ISSUE TITLE
PWA install review

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1542]
The PWA features and install process were cutting edge when released and we should investigate whether they should be upgraded or refined. This is not an urgent issue, but is an area we should check back with from time to time. 

Potential issues:

- Updating of standards or best practices
- Some browsers appear to be PWA compatible but not registering as such, see [here](https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/429).
- Consider using `<pwa-install>`. This makes the install process smoother and more "native" on various devices. 
    - https://medium.com/pwabuilder/installing-progressive-web-apps-b7274ebffe80
    - https://mobile.twitter.com/Justinwillis96/status/1192605368901230592
- Also consider web bundles: https://web.dev/web-bundles/

See also #1339 #1427

**Comment by michaelh-sc** [comment]
- I think that the current Add to Home Screen is still a best practice, supported by Google, also an app store entry that is verified is best practice, I think.
- That [bug report](https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/429) does highlight that D&D has same name on home screen, I thought that was my own app but that really needs addressing.
- With Edge not prompting for home screen, this might be fixable by looking through pwabuilder code and adding it to site. I don't see the prompt to add to Home Screen in Firefox if it's already been in added in Chrome on my phone, could have been a browser cache thing perhaps.
- People are already weary of in-browser stuff that prompts to install apps in a way that doesn't feel familiar - pwa-install's interface doesn't look native (and it isn't). I would never click through that install screen if I saw it myself.
