### ISSUE TITLE
Give language details on "title" attribute in language icons in sidebar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1574]
When hovering over the language icons in the sidebar, a user should see the name of the language.

There should possibly be a bit of explainer texts, too, perhaps: "root text: Chinese" or "original language: Chinese".

**Comment by ihongda** [comment]
The pseudo element can't find a place to add title at present, but can try to modify the title of the first level menu to achieve this function.

**Comment by ihongda** [comment]
![abcd](https://user-images.githubusercontent.com/4037966/71628284-2f31c800-2c32-11ea-9fec-4442355976d7.gif)

Bhante, should we add a zoom effect to language icons?

**Comment by ihongda** [comment]
Or

![ddfe](https://user-images.githubusercontent.com/4037966/71628584-9ac86500-2c33-11ea-960e-dfcb3b1038f0.gif)

**Comment by sujato** [comment]
Ahh, yes I forgot they were pseudo elements. In that case, yes, we would have to add the language to the title attribute for the menu item as a whole. 

Currently the title attribute merely repeats the name of the item, which is not good. The title attribute has accessibility issues, and as a rule, it's best to avoid polluting the title attribute with unnecessary information. A screen reader, for example, might read "Dīgha Nikāya" twice. 

How about we remove the item name and put something like this instead: 

    title ="root language: Pali"

As for the animations, best leave it, I don't think it is really solving a problem.

What we do need to do, though, is to look more closely at how we can integrate the translated title names into the toolbar. That's not an easy thing!

**Comment by ihongda** [comment]
>title ="root language: Pali"

I think it works 😄

**Comment by ihongda** [comment]
![efg](https://user-images.githubusercontent.com/4037966/71673312-6aa7d000-2db3-11ea-83f4-fed563788a3a.gif)
