### ISSUE TITLE
Requesting to add Kannada sutta

### ISSUE THREAD

**Issue by akileshv** [suttacentral/suttacentral#1577]
Requesting to add **[Kannada](https://en.wikipedia.org/wiki/Kannada)** sutta's to the  [suttacentral](https://suttacentral.net/), I can provide sutta documents from **[Mahabodhi Society Bangalore](https://mahabodhi.info/)** since they have a large collection of Kannada sutta document in their publication and I can also provide technical help if needed.

**Comment by sujato** [comment]
Thank you so very much, this is wonderful! I have known about your excellent work for some time via Ven Bodhidhaja, and we would be delighted to work together to host these translations.

**Comment by akileshv** [comment]
thanks for accepting our request.
Bhante, please provide us more details about the process and communication channels details to conduct our future meetings. My email address is **akileshv@mail.com**

**Comment by sujato** [comment]
This work is underway, I will close the issue.

**Comment by akileshv** [comment]
Thank You, Bhante 🙏🙏🙏
