### ISSUE TITLE
Change background color of prev/next bar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1579]
Currently prev/next bar has the primary app color as background.

Change it to `var(--sc-secondary-text-color)` to match the top of the sidebar drawer.

**Comment by ihongda** [comment]
![深度截图_选择区域_20200210200202](https://user-images.githubusercontent.com/4037966/74148362-3cce6a80-4c40-11ea-9308-139f08b46d1e.png)

Bhante, does this meet the requirements?
