### ISSUE TITLE
Error message says "you're offline" when it is a different error

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1580]
The error message says "You're offline". But if I go to an incorrect URL it says the same thing even though I am online:

https://suttacentral.net/sn41.6/en/bodhi

The error message should not itself be an error!

Either:

1. Give a generic message that is not misleading: "Error!"
2. Give an error message that is useful and correct per context: "You're offline" when someone is actually offline, "Incorrect URL" when serving an incorrect URL, etc.
3. When someone uses search, or something else that requires a connection, the error message should tell them this. "Please connect to the internet to use search."

**Comment by ihongda** [comment]
![深度截图_选择区域_20200415204605](https://user-images.githubusercontent.com/4037966/79338881-99107c00-7f5a-11ea-85a1-b8969004ee57.png)

More error types have been added and applied first to sc-page-search.js
