### ISSUE TITLE
Check Pali files against accidental loss

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1601]
As a final step, we must ensure that all the Pali texts have made it into the final thing with no textual loss. 

This is done by diffing against the original Mahasangiti text. We have an archive on Github, but it contains errors, so use this one.

Diffing is not straightforward.

- The Mahasangiti files include markup and navigation info
- The SC files have heading structures that may differ

We only want to diff the actual text and headings

- Remove all markup
- Remove navigation, metadata, variant readings, comments, etc. from Mahasangiti.

Things that are insignificant and should be excluded from diffing:

- new lines
- punctuation
- special characters apart from āīūṇṭḍḷṃṁñṅ
- case
- numbers
- spaces
- files
- folders

[ms_blake.zip](https://github.com/suttacentral/suttacentral/files/4597720/ms_blake.zip)

[ms_sujato.zip](https://github.com/suttacentral/suttacentral/files/4597704/ms_sujato.zip)

[ms_yuttadhammo.zip](https://github.com/suttacentral/suttacentral/files/4597714/ms_yuttadhammo.zip)

**Comment by michaelh-sc** [comment]
This coincides with an issue I faced with subtitling suttas recited in their expanded form. Being able to view suttas in the unexpanded form based on the metadata files is a far more difficult thing to achieve and perhaps beyond this this issue, but identifying what is in the elisions programmatically might not be impossible.

Perhaps what exact portions of Mahasangiti (at word-level) have been taken out could be generated and placed into the metadata folder.

This would involve guessing which word is the replacement in any sequences repeated where only a specific word is changing for each repetition, and identifying exactly where possible complete elisions are if they already exist elsewhere in the sutta. 

Re-adding punctuation and re-doing SC formatting would be a fair bit harder though I think.

**Comment by sujato** [comment]
Unless I am mistaken, I don't believe this relates to the issue at hand.

But more generally, regarding the notion of regenerating text, I have persistently argued that this is wrong in principle and impossible in practice, if pursued as a general strategy. In specific limited instances, for example, to make a text for a class, or do a detailed study, then sure. But you cannot generalize from such instances. The complexities are great, and can only be resolved by careful study of each passage by a Pali expert. You can't just look at a few examples and assume it is doable programmatically. It is not.

Moreover, to even attempt it is to move further away from the actual canon as passed down by the tradition, which carries its own limitations based on the media and technologies of the time. IMHO, to generate a new set of texts is just wrong. It is the canon, we carry it forward and bring it to light. We don't, in our textual presentation, judge it and improve it.

**Comment by michaelh-sc** [comment]
I'd like to remove that flippant comment from this issue unless you'd prefer this recorded for others to reflect on which would be fine with me. I hope I didn't cause any offence - of course back-referencing a huge collection of texts edited with such care wouldn't be possible programmatically.
