### ISSUE TITLE
Migrate to Stripe Checkout for payments

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1614]
Stripe has updated their payment method. The new way is to do the payment on Stripe itself, so we just have a button that sends data to stripe. No need to worry about forms, submissions, security, accessibility, and all that. Yay!

Stripe has always set great standards for both UX and security, so this looks really cool.

https://stripe.com/docs/payments/checkout

https://stripe.com/docs/payments/checkout/migration

## How it will work

So far as I understand, the basic donation page will remain unchanged.

https://suttacentral.net/donations

However, when you click the "donate" button, it will take you to Stripe to fulfill all the details. We set it up on Stripe, and that's it. 

We still need to load `stripe.js` though, so the tracking issue remains:

https://github.com/suttacentral/suttacentral/issues/1613

If we cannot remove this, then we must put a statement informing users.

## Security

We have recently been getting a lot of fraudulent donations via bot, and need to do something about it. Updating to the latest version of stripe is obviously a start.

We have been in contact with Stripe about this, and they recommend implementing reCaptcha. However, if more security is needed I would rather avoid using a Google product. [hCaptcha](https://www.hcaptcha.com/) would be better.

However, all captcha services are poor UX and easily hacked. A newer approach is using "proof of work". What this does is give your browser a problem to solve before the form is submitted. This creates a computational cost that is, in theory, unobtrusive for genuine users but prohibitive for bots, which would have to solve these problems at a massive scale.

https://friendlycaptcha.com/

Another approach is to use the new Web Authentication API:

https://webauthn.guide/

https://w3c.github.io/webauthn/

https://webauthn.me/

https://caniuse.com/?search=webauthn

## Stripe/lit integration

I'm not sure if this is relevant, it seems to use the older stripe method?

https://github.com/bennypowers/stripe-elements/tree/master

**Comment by Prograd** [comment]
@sujato  I've pushed the recent changes, you should be able to process one time payment as well as monthly. However there are still a few issues which I'd like to discuss on standup. Please do not merge it until we talk about it.
