### ISSUE TITLE
Nav cards: yellow brick road (basic)

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1662]
The concept of the "yellow brick road" is currently applied in the sidebar, visible as "green dots". These indicate that there is a translation in the user's language.

In nav cards, the green dot is replaced by an actual yellow brick! 

- If the card contains translations in the user's language, display a yellow brick
- If there are no translations in the user's language, display nothing.

**Comment by sujato** [comment]
This is mostly working, but is not always consistent. For example, if I navigate to the vagga level I can see the yellow brick. However, if I navigate to the suttaplex list and then back again, the yellow bricks are no longer there.


![Screencast from 08-08-20 09_15_58](https://user-images.githubusercontent.com/6112010/89695842-d315eb80-d958-11ea-97c6-9a74e0b58cdb.gif)

**Comment by sujato** [comment]
Check mark in yellow brick must be icon, not character. See also this comment:

https://github.com/suttacentral/suttacentral/issues/1672#issuecomment-672377136

**Comment by ihongda** [comment]
> This is mostly working, but is not always consistent. For example, if I navigate to the vagga level I can see the yellow brick. However, if I navigate to the suttaplex list and then back again, the yellow bricks are no longer there.
> 

This problem has now been fixed.

**Comment by ihongda** [comment]
The localized file for the title is in the `/localization/sc-navigation` directory.

**Comment by sujato** [comment]
I can confirm, the bricks now appear consistently at different levels. :+1:
