### ISSUE TITLE
Nav cards: steps (basic)

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1664]
By default, each nav card leads to the **next level** of the hierarchy. The link is the whole card.

The steps themselves are **identical with the current implementation in the sidebar**. The data for this is, I believe, in sc-data/structure.

For example, consider DN. here the hierarchy is: 

- DN
  - vagga
     - sutta

So the default navigation proceeds from the whole nikaya to the list of vaggas, to the suttas for each vagga.

Let us take imagine someone is navigating to DN 3.

First they are on https://staging.suttacentral.net/pitaka/sutta

>- DN
> - MN
>- SN
> - AN
>- KN

Then click on DN and see:

>- Silakkhandhavagga
>-  Mahā Vagga
>-  Pāthika Vagga

Then click on Silakkhandhavagga and see the 13 suttas in that vagga. Go to the sutta that you want!

Okay, now consider MN. here we have:

- MN
    - pannasa
        - vagga
            - sutta

It's exactly the same, except there is an extra level in the hierarchy, the pannasa (group of 50 discourses).

The default navigation proceeds from the whole nikaya to the list of pannasas, to the vaggas for each pannasa, to the suttas for each vagga.

As a final example, consider SN, which has perhaps the most deeply nested hierarchy of any collection.

- SN
   - Vagga
       - samyutta
           - (pannasa)
               - vagga
                     - sutta

We start with the five "big" vaggas, then the samyuttas for each vagga. Some of the longest samyuttas have pannasas, others do not. Then there is the "little" vagga as usual, and finally the sutta.

**Comment by sujato** [comment]
This is not implemented.

**Comment by sujato** [comment]
Reviewing latest changes, based on the same cases I tested above.

## DN

This is now incorrect. As stated in previous comment, it was fine then. But now there is another step where it goes from vagga to list of suttas, then to an individual suttaplex. This is incorrect.

![Screenshot from 2020-08-27 09-21-27](https://user-images.githubusercontent.com/6112010/91366387-ed036980-e846-11ea-80b3-323480d2dacf.png)

As stated above, there is no list of plain suttas. There is only the list of suttaplexes. This is correct.

![Screenshot from 2020-08-27 09-23-47](https://user-images.githubusercontent.com/6112010/91366499-3bb10380-e847-11ea-9f95-4173132c6e97.png)

## MN

Looks good!

## SN 

Looks good!

**Comment by sujato** [comment]
The DN issue appears to be solved, and the three test cases above now work correctly. I'll try out testing other cases, too!

**Comment by sujato** [comment]
SN is not working in cases where there is a pannasaka inside a samyutta.

Khandhasamyutta > `sn/sn-khandhavaggasamyutta/sn22` which correctly displays the three pannasakas:

![Screenshot from 2020-08-29 10-28-19](https://user-images.githubusercontent.com/6112010/91624243-73a07e00-e9e2-11ea-9f1e-ac1d2d29e39a.png)

So far so good!

But if we click on the pannasaka, we get the full list of suttaplexes for that pannasaka. Eg. at `sn22-mulapannasaka`  we have sn22.1 all the way to sn22.52

![Screenshot from 2020-08-29 10-30-06](https://user-images.githubusercontent.com/6112010/91624280-ad718480-e9e2-11ea-9edc-2d6a8339864d.png)

It should show, rather, the list of five vaggas in the pannasaka.

**Comment by ihongda** [comment]
>But if we click on the pannasaka, we get the full list of suttaplexes for that pannasaka. Eg. at sn22->mulapannasaka we have sn22.1 all the way to sn22.52

This bug has been fixed.

**Comment by sujato** [comment]
The basic steps appear to work correctly, I'll close this issue but we should keep checking.
