### ISSUE TITLE
Nav cards: essays

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1666]
We have a variety of essays and resources in the SC static pages. However currently these are not very well connected with the relevant texts. Let us add relevant essays to the nav cards.

- If there is an essay on SC about the current nav card, include it.

Include the following:

- https://suttacentral.net/discourses
- https://suttacentral.net/vinaya
- https://suttacentral.net/abhidhamma
- https://suttacentral.net/dn-guide-sujato
- https://suttacentral.net/mn-guide-sujato
- https://suttacentral.net/sn-guide-sujato
- https://suttacentral.net/an-guide-sujato

Others can be added if we have them.

- Localize where possible.
- Use the title of the essay for the link content.

**Comment by sujato** [comment]
- titles are incorrect
- essays are in the wrong place. The guides for dn, mn, etc. apply to the **Pali** text only, thus they should be at Dīghanikāya (DN), not at the general "long" category, which includes DA, etc.

**Comment by sujato** [comment]
There is a bug in the `essay` display. If I navigate from the Home page the essay appears.

![Screenshot from 2020-08-11 09-45-15](https://user-images.githubusercontent.com/6112010/89841858-6c423d80-dbb7-11ea-8a58-158c6a5e195d.png)

However if I navigate back from a lower level, it does not appear.

![Screenshot from 2020-08-11 09-49-34](https://user-images.githubusercontent.com/6112010/89842138-1de16e80-dbb8-11ea-878d-a87cb623d2ce.png)

The attribute `hidden` has been wrongly applied.

**Comment by ihongda** [comment]
> There is a bug in the `essay` display. If I navigate from the Home page the essay appears.

This bug has been fixed.

**Comment by ihongda** [comment]
>titles are incorrect: always use the actual title of the essay, i.e. the text inside <h1>.

>essays are in the wrong place. The guides for dn, mn, etc. apply to the Pali text only, thus they should be at Dīghanikāya (DN), not at the general "long" category, which includes DA, etc.

This bug has been fixed.

**Comment by sujato** [comment]
Everything seems good, except I find that the essays don't always appear. I still find `hidden` applied sometimes, and I don't know why. I can't discern any pattern.

![Screenshot from 2020-09-19 07-40-44](https://user-images.githubusercontent.com/6112010/93648210-948e4900-fa4d-11ea-893c-431adcfd5f54.png)

**Comment by ihongda** [comment]
>Everything seems good, except I find that the essays don't always appear. I still find hidden applied >sometimes, and I don't know why. I can't discern any pattern.

Okay, Bhante, I'll check it again.

**Comment by ihongda** [comment]
>Everything seems good, except I find that the essays don't always appear. I still find hidden applied >sometimes, and I don't know why. I can't discern any pattern.

Bhante, this problem has been fixed and pushed to `Hongda-work` branch.
