### ISSUE TITLE
Universal toolbar: breadcrumbs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1672]
A breadcrumb menu appears at the left of the Universal toolbar.

- The first item is always "Home".
- Applies to static and search pages as well as texts and navigation
- Always shows the full hierarchical position of the text. 

## Behavior

The breadcrumbs indicate the position of that page within the site hierarchy, **not** the user history. Thus if I click on a link to suttacentral/mn it shows the breadcrumbs just as if I had navigated there. In other words, **the breadcrumbs for a particular view are always the same**.

- When the user navigates to a new page, it is added as a breadcrumb item.
- Breadcrumbs are clickable
- Current page is prominent but not clickable
- Breadcrumb menu is horizontally scrollable if there are too many items (especially for mobile). (This is the same as the tab bar.)

## Content of breadcrumb items

Since the suttas can become deeply nested, use the shortest form of name available, to preserve horizontal space.

- Use acronym where available, eg. “MN” not “Majjhima Nikāya”. (Remember, **never** use the `uid` and transform it to uppercase, **always** use the explicit `acro` field from `uid_expansion`.)
- Use translated form if there is no acronym.
- Use root form if there is neither acronym nor translation.

⚡ Do not add "Sutta" or other unnecessary words. ⚡

See the "gingerbread" mockup for an example in the case of DN.

As another example, instead of, say:

> Home > Sutta > Minor > Khuddhakanikāya > Udāna > Tatiyabodhi Sutta

It should be:

> Home > Discourses > Minor > KN > Ud > Ud 1.3

The full title is visible to the user just below in the titlebar, it does not need to be in the breadcrumbs as well.

## Style

The breadcrumbs are not defined in Material Design. My design, however, follows general MD principles. The main point is that the touch target for each item must be large.

- The clickable area or touch target must be identical with the region that is visually indicated as clickable.

**Comment by sujato** [comment]
There are currently some bugs in the implementation. I have these three pages all showing at the same time, and they are all in error.

![Screenshot from 2020-07-20 09-53-21](https://user-images.githubusercontent.com/6112010/87888260-24743e80-ca6f-11ea-9342-9426a58ea213.png)

1. The left page is incorrect, as it only shows Home and the Sutta. 
    - **The breadcrumbs indicate the primary canonical position of that page**. This means that they always display the full hierarchical position of whatever the current view is. This is the primarfunction of breadcrumbs.
2. The middle page shows a series of suttas, not the hierarchy. 
3. The right side page shows a sutta title, it should be Home > Search.

**Comment by sujato** [comment]
Currently the breadcrumbs rely on inserting the character `❭` as a pseudo-element. This glyph is **not** included in Skolar, and is rendered with local fonts:

![Screenshot from 2020-08-09 09-02-02](https://user-images.githubusercontent.com/6112010/89721288-310d0680-da1f-11ea-88f7-03ad52689d7b.png)

We should never rely on local fonts, as they give an unreliable user experience. Glyphs may be missing, or differently sized or shaped. Always use the appropriate material icon.

In this case, I think either `chevron_right` or `arrow_forward_ios`.

**Comment by sujato** [comment]
There are currently some bugs in the implementation. I have these three pages all showing at the same time, and they are all in error.

![Screenshot from 2020-07-20 09-53-21](https://user-images.githubusercontent.com/6112010/87888260-24743e80-ca6f-11ea-9342-9426a58ea213.png)

1. The left page is incorrect, as it only shows Home and the Sutta. 
    - **The breadcrumbs indicate the primary canonical position of that page**. This means that they always display the full hierarchical position of whatever the current view is, and this is always the same. This is the primary function of breadcrumbs.
2. The middle page shows a series of suttas, not the hierarchy. 
3. The right side page shows a sutta title, it should be Home > Search.

These are just some examples, there are other cases, but as they are covered in the original spec I will not repeat them.

**Comment by ihongda** [comment]
> Static pages display the correct item. However, they have an `undefined` link. The static page item should have no link.
> 

This problem has now been fixed.

**Comment by ihongda** [comment]
> Currently the breadcrumbs rely on inserting the character `❭` as a pseudo-element. This glyph is **not** included in Skolar, and is rendered with local fonts:
> 
 
> We should never rely on local fonts, as they give an unreliable user experience. Glyphs may be missing, or differently sized or shaped. Always use the appropriate material icon.
> 
> In this case, I think either `chevron_right` or `arrow_forward_ios`.

Has been replaced with <MWC-icon>chevron_right</mwc-icon>

**Comment by sujato** [comment]
> > Static pages display the correct item. However, they have an `undefined` link. The static page item should have no link.
> 
> This problem has now been fixed.

They no longer have "undefined", but they still have a link. When you click a static page, it triggers a page refresh. It should do nothing, there should be no link there.

![Screenshot from 2020-09-17 10-18-17](https://user-images.githubusercontent.com/6112010/93405074-5539ee00-f8cf-11ea-86ab-a3fa246ae5ab.png)

In the main text navigation, when you click the last item, it behaves correctly, since there is no page refresh. However, the link is still present in the HTML. This should be removed: only use a link when you actually want to link something. 

Also, as a minor detail of styling, it would be better if there was no ripple effect either.

![Screenshot from 2020-09-17 10-21-46](https://user-images.githubusercontent.com/6112010/93405322-017bd480-f8d0-11ea-9939-f087308597e6.png)

**Comment by ihongda** [comment]
>They no longer have "undefined", but they still have a link. When you click a static page, it triggers >a page refresh. It should do nothing, there should be no link there.

This problem is fixed, has been submitted to Hongda-work branch.

**Comment by sujato** [comment]
Good, I can confirm the fix!
