### ISSUE TITLE
Context toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1675]
Every page has a context toolbar immediately below the universal toolbar.

- Context toolbar is site primary color
- It is a little taller than the universal toolbar, maybe 8px or 16px taller.
- On the Home page, the context toolbar uses the tall "prominent" style.
- On all other pages, use the standard size. This includes the static pages, which currently have the tall toobar, this is a mistake.

**Comment by sujato** [comment]
Still uses the "prominent" toolbar for static pages, this must be removed. The "prominent" style is a special style for the Home page only.

![Screenshot from 2020-08-08 10-14-08](https://user-images.githubusercontent.com/6112010/89697822-47548d00-d961-11ea-8d22-d9b5776ece7a.png)

**Comment by sujato** [comment]
Still uses the "prominent" toolbar for static pages, this must be removed. The "prominent" style is a special style for the Home page only.

![Screenshot from 2020-08-08 10-14-08](https://user-images.githubusercontent.com/6112010/89697822-47548d00-d961-11ea-8d22-d9b5776ece7a.png)

**Comment by sujato** [comment]
Prominent toolbar problem is fixed!

However:

- scroll behavior is still not fixed. 
- static page toolbar incorrectly adds site title on scroll. Site title appears only on Home page! 
    - In other words, a toolbar only ever has ONE title.

![Screenshot from 2020-08-27 08-58-43](https://user-images.githubusercontent.com/6112010/91365204-e6272780-e843-11ea-9496-bea25bc3208a.png)

**Comment by ihongda** [comment]
>static page toolbar incorrectly adds site title on scroll. Site title must appear only on Home page!
>In other words, a toolbar only ever has ONE title.

This problem is fixed!

**Comment by sujato** [comment]
The only remaining issue now is the scroll behavior.

**Comment by sujato** [comment]
Actually scroll behavior pertains to the whole app bar not just the context toolbar, so I will close this and re-open the app-bar issue.
