### ISSUE TITLE
Context toolbar: title

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1676]
On the left of the context toolbar there is a page title. 

- *Here is a REVISED PROPOSAL*

For the title, use the **ROOT NAME**.

Why? Because in the translated texts, we can then see both the translated and root titles.

Compare the following. On the left is the current segmented text view, on the right, the legacy text. The legacy text shows both root and translated title, and hence is more informative.

![Screenshot from 2020-12-17 07-59-17](https://user-images.githubusercontent.com/6112010/102406086-2baf7080-403e-11eb-8a9d-73ff03cfc39b.png)

***

- Every page has a title in the context toolbar
- The title is always the same as the MAIN TITLE in the card that was clicked to get to that view.

For example:

- On the HOME page, the first card has the main title "Discourses". Click that!
- The next page is /pitaka/sutta. This has the title in the toolbar "Discourses".

**Comment by sujato** [comment]
The titles are currently mostly incorrect. Tell me the source files for these and I will ensure they are corrected.

**Comment by ihongda** [comment]
> The titles are currently mostly incorrect. Tell me the source files for these and I will ensure they are corrected.

The localized file for the title is in the /localization/sc-navigation directory.

**Comment by sujato** [comment]
Thanks, I will look into this.

**Comment by sujato** [comment]
There is a bug on the search results pages, the title is not correct, it should be the same as the old SC.

**Comment by sujato** [comment]
There is still a bug here. The context toolbar is using data from sc-data/structure/division. This folder is deprecated and should be removed.
