### ISSUE TITLE
Context toolbar: icons

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1677]
At the right of the context toolbar are icons that indicate primary actions for that page.

- Context icons may change per context

Because these actions are more specific and less general than say "search" or "menu", use icon + text to distinguish them. (This is why the context toolbar must be a little taller than the universal toolbar.)

These icons are to start with, we may add more over time.

- On nav card pages (including suttaplex) have "compact" icon.
   - This activates "compact view"
- On text pages, have 
   - (i) icon for information
   - "View" icon for text tools

**Comment by sujato** [comment]
Ignoring the search and menu icons, currently we have:

- Navigation pages: 
    - dark mode toggle 
    - compact view toggle
- text pages: 
    - dark view toggle
    - "information" metadata (present, but the metadata is not included.)
    - "tools" sheet (partially functional)

This seems good!

**Comment by sujato** [comment]
The static pages and search pages display the "spacing" toggle. 

This is incorrect. The "spacing" toggle should only be displayed on pages where it has an effect.

**Comment by ihongda** [comment]
> The static pages and search pages display the "spacing" toggle.
> 
> This is incorrect. The "spacing" toggle should only be displayed on pages where it has an effect.

This bug has been fixed.

**Comment by sujato** [comment]
> The "spacing" toggle should only be displayed on pages where it has an effect.
>
>This bug has been fixed.

Can confirm. I believe this issue is complete and will close it.
