### ISSUE TITLE
 Nav cards: block links

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1679]
It is common for cards to be clickable across the entire surface. Call these "block links". Such block links are easy to do poorly, and hard to do well. In my mockup I used a very naive HTML solution, but this suffers a number of problems:

https://css-tricks.com/block-links-are-a-pain-and-maybe-just-a-bad-idea/

Here is an excellent article that specifies exactly how to solve all the problems with block links:

https://css-tricks.com/block-links-the-search-for-a-perfect-solution/

And lucky for us, here is a web component that implements the solution. Let's use it!

https://www.npmjs.com/package/@alangdm/block-link

## Implementation

In the mockup I made, the basic idea is that:

1. The block link is the main default navigation option.
2. The main default is **also** represented by a button (else people don't know it's supposed to be clickable)
3. Other navigation options **may** be present, depending on the specific card and context.

**Comment by ihongda** [comment]
Nice component!

**Comment by sujato** [comment]
Block links are working well, I will close this issue.
