### ISSUE TITLE
Consider snowpack with esbuild as new bundler

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1680]
SC currently uses webpack for bundling, minifying, and tree-shaking. This is an area that is undergoing very rapid evolution. More modern tools use better standards and have much easier configuration.

- Snowpack: https://www.snowpack.dev/
- esbuild: https://github.com/evanw/esbuild

As of writing, snowpack with esbuild seems to be the most advanced option. It offers exponentially faster build times, with out of the box support for typescript. Bundle sizes are <s>marginally larger</s> now smaller than Rollup!

https://esbuild.github.io/faq/#benchmark-details

See here for comparison:

https://bundlers.tooling.report/

Esbuild is available via the folks at open-wc:

https://www.npmjs.com/package/@web/dev-server-esbuild

https://github.com/modernweb-dev/web/tree/master/packages/dev-server-esbuild

And it is the new default for snowpack:

https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0

***

Meanwhile, this is TODO in the current config:

https://github.com/suttacentral/suttacentral/pull/1974/files

**Comment by blake-sc** [comment]
Snowpack looks really nice. It also stands to reason that using Snowpack with the webpack bundler plugin could be a useful intermediate step.

**Comment by sujato** [comment]
Are you using a bundler for Bilara?

**Comment by blake-sc** [comment]
> Are you using a bundler for Bilara?

At the moment I'm using prpl-server, looking at the (basically default) configuration it looks like it uses (minified) modules if the browser supports modules, and otherwise makes a bundle targeting the browser's capabilities.
