### ISSUE TITLE
Context toolbar: Home page prominent toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1692]
The Home page has a special "prominent" toolbar to announce the site for new visitors.

**Prominent toolbar is only on Home page, not any other page.**

The prominent toolbar has the same basic structure as the normal toolbar, but has the following special features.

- [X]  Taller (approx 160px)  
- [X] Title is centered
- [X] title has special styles (larger, uses small-caps)
- [X] subtitle is included
- [x] Site Lotus logo next to title.
- [x] no action icons on toolbar
- [x] On scroll, the prominent toolbar, the main title, and the lotus all shrink, and the subtitle disappears.
- [X] Home page toolbar is `sticky`. That means it is always visible to the user when they are on the Home page. This is to help orient the new user.

The Home page main title animation is illustrated here. 

Note that the whole point of animation is to make the experience smoother and nicer for the user. Animations convey a sense of care and purpose. Badly done animations are worse than none at all.

> *Note this is a demo for the title animation only! Many things are wrong in this demo!*

![Screencastfrom12-08-20103524](https://user-images.githubusercontent.com/6112010/89983373-c677f700-dcba-11ea-81a7-86366709a777.gif)

**Comment by sujato** [comment]
There is an animation, but it is jarring. See #1694

**Comment by sujato** [comment]
- The first five items on the checklist are fine.
- Removing the action items has no been done, I assume that is pending.

Some mistakes are still present.

- on scroll, the lotus icon should *shrink* along with the site title, not disappear.
- tabs should not disappear on scroll. As per #1694 the tab bar is part of the app bar. It scrolls and animates together with it. See my gif animation in the original post for example. On the Home page, the app-bar is sticky, and thus the tab bar, since it is part of the app-bar, is sticky. In other words, apply `position: sticky` to the wrapper element that includes the entire app-bar.

The animation is still unacceptable. It jumps randomly back and forth,.

**All animations must be 100% smooth and flawless under all circumstances. Make sure to test the animation thoroughly**

![Screencast from 16-09-20 09 35 47](https://user-images.githubusercontent.com/6112010/93275695-f148f400-f800-11ea-8de0-89daa42bb855.gif)

The root of the problem is that there are two site titles in two HTML elements. 

![Screenshot from 2020-09-16 09-45-01](https://user-images.githubusercontent.com/6112010/93275934-9d8ada80-f801-11ea-97c9-c75a46d81b91.png)

This is incorrect. It is the same title, only the presentation is different. Changes in presentation are handled in CSS, not in HTML. It is impossible to smoothly animate from one HTML state to another. 

In addition, this is bad for SEO. Search engines look for one, semantically marked, and unambiguous site title.

Finally, the animation cannot be smooth because it is applied to the CSS height:

```
<div id="titlebar" style="display: inherit; transition: height 0.2s ease 0s; height: 8em;">
```

This is incorrect. **Never** apply CSS animation to height, width, left, right, padding, margin, or any other property that affects the position of the elements on the page, except the four properties below. 

This is because a change in a single pixel triggers a page reflow, which is computationally demanding and requires high CPU. It is a basic problem with CSS. For details, see:

https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108

The solution is to use **only** these four properties for CSS animations:

-    Position — transform: translateX(n) translateY(n) translateZ(n);
-    Scale — transform: scale(n);
 -   Rotation — transform: rotate(ndeg);
 -   Opacity — opacity: n;

These properties are designed for efficient animation. They offload computation to the GPU.

Here is the file for the Home page demo I made.

[sc-frame-three-home.zip](https://github.com/suttacentral/suttacentral/files/5228783/sc-frame-three-home.zip)

Here, I animated the `transform: translateY` property using `transition: transform 300ms ease-in-out;`.

I also dynamically applied `will-change: transform;` in order to eliminate unwanted animations on zoom or page resize.

As a result, the animations are smooth, as can be measured using the "performance" tab in the Chrome console.

![Screenshot from 2020-09-16 10-08-09](https://user-images.githubusercontent.com/6112010/93277089-b648bf80-f804-11ea-90fc-2e98b6c2c036.png)

By contrast, testing the animations here:

![Screenshot from 2020-09-16 10-13-15](https://user-images.githubusercontent.com/6112010/93277656-b6958a80-f805-11ea-843e-f167bc8c1861.png)

The FPS rate is less smooth, and the CPU usage is extremely demanding, even for such a simple animation.

It is crucial to always test these things and ensure that the site uses as few computer resources as possible. At the end of the day, we are only showing people some texts, and this does not require a lot of computing power. If we are demanding 100% CPU usage, we are doing something wrong.

The way to do this is:

1. Build the page from clear, semantic HTML.
2. Use CSS to style it.
3. Animate only the four properties mentioned above
4. Use as little JS as possible, and only for things that cannot be done in HTML and CSS.

**Comment by ihongda** [comment]
The animation code has been rewritten as required and will be submitted today.

**Comment by sujato** [comment]
I've tested the new header, it's looking good!

Here's the performance test:

![Screenshot from 2020-10-01 19-52-15](https://user-images.githubusercontent.com/6112010/94794989-0e480e80-0420-11eb-9111-88d82b83cfdc.png)

So that is excellent.

A few minor points:

- the tab bar is displaying everywhere, it should only be on Home page and other static pages.
- don't use UPPERCASE for the text in the tab bar. Use ordinary Capital Case and `text-transform: uppercase`. Why? Because it makes it easier to style, especially if we want to present it differently in future. In fact, as a general rule **never** use UPPERCASE when writing in HTML, always transform with CSS if needed.

**Comment by sujato** [comment]
I just discovered, the problem with the UPPERCASE is actually because the localization is not being applied. 

![Screenshot from 2020-10-03 09-09-04](https://user-images.githubusercontent.com/6112010/94976481-7863cf00-0558-11eb-9dfd-91fd82e98194.png)

**Comment by ihongda** [comment]
>1. the tab bar is displaying everywhere, it should only be on Home page and other static pages.
This problem has been fixed.

>2. don't use UPPERCASE for the text in the tab bar. Use ordinary Capital Case and text-transform: >uppercase. Why? Because it makes it easier to style, especially if we want to present it differently in >future. In fact, as a general rule never use UPPERCASE when writing in HTML, always transform with CSS >if needed.

A localized title has been added for the corresponding title, which defaults to ordinary capital case.

**Comment by sujato** [comment]
Everything in this issue appears to be done, **except** for removing the action items from the Home page, which is listed in the original spec for this issue.

> [ ] no action icons on toolbar

![Screenshot from 2020-10-15 07-17-30](https://user-images.githubusercontent.com/6112010/96041967-610dd580-0eb8-11eb-8ada-b4878a4a92c6.png)

This should look like this:

![Screenshot from 2020-10-15 07-11-12](https://user-images.githubusercontent.com/6112010/96040555-3b7fcc80-0eb6-11eb-93bc-4e8c241f19df.png)
