### ISSUE TITLE
Ripple the nav cards and breadcrumbs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1695]
The nav cards and breadcrumb items should ripple when clicked. 

- For nav cards, the ripple effect should be the same as when clicking a text on the suttaplex cards.
- For breadcrumbs, compare the tabs.

I tried adding `<mwc-ripple>` but i couldn't get it to work!

**Comment by sujato** [comment]
Ripple works well for cards. However on breadcrumbs, the ripple is *unbounded*. It must be bounded.

![Screenshot from 2020-08-27 09-04-15](https://user-images.githubusercontent.com/6112010/91365545-bf1d2580-e844-11ea-93e3-edc1c3cf8108.png)

In `paper-ripple` you do this by adding `<li style='position: relative'` to the containing element. 

However, we must not use paper elements. Use `mwc-ripple`. 

If you can't get that to work easily, then make a note and we will leave it for the future. Displaying a ripple is not critical functionality; removing dependence on paper elements is critical.

**Comment by ihongda** [comment]
If you can't get that to work easily, then make a note and we will leave it for the future. Displaying a ripple is not critical functionality; removing dependence on paper elements is critical.
----

Paper-ripple is only temporary, when mwc-ripple can be used, I will replace it.
