### ISSUE TITLE
Delay the loading spinner

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1701]
When transitioning between views, a loading spinner is seen. But it comes in too fast, often flashing for a fraction of a second as a page is loading.

the loading spinner should only appear when there is a noticeable delay to the loading. perhaps delay it by 500ms or so before appearing.

**Comment by ihongda** [comment]
Since there is less data to read from the server in the navigation component, it is not relatively time consuming, and I am removed the loading spinner from the navigation component.
