### ISSUE TITLE
Fix font-loading, use only self-hosted fonts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1719]
Fonts from Google are blocked, which results in the icons not displaying:

![Screenshot from 2020-10-03 07-07-08](https://user-images.githubusercontent.com/6112010/94970085-3aaa7a80-0547-11eb-817b-745ae7ca78ee.png)

This is an intermittent bug.

The reason there is a block on Google fonts was because the Polymer library was automatically loading  Roboto fonts that we were not using. This should not be a problem any more, as MWC does **not** automatically load fonts.

However, we need to make sure that:

- Only load the fonts that are needed on a per-language or per-text basis.
- Only serve fonts that we host ourselves. Never serve fonts directly from Google fonts, as they may be blocked in China or elsewhere, and there are also concerns with tracking and privacy. 

Even though we block the google fonts there is still a cost in DNS lookup time.

![Screenshot from 2020-11-29 10-45-33](https://user-images.githubusercontent.com/6112010/100528386-5cb33700-3230-11eb-994c-83baad9b1cd6.png)

**Comment by robertmusil** [comment]
@sujato This can be fixed very quickly, byt setting up a proper flag for polymer: adding following line in index.html will stop the font from being loaded:
```
   window.polymerSkipLoadingFontRoboto = true;
```

**Comment by sujato** [comment]
Awesome. Took us three years but we got there!
