### ISSUE TITLE
Unwanted scroll bar on more-menu

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1732]
An unwanted scrollbar has appeared on the more-menu. The CSS should be adjusted to ensure this does not happen. Unfortunately I can't figure out how to do it, as the CSS is buried deep inside a component.

![Screenshot from 2020-10-18 17-19-47](https://user-images.githubusercontent.com/6112010/96360226-dd2d4500-1166-11eb-8b8d-aaf7638f78cc.png)

**Comment by ihongda** [comment]
This problem has been solved.
The impact in unexpected places triggered this problem.
