### ISSUE TITLE
Use updated bilara-data for texts and references.

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1752]
Following our extensive revision of the data earlier this year, we must actually ensure that this data is being used. Currently stale data is still being used.

- **Use bilara-data published sources for all segmented texts.**

https://github.com/suttacentral/bilara-data

This includes the texts as well as references etc., everything that is in bilara-data.

(One easy way to tell the data is stale: old texts use ṃ, updated texts use ṁ)

The data should replace the contents here:

https://github.com/suttacentral/sc-data/tree/master/segmented_data

**Comment by Prograd** [comment]
https://github.com/suttacentral/sc-data/pull/90
