### ISSUE TITLE
Implement reference settings in top sheet

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1754]
The top sheet contains a set of check buttons for displaying the reference details of texts.

- None: Display no references. This is default.
- Main: Display segment number references. This currently works.
- Other Pali editions: a set of about twenty editions of the Pali canon for which we have reference data. Each of these can be individually toggled. **Currently this is a mockup only**

Currently the Pali editions are hard coded. Remove this and use the data from `pali_reference_edition.json`

https://github.com/suttacentral/sc-data/tree/master/misc

This will have to be loaded to DB first #1942 
:warning: the order is significant, please preserve it.

- Display a checkbox for each `uid` or set of `uid`s. 
- Note that in some cases, multiple related editions are toggled with the same checkbox.
- Show the name as the label of the checkbox.
- When checked, toggle all reference IDs in text for that `uid` or set of `uid`s.
- All settings should persist on the site until the user changes it.

**Comment by ihongda** [comment]
>There is a bug: the references do not turn off.

Our original design had only three ridio options. After you extended it, I didn't follow up in time. Now I have fixed this error. :smile:

**Comment by Prograd** [comment]
I'm not sure how I should get the data. Should make an asynchronous call or the data are already loaded somewhere?

**Comment by sujato** [comment]
I don't believe the data is loaded already, it should be called only when the top sheet is opened.

**Comment by Prograd** [comment]
@ihongda @sujato How can I reach a page with **SCSimpleText**. I can see that it react on **chosenReferenceDisplayType** from redux therefore my changes will affect this component as well. I'd like to test it and adapt the logic inside to the new state of it.
