### ISSUE TITLE
API 4: Get the data structure needed for navigation

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1781]
## URL 

```
/api/menu?language=[lang_iso]
/api/menu/[uid]?language=[lang_iso]
```

e.g.

```
https://staging.suttacentral.net/api/menu?language=en
https://staging.suttacentral.net/api/menu/sn?language=en
```

## Parameters

| Name | Data type | Description |
| --- | --- | --- |
| uid | String | e.g. `sn`, `an`, `mn-mulapariyayavagga` |
| language | String | e.g. `en`, `zh_ch` |

## Data format returned: JSON
 
Consistent with current data structure. 

## Other description 

At present, this API already exists, but the old data source needs to be replaced by a new data source. Please refer to the relevant issue for details. 

## Related issue 

https://github.com/suttacentral/suttacentral/issues/1714

**Comment by ihongda** [comment]
After discussion in the meeting yesterday and actual use, I tailored the data structure returned by the second API(`/api/menu/[uid]?language=[lang_iso]`), and some unnecessary fields and structures were deleted, here is the adjusted structure, with `/api/menu/sn-sagathavaggasamyutta?language=en` is an example:
[Adjustedjson.zip](https://github.com/suttacentral/suttacentral/files/5642664/Adjustedjson.zip)

Where the `num` field is deleted, and the unwanted `children` node is deleted, leaving only the first-level `children` node.

With adjustments, in this case, you can reduce the amount of data transferred by about three-quarters.

**Comment by sujato** [comment]
Hongda in this example you have fields `type` and `display_num` that are not found in the updated data sources. They are only in the old /division/ data that is to be deleted. Are these necessary? 

If not, take them out. 

If so, we need to give Alex an indication of how they are to be calculated. 

So far as I can tell:

- A `div` is:
    - everything in `super-tree`.
    - all branch nodes in the other `tree` files.
- `display_num` is the sequence number of sibling nodes.

**Comment by ihongda** [comment]
>Hongda in this example you have fields type and display_num that are not found in the updated data sources. They are only in the old /division/ data that is to be deleted. Are these necessary?

Yes, both of these fields are currently used, `type` is used to determine if there are children, and `display_num` is used to supplement the title prefix.

**Comment by ihongda** [comment]
At present, the blurb and acronym of the Scripture can be obtained from the other two APIs, but if this information can be added to the navigation API, the number of data requests can be reduced.

for example: /api/menu/sn?language=en

![深度截图_选择区域_20201209185705](https://user-images.githubusercontent.com/4037966/101712630-e97faf80-3ad0-11eb-9347-1133a69b6a5d.png)

The acronym's data source is [super_extra_info.json](https://github.com/suttacentral/sc-data/blob/master/structure/super_extra_info.json) and [text_extra_info.json](https://github.com/suttacentral/sc-data/blob/master/structure/text_extra_info.json)

The blurb's data source is [Blurb](https://github.com/suttacentral/bilara-data/tree/published/root/en/blurb)

**Comment by sujato** [comment]
Should we not add `root_lang` too?

https://github.com/suttacentral/suttacentral/issues/1821

**Comment by ihongda** [comment]
> Should we not add `root_lang` too?
> 
> #1821

Yes, according to the requirements of this issue, we need to add `root_language` field.

**Comment by sujato** [comment]
Actually see the updated issue #1821 

I have just pushed a new file `super_root_lang` which contains exactly the info needed for this, it should make it much easier.

**Comment by ihongda** [comment]
Alex, Here is a sample of the latest adjustments(https://staging.suttacentral.net/api/menu/dn?language=en):
`[
  {
    "id": "dn",
    "name": "D\u012bghanik\u0101ya",
    "acronym": "DN",
    "blurb": "blurb of DN",
    "lang_iso": "pli",
    "lang_name": "P\u0101li",
    "root_lang": "pli",
    "range": "",
    "children": [
      {
        "id": "dn-silakkhandhavagga",
        "name": "S\u012blakkhandha Vagga",
        "type": "div",
        "acronym": "acronym of dn-silakkhandhavagga",
        "blurb": "blurb of dn-silakkhandhavagga",
        "lang_iso": "pli",
        "lang_name": "P\u0101li",
        "root_lang": "pli",
        "range": "1\u2013\u206013",
        "yellow_brick_road": true
      },
      {
        "id": "dn-mahavagga",
        "name": "Mah\u0101 Vagga",
        "type": "div",
        "acronym": "acronym of dn-mahavagga",
        "blurb": "blurb of dn-mahavagga",
        "lang_iso": "pli",
        "lang_name": "P\u0101li",
        "root_lang": "pli",
        "range": "14\u2013\u206023",
        "yellow_brick_road": true
      },
      {
        "id": "dn-pathikavagga",
        "name": "P\u0101thika Vagga",
        "type": "div",
        "acronym": "acronym of dn-pathikavagga",
        "blurb": "blurb of dn-pathikavagga",
        "lang_iso": "pli",
        "lang_name": "P\u0101li",
        "root_lang": "pli",
        "range": "24\u2013\u206034",
        "yellow_brick_road": true
      }
    ],
    "yellow_brick_road": true
  }
]
`

**Comment by sujato** [comment]
Hongda, this is til using the old names and fields. Can we please make sure to use only the updated fields. If we do not change everything to be consistent now, I fear that in five years or ten years we will have the discussion about "what does `display_num` mean again?!?"

As I understand, what it should be is:

```
[
  {
    "name": "Dīghanikāya",
    "id": "dn",
    "children": [
      {
        "name": "Sīlakkhandhavagga",
        "node_type": "branch",
        "id": "dn-silakkhandhavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 1–⁠13",
        "yellow_brick_road": true
      },
      {
        "name": "Mahāvagga",
        "node_type": "branch",
        "id": "dn-mahavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 14–⁠23",
        "yellow_brick_road": true
      },
      {
        "name": "Pāthikavagga",
        "node_type": "branch",
        "id": "dn-pathikavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 24–⁠34",
        "yellow_brick_road": true
      }
    ],
    "yellow_brick_road": true
  }
]

```

The `type` represents the place this item has in the data "tree" so let us use explicit Tree Structure terminology to label it as such. 

https://en.wikipedia.org/wiki/Tree_%28data_structure%29

Call it `node_type` and it may be one of three kinds:

- `root` (Presumably this would be the three Tipitaka items)
- `branch` (= `div` = Any inner node such as a nikaya, a vagga, and so on)
- `leaf` (Usually a text, although it may not be an actual text, as we do not have all texts on our system. Sometimes it is a purely theoretical or hypothesized entity.)

`root_lang` is not specified at the vagga level as this is not in `super_root_lang`.

**Comment by ihongda** [comment]
Originally, I just asked to replace the old data source with a new data source, and the structure does not need to be changed, which saves the most time, because there will be few changes to the program.


In this case, let's take this opportunity to sort it out thoroughly and revise all unreasonable ones.

**Comment by ihongda** [comment]
need to add blurb and acronym：
```
[
  {
    "name": "Dīghanikāya",
    "id": "dn",
	"acronym": "",
    "children": [
      {
        "name": "Sīlakkhandhavagga",
        "node_type": "branch",
        "id": "dn-silakkhandhavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 1–⁠13",
		"blurb": "",
        "yellow_brick_road": true
      },
      {
        "name": "Mahāvagga",
        "node_type": "branch",
        "id": "dn-mahavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 14–⁠23",
		"blurb": "",
        "yellow_brick_road": true
      },
      {
        "name": "Pāthikavagga",
        "node_type": "branch",
        "id": "dn-pathikavagga",
        "root_lang_iso": null,
        "root_lang_name": null,
        "child_range": "DN 24–⁠34",
		"blurb": "",
        "yellow_brick_road": true
      }
    ],
    "yellow_brick_road": true
  }
]

```

**Comment by sujato** [comment]
Also, we should use `uid` instead of `id` to be more consistent with the data sources. I think it's also a good practice, as it makes it clear that a `uid` is not necessarily the same thing as an HTML `id`. A `uid` is often used as the HTML `id` but conceptually it is a different thing.
