### ISSUE TITLE
Breadcrumb nav: URLs and breadcrumbs must be consistent and correct no matter how you get there

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1788]
It's essential that the nav system be robust and reliable. If you enter a URL or click a link, you should always go to the right place and have the correct details shown.

Let's take a typical user journey.

- Basket of Discourses
- Discourses
- Long discourses
- Long Discourses collection

So far so good!

- The Entire Spectrum of Ethics

Oops! Now we see the breadcrumbs just say SUTTAPLEX. The trail of breadcrumbs is lost

Click on a sutta, and the trail of breadcrumbs is also lost, instead it just says `Home / SUTTA /DN 1`

The other things are ok, it's just the breadcrumbs.

There is also a bug where the breadcrumbs differ if you navigate to a sutta via search. Eg. if I search `mn3` and click on the results it is incorrect, as it does not indicate where I am in the collection.

![Screenshot from 2020-11-30 18-18-37](https://user-images.githubusercontent.com/6112010/100579759-e3ebd200-3338-11eb-9c19-543cfe66e971.png)

- The URL, the breadcrumbs, the app bar title, and the content displayed must always agree.
- One URL = one set of breadcrumbs. You must never have different navigation displayed at the same page.
- **Breadcrumbs are not history**. They have nothing to do with *where a user was previously*. They only indicate one thing: *where a user is currently*.
- If a malformed URL is entered, go to the *highest correct level*. Eg. if someone enters `/long/mn` redirect to `/long`.

**Comment by sujato** [comment]
Some other cases to check:

- If you click on AN, then "shortcut to all suttas" for say AN 3, the URL is `suttacentral.net/an3` and the breadcrumbs are just "AN".
- If I enter the url `https://staging.suttacentral.net/sn1` it only has "Home" in the breadcrums (and it is not clickable".

**Comment by ihongda** [comment]
![1](https://user-images.githubusercontent.com/6112010/100390438-7adc3400-3084-11eb-8b73-cf98a1f62c1c.png)
![2](https://user-images.githubusercontent.com/6112010/100390440-7ca5f780-3084-11eb-8c54-3ac3765045a2.png)

Both cases in PR #1802 should have been resolved :smile:

**Comment by sujato** [comment]
Great, that's good!
