### ISSUE TITLE
Review content security policy

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1795]
The current content security policy has duplicates and a bunch of unneded cases. I have removed them:

```
default-src 'self'; script-src 'self' data: about: 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; img-src 'self' data: https://legacy.suttacentral.net https://suttacentral.net; connect-src 'self' https://api.stripe.com https://js.stripe.com; style-src 'self' 'unsafe-inline' ; font-src 'self'; frame-src about: https://www.google.com https://js.stripe.com; object-src 'none'; media-src 'self' https://ia801504.us.archive.org;require-trusted-types-for 'script';
```

However there are still concerns.

![Screenshot from 2020-11-29 16-31-11](https://user-images.githubusercontent.com/6112010/100535115-02cf6300-326a-11eb-8c8e-10388ab4596f.png)

**Comment by ihongda** [comment]
I have tried to delete the `script-src` node: data: about:'unsafe-inline''unsafe-eval', and now I test it locally for a while to see if there is a problem.
