### ISSUE TITLE
Automated data migration from bilara-data to sc-data

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#1801]
When `bilara-data/published` branch is updated the changes should be automatically and promptly migrated to sc-data. For an overview refer to https://github.com/suttacentral/suttacentral/wiki/Data-flow-for-Bilara-and-SC

The form of the data is extremely similiar but there must still be a step where transformations are applied, for example:

The Nilakkhana transformation should be applied: https://github.com/suttacentral/suttacentral/issues/1590
UI translations should also undergo transformation (create issue?)

I believe that a Github Action would be the most appropriate implementation.

**Comment by alexander-vo** [comment]
Hey, @sujato 
what about this ticket? can we close it?
