### ISSUE TITLE
Load `name` and `tree` data to ArangoDB

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1806]
## Background

- Data flow: https://github.com/suttacentral/suttacentral/wiki/Data-flow-for-Bilara-and-SC
- `tree` and `name` files: https://github.com/suttacentral/suttacentral/issues/1714

## Task

- The data in the `tree` and `name` files must be loaded to the database via `arangoload.py`. 

These files are located here:

https://github.com/suttacentral/sc-data/tree/master/structure

## Required for

Once the data is in ArangoDB it will be queried for the navigation API.

https://github.com/suttacentral/suttacentral/issues/1781

## Note

Currently these files include names in root language only. The translations are currently being made in Bilara. We will add the translated names at the next step.

**Comment by alexander-vo** [comment]
As we discussed

Now all data are loaded from `name` files from in the `sc-data/structure/name/` folder and from the `uper-name.json` file. All data are uploaded to a collection called `super_nav_details` in our Arango database.
All relations between the data from the previous paragraph are described in `tree` files from the `sc-data/structure/tree/` folder and from the file `super-tree.json`. These data are also uploaded to the collection `super_nav_details_edges` and use the fields `_from` and `_to` to describe relations between the files in the `super_nav_details` collection.

Document structure from the `super_nav_details` collection:
```
{
    'uid': '',
    '_key': '',
    'name': '',
    'root_lang': '',
    'volpage': '',
    'biblio_uid': '',
    'acronym': ''
}
```
Where:
`uid` - unique id of the document, keys from `name` files (dn, dk, etc.)
`_key` - same as uid, unique id in the database
`name` - ame of the document, values from `name` files
`root_lang` - document source language, could be found in the `language.json` by document `uid`
`volpage`, `biblio_uid`, `acronym` - could be found in the `super_extra_info.json` by document `uid`. If data couldn't be found in this file, then we are trying to search this in the `text_extra_info.json` in the same way.

**Comment by sujato** [comment]
Alex, for `root_lang` use instead the new file `super_root_lang.json` as discussed here.

https://github.com/suttacentral/suttacentral/issues/1821

The reason is that we do not want to list the root lang for every text, but only at the places where it is useful. That's what is found in the list above. This gives us the correct `root_lang_iso` and `root_lang_name` for the places where it is needed.

**Comment by alexander-vo** [comment]
@sujato done in the latest commit, document structure description changed too

**Comment by sujato** [comment]
Yes, this is the case for texts for which we have no text. For example, this particular case is a Tibetan text. It is a treatise of the 8th century. Normally such a text would be on no interest for us. However it extensively quotes from the Suttas, so we list these cases. The work is being translated by a colleague of ours, and one of our to-do items is to adopt the whole text and translation on SuttaCentral. But that is not done yet. So there are no corresponding text files and no names. All we have is the overall title of the text, and sets of parallels.

Now, in this particular case, we have an expectation that we will have text eventually. In other cases, that is not so. Sometimes, for example, there is a relevant quote or passage that is merely a few lines buried deep inside a massive and complex text. Or else all we have is literally a scrap or fragment of a manuscript with a few words on it. Such cases are better handled by people specializing in those areas rather than SuttaCentral.

They are like leaves in winter: the stalk is there but the leaf has fallen.

**Comment by alexander-vo** [comment]
> They are like leaves in winter: the stalk is there but the leaf has fallen.

Well said!

If I remove the check for empty names, we may have errors about duplicate `uid`, because they all end up in the database
But maybe now I could remove the check for empty values, but when a duplicate `uid` appears I could keep only the version that is meaningful to us :thinking: 
What do You think?

**Comment by sujato** [comment]
> > They are like leaves in winter: the stalk is there but the leaf has fallen.
> 
> Well said!

It was wasn't it! I was quite proud of myself!
