### ISSUE TITLE
Add acronym and sutta ranges to navigation-nerdy-row

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1826]
We should have acronyms with sutta range numbers where appropriate in the navigation nerdy row. These show the user where the suttas they need are.

For example, they may see "Chapter on Similes" but they don't know if the sutta they are looking for is in there. So we add "MN 31–40" to help.

This is similar to the implementation in the old SuttaCentral, where these numbers are displayed in the sidebar. Now, however, we have more room so we can do it better.

## Use child_range.json!

The other details below are probably unnecessary now. Just use `child_range.json`, it tells you exactly what IDs to supply the info. The info is complete and does not require any additions or transformations: just add the literal strings and we're good to go.

## Implementation

An initial implementation has been made by Hongda here:

https://github.com/suttacentral/suttacentral/pull/1823/commits

These comments aim to correct this.

Start with DN. Actually it's perfect, great, move on.

Now, with MN we have a bug. At the pannasa display (http://localhost/pitaka/sutta/middle/mn) we have the acronym `MN` for every case. 

- Here we should show the range: `MN 1–50` and so on. 

Next we have the vagga level (http://localhost/pitaka/sutta/middle/mn/mn-mulapannasa)

Here  we see the name of the pannasa in the acronym range. Eg `Mulapannasa 1–10`. This is incorrect, we **always** use the acronym of the **collection**. 

- So this should be `MN 1–10` etc.

Next to SN. Let's see the Vaggasamyutta level: http://localhost/pitaka/sutta/linked/sn

Here we have acronym `SN`. 

- This should be, eg. `SN 1–12`, etc.

Then to the individual samyuttas (http://localhost/pitaka/sutta/linked/sn/sn-sagathavaggasamyutta). 

- These should say `SN 1`, `SN 2`, etc.

Where there are pannasas, they too are incorrect: http://localhost/pitaka/sutta/linked/sn/sn-khandhavaggasamyutta/sn22

- They should be e. `SN 22.1–50` etc.

Then to the vaggas: http://localhost/pitaka/sutta/linked/sn/sn-sagathavaggasamyutta/sn1

- These should say, `SN 1.1–10`, `SN 1.11–20`, etc.

Now to the Anguttara. The nipata level is correct, great. http://localhost/pitaka/sutta/numbered/an

But the vagga level is not. http://localhost/pitaka/sutta/numbered/an/an1

- It should be `AN 1.1–10`, etc.

Where there are pannasas, they too are incorrect, eg. http://localhost/pitaka/sutta/numbered/an/an4

- This should be eg. `AN 4.1–50` etc.

In KN, the texts have the acronym for the collection. http://localhost/pitaka/sutta/minor/kn

- This should display the acronym of the text, eg. `Kp`, `Dhp`, `Ud`.

Checking through a few cases, the vaggas of the Udana are correct: http://localhost/pitaka/sutta/minor/kn/ud

However in the Iti we have just `Iti`.

- It should have the range of suttas in each nipata, eg. `Iti 1–27`

In the vaggas the Iti is missing: http://localhost/pitaka/sutta/minor/kn/iti/iti-ekakanipata

- It should have `Iti 1–10` etc.

In Dharmapadas we have the acronym Dharmapadas http://localhost/pitaka/sutta/minor/dharmapadas

- It should have the acronyms for each text.

Probably enough examples for now!

**Comment by sujato** [comment]
Hongda see above, just use child_range.json.

**Comment by alexander-vo** [comment]
Child ranges are in the database now!

![image](https://user-images.githubusercontent.com/35242752/101904999-60937180-3bbf-11eb-8900-b22a1bcdab75.png)
