### ISSUE TITLE
Remove the paper dropdown

### ISSUE THREAD

**Issue by Prograd** [suttacentral/suttacentral#1835]
#### User story
This is a part of bigger issue #1310.

#### Feature description
Remove the [paper dropdown](https://www.webcomponents.org/element/@polymer/paper-dropdown-menu) dependency form the project. Use [material menu](https://github.com/material-components/material-components-web-components/tree/master/packages/menu) instead.

**The scope has been change a bit. The main idea is the remove the dependency from the more and language menu. Currently, it works correctly but there are a few issues which needs to be address.**

#### Known issues check:
- [x] the list of languages should be modern languages only i.e. not Pali, Sanskrit, etc.
- [x] sc-language-base-menu should have the same width as the main more menu, the transition would be smoother.(**It's done partially, the min and max width is set properly but scrollbar do not follow this value**) 
- [ ] specify overflow-y: scroll; on the sc-language-base-menu (not the more menu).
- [x] There's a weird positioning bug if you scroll down the page and open the menu, it is not in place.
- [x] We have both id="more-menu" and id="more_menu". We should use more clear naming
- [ ] The ripple effect on the switches is bounded, even though it is set to unbounded. This is because .mdc-list-item__text is set to overflow: hidden. Again, fix it if it is an easy fix, else leave it.

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

- Affected components works in the same way as previously, the design as well
- paper dropdown dependency is removed from the project 

#### Done check:
- [x] Project builds without errors
- [ ] Peer Code Review performed/pull request approved 
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed

**Comment by Prograd** [comment]
I'm not able to to find the usage of **sc-search-filter-menu**. I've seen that it is imported to the **sc-settings-menu** but I haven't seen any usage of it. We can remove it if doesn't use anymore.

**Comment by ihongda** [comment]
Hey, Jakuba, It is also used in sc-page-search.js.

**Comment by sujato** [comment]
The `sc-search-filter-menu` is just a simple dropdown selector which lacks the rich functionality of the toolbar menu. It is rarely used used (as the correct search results should float to the top anyway). TBH I have never used it. I'd like to get rid of it, but that would require a deeper overhaul of search.

Meanwhile, I would recommend replacing `<paper-menu> in this instance with the native HTML `<select>`. Don't add JS unless absolutely necessary.

If there is some insuperable obstacle to using `<select>` then try `<mwc-select>`.

**Comment by Prograd** [comment]
Regarding the language menu, @robertmusil suggests changing the design a bit to make it more clear and ease to implement without polymer components. I'd like to discuss this on daily standup.

**Comment by sujato** [comment]
Happy to look at new suggestions for language selection. (I always quite liked how Youtube does it.)

**Comment by Prograd** [comment]
Actually, that was the suggestion. If you happy to have something similar, I can start developing it.

**Comment by sujato** [comment]
Just running this locally, the menu works great. At last, it actually animates correctly and has the right shadow! Small things, but they add up.

A few minor details:

- the list of languages should be **modern languages only** i.e. not Pali, Sanskrit, etc. The old implementation does this correctly. The correct languages are defined in `language.json` with `"is_root": false,`.
- the back arrow in the language selection should use our icon color, which is called `var(--sc-disabled-text-color);`. 
- Also make sure to use `sc-sans-font`
- Another stylistic detail: it would be nice if `sc-language-base-menu` had the same width as the main `more menu`, the transition would be smoother. 
- Finally, I assume it's just because its unfinished, but make sure to remove all reference to iron, polymer, and paper elements and styles.

**Comment by Prograd** [comment]
I'm not sure what do you mean by saying **the menu does not theme properly**. Is this issue still exist or it's fixed by you in your PR?

**Comment by Prograd** [comment]
Regarding **specify overflow-y: scroll; on the sc-language-base-menu (not the more menu)** I can specify it but there is no direct API from the component. It can be done by reference like this `this.shadowRoot.querySelector("#more-menu").shadowRoot.querySelector("mwc-menu-surface").shadowRoot.querySelector("div")` but I guess it's the way we'd like to go.

**Comment by Prograd** [comment]
The last dependency is placed inside donate page. Today we've talked that all in all we'd like to upgrade the way of dealing with payment  API. I briefly took a look on the new API and we wouldn't need to specific card number, expiration date and CVC code. The whole page is build with polymer components. Therefore I'd like to create a new form, from scratch, using mwc components and connect it with the new API. We'll have 2 major benefit thanks to this approach, we will remove the stale dependency, at the same time we'll update the way of dealing with the API and it should take less time than replacing polymer component inside step by step. I wouldn't like to add those changes to the current PR because it's pretty big already. So, I'm gonna base on it and raise another one with those changes. @sujato Let me know whether this approach is ok to you.
