### ISSUE TITLE
Use `optimize-plugin` for webpack?

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1837]
I came across this webpack plugin that promises a better way of optimizing webpack. it looks cool and very simple. Maybe we should try it out?

https://github.com/developit/optimize-plugin

From their Readme:

>Optimize your code for modern browsers while still supporting the other 10%, increasing your build performance, reducing bundle size and improving output quality.
>
>Put simply: it compiles code faster, better and smaller.

>Features

-    Much faster than your current Webpack setup
-    Transparently optimizes all of your code
-    Automatically optimizes all of your dependencies
-    Compiles bundles for modern browsers (90%) and legacy browsers (10%)
-    Removes unnecessary polyfills, even when inlined into dependencies
-    Builds a highly-optimized automated polyfills bundle

**Comment by robertmusil** [comment]
@sujato The idea is sound, but it's not as straightforward as just adding a plugin as it's used instead of Babel, which is already used to split the 90-10 problem with `BabelMultiTargetPlugin`. The OptimizePlugin might do a better job though, as it uses slightly different approach to polyfilling.

**Comment by sujato** [comment]
Every kb matters …

**Comment by ihongda** [comment]
I've added this plug-in, but it looks pretty much the same as before.
