### ISSUE TITLE
Load sc_bilara_data to the ArangoDB

### ISSUE THREAD

**Issue by alexander-vo** [suttacentral/suttacentral#1858]
## Background

- Data flow: [flow](https://github.com/suttacentral/suttacentral/wiki/Data-flow-for-Bilara-and-SC)
- Loaded `name` and `tree` #1806 
- Nilakkhana text processing completed #1590 during data migration #1801 

## Task

After migrating data from `bilara-data/published` to `sc-data` as described in #1801, there is a question of loading this data into the ArangoDB database while running the `make load-data` script.

## Details

All data from the `sc_bilara_data` folder is loaded into the database (data from this folder is taken from the bilara_data repository, published branch). Only the following data are not uploaded to the database 

- `_author.json`
- `_category.json`
- `_edition.json`
- `_language.json` 
- `.scripts` folder
- `nilakkhana` folder
- `README.md`

### Loading details

- From the `_publications.json` file all key values are loaded into the `publications` collection as is.

-  Subtree of the `sc_bilara_data` folder contains folders named `blurb` (an example of one of them is `root/en/blurb`). All documents from these directories must be loaded into the `blurbs` collection with the following structure:
```
{
  "uid": "",
  "lang": "",
  "blurb": ""
}
```
Where `uid` is taken from the keys of the blurb files (**attention**, the keys have the following structure `<prefix>:<uid>` from which we need only the uid part). Python `re` module used with the next regex pattern `r'^.*?:(.*?)$'` .
The `lang` field must be taken from the file structure, we take the language of the folder that contains the blurb folder we are parsing at the moment (for example for a blurb file in the `root/en/blurb/` directory the `lang` field will have the value `en`).
The `blurb` field is taken from the values in the blurb files.

- Subtree of the `sc_bilara_data` folder contains folders named `name` (an example of them are `root/misc/site/name/` and `translation/en/sujato/name/`). All documents from these directories must be loaded into the `names` collection with the following structure:
```
{
  "uid": "",
  "lang": "",
  "is_root": true|false,
  "name": ""
}
```
Where `uid` is taken from the keys of the name files (**attention**, the keys have the following structure `<prefix>:<some_number>.<uid>` from which we need only the uid part). Python `re` module used with the next regex pattern `r'^.*?:\d+\.(.*?)$'` .
The `lang` field is retrieved in exactly the same way as in the case of blurb files. Also, if the current `name` folder is under the `misc` directory, the `lang` field will take the `misc` value.
The `is_root` field will be set to `true` if the path to the current `name` file will go through the `root` directory, in any other case it will be `false`.
The `name` field is taken from the values in the name files.

- All other files in the `sc_bilara_data` folder should be loaded into the `sc_bilara_texts` collection with the following structure:
```
{
  "uid": "",
  "lang": "",
  "muids": [],
  "filepath": ""
}
```
The `filepath` field is the path to the file from the `sc_bilara_data` folder (for example for the file `translation/en/sujato/sutta/dn/dn10_translation-en-sujato.json` the field will take the same value)
The `lang` field is retrieved in exactly the same way as in the previous cases.
The `uid` and `muids` fields are taken from the file name. Each file name has the following structure `<uid>_<muids_solid>`, where the `uid` part will be the value of the `uid` field, and the `muids_solid` part should be split into parts through the `-` separator and the resulting array of lines will be the value of the `muids` field. For example for file `dn10_translation-en-sujato.json` the field `uid` will have value `dn10` and field `muids` will have value `["translation", "en", "sujato"]`.

## Next steps

Add translation support for #1781 using collections created in this ticket

**Comment by sujato** [comment]
Alex I'll answer here and leave it to you to edit the OP.

> What data are we loading into the database?

I'm not sure how much detail you want here. Are you looking for a full list of files loaded to the DB? 

> how to determine the translation language

As far as determining the language, this may be done in two ways:

- the translations are kept in directories named after the language.
- each text file in `html_text` has a defined language, eg. `<article id='kp5' lang='af'>`. 

The latter method is probably better, as it is safer to rely on the explicit metadata in the file rather than the position in a directory (which could get displaced). However I do not know if that is what it does or not.

> Which collections in the database are used to store this data?

Again, i'm not sure: are you asking for a complete list of all DB collections, where they are sourced from, and how the data gets there? Because that sounds like a good idea! But it would be a bit of work to put it together, so I'm just checking exactly the scope that you're looking for.

>In what form should the data be stored (fields, structure, etc.)?

This is too technical for me, I don't know anything about the internals of ArangoDB.

**Comment by alexander-vo** [comment]
I have questions about uploading data to the database
Here they are:

1) We have duplicated uids in `name` files:
`lzh-art-name_translation-en-sujato.json`:
https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/translation/en/sujato/name/sutta/lzh-art-name_translation-en-sujato.json#L2
and duplicated value in `super-name_translation-en-sujato.json`:
https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/translation/en/sujato/name/super-name_translation-en-sujato.json#L50
(after parsing keys of these files we will get the same uid `lzh-art` from both files)
Is it ok? What should I do with it?

2) We have duplicated uids in `blurb` files:
`pli-tv-bu-vb-blurbs_root-en.json`:
https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/root/en/blurb/pli-tv-bu-vb-blurbs_root-en.json#L162 (it also contains html btw)
and duplicated in `super-blurbs_root-en.json`:
https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/root/en/blurb/super-blurbs_root-en.json#L88
as I said before: after keys parsing I will get uid `pli-tv-bi-pm` two times from different files.
Same situation with `pli-tv-bi-pm-blurbs_root-en.json` and `super-blurbs_root-en.json`
`pli-tv-bi-vb` uid here: https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/root/en/blurb/super-blurbs_root-en.json#L84
and here: https://github.com/suttacentral/bilara-data/blob/116352dae9b159dd076c4fd6fb6edca699102685/root/en/blurb/pli-tv-bi-pm-blurbs_root-en.json#L237

3) Also I have problems with duplicates during loading `html` folder cause we have several files with the same names:
`mn16_html.json` here: https://github.com/suttacentral/bilara-data/tree/published/html/lzh/sct/sutta/ma
and `mn16_html.json` here: https://github.com/suttacentral/bilara-data/tree/published/html/pli/ms/sutta/mn
Same problem with `mn31_html.json`
here: https://github.com/suttacentral/bilara-data/tree/published/html/lzh/sct/sutta/ma
and here: https://github.com/suttacentral/bilara-data/tree/published/html/pli/ms/sutta/mn

@sujato @blake-sc to all 3 points the same questions:
is this ok? what should I do with it? 
if it is normal, should I just not add repeated entities to the database a second time?
or add both, but with different keys, and then somehow distinguish them using other fields?
