### ISSUE TITLE
remove numbers from bilara-data headings

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1860]
When setting up the texts many years ago I made the choice to always include the Sutta number in the heading. This was primarily to handle cases where there was no title so at least there would be something.

This convention has carried over to Bilara, and I propose that we remove these numbers. Sutta numbers should be exposed in an appropriate way in the UI and be distinct from the title. (Currently users can see the ID in the breadcrumbs menu)

- **Remove all numbers from main titles and supertitles in all texts, except where there is only a number as title.**

Some examples.

```
  "mn1:0.1": "Middle Discourses 1 ",
  "mn1:0.2": "The Root of All Things",
```

becomes

```
  "mn1:0.1": "Middle Discourses",
  "mn1:0.2": "The Root of All Things",
```

And 

```
  "sn46.39:0.1": "Linked Discourses 46 ",
  "sn46.39:0.2": "4. Hindrances ",
  "sn46.39:0.3": "39. Trees ",
```

becomes

```
  "sn46.39:0.1": "Linked Discourses",
  "sn46.39:0.2": "Hindrances ",
  "sn46.39:0.3": "Trees ",
```

And 

```
  "an10.240-266:0.1": "Aṅguttara Nikāya 10 ",
  "an10.240-266:0.2": "23. Rāgapeyyāla ",
  "an10.240-266:0.3": "240–266 ",
```

becomes

```
  "an10.240-266:0.1": "Aṅguttara Nikāya",
  "an10.240-266:0.2": "Rāgapeyyāla ",
  "an10.240-266:0.3": "240–266 ",
```

**Comment by cuboids** [comment]
Should the trailing spaces be preserved

**Comment by sujato** [comment]
The rule with trailing spaces is: always have a trailing space except after an em-dash. So yes, use the trailing space.

The reason for this is that we should expect that applications can naively stick one segment after another. In the case of headings this does not matter, but in body text it ensures that applications don't run words together.

**Comment by thesunshade** [comment]
It looks like Bhante S closed a PR for this without merging https://github.com/suttacentral/bilara-data/pull/319#issuecomment-1093407112

**Comment by sujato** [comment]
This still remains as a best practice, but as indicated in the PR it is tricky because of the different handlings in different texts. So best to proceed on a case by case basis, on the understanding that it is preferential to remove numbers from headings.
