### ISSUE TITLE
ToC button displays when there is no ToC

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1883]
Under some circumstances, the ToC button still displays when there is no ToC.

This occurs when you navigate to a text. 

If, for example, I start here:

http://localhost/sn1-nandanavagga

Then click on the top sutta by Bodhi:

http://localhost/sn1.11/en/bodhi

I can see the ToC button at the top, containing just the heading.

![Screenshot from 2021-01-12 17-32-53](https://user-images.githubusercontent.com/6112010/104278243-6355ef00-54fc-11eb-8376-13df4066f16f.png)

But if I refresh the page it goes away.

![Screenshot from 2021-01-12 17-33-35](https://user-images.githubusercontent.com/6112010/104278268-6d77ed80-54fc-11eb-9ad3-582d13560626.png)

**Comment by robertmusil** [comment]
@sujato You sure that it occurs on newest master? I was fixing this issue specifically yesterday and I cannot reproduce it

**Comment by sujato** [comment]
Yes, but tell you what, let's wait till everything's merged and test it again live on staging.
