### ISSUE TITLE
In nav cards, show root language when it is useful

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1893]
Currently we don't explicitly show the root language in the nav cards.

In this commit I make a naive first attempt at doing so:

https://github.com/suttacentral/suttacentral/commit/a30ff0352ea5e455427b9aada0627580d8bd966e

But this shows the language on every card. It should only do so at the top level of the collection to be defined.

This can be easily done using the data from sc-data/structure/language.

The logic is as follows:

- **If** a UID is  included in ` "contains"`
- **Then** add class `show-root-language` to nerdy-row `subTitle`.
- Put your feet up and relax, job well done! (I'll make it work with CSS)

**Comment by ihongda** [comment]
>If a UID is included in "contains"

Bhante, What does that mean?

**Comment by sujato** [comment]
In the `contains` field here:

https://github.com/suttacentral/sc-data/blob/master/structure/language.json

**Comment by sujato** [comment]
This is working well in the latest commit.
