### ISSUE TITLE
Let users share state of text by extending URLs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1907]
## User story

I just wanted to share a sutta with Karl. I opened up the URL. But I specifically wanted him to see the text in Pali and English side by side, with the Pali text converted to a different script. There's no way of doing that, as the view logic is not represented in the URL

## Feature description

Take a basic URL:

```
https://staging.suttacentral.net/sn56.1/en/sujato
```

In Views, I enable Pali/English side by side. This works exactly as it does currently, but in addition, the URL changes. here I give pseudo-code to illustrate the function.

```
https://staging.suttacentral.net/sn56.1/en/sujato?lang=pli+en&layout=column
```

Now I want to change the script to Khom Thai. The URL changes to:

```
https://staging.suttacentral.net/sn56.1/en/sujato?lang=pli+en&layout=column&indic_script=KhomThai
```

The following options would be supported:

- notes: `none/tooltip/sidenote`
- lang: root + translation
- layout: `column/row`
- script
- Highlight
- reference: `none/main/<list of specific editions>`

**Comment by ihongda** [comment]
Bhante, in this case, what is the processing logic?
`https://staging.suttacentral.net/sn56.1/en/sujato?lang=pli+de`

Different languages： 
sn56.1/`en`  and  lang=pli+`de`
