### ISSUE TITLE
there is a ghost haunting `main.js`  👻 we need an exorcism

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1918]
SuttaCentral is slower than it should be. Why?

Some time ago I discovered that our JS appears to take much longer, maybe twice as long, to parse and execute compared to similar JS payloads on other sites. Why?

Analysis of our JS payload shows that we are delivering `main.js` *twice*.

See here for example:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fstaging.suttacentral.net%2F&tab=desktop

![Screenshot from 2021-01-21 22-18-17](https://user-images.githubusercontent.com/6112010/105344164-b6375100-5c36-11eb-93d6-20069b9a0d37.png)

It looks like it is loaded twice, once using a preload link. Is this a misconfiguration in webpack?

The two files are loaded and executed separately.

![Screenshot from 2021-01-21 22-22-40](https://user-images.githubusercontent.com/6112010/105344657-58573900-5c37-11eb-8a3d-612f2ebbd310.png)

But it appears intermittently. Where is that pesky ghost hiding!

Chrome dev tools also show a duplicated `main.js`.

![Screenshot from 2021-01-21 23-02-09](https://user-images.githubusercontent.com/6112010/105348776-eb46a200-5c3c-11eb-864a-90f340db7328.png)

Even though the file sizes seem different, I have diffed them and the files are identical.

In this test we see the two `main.js` but only one is loaded and parsed.

https://gtmetrix.com/reports/staging.suttacentral.net/MGTKO6tk/

![Screenshot from 2021-01-21 22-29-54](https://user-images.githubusercontent.com/6112010/105345566-88530c00-5c38-11eb-8dde-dcb31514ac62.png)

Now, looking closer at this test, it seems that the files are identical but the response headers are not exactly the same.

![Screenshot from 2021-01-21 23-12-32](https://user-images.githubusercontent.com/6112010/105349887-6fe5f000-5c3e-11eb-875e-7e6eb96526f1.png)

Most of the details are the same, except:

- format is different (The "real" version has no pipe dividers | but puts things on new line; I put them on the same line to compare).
- "real"version sets a cookie
- "ghost" version has an origin

So I'm guessing that the two versions are there, but depending on conditions one might not be downloaded? Either way, it shouldn't be duplicated. Exorcise it now!

## Code

In `nginx/conf.d/prod.nginx.conf` we have the following:

```
    set $prefetch_link "</main.js>; rel=preload; as=script,</node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>; rel=preload; as=script";
```

**Comment by robertmusil** [comment]
Should be resolved by #1974
