### ISSUE TITLE
Does this suttaplex code do anything?

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1922]
In `sc-suttaplex.js` we find som code dealing with `hidden-nerdy-row`. This adds some code with vol-page. But I can't understand what it does; if I take out the following code blocks it appears to not affect anything. It adds a bunch of data duplicating what is there already, which is not used. And it supposed to be activated by a popup, but I can't recall that we have any such thing.

Is this maybe code left over from an earlier version of the suttaplex?

Can we delete it?

```


          ${this.item.volpages && html`
            <span class="book no-margin">
              <iron-icon class="small-icon" icon="sc-iron-icons:book"></iron-icon>
            </span>
            <span class="vol-page nerdy-row-element" title="${this.volPageTitle}">
              ${this.volPage}
            </span>
          `}
```
```
                  <span class="popuptext" id="hidden-nerdy-row">
          ${this.item.translated_title && this.item.original_title && html`
            <span title="${this.localize('originalTitle')}" class="nerdy-row-element">
              ${this.item.original_title}<br>
            </span>
          `}
          ${(this.item.translated_title || this.item.original_title) && html`
            <span title="${this.acronymTitle}" class="nerdy-row-element">
              ${this.acronymOrUid}<br>
            </span>
          `}
```

 ```  
  revealHiddenNerdyRowContent() {
    const detailsElement = this.shadowRoot.querySelector('.volpage-biblio-info');
    const nerdyRow = this.shadowRoot.querySelector('.suttaplex-nerdy-row');
    const popup = this.shadowRoot.querySelector('#hidden-nerdy-row');
    const widthReduction = 16;

    if (nerdyRow.clientWidth < nerdyRow.scrollWidth) {
      popup.classList.toggle("show");
      popup.style.width = nerdyRow.clientWidth - widthReduction;
      popup.style.marginLeft = `-${nerdyRow.scrollWidth}px`;
      if (detailsElement) {
        detailsElement.style.display = 'none';
      }
    } else if (detailsElement) {
      detailsElement.style.display = null;
    }
  }
```

```
           @tap="${this.revealHiddenNerdyRowContent}"


```

**Comment by sujato** [comment]
I have gone ahead and deleted this code with https://github.com/suttacentral/suttacentral/commit/21f3ba6b4f7dcbc41e48a24a4ec4240f753ceb23

**Comment by ihongda** [comment]
Sorry, I just saw it.
In some cases, when the visual area is small, clicking nerdy-row will show:
![深度截图_选择区域_20210204113151](https://user-images.githubusercontent.com/4037966/106841328-dc4ffd00-66dc-11eb-9c76-3b5c9edc962f.png)

**Comment by sujato** [comment]
Oh, okay, well now I know. Still, i think it's unnecessary complexity. We should be able to handle such cases just with CSS. 

I've removed the code, let's see if it is okay.
