### ISSUE TITLE
suttaplex share menu has broken

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1935]
The suttaplex "share" menu provides a useful way for researchers or writers to grab the data from our parallels.

I recently updated it to remove paper dependencies. At the time, I tested it and it worked fine.

Now it doesn't work; maybe because of the updated data sources?

Anyway, when you open it it is disabled and there is no data to copy.

**Comment by ihongda** [comment]
It looks functional at the moment on my local.

Is it okay on your machine now? Bhante

**Comment by sujato** [comment]
Okay well it half-works now. It opens fine and you can see the three options. if you click "copy link" it's fine. 

But "copy table" and "Cite" just give you the same data as "copy link".
