### ISSUE TITLE
Load guides and pali_reference_edition into the database

### ISSUE THREAD

**Issue by alexander-vo** [suttacentral/suttacentral#1942]
### Task
We need to load files `sc-data/structure/guides.json` and `sc-data/misc/pali_reference_edition.json` into the database.

### Details
The `guides.json` must be loaded into the `guides` collection.
The `pali_reference_edition.json` must be loaded into the `pali_reference_edition` collection.

### DB structure

- Document structure for `guides`:

_...IN PROGRESS..._

- Document structure for `pali_reference_edition`:

All documents must be loaded exactly the same as they appear in the `pali_reference_edition.json` file.

**Comment by sujato** [comment]
Don't separate out the grouped editions. They are grouped for a reason: they will all appear in the UI as one set, and will be toggled on/off with one switch. Give me a minute, I'll see if I can make this more explicit in the data.

**Comment by sujato** [comment]
I've pushed an updated version, hopefully it makes the intent clearer. We now have, for example:

```
  {
    "edition_set": "sya",
    "includes": [
      "sya1ed",
      "sya2ed",
      "sya-all"
    ],
    "name": "Other Thai editions"
  }
```

Each `edition_set` must be preserved as a single entity. 

Whether you split each entry into a separate document is up to you, it's an implementation detail. But conceptually there is no need: all this data will invariably be queried and served at one time. It is one set of data to create one UI interface.

**Comment by alexander-vo** [comment]
@sujato ok, all documents in `pali_reference_edition` will be loaded as-is

**Comment by alexander-vo** [comment]
@sujato now we have a structure similar to this (`guides.json`):
```
{
  "lang": {
    "en": {
      "sutta": "discourses-guide-sujato",
      "vinaya": "vinaya-guide-brahmali",
      "abhidhamma": "abhidhamma-guide-sujato",
      "dn": "dn-guide-sujato",
      "mn": "mn-guide-sujato",
      "sn": "sn-guide-sujato",
      "an": "an-guide-sujato"
    }
  }
}
```

and from what I understand so far, I can suggest the following structure in the database for each document:
```
{
    "type": "<root_key>",
    "lang": "<parent_key>",
    "uid": "<key>",
    "guide": "<value>"
}
```

and then from the existing document we will get the following documents in the database:
```
[{
    'guide': 'discourses-guide-sujato',
    'lang': 'en',
    'type': 'lang',
    'uid': 'sutta'
  },
  {
    'guide': 'vinaya-guide-brahmali',
    'lang': 'en',
    'type': 'lang',
    'uid': 'vinaya'
  },
  {
    'guide': 'abhidhamma-guide-sujato',
    'lang': 'en',
    'type': 'lang',
    'uid': 'abhidhamma'
  },
  {
    'guide': 'dn-guide-sujato',
    'lang': 'en',
    'type': 'lang', 
    'uid': 'dn'
  },
  {
    'guide': 'mn-guide-sujato', 
    'lang': 'en', 
    'type': 'lang', 
    'uid': 'mn'
  },
  {
    'guide': 'sn-guide-sujato', 
    'lang': 'en', 
    'type': 'lang', 
    'uid': 'sn'
  },
  {
    'guide': 'an-guide-sujato', 
    'lang': 'en', 
    'type': 'lang', 
    'uid': 'an'
}]
```

or do we not need the `type` field and all root keys should be ignored?

**Comment by sujato** [comment]
Okay, again, let me redo the file structure to make it more explicit, just one minute …

**Comment by sujato** [comment]
Okay so now I've pushed it as :

```
  {
    "guide_uid": "an-guide-sujato",
    "text_uid": "an",
    "lang": "en"
  }
```

And yes, there's no need for a `type`.
