### ISSUE TITLE
fix swagger at /api/docs 

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1982]
According to our README, Swagger documentation for API is available at `/api/docs` however that shows an error.

This should be fixed!

***

**NOTE:** this issue was raised and fixed previously, but it seems it is broken again.

**Comment by thesunshade** [comment]
It looks like this is broken again and may have been broken for some time.

Is there any plan to fix? If it's been broken so long, is there really any need for this?

**Comment by ihongda** [comment]
Oh, after a long time, I finally fixed this bug.  @sujato  @thesunshade

**Comment by thesunshade** [comment]
Thanks @ihongda . I have added links to this from the API documentation on D&D

@buddhist-uni fyi, I think you had asked about this.
