### ISSUE TITLE
Investigate options for search

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1986]
## conclusions

We considered the options below, and decided to proceed to implement search via ArangoDB. However we will also look at Meilisearch as an experiment.

## elasticsearch

**pros**
- reliable
- full-featured
- familiar
- already set up
- more languages

**cons**
- java
- heavy
- lots of config
- out of date

## arangoDB

**pros**
- already in use
- nice to work with AQL
- has better understanding of relations
- can compose queries
- can do graph and other things
- about 20 languages

**cons**
- not dedicated search engine
- may not be as performant (but maybe it is!)

## flexsearch

https://github.com/nextapps-de/flexsearch

**pros**
- fast
- new concepts

**cons**
- difficulty?
- maintainability?
- features?
- pre-release

## meilisearch

https://docs.meilisearch.com/learn/what_is_meilisearch/

**pros**
- modern
- rust
- learns from Algolia
- uses algolia's instantsearch.js
- open source
- easy set up and use

**cons**
- not stable
- untested

## typesense

**pros**
- similar aims to meilisearch
- more mature (start in 2015 vs 2018)
- uses algolia's instantsearch.js
- c++

**cons**
- ??

## algolia

**pros**
- easy
- off-source work

**cons**
- closed source
- pay as you go (may be cheaper than doing our own development, though)

***

## comparisons

https://spinscale.de/posts/2020-10-20-search-engines-and-libraries-overview.html

https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html

https://tantivy-search.github.io/bench/

**Comment by thesunshade** [comment]
@buddhist-uni FYI
