### ISSUE TITLE
sort order of segments is sometimes wrong

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1987]
The order of segments does not vary. It is always the same as it is in the file, and as sorted by the UID keys.

However sometimes this is not correct:

http://localhost/an2.1-10/en/sujato

![Screenshot from 2021-02-15 09-45-03](https://user-images.githubusercontent.com/6112010/107891414-9c0d3c00-6f72-11eb-8962-1749df7fec09.png)

**Comment by robertmusil** [comment]
Should be resolved by #1991

**Comment by robertmusil** [comment]
(Still will require a backend rework as stated in the comment)
