### ISSUE TITLE
Nilakkhana transformation adds HTML entities to markup

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2011]
Somehow there are HTML entities appearing in the transformed text.

If I search for `&lt;/` in bilara-data, there are zero. The same search in sc_bilara_data gives me 22.

The bug occurs transforming `*foo*` to `<em>foo</em>`.

It also occurs in one case where a `<p>` tag is present, even though it has been removed from the source in bilara-data. There are no block-level tags in blurbs. super-blurbs:pli-tv-bi-vb . Probably this just needs a full refresh.

Finally there are a bunch of cases in `dn2-a` where `&lt;/blockquote&gt;` is in the root text. This is a fault in the text preparation, these are experimental texts. Nevertheless, they shouldn't have HTMl entities.

**Comment by alexander-vo** [comment]
@sujato I just found p tags inside `super-blurbs:pli-tv-bi-vb`, that's not ok
![image](https://user-images.githubusercontent.com/35242752/108962313-424af700-7681-11eb-9b0a-facd2cec9c73.png)

I'll take a look at `dn2-a`, indeed some strange behavior

**Comment by alexander-vo** [comment]
HTMl entities fix https://github.com/suttacentral/bilara-data/pull/360

**Comment by sujato** [comment]
I've removed stray tags.
