### ISSUE TITLE
Navigation: further issues

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2012]
The navigation is mostly sorted out. There are a few remaining issues, which I will list. All these cases were tested in Firefox, I have not tested them in Chrome.

- [x] After a search, the URL still retains the search query. **Search query should only be in URL on search result pages**

- Make a search.
- Then navigate somewhere.
- the search query is still in URL: `https://staging.suttacentral.net/sf?query=arthaviniscaya`
- This is super-persistent, it remains even after deleting it by hand - [ ] In some cases translated title is missing from suttaplex.

![Screenshot from 2021-02-26 09-18-49](https://user-images.githubusercontent.com/6112010/109226993-b87f6300-7813-11eb-8661-f6c2d8db40e0.png)and refreshing.

- [x] Breadcrumbs for Dhammapada are incorrect

- If I navigate to KN / Dhammapada it is fine up until the suttaplex list at https://staging.suttacentral.net/dhp
- If I click on a text the breadcrumb items disappear, leaving only : Home / Dhp 1-20
- The same bug appears if I navigate to Dhammapada via "Dharmapadas" collection.
- The full list of items also sometimes apperas in a flash then vanishes

- [x] Breadcrumb name of "dharmapadas" page should be "Dharmapadas" not "Dhp".

`Dhp` is the uid/acronym for the Pali Dhammapada text only, not for the whole group of Dhammapada texts.

- [x] Under some conditions, the breadcrumbs are mismatched.

![Screenshot from 2021-02-24 09-06-41](https://user-images.githubusercontent.com/6112010/108914762-f64b8280-767f-11eb-942c-a543f06041ab.png)

This persists even after a hard refresh. Unfortunately I can't recall how I created this condition. However, 

- [x] While trying to recreate the above, I got another set of mismatched breadcrumbs.

Here I navigated to https://staging.suttacentral.net/pitaka/sutta/linked/sn/sn-sagathavaggasamyutta then wrote https://staging.suttacentral.net/arv

![Screenshot from 2021-02-24 16-51-26](https://user-images.githubusercontent.com/6112010/108954460-f455e380-76c0-11eb-9666-03bfeb1b3a1f.png)

- [x] Another case. In this case, I navigated to https://staging.suttacentral.net/lal1/san/vaidya then entered https://staging.suttacentral.net/dk10 by hand in the URL bar. But the breadcrumbs for Lal remain.

![Screenshot from 2021-02-24 16-42-40](https://user-images.githubusercontent.com/6112010/108953552-80670b80-76bf-11eb-8b58-b90f9a6c21c8.png)

- [x] a similar bug. This time I start with a buggy set of breadcrumbs and enter a Sanskrit Abhidharma text in.

![Screenshot from 2021-02-24 16-58-09](https://user-images.githubusercontent.com/6112010/108954971-8f4ebd80-76c1-11eb-8f8d-2603e5d59e57.png)

- [x] Another case. Here I clicked on a "parallels" link. It takes me to the right page, but the breadcrumbs are wrong.

![Screenshot from 2021-02-24 16-48-10](https://user-images.githubusercontent.com/6112010/108954112-64179e80-76c0-11eb-9796-6f807a24d9fe.png)

- [x] Breadcrumbs for legacy HTML texts are missing the final breadcrumb, i.e. the Sutta UID.

![Screenshot from 2021-02-24 09-28-19](https://user-images.githubusercontent.com/6112010/108916745-ca7dcc00-7682-11eb-91fc-1f29e9ce9446.png)

This applies to legacy translations and root texts in Sanskrit, Chinese, etc.

- [x] Abhidhamma texts have breadcrumb bug

Navigate: Abhidhamma > Theravada > Compendium.

then click on a text: "Systematic Treatises" disappears from breadcrumbs instead we have "ab".

Similar bugs appear in other Abhidhamma texts.

**Comment by ihongda** [comment]
>On suttaplex-list pages, use translated title for sc-suttaplex-section-title.

The Related Suttaplex API needs to be modified here to update the relevant translations, I'll revise it later.

**Comment by sujato** [comment]
> > On suttaplex-list pages, use translated title for sc-suttaplex-section-title.
> 
> The Related Suttaplex API needs to be modified here to update the relevant translations, I'll revise it later.

Okay, I'll make a separate issue for this.

Most of the other items are fixed. I have put the ones still to do at the top. Note that the Dhammapadas navigation is still unreliable, I have updated the bug description.

**Comment by ihongda** [comment]
>After a search, the URL still retains the search query. Search query should only be in URL on search result pages

This problem has been fixed :)
