### ISSUE TITLE
Translated titles do not appear for some segmented texts in suttaplex list view

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2039]
The suttaplexes should also try to get a translated title. The following should be the order of priority:

1. from `name` file if available
2. from segmented translation if available
3. from legacy HTML  

Currently we don't have any titles for Brahmali's Vinaya.

![Screenshot from 2021-03-08 07-32-06](https://user-images.githubusercontent.com/6112010/110253915-d18cce80-7fe0-11eb-82cf-14c50f188823.png)

The same problem appears for the Japanese translations.

If I set the site language for Japanese, I should see the sutta titles in Japanese where available. But this is not the case:

![Screenshot from 2021-03-08 08-40-36](https://user-images.githubusercontent.com/6112010/110255873-1701c980-7fea-11eb-9400-171f750af26b.png)

The German translations work fine.

**Comment by ihongda** [comment]
The current rule is to use the translation title if there is a translation title, otherwise the original title is used.

`pli-tv-bu-vb-pj` currently has only the original title in the database 'names' collection.

`an4.58` only the `de` and 'root' version title in the `names` collection.
