### ISSUE TITLE
Prev/next localization and breadcrumbs are still buggy

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2046]
Here is a Japanese text. I got to it by selecting japanese from the menu, then navigating through the nav cards.

As you can see, the breadcrumbs are missing items. And the prev/next is in German!

![Screenshot from 2021-03-08 18-16-21](https://user-images.githubusercontent.com/6112010/110287640-f9108500-803a-11eb-82bb-1c3a2bc3aae9.png)

If I change language to English and navigate there, the breadcrumbs are correct, but the prev/next is still in german!

![Screenshot from 2021-03-08 18-22-11](https://user-images.githubusercontent.com/6112010/110287871-4c82d300-803b-11eb-9782-eea76dc12a98.png)

**Comment by ihongda** [comment]
Currently, the prev/next name is always obtained from the `names` collection, such as `an4.58`, with only `pli` and `German` versions, no English version, and the pali name is displayed by default if there is no version of the language.
