### ISSUE TITLE
Fixes for Chinese segmented texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2049]
Charles is introducing Chinese translations, so for the first time we have Chinese texts through Bilara. Currently they work great, but there are a couple of bugs.

## on suttaplex page

![Screenshot from 2021-03-09 09-49-15](https://user-images.githubusercontent.com/6112010/110392352-ea6ab200-80bc-11eb-975e-7717f5f2af21.png)

- [x] duplicate of segmented translation and legacy HTML. **Charles**: can we delete legacy HTML translations? How should we do this?
- [x] improper metadata for Chinese text. (Hopefully will be fixed by update to publication.json)

## on root chinese page

![Screenshot from 2021-03-09 09-52-50](https://user-images.githubusercontent.com/6112010/110392628-5816de00-80bd-11eb-984d-5aa555afd876.png)

- [x] translation data load error on root page

**Comment by winterdharma** [comment]
You can delete my legacy translations. The translations prior to 2019 are flawed and the translations in Bilara are the most up-to-date versions for those after 2019.

**Comment by sujato** [comment]
The metadata for Chinese texts is unfortunately *not* fixed by updating the relevant data files. I have done this, and the result is this:

![Screenshot from 2021-03-13 08-01-29](https://user-images.githubusercontent.com/6112010/110998248-a46e6080-83d2-11eb-88e0-cee2a65291a1.png)

The logic for this is in `sc-suttaplex-tx.js` inside `tx-publication`. (Note that in the CSS class, `creator` means both `author` and `edition`.)

The problem is that the logic is hard-coded with the expectation that the root will be Pali. So we have to define it dynamically.

The logic should be as follows:

- **if** this is a legacy HTML text, **then**:
    - root text = root language
    - translation = translation language
- **if** this is a segmented text, **then**:
    - root text = root language
    - translation = translation language + root language
