### ISSUE TITLE
Fix Chinese lookup tool

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2058]
The chinese lookup doesn't work.

Also, while we're at it, we can update the source files from the DDB.

**Comment by ihongda** [comment]
Bhante, where is DDB?

**Comment by sujato** [comment]
The website is here. Check it out, it's amazing!

http://www.buddhism-dict.net/ddb/

This dictionary is constantly improving, and there are new entries and corrections every month.

In the past, the developer Chuck Muller has kindly supplied us with a "concise" version of the dictionary, which we use for SC, and we link to the page on his site for the full entry. I just checked, and the link we use for the lookup is broken. I have emailed him to see about an update.
