### ISSUE TITLE
Use `main` instead of `master` for all repos

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2068]
In the last year, Github (and much of the developer community) has shifted from using "master" to "main", The reason is that the word "master" in English has a long and deep history with slavery, and thus carries racist connotations.

https://github.com/github/renaming

We should adopt "main" for our repos, at least for the active ones. If we do not, we will gradually fall out of step with best practices in the community.

Inactive repos are "archived", so rename all those that are not archived.

**Comment by thesunshade** [comment]
I just noticed this has never been completed. Here is the github documentation on re-naming: https://github.com/github/renaming

@sujato, was there some issue with making this change?

**Comment by sujato** [comment]
No, we should still go ahead with this, we simply never got around to it. 

As a rule, we should always strive to remain up to date with industry best standards. Better face an annoying bit of work now than maintain a code base that over time becomes ever more archaic.

**Comment by thesunshade** [comment]
@ihongda Does this seem like something you could do? The instructions are here: https://github.com/github/renaming?tab=readme-ov-file#renaming-existing-branches

With more information here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch

**Comment by ihongda** [comment]
@thesunshade Bhante, let me check and try.

**Comment by thesunshade** [comment]
Looks like there are a few places in the reop it needs to be changed:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/71237184-1aa3-4080-ab15-194035fc11d0)

**Comment by thesunshade** [comment]
Is `deploy.yml` still used?

**Comment by ihongda** [comment]
> Is `deploy.yml` still used?

Bhante, Yes, this is a github action that will run automatically when the code is submitted.

I have updated the deploy.yml in `main` branch.
