### ISSUE TITLE
Transliteration: Fonts missing for some scripts

### ISSUE THREAD

**Issue by virtualvinodh** [suttacentral/suttacentral#2116]
#### Description:

For some scripts, fonts are missing resulting in either boxes or just incorrect rendering.

#### Steps to reproduce:

Any Sanskrit/Pali page with transliteration plugin

#### Expected behavior:

The fonts are not being loaded for some reason. For instance, "Tamil Extended" should be rendered using the font "Agastya Tamil Extended" according to the CSS. But this is not being loaded. 

Similarly, for "Hanunoo" "Noto Sans Hanunoo" should be loaded. Currently, only boxes are being displayed.

#### Screenshots:
Hanunoo Page.

![image](https://user-images.githubusercontent.com/1050975/113928503-3493a000-97ef-11eb-8c8d-026bc327d834.png)

V

**Comment by ihongda** [comment]
Thank you for your feedback @virtualvinodh :pray:

**Comment by virtualvinodh** [comment]
@ihongda I noticed that this problem still exists in the new version.

The fonts are still not missing/loading for the following scripts:

(i) Tamil (Extended)
(ii) Vatteluttu
(iii) Ranjana
(iv) Hanunoo

Cheers!

Vi

**Comment by virtualvinodh** [comment]
Few more scripts that do not have the proper fonts loaded.

Khom Thai
Urdu

V

**Comment by ihongda** [comment]
@virtualvinodh Thank you :pray:  I will deal with it as soon as possible.

**Comment by ihongda** [comment]
Hey @virtualvinodh 
I have fixed the related problems, please take a look at some time :)

**Comment by virtualvinodh** [comment]
Looks good to me!

**Comment by ihongda** [comment]
> Looks good to me!

Thank you @virtualvinodh
