### ISSUE TITLE
Search engine not working

### ISSUE THREAD

**Issue by AlbertCoca** [suttacentral/suttacentral#2125]
#### Description:
Dear venerable Bhikkhu Sujato,

Today between 8:15UTC and 9:15 UTC I was trying to search for some suttas by title but the requests give 0 results.

Today at 10:30 UTC the problem persists.

#### Steps to reproduce:
* Open https://suttacentral.net and click on the search icon introduce the texts: 
* "Five aggregates": https://suttacentral.net/search?query=Five%20aggregates (Screenshot 1)
* "The All": https://suttacentral.net/search?query=The%20All (Screenshot 2)
* I guess with any other text will happen the same
* And the result will be 0 hits also.

#### Expected behaviour:
* When searching I would expect to find the suttas with the related search text.

#### Screenshots:
1. ![image](https://user-images.githubusercontent.com/20433529/115109726-cf227a80-9f77-11eb-905c-c6cf2d797762.png)
2. ![image](https://user-images.githubusercontent.com/20433529/115109759-f5481a80-9f77-11eb-9593-0407deebc5b0.png)

I would like to use this opportunity to thank you a lot for this amazing work. I'm using suttacentral very often and I find it an essential tool to keep learning the dhamma.

Thank you to bring the texts closer to everyone in the world.

**Comment by ihongda** [comment]
@AlbertCoca  Thank you for the feedback, We'll fix it as soon as possible :)

**Comment by sujato** [comment]
It's fixed now
