### ISSUE TITLE
Root title in parallels is sometimes in wrong language

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2135]
I came across a case here:

https://suttacentral.net/sa200/en/analayo

The root text is in Pali, but it has a title in German:

![Screenshot from 2021-04-27 09-27-54](https://user-images.githubusercontent.com/6112010/116163559-5374ba80-a73b-11eb-8aa3-946a50db55e8.png)

Here's another case. In this one, there is only one title, no translated + root titles. And the titles are randomly either in English, German, or root!

![Screenshot from 2021-04-27 09-36-28](https://user-images.githubusercontent.com/6112010/116164070-65a32880-a73c-11eb-8210-1ab749e35741.png)

**Comment by ihongda** [comment]
Strange, local and staging are normal.
I'll check after the production update.

**Comment by ihongda** [comment]
This problem has been fixed!
