### ISSUE TITLE
Search returns stale results

### ISSUE THREAD

**Issue by firepick1** [suttacentral/suttacentral#2153]
#### Description:
SuttaCentral apparently uses a cookie to cache search results. If the actual search results change, then the cached result is stale. Deleting SC cookies solves the issue, but that's not something a user would be expected to do.

#### Steps to reproduce:

* [include links were possible]
https://suttacentral.net/api/search?limit=50&query=root%20of%20suffering&language=en&restrict=all

#### Expected behaviour:
Suggest not using cookies or using a cookie with a 5-minute expiration date. Caching search results is not a good idea when content changes as it does with SC.

#### Screenshots:
n/a

**Comment by sujato** [comment]
agree, I think there should be no need to cache search results at all.
