### ISSUE TITLE
Change the way we mark up verses

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2167]
There's no explicit markup for verses in HTML. Currently we follow the following:

```
<blockquote class='gatha'>
<p>Line of verse <br>
Another line here<br>
And here is a third<br>
And finally a fourth.</p>
</blockquote>
```

This is an effective and simple method, however it creates a problem when there is a verse in the root but not in the translation. The `<br>` tags still generate new lines.

Another recommended approach is to use `white-space: pre`. The problem with this, however, is that it relies on the `\n` being respected, which is usually not the case when content is minified.

The final approach is the most explicit one, and is used by TEI: wrap each line in a tag.

```
<blockquote class='gatha'>
<p>
<span class='verse-line'>Line of verse </span>
<span class='verse-line'>Another line here </span>
<span class='verse-line'>And here is a third </span>
<span class='verse-line'>And finally a fourth. </span>
</p>
</blockquote>
```

This is more verbose, but it has the advantage of being fully explicit. It also enables more sophisticated styling, eg. we could indent every second line. Metrical details could also be added per-line using `::before`.

Let's do this!

**Comment by MareinK** [comment]
I think this regex might be close to achieving the desired effect, I might try it large-scale later.

pattern:
```
(?<=<blockquote class='gatha'>[\s\n]*<p>(?:(?!blockquote)[\s\S\r])*)(.+)(?=<\\?/? *(br|p)>[\s\S\r]*?</blockquote>)
```
replacement:
```
<span class='verse-line'>$1</span>
```

**Comment by sujato** [comment]
We've actually implemented this in Bilara, so there's no real need.

The HTML legacy texts still use the old standard, but that's okay, we are pretty much just leaving them as-is.

I'll close this issue, sorry to waste your time.
