### ISSUE TITLE
Sometimes translated titles are not being used

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2172]
Sometimes, even in English where we know all suttas are translated, we find a mix of translated titles and root language titles:

![Screenshot from 2021-06-01 10-10-13](https://user-images.githubusercontent.com/6112010/120250518-c4227000-c2c1-11eb-9e27-f5bbe2ed6d86.png)

**Always use translated title if there is one**

**Comment by ihongda** [comment]
The titles of some sutta are indeed untranslated, such as MN144, MN145:

`bilara-data/translation/en/sujato/name/sutta/mn-name_translation-en-sujato.json`

**Comment by sujato** [comment]
No, the sutta titles should pull from the name files first, then fallback to the sutta files if there is nothing in the `name` file. 

We have always used the sutta files for adding names. The `name` files are an extra, which we use primarily for the upper navigation levels (vagga, etc.). There was never any intention to use *only* the name files. 

See previous discussions:

https://github.com/suttacentral/suttacentral/issues/2039

https://github.com/suttacentral/suttacentral/issues/1660

In the following case, the sutta name *is* appearing on the site, even though it is not in the `name` file:

https://github.com/suttacentral/suttacentral/issues/2026
https://suttacentral.net/sn1.68
