### ISSUE TITLE
Localization: Pluralization

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#2202]
In the current client code we only have a few examples of pluralization which are handled in a variety of ways using linguistic or code hacks. One such case is:

```js
    const translationKey = this.item.parallel_count === 1 ? 'countParallel' : 'countParallels';
    this.localize(translationKey, { count: this.item.parallel_count })};
```

So there are two strings: countParallel for 1 parallel, and countParallels for 0 or more than 1 parallel. This works fine for English and many other languages, but for a languages such as French and Russian the resulting strings will not always read correctly, having exactly the same problem as saying "1 parallels" in English. If it's worth doing right in English, it's worth doing right in all languages. (Of course, not doing it right in any language is an option...)
     
One possibility to use polyglot.js as it fits our needs well. polyglot.js is a tiny standalone library that handles pluralization for many languages using gettext conventions for locale pluralization rules.

In polyglot the english string looks like this:

```text
"%{smart_count} parallel |||| %{smart_count} parallels"
```

A quad pipe is used to delimit each plural form, and as many quad pipes are used as required to delimit the plural forms for the locale. With the locale set correctly, polyglot.js will correctly interpret the quad-pipe delimited string. The translator needs to be aware of the order of the plural forms for their locale, but this follows gettext conventions so is nothing too crazy.

The important thing for us, is that for each language the plural forms are *just one string*, this makes it fit perfectly with Bilara which is a simple one string to one string translation whether the language has 1 or 5 plural forms.

To consider an alternative: Modern Browsers have a built-in function for pluralization in the form of **Intl.PluralRules** which can be used like this:

```js
new Intl.PluralRules('en').select(0);
// "other"
new Intl.PluralRules('en').select(1);
// "one"
new Intl.PluralRules('fr').select(0);
// "one"
new Intl.PluralRules('fr').select(1);
// "one"
```

When fed a locale and a number, this returns an english word describing the plurality. English and French only have `["one", "other"]` (but french also applies "one" for 0). Welsh on the other hand, can return `["zero", "one", "two", "few", "many", "other"]`

Intl.PluralRules is not widely used, or at all as far as I can tell so there don't seem to be any conventions for its use, altough it does seem to actually work and would save a few ten's of kb and it seems to be well supported in modern browsers. From what little reference I could find to it being used, it seems to be regarded as eccentric

We could imagine a scheme for putting this into a single string, something like:
```text
"#ONE {count} parallel #OTHER {count} parallels".
```
A concept I've also seen in some other javascript libraries is the ability to put arbitrary numbers in the list of plurals to allow more natural looking use of language for particular numbers, for example:
```text
"#0 No parallels #111 Eleventyone parallels #ONE {count} parallel #OTHER {count} parallels"
```
Whether or not it is useful, it is quite a trivial thing for a pluralization function to handle.

While Intl.PluralRules is widely not used it would be tempting to use it for the sake of leveraging modern browser abilities and the use of named plural groups makes it possible for the pluralization function to recognize not only that a plural form is missing, but which one is missing.

**Comment by thesunshade** [comment]
I don't think this issue is still relevant to the current site design/localization coding so I will close for now.
