### ISSUE TITLE
Replace Upper Case E and O as well during transliteration

### ISSUE THREAD

**Issue by virtualvinodh** [suttacentral/suttacentral#2205]
Currently, only lower case e/o is being replaced. This should include upper case E/O as well. This causes sentences such a "Evaṁ me sutaṁ" to be transliterated incorrectly.

This can be avoided by converting everything into lowercase or just adding two more replace statements.

Replace Line 1012 in views.py:

`sutta_texts[uid][key] = transliterate.process('ISO', target, value.replace('o', 'ō').replace('e', 'ē'))
`

with

`sutta_texts[uid][key] = transliterate.process('ISO', target, value.lower().replace('o', 'ō').replace('e', 'ē'))
`

or 

`sutta_texts[uid][key] = transliterate.process('ISO', target, value.replace('o', 'ō').replace('e', 'ē').replace('O', 'Ō').replace('E', 'Ē'))
`

V

**Comment by ihongda** [comment]
Thank you @virtualvinodh

**Comment by virtualvinodh** [comment]
@ihongda Could you give me a shout once the changes are live (or on the staging site)? I can have a look.

V

**Comment by ihongda** [comment]
> @ihongda Could you give me a shout once the changes are live (or on the staging site)? I can have a look.
> 
> V

@virtualvinodh Sure! :smile:

**Comment by ihongda** [comment]
Hey @virtualvinodh , The latest update has been pushed to [staging](https://staging.suttacentral.net)
