### ISSUE TITLE
Introduction to SuttaCentral page doesn't display Portuguese or German translation as expected

### ISSUE THREAD

**Issue by ccronje** [suttacentral/suttacentral#2217]
#### Description:
[Introduction to SuttaCentral](https://suttacentral.net/introduction) is not displaying Portuguese or German translations as expected.

The Portuguese translation displays with English segments dispersed throughout. The source file is located at:
https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/pt/site/introduction_translation-pt-site.json

The German translation displays English. The source file is located at:
https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/de/site/introduction_translation-de-site.json

#### Steps to reproduce:
* Go to https://suttacentral.net/introduction
* Select Deutsch or Portuguese from vertical ellipsis top right of screen

#### Expected behaviour:
Display source file data.

#### Screenshots:
Portuguese examples.

https://suttacentral.net/introduction:
![image](https://user-images.githubusercontent.com/7553548/123630782-47030000-d859-11eb-8c83-e1ca09de14a1.png)

Corresponding [source file](https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/pt/site/introduction_translation-pt-site.json) segment not being displayed as expected:
![image](https://user-images.githubusercontent.com/7553548/123635223-c7782f80-d85e-11eb-82b3-617c0c47af1d.png)

https://suttacentral.net/introduction:
![image](https://user-images.githubusercontent.com/7553548/123633150-30aa7380-d85c-11eb-80e6-56a92e6924da.png)

Corresponding [source file](https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/pt/site/introduction_translation-pt-site.json) segments not being displayed as expected:
![image](https://user-images.githubusercontent.com/7553548/123634261-90554e80-d85d-11eb-8f3d-d9ed973642e0.png)

**Comment by MareinK** [comment]
This seems fixed. At least on https://suttacentral.net/introduction all text is properly translated when selecting German or Portuguese.
