### ISSUE TITLE
Transliteration not working for Sanskrit texts

### ISSUE THREAD

**Issue by virtualvinodh** [suttacentral/suttacentral#2228]
Transliteration doesn't seem to work for Sanskrit texts.

[https://suttacentral.net/san-mu-kd1/san/gbm](https://suttacentral.net/san-mu-kd1/san/gbm)

![image](https://user-images.githubusercontent.com/1050975/126869983-6912cd94-8436-40ad-b718-551eab5c44e9.png)

If it's just a loading delay, a loading indicator might be helpful for longer texts.

Vinodh

**Comment by sujato** [comment]
Yes, that’s correct, we’ve only implemented it for Pali. It’s been in the back of my mind, but I haven’t made an explicit issue for it up to now. But here it is!

https://github.com/suttacentral/suttacentral/issues/2229

**Comment by thesunshade** [comment]
It looks like this could be closed since there is a full issue for this now.
