### ISSUE TITLE
Info tab CC0 license image b0rken

### ISSUE THREAD

**Issue by mxmilkiib** [suttacentral/suttacentral#2235]
#### Description:

"This site can’t be reached
licensebuttons.net’s server IP address could not be found.
DNS_PROBE_FINISHED_BAD_CONFIG"

![Screenshot_20210802-012722_Chrome](https://user-images.githubusercontent.com/108225/127790201-877e3a1c-9efc-47eb-83eb-4be88397ddd5.png)

**Comment by sujato** [comment]
This is a genuine bug, but it has been resolved already. Probably a hard refresh should fix this for you. Thanks for reporting!
