### ISSUE TITLE
Content is sometimes outside HTML

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2243]
Have a look at the Dhammapada:

https://suttacentral.net/dhp1-20/en/sujato

```
<h2 class="sutta-title"></h2>
<span class="segment" id="dhp1:0.4"><span class="root" translate="no" lang="pli"><span class="text"><span class="word" id="word_3">Cakkhupālattheravatthu</span> </span></span></span>
```

As you can see the content falls outside its HTML. It should be:

```
<h2 class="sutta-title">
<span class="segment" id="dhp1:0.4"><span class="root" translate="no" lang="pli"><span class="text"><span class="word" id="word_3">Cakkhupālattheravatthu</span> </span></span></span>
</h2>

```

Also see this issue on Discourse, which may be the same thing:

https://discourse.suttacentral.net/t/continuation-of-discussion-for-bilara-users-part-2/20151/102

- **content must always be wrapped in the relevant HTML**

**Comment by ihongda** [comment]
It seems that the related markup lacks curly braces 
e.g.  http://localhost/dhp1-20/en/sujato
server/sc-data/sc_bilara_data/html/pli/ms/sutta/kn/dhp/dhp1-20_html.json

`"dhp1:0.4": "<h2 class='sutta-title'></h2>\n",`

to  

`"dhp1:0.4": "<h2 class='sutta-title'>{}</h2>\n",`


![深度截图_选择区域_20210820171929](https://user-images.githubusercontent.com/4037966/130211437-4abd5d18-7ecd-4254-95bf-4e3b892c328c.png)

**Comment by sujato** [comment]
ahh okay, well let me look at that and fix it. It should go into our testing integrity suite, I'll discuss with Andrew.
