### ISSUE TITLE
lookup tool is not working

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2254]
See thread here:

https://discourse.suttacentral.net/t/dictionary-lookup-not-working/21330/1

Both the Pali and The Chinese lookup tools are not working.

**Comment by ihongda** [comment]
The related dictionary API does not return the expected data, but it is normal locally and staging, I am checking.

**Comment by ihongda** [comment]
This problem has been fixed, This problem is related to Nginx cache. After I emptied the cache, it returned to normal.
