### ISSUE TITLE
Don't let "reading" icons get squashed

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2285]
https://discourse.suttacentral.net/t/suttacentral-2021-bug-reports-here/19609/106

**Comment by thesunshade** [comment]
The squished icons problem seems to be solved, so I'm going to close this.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/1a85a17d-6c02-4fde-94ef-ec1441691691)

As well, all other issues linked to above seem to have been solved.
