### ISSUE TITLE
Voice links for vagga-suttas

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2288]
In an 1s and 2s, there's no Voice link in the SuttaPlex. Voice handles these as individual suttas, so we have to figure out how to link to the whole vagga.

**Comment by sabbamitta** [comment]
This issue has still not been solved.
>Voice handles these as individual suttas

I think this is not quite correct. If you type `an1.1` in Voice, or any number within that range, you get AN1.1-10.

I just noticed that for the Dhp there are also no Voice icons, and I think this is for the same reason: they are "vagga suttas".

I am still adding another bug with Voice icons on SC: They only appear when SC language is set to English, whether vagga sutta or not.

**Comment by ihongda** [comment]
These two bugs have been fixed :) @sabbamitta
