### ISSUE TITLE
Clean up breadcrumbs (linden leaves) logic.

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#2299]
Currently the strings that appear in the bread crumbs for navigating up are localized using site (client side) localization.

Example crumbs might be:

    Home -> Discourses -> Long -> DN

With Home, Discourses and Long being generally localized.

This presents an issue, because the value like "Long" is not derived from the client javascript, but instead arrives from the data API in the form of "acronym".

My suggestion is that ALL values that arrive from the API should be localized by the API and not the client. Much content is already localized on the API end, including of course texts and also things like super-names.

While the super-names data comes close to what we want, it is not exactly right, as it is often localized without the thought that it might be used for breadcrumbs. So it would probably be most logical to create a new data file under root/misc/site called something like "breadcrumbs", and have the API pull localized values from that to send to the client.

**Comment by sujato** [comment]
Is this still relevant?

**Comment by ihongda** [comment]
Let me check :)

**Comment by ihongda** [comment]
I have removed the code to get the translated title from the local file, it is currently preferred to get it from the API.
