### ISSUE TITLE
clicking on search or menu in toolbar makes page go back to top

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2322]
Open any page, scroll down. Then click in the universal toolbar for either "search" or "menu". The search or menu opens up; and meanwhile, the page jumps back to the top.

This doesn't affect the contextual toolbar, which has the correct behavior: don't change the page position when you interact with the toolbar. When you *close* the search or menu, it's also correct. The bug only affects opening.

- **Opening search or menu should not affect the page scroll position.**

**Comment by ihongda** [comment]
Currently, chrome, edge, and firefox on my machine cannot reproduce this problem, I will continue to observe.

**Comment by sujato** [comment]
It's very strange, it happens all the time on my desktop, but using the exact same Chrome version on my laptop it doesn't happen at all.

It doesn't seem to be affected by any variables or settings.

There's no console errors.

Here's a screencast of the problem on my desktop. (link expires in 24 hours)

https://wormhole.app/jobrj#XNe95-VsztgOHOiFdlCuQw
