### ISSUE TITLE
German translation of Puggalapannati has disappeared

### ISSUE THREAD

**Issue by Manfredsuttacentral** [suttacentral/suttacentral#2324]

**Comment by thesunshade** [comment]
It is there in part: 

![image](https://github.com/suttacentral/suttacentral/assets/82448383/da4a451a-1ace-4345-a937-6af12aac92cc)

@sabbamitta do you know if the complete translation was ever there?

**Comment by sabbamitta** [comment]
Yes, the texts from pp2.1 onward have been translated by Ven. Nyanatiloka. I don't remember having ever seen the entire thing, so as far as my memory goes, no, it has never been complete.

But I could still ask Ayya Agganyani, *the* German master of Abhidhamma texts. (She also has some contributions on SC.)

**Comment by Manfredsuttacentral** [comment]
Dear ven. Sabbamitta,

I am quite sure I once saw PP in German on SC and that it disappeared at some point. That's why I created the ticket. Maybe it can be found in some old backups?

 

Kind regards,

 

Manfred

 
 

Gesendet: Dienstag, 27. Februar 2024 um 09:20 Uhr
Von: "sabbamitta" ***@***.***>
An: "suttacentral/suttacentral" ***@***.***>
Cc: "Manfredsuttacentral" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [suttacentral/suttacentral] German translation of Puggalapannati has disappeared (Issue #2324)


 

Yes, the texts from pp2.1 onward have been translated by Ven. Nyanatiloka. I don't remember having ever seen the entire thing, so as far as my memory goes, no, it has never been complete.

But I could still ask Ayya Agganyani, the German master of Abhidhamma texts. (She also has some contributions on SC.)

**Comment by sabbamitta** [comment]
Dear Manfred, 
Thank you so much for your great care for this text. I can't tell 100% if it has ever been complete, I haven't been with SC from its very beginnings. I only can tell as far as my memory goes.

I also have no idea if there are any old backups somewhere, I'd rather doubt it. Then the question is: who might know about this?

Looking into the "info" section of the existing text, it says:

> Übersetzer:Bhikkhu Nyanatiloka.
> 
> Cip-gegevens Koninklijke Bibliotheek, Den Haag:
> 
> Puggala Paññatti—Das Buch der Charaktere / aus dem buddhistischen Pali-Kanon (Abhidhammo) zum ersten Male übers. von Bhikkhu Nyanatiloka.
> 
> Capelle aan den Yssel: Schloss 1e dr.: Breslau Walter Markgraf, 1910.—(Veröffentlichungen der Deutschen Pali-Gesellschaft, 1)
> 
> © 1995 Oskar Schloß Verlag, Capelle a/d Yssel
> 
> Alle Rechte vorbehalten
> 
> Umschlaggestaltung: Gerolf T'Hooft
> 
> Gesamtherstellung: Optima Druck, Molenaarsgraaf
> 
> ISBN 90–5642–004–6
> 
> Digitale Fassung entnommen aus:[http://palikanon.de/](http://www.palikanon.de/).
> 
> Prepared for SuttaCentral by Ayya Vimala.

So one path could be to find out if this Oskar-Schloß-Verlag does still exist, another would be to ask Ven. Vimala who prepared the text for SC if they remember the details. Or else to ask Ayya Agganyani if she knows what exactly has been translated by Ven. Nanatiloka.

**Comment by Manfredsuttacentral** [comment]
I think, the easiest way would be to ask ven. Vimala. Would you like to do that, or should I?

 
 

Gesendet: Dienstag, 27. Februar 2024 um 10:27 Uhr
Von: "sabbamitta" ***@***.***>
An: "suttacentral/suttacentral" ***@***.***>
Cc: "Manfredsuttacentral" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [suttacentral/suttacentral] German translation of Puggalapannati has disappeared (Issue #2324)


 

Dear Manfred,
Thank you so much for your great care for this text. I can't tell 100% if it has ever been complete, I haven't been with SC from its very beginnings. I only can tell as far as my memory goes.

I also have no idea if there are any old backups somewhere, I'd rather doubt it. Then the question is: who might know about this?

Looking into the "info" section of the existing text, it says:


Übersetzer:Bhikkhu Nyanatiloka.

Cip-gegevens Koninklijke Bibliotheek, Den Haag:

Puggala Paññatti—Das Buch der Charaktere / aus dem buddhistischen Pali-Kanon (Abhidhammo) zum ersten Male übers. von Bhikkhu Nyanatiloka.

Capelle aan den Yssel: Schloss 1e dr.: Breslau Walter Markgraf, 1910.—(Veröffentlichungen der Deutschen Pali-Gesellschaft, 1)

© 1995 Oskar Schloß Verlag, Capelle a/d Yssel

Alle Rechte vorbehalten

Umschlaggestaltung: Gerolf T'Hooft

Gesamtherstellung: Optima Druck, Molenaarsgraaf

ISBN 90–5642–004–6

Digitale Fassung entnommen aus:http://palikanon.de/.

Prepared for SuttaCentral by Ayya Vimala.


So one path could be to find out if this Oskar-Schloß-Verlag does still exist, another would be to ask Ven. Vimala who prepared the text for SC if they remember the details. Or else to ask Ayya Agganyani if she knows what exactly has been translated by Ven. Nanatiloka.

**Comment by thesunshade** [comment]
I think this is the folder of Pp from the legacy site:

https://github.com/suttacentral/legacy-suttacentral-data/tree/master/text/de/pi/ab/pp

And this is what is published on Palikanon.de:  http://www.palikanon.de/abhidham/puggalap/pp_idx.html

**Comment by sabbamitta** [comment]
Thank you for this, Ven. @thesunshade ! This shows that SC-legacy only had the text from 2.1 onward, as the current SC has. The first text on palikanon.de, although a different numbering, is also titled "Der Zeitweilig-Befreite" and seems to be the same text as pp2.1 on SC.

>I think, the easiest way would be to ask ven. Vimala. Would you like to do that, or should I?

I will meet them tomorrow and can ask them. 

---
**Added:**
I also notice that the first chapter on palikanon.de is titled "Einer-Darstellung", and the second from their number 51 onward "Zweier-Darstellung". Perhaps what we have on SC is a misnumbering? But I am just not familiar with Abhidhamma texts and their organization at all to say anything on this.

---
**Correction:**
Looking more closely, I see that SC too has "Einer-Darstellung" at the top of pp2.1. So it appears indeed that this is all that Ven. Nyanatiloka has translated. I don't know, maybe he used a manuscript that only had the second part?

**Comment by sabbamitta** [comment]
I also see that the issue originally stems from Nov 2021! Wow!

Thank you so much, Ven. @thesunshade , for digging out all these old issues that haven't received any attention so far—which they certainly deserve; even if it turns out that the initial assumption doesn't apply. It's always good to have clarity.

**Comment by sabbamitta** [comment]
I have now compared what is on SC with what is on palikanon.de; not word by word, but title by title, and they seem to be identical. I.e. all that is on palikanon.de is also on SC. SC's manuscript seems to have another section that Ven. Nyanatiloka's perhaps didn't have, I don't know, but manuscripts do in fact vary.

I can ask Ven. Vimala if there's still another source that has been used when I see them tomorrow, but I don't think so. I have a vague memory—slowly coming up while I am doing this here—that this was in fact the source that was used.

So it seems your memory wasn't correct, @Manfredsuttacentral —that happens … you are not alone with this! :smiley:

**Comment by thesunshade** [comment]
I'm going to close this issue for now. If you find out that there is indeed something that should be added to this collection, please start a new issue.

And feel free to keep discussing in this issue if need be.

Thanks to both of you!

**Comment by Manfredsuttacentral** [comment]
Touché!

 
 

Gesendet: Dienstag, 27. Februar 2024 um 13:06 Uhr
Von: "sabbamitta" ***@***.***>
An: "suttacentral/suttacentral" ***@***.***>
Cc: "Manfredsuttacentral" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [suttacentral/suttacentral] German translation of Puggalapannati has disappeared (Issue #2324)


 

I have now compared what is on SC with what is on palikanon.de; not word by word, but title by title, and they seem to be identical. I.e. all that is on palikanon.de is also on SC. SC's manuscript seems to have another section that Ven. Nyanatiloka's perhaps didn't have, I don't know, but manuscripts do in fact vary.

I can ask Ven. Vimala if there's still another source that has been used when I see them tomorrow, but I don't think so.

So it seems your memory wasn't correct, @Manfredsuttacentral —that happens … you are not alone with this! 😃

**Comment by sabbamitta** [comment]
Mach dir nichts draus, @Manfredsuttacentral . Zumindest hat es geholfen, dass ich mein Gedächtnis für manche Sachen wieder ein bisschen aufgefrischt habe. :smiley: 

Ich hoffe, es geht dir gut, und schicke Grüße nach Hamburg!

**Comment by Manfredsuttacentral** [comment]
Danke für die schicken Grüße!

 

Bei mir ist alles gut. Ich arbeite an der Digitalisierung der Sri Lankanischen Encyklopädie des Buddhismus und den Nikayas auf Deutsch. S ist gerade fertig (https://www.suttanta.de/bibliothek/) und Andrea Kohn - ich weiß nicht ob Du sie kennst - fängt gerade das Korrekurlesen von AN an. Die Jatakas von Dutoit liegen auch digital vor, falls Du die als Vorlage brauchen solltest. Sind aber noch nicht korrigiert.

 

Sag gerne Bescheid wenn Du mal wieder nach HH kommst wegen Dana oder Austausch oder Beides.

 

Liebe Grüße,

 

Manfred

 

 

 
 

Gesendet: Mittwoch, 28. Februar 2024 um 11:36 Uhr
Von: "sabbamitta" ***@***.***>
An: "suttacentral/suttacentral" ***@***.***>
Cc: "Manfredsuttacentral" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [suttacentral/suttacentral] German translation of Puggalapannati has disappeared (Issue #2324)


 

Mach dir nichts draus, @Manfredsuttacentral . Zumindest hat es geholfen, dass ich mein Gedächtnis für manche Sachen wieder ein bisschen aufgefrischt habe. 😃

Ich hoffe, es geht dir gut, und schicke Grüße nach Hamburg!

**Comment by sabbamitta** [comment]
Lieber Manfred, wenn du willst, können wir den Austausch gerne via Email fortsetzen, das ist vielleicht einfacher. Meine Email-Adresse dhammaregen@gmail.com ist ohnehin öffentlich, wenn du willst kannst du gerne dahin schreiben (und sobald ich von dir eine Email erhalte, werde ich trotzdem diesen Post löschen, da er nichts mit der ursprpnglichen Frage zu tun hat).

**Comment by sabbamitta** [comment]
>Ich arbeite an der Digitalisierung der Sri Lankanischen Encyklopädie des Buddhismus und den Nikayas auf Deutsch. S ist gerade fertig (https://www.suttanta.de/bibliothek/) und Andrea Kohn - ich weiß nicht ob Du sie kennst - fängt gerade das Korrekurlesen von AN an. Die Jatakas von Dutoit liegen auch digital vor, falls Du die als Vorlage brauchen solltest. Sind aber noch nicht korrigiert.

Ich wollte eigentlich gerne wissen, was der Unterschied ist zwischen dem, was bisher auf SC vorliegt (ich dachte, das sei auch digital), und dem, was ihr gerade macht. Bin neugierig! :smile:
