### ISSUE TITLE
Feature Request: Consider adding margin to segment class

### ISSUE THREAD

**Issue by Chetan11-dev** [suttacentral/suttacentral#2331]
Visit https://suttacentral.net/mn118/en/sujato?layout=linebyline&reference=mr&notes=asterisk&highlight=false&script=Devanagari 
Text will look like
![Screenshot from 2021-11-25 03-55-34](https://user-images.githubusercontent.com/53407137/143320533-fccef34d-e147-48d4-9c9c-ba282da0f66e.png)
Now add (margin: 50px 0) to .segment class
![Screenshot from 2021-11-25 03-56-37](https://user-images.githubusercontent.com/53407137/143320634-bf242593-8269-4b25-9bc6-a610bbcc563a.png)
You will observe that text will become so much more observable.

**Comment by sujato** [comment]
Thanks for the suggestion, but we'll be leaving it as-is. Currently you can see the margin when there is a paragraph break. If we added margins to every segment, you could no longer see where the paragraphs are. 

In addition, I don't think this makes it more readable—too much whitespace—although that's obviously a personal judgment.

If you want to do this for your own reading, you can install the Stylus browser addon, then for SC add the following CSS (modify as you wish, this is just a starter):

```
.segment {
    gap: 2em
}
```

**Comment by Chetan11-dev** [comment]
:)
