### ISSUE TITLE
Nilakkhana transformation for links  in comments (and probably generally)

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2335]
Comments will frequently link to somewhere else in the Pali texts, or less often, to things external. We'll need to make sure we have a clear notation, which allows (a) simple writing by translators, and (b) simple processing.

## internal links

Internal links indicate another Bilara text; most often, in Pali, but including roots in Chinese, Sanskrit, etc.

**The translator inputs the raw Bilara ID inside a bare markdown link**

```
See variant reading at [sn1.1:1.7]().
```

A regular commonmark transformation would make this:

```
<a href="">sn1.1:1.7</a>
```

This wouldn't work as a link, but at least it's readable, so that's a robust fallback.

To make it work, we'll need to add a proper `href`. Add it to root. 

Note that **the colon in the `href` must be changed to a hash**. Note that the visible text still uses colon.

```
<a href="/sn1.1#1.7">sn1.1:1.7</a>
```

Now, this URL will in fact point to a bare suttaplex, not a text, because the translator and language are not specified. So, we need to add these; they are the same as the language and translator of the comment.

```
<a href="/sn1.1/en/sujato#1.7">sn1.1:1.7</a>
```

Finally, we can cook the raw ID by using the acronym. Remember to do this only using our explicit data, not by auto-uppercasing!

https://github.com/suttacentral/sc-data/blob/master/misc/uid_expansion.json

```
<a href="/sn1.1/en/sujato#1.7">SN 1.1:1.7</a>
```

In some cases there is no segment ID, just a sutta ID. This is treated exactly the same, except there is no hash.

Thus `[sn1.1]()` becomes

```
<a href="/sn1.1/en/sujato">SN 1.1</a>
```

## external links

In this case, since the external link might be any kind of resource (a PDF, a discourse discussion, a website, a Youtube video …) we cannot predict or control the form, so we simply require a proper commonmark specification from translators. They must include the full text and URL. 

```
See [this Youtube video](https://www.youtube.com/watch?v=dQw4w9WgXcQ).
```

Which becomes

```
See <a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ'>this Youtube video</a>.
```

- [x] use hash not colon for segment number in `href`
- [x] specify translator and language in URL
- [x] transform visible ID to formal acronym style (snp1.3:7 becomes Snp 1.3:7)

**Comment by blake-sc** [comment]
This should be done now with https://github.com/suttacentral/bilara-data/commit/236f677e38753de152d90fc1039c211f225fe379 the changes have also been propagated to comments in sc-data
