### ISSUE TITLE
make load-data has extra de blurbs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2336]
I thought we fixed this?

Duplicate key value：pli-tv-bu-vb-as1_de
Duplicate key value：pli-tv-bu-vb-as2_de
Duplicate key value：pli-tv-bu-vb-as3_de
Duplicate key value：pli-tv-bu-vb-as4_de
Duplicate key value：pli-tv-bu-vb-as5_de
Duplicate key value：pli-tv-bu-vb-as6_de
Duplicate key value：pli-tv-bu-vb-as7_de
Duplicate key value：pli-tv-bu-vb-as_de
Duplicate key value：pli-tv-bu-vb-ay1_de
Duplicate key value：pli-tv-bu-vb-ay2_de
Duplicate key value：pli-tv-bu-vb-ay_de
Duplicate key value：snp-atthakavagga_de
Duplicate key value：snp-culavagga_de
Duplicate key value：snp-mahavagga_de
Duplicate key value：snp-parayanavagga_de
Duplicate key value：snp-uragavagga_de
Duplicate key value：pli-tv-bu-vb-sk69_de
Duplicate key value：pli-tv-bu-vb-sk_de

**Comment by thesunshade** [comment]
This is a duplicate of https://github.com/suttacentral/suttacentral/issues/2441
