### ISSUE TITLE
Use Cloudflare web analytics

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#2344]
At the moment we don't have browser-side  analytics to provide information like page load timings and javascript errors as experienced by real users in the wild.

I suggest we use Cloudflare web analytics, here is the friendly page with infographics:

https://www.cloudflare.com/web-analytics/

For a site proxied through Cloudflare with a pro or better plan there is already fairly good analytics based on the edge servers, though this analytics by its nature can not provide any insight into what the user (should they be a human and not a robot) experiences.

Adding web analytics should be as simple as giving Cloudflare permission to add the snippet automatically.

**Comment by sujato** [comment]
Here's a good technical review:

https://www.ctrl.blog/entry/review-cloudflare-analytics.html

It looks good, the privacy standards seem strong, and the front-end cost is only 4.31kb.

Note that there are some technical issues flagged in the article.

>In my testing of the service, I found that Cloudflare Web Analytics misidentifies almost all page views as visits to / (the root path/home page). This completely undermines its ability to track which pages on your website receive the most visitors. Cloudflare’s script collects the correct path, so this seems to be a bug in how Cloudflare processes the submissions.
