### ISSUE TITLE
Service worker download a bunch of pointless files

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#2346]
#### Description:

When the service worker is freshly loaded it will download .otf font files even if the browser won't ever use them, *.js.LICENESE.txt files and the localization files for all languages.

This results in it downloading something like 8 mb of stuff: the home page itself only needs around 2 mb of stuff.

#### Steps to reproduce:

Open an incognito window in Chrome. Open inspector. Browse to suttacentral.net and check the network tab.

#### Expected behaviour:

Only essential files should be pre-cached, this should probably be a whitelist: pre-cache nothing if not explicitly told to. Stuff which should be pre-cached is probably only the build .js files.

We could probably just not create the *.js.LICENESE.txt files at all, not sure about the official legality but there are ways: https://github.com/webpack/webpack/issues/12506

#### Screenshots:
![too many files](https://user-images.githubusercontent.com/5808762/145382730-c1579d89-396f-42bb-b97e-e4cce22fab34.png)

**Comment by sujato** [comment]
There should be no otf fonts at all, I will make a separate issue for this.

**Comment by sujato** [comment]
Just a hunch, but this kind of major payload sounds like the dev version. I wonder if, since converting to Vite, we are mistakenly serving the dev version in production?

**Comment by ihongda** [comment]
> Just a hunch, but this kind of major payload sounds like the dev version. I wonder if, since converting to Vite, we are mistakenly serving the dev version in production?

As pointed out in PR #2319, due to some advantages, currently production still uses webpack to build

The production build of vite is also different from the development model, and it is also packaged using rollup.
