### ISSUE TITLE
Internal Server Error on download page

### ISSUE THREAD

**Issue by Naitreey** [suttacentral/suttacentral#2351]
#### Description:
Hi, I'm trying to download sutta epubs from [the download page](https://suttacentral.net/downloads). But only a JSON file `mn_en_sujato.epub.json` containing the following message is actually downloaded:

```json
{"message": "Internal Server Error"}
```

Please inspect the issue, thank you with Metta. 🙏 

#### Steps to reproduce:

1. Try downloading any ePub from https://suttacentral.net/downloads, e.g., [Middle Discourses ( Majjhima Nikāya ), Bhikkhu Sujato](https://suttacentral.net/api/ebook/mn_en_sujato.epub).
2. downloaded a JSON error file as shown above, rather than the ePub itself.

**Comment by sujato** [comment]
Unfortunately this is a known bug. We are planning a bigger overhaul of the publications, including EPUBs, so they won't be fixed for a little while. I know, we should fix the page to tell folks that! I will try to get around to it.

**Comment by thesunshade** [comment]
I'm closing this since the download page no longer exists.
