### ISSUE TITLE
references in dictionaries should link to SC

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2358]
Currently references in "complex" dictionaries (PTS dict, DPPN, and Dhammika) use old-style PTS vol/page.

```
<span class='ref'>AN.v.110</span>
```

We should transform these so that they can properly link to the correct page on SC using our segment IDs. These should be hard-coded links in the source files.

```
<a class='ref' href='/an10.60/en/sujato#7.1'>AN.v.110</a>
```

This will be done via our bilara `reference` files. These files contain both the old PTS reference and the required SC ID.

Generally, the PTS reference will be marked `pts-vp-pli` (i.e. Pali Text Society, volume/page, Pali text). 

Note that not all references in the Dictionary files are included in our files. Some point to commentaries or to other extra-canonical texts that we do not have. Such cases should be ignored and remain as static references.

The references in the source texts should be first checked for consistency and massaged into shape if need be. But generally they will have the form:

```
<span class='ref'>MN.i.344</span>
```

- The first item is the *division*, and will be the same as the SC ID. 
- The second item is the *volume number*. This is in Roman numerals, and will have to be transformed to modern numerals to match SC.
- The final item is the page number.

Note that the SC vp numbers in bilara-data/reference are, by themselves, incomplete. They omit the first part of the reference ID, namely the division ID. This is because they refer to the "volume and page" of a printed edition, and each division will have, for example, a "volume 1, page 45" . The correct division is inferred from the file's location.

## preparing the source 

- [ ] Ensure all references use SC standard abbreviations.
- [ ] Fix all malformed references.
- [ ] Where referencing by verse number (eg. `dhp`, `thag`,  `snp`) make sure that the verse numbers match those found in bilara-data/reference. 
- [ ] Make the programmer's job simpler by decorating the reference: 
     - `<a class='ref' data-division='/sutta/an' data-reference='pts-vp-pli5.110' data-url='/en/sujato'>AN.v.110</a>`

***

- SC [will support references to `dhp` by simple verse number (`/dhp34`or `/dhp#34`)](https://github.com/suttacentral/suttacentral/pull/2343) but not for `snp` or other collections. 
- bilara-data/reference may well include alternate verse numbering systems. If this is the case, make sure the correct system is specified.
- `data-division` tells the programmer where to locate the reference
- `data-reference` gives the exact reference as found in bilara-data/reference.
- `data-url` tells the programmer what to add to correctly form an SC URL. It is one of these three:
     - `en/sujato` (for `dn`, `mn`, `sn`, `an`, `kp`, `dhp`, `snp`, `thag`, `thig`, `ud`, `iti`)
     - `en/brahmali` (for `vinaya`)
     - `pli/ms` (for untranslated texts)
- If reference is not found in bilara-data/reference, leave it as a static span. The script will ignore these and they will be just static references.

## how the script should work

- check a reference in a complex dictionary 
    - `<a class='ref' data-division='/sutta/an' data-reference='pts-vp-pli5.110' data-url='/en/sujato'>AN.v.110</a>`
- match the `data-reference` located in the `data-division`:
    - `"an10.60:7.1": "bj23.198, cck24.98, csp1ed17.344, csp2ed17.344, dr24.118, ms17A10_434, ndp19.187, pts-vp-pli5.110"`: 
- get the corresponding bilara segment ID
    - `an10.60:7.1`
- parse that into the URL form
    - `/an10.60/en/sujato#7.1`
- add the segment ID as `href` on reference in dictionary. Delete unneeded extra info.
    - `<a class='ref' href='/an10.60/en/sujato#7.1'>AN.v.110</a>`

***

- [ ] Go over the three complex dictionaries, and ensure all references are correct and consistent.
- [ ] Decorate reference links.
- [ ] Programmatically add SC numbers to `href`.
- [ ] Manually check links for correctness.

**Comment by thesunshade** [comment]
Not sure if this is what is needed, but I took a look at the citations in Ven. Dhammika's dictionary of flora and fauna, https://raw.githubusercontent.com/suttacentral/sc-data/master/dictionaries/complex/en/pli2en_dhammika.json, pulling out everything with a span tag `class='ref'`. A pdf of his book can be found [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjYpZ6R_Kb1AhUsUGwGHXZWDPgQFnoECAQQAQ&url=https%3A%2F%2Focbs.org%2Fwp-content%2Fuploads%2F2015%2F09%2Fjournalsuppneeb.pdf&usg=AOvVaw1ZUgoEpMGXexMgEV44KS5e)

I am calling a standard citation something like `D.i.123`
Everything that I believe to be a typo/inconsistency is bolded.

* D, M, S, A, Ja,  Vin have what appear to be standard citations **(except for `A.168`, `A.v..22`, `M.178`, `M.iv. 420` (extra space), `Ja.137`, `Ja.281`, `Ja.426`, `Ja.437`, `Vin.136`, `Vin.201`, `Vin.201`, `Vin.201`, `Vin.246`, `Vin.246` )**
* Dhp citations are to verse number
* There are citations for both `Mv` and **`Mvu`**. The pdf of his book only lists the abbreviation `Mv`. Except for **one odd citation(`Mvu.473`)** they all appear to be standard citations
* Sn has only one number and they range from `1` to `1604`. I'm guessing those are verse numbers.
* `Ap` has 13 citations, all of them single numbers ranging from `16` to `347` **(except for `Ap.16.193`)**. His book gives this as Apadāna, ed. Mary E. Littey, PTS Oxford 2000
* `Bc` has 6 citations in the form of two arabic numbers. The lowest is `Bc.4.49` and the highest is `Bc.13.65`. Strangely, this citation is not listed in his book.
* `Bv` has 21 citations in the same form as `Bc` with the lowest being `Bv.1.31` and the highest `Bv.34.11`
* There is a single **`Bcv.viii.26`, `Jm.xiv.10-2`, `Nidd.ii.304`, `Pp.29`**. None of these are listed in his book as citations
* There is a single  `Dhp-a.273`
* `It` has 4 citations with just a single arabic number which are likely page numbers. `Ud` is similar with numbers from `1` to `90`
* `Mil` citations have a single arabic number **except for `Mil.ii.372`, Mil.ii.393`, Mil.ii.404`.** Milindapañho, ed. V. Trenckner, PTS London 1880
* `Mv` has six citations in the standard form. There are also **`Mvu.473`, `Mvu.iii.302, `Mvu.iii.311`** which is not a citation listed in his book
* `Vv` and `Pv` are in the form of two arabic numbers, e.g `Pv.35.5`. There are a few `Vv-a` citations and they all have a single arabic number.
* `Th` has single numbers from `1` to `1232`. `Tha` has the same with a range of `49` to `1135`
* `Vism` has a single arabic number

**Comment by sujato** [comment]
Okay, that's actually super-helpful. We can use that to debug and standardize the references.

**Comment by thesunshade** [comment]
Does the original source file for what became the PED on SC exist somewhere online? It might be helpful to figure out the odd citations. I'm assuming since I'm trying to clean things up it would be good to clean up non-SC texts as well even though they won't be linked up.

**Comment by sujato** [comment]
There are online versions, but if correcting things, i'd recommend going back to the print edition (or scanned).

**Comment by thesunshade** [comment]
Some questions:

1. When there are ranges in the citations, like `M.i.123-8`
     * I assume we will leave that in for the front facing text. But are we ignoring the range when it comes to generating the link?
     * On the front facing text, should it be an en dash or a hyphen?

2. (Apologies if you have already told me the answer) When the pts page number points to the wrong sutta, are we just waiting to handle those until the final checking phase? For example in Ven Dhammika's dictionary, "kapota" has the citation `Ud.39`. The pts reference appears in [Ud4.3](https://suttacentral.net/ud4.3/en/sujato?layout=linebyline&reference=main/pts&notes=asterisk&highlight=false&script=latin#pts-vp-pli39). But the actual sutta it is mentioning is [Ud4.4](https://suttacentral.net/ud4.4/en/sujato?layout=linebyline&reference=main/pts&notes=asterisk&highlight=false&script=latin#1.3). I only came across this when trying to verify the nature of his citations.

3. The two versions of Ven. Dhammika's dictionary I have found online do not match what we have on SC. For example the entry for "satapadi" in the SC version has an extra line at the end that says
```
The commentary to the Vinaya mentions monks” robes being the color of a centipede’s back <span class='ref'>Vv-a.1083</span>.</p></dd></dl>
```
This is obviously not the Vimanavatthu commentary. I came across another sentence that was in SC but not the PDFs I have. (Budblooms Edition by Ven. S. Dhammika © 2020, BPS 2015, and a third by Buddha Dhamma Mandala Society). I can appreciate if we no longer have the file used to create the SC version and/or if you don't think having it would be helpful.

**Comment by sujato** [comment]
> are we ignoring the range when it comes to generating the link?

Yes. The link can anyway only point to the start of the passage, so there's little point in trying to encompass the whole range. So that will have to be part of the processing.

>On the front facing text, should it be an en dash or a hyphen?

Be still my 💓 ! En-dash of course! For ranges, UIDs use hyphen, acronyms use en-dash. These should have been enforced when editing the text for SC, but sometimes they slip through.

>When the pts page number points to the wrong sutta, are we just waiting to handle those until the final checking phase?

If you notice mistakes along the way, just fix them. 

>The two versions of Ven. Dhammika's dictionary I have found online do not match what we have on SC

Yes, he has continued editing the text, and there are different editions out there. I can ask him for the latest edition if you like. But that would mean a fair amount of additional effort in re-creating the HTML from his Word file. Still, it may be worth it.

**Comment by thesunshade** [comment]
> > When the pts page number points to the wrong sutta, are we just waiting to handle those until the final checking phase?
> 
> If you notice mistakes along the way, just fix them.

Sorry. What I meant was that the citation is correct as far as the PTS pages go, but because the suttas are small, it ends up pointing you to the sutta prior to the one intended. So there is no way to correct it because it's already correct. I'd have to just hard code in what the final url should be, which I guess I could do. Is that what you meant? Because in the end, the urls will be to SC segment ids, eh? 

> But that would mean a fair amount of additional effort in re-creating the HTML from his Word file. Still, it may be worth it.

That would mean starting over, wouldn't it? I just thought that a more updated version might help with troubleshooting problems that I found. But I can also try to hunt them down in traditional ways.

**_New question:_** Would it make more sense for the (currently) untranslated suttas to have the link point to the SuttaPlex card? That way if there is a translation in the future the user could decide that they wanted to go there. Otherwise people mostly are being sent to translations and then suddenly they end up on a root text. They then will have to check the "Paralells" icon (which in this case is not the best name, but I know, naming icons is hard) and then find if there is a translation.

**Comment by thesunshade** [comment]
I think this is done, no? I'm going to close for now.
