### ISSUE TITLE
Add date to Bilara translations in suttaplex

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2362]
The suttaplex gives the date, where available, for legacy translations. But for Bilara translations we have not added the date. That's just an oversight, it was never planned that way.

Let's add the date!

The date of Bilara translations is found in `publications.json` and is used in the text metadata.

![Screenshot from 2022-01-17 06-37-46](https://user-images.githubusercontent.com/6112010/149675200-47755d39-d930-470c-81d2-2b6580aa7663.png)

**Comment by thesunshade** [comment]
> The date of Bilara translations is found in `publications.json` and is used in the text metadata.

For the life of me I can't find this file in any repository.

I think this is a really important thing to fix, since age of translation is one way people can decide on the quality of a translation.

**Comment by ihongda** [comment]
This issue has been fixed.

![image](https://github.com/suttacentral/suttacentral/assets/4037966/4477bdd2-37a5-4336-a839-98022e44b075)
