### ISSUE TITLE
Standalone HTML—let’s make a demo for fun!

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2365]
We will make publications available in standalone HTML. This has two main uses.

- It can be handy to just view it in the browser, or import into Word, etc.
- It will be a basis for creating EPUB and LaTeX files.

Let's walk through the process of creating a simple standalone HTML file. This will help us learn what is involved on a practical level, and give an idea what we are aiming for.

Outcomes!

- learn bilara i/o
- get familiar with how our content works
- get an idea of how references work
- work with heading levels
- make a ToC
- get an idea what kind of matter to add.

## make the content

Bilara i/o is a utility for processing bilara data. Essentially it takes the data from all the sources for a given text and outputs them as TSV. (Other outputs are possible.) See the bilara-data README for details.

- set up bilara i/o
- `./sheet_export.py dn dn.tsv`
- open as spreadsheet
- delete all columns except for English, HTML, references, and segment IDs.
- copy reference column into text editor
- delete all references except bj and pts-vp-pli (these are some well known editions)
- make references of the form `<a class='bj' id='bj7.2'>BJ 7.2</a>` (now we can display edition references if we want.)
- paste back into spreadsheet
- copy segment ID column into text editor
- `<a id='dn1:0.1'></a>` (we don't want to display these, just use them as targets)
- paste back into spreadsheet
- copy entire spreadsheet into text editor
- regex: `(.*?)\t(.*?)\t(.*?){}(.*?)\t(.*)` --> `\3\1\5\2\4`
- save as `dn.html`
- `tidy --doctype html5 --output-html 1 --tidy-mark 0 --quiet 1 --output-encoding utf8 -w 0 --show-warnings 0 -m  dn.html`

## make sane references

We now have a standalone HTML file with the English translation. Segments are retained. We don't want to display all of them, it's too much. Just display the first segment number of a paragraph.

- `<p(.*?)<a id='dn(.*?)'></a>` --> `<p\1<a class='sc-main' id='dn\2'>DN \2</a>`

Okay, so now we can display the following references if we wish. 

- PTS
- BJ
- SC main

But we have a problem. In some cases, there are references, but no text. (This is because the translation sometimes elides repeated text, so there is a root with references, but no translation.)

- delete all paragraphs that have only references but no text.

## organize heading levels

I'll go into this in more detail later, but for now:

- get rid of the `<header>` element and the `<ul>` inside it. Just keep the h1.
- increment all heading levels (h1 becomes h2, h2 becomes h3, etc.
- add the following (outside the `<article>` tags
    - before dn1: `<h1>The Entire Spectrum of Ethics</h1>`
    - before dn14: `<h1>The Great Chapter</h1>`
    - before dn24: `<h1>About Pāṭikaputta</h1>`
- add `class='subheading'` to all heading h3 and below.
- add `class='heading'` to all h1 and h2.
- add the sutta ID number to headings: `<h2 class='sutta-title heading'><a id='dn(\d+):(.*?)'></a>` --> `<h2 class='sutta-title heading'><a id='dn\1:\2'></a><span class='sutta-title-id'>DN \1</span> `

Good enough!

## add the front and back matter

So far we have the main matter, i.e. the list of suttas. Let's add the rest of the stuff that will make it a proper book, i.e. the front and back matter.

So what do we have? Bilara i/o doesn't work with front and back matter, not yet anyway, so we'll just gather it by hand for now. It's just a demo!

### frontmatter

Add all the following as individual sections within `<section id='frontmatter'>`
- there's an essay on DN, we can get it from here, clean it up a bit: https://suttacentral.net/dn-guide-sujato?lang=en
- add a title page. Note, we can use pretty much exactly what is used to generate the EPUB cover image here.
- add a license section
- add a forward (just make it up!)
- add the blurbs. these are in `sc-data/sc_bilara_data/root/en/blurb/dn-blurbs_root-en.json`. Process them into a list.

### backmatter

Add all the following as individual sections within `<section id='backmatter'>`

- author bio
- about SuttaCentral

Okay, that's enough, we've got a good idea what it involves.

Wrap the whole document up:

```
<main>
    <section id='frontmatter'>…</section>
    <section id='mainmatter'>…</section>
    <section id='backmatter'>…</section>
</main>
```

## make reference links work

We also have reference links. Let's make them work!

- `href="/dn` ---> `href="#dn`
- `href="/` ---> `href="https://suttacentral.net/`

Now all the internal links will work in the file, the external links will point to SC. Good enough!

## make a Table of Contents

Let's make a simple HTML contents. Loop over the headings with js and build a toc as a list in a nav element. See the included js, this is pretty neat! One thing, it only works with plain `<hX>` tags, anything with classes or whatever is ignored.

For publishing, generate the ToC first and publish as static file.

## make it pretty

Add some CSS and fonts. Even use a horrifying hack to create a theme-switcher. Yikes, don't do this in production! 😱

There's a little bit of markdown in these files, let's make it HTML.

- `\*(.*?)\*` ---> `<em>\1</em>`

## here it is

Not too bad!

[dn.zip](https://github.com/suttacentral/suttacentral/files/7900805/dn.zip)

This gives us a good idea what we will be doing, and what we'll end up with. DN is one of the simpler texts. We'll have to learn to abstract and automate these processes for a range of texts, each of which has its own idiosyncrasies.

**Comment by blake-sc** [comment]
Here is an example of some TSV files as spat out be `./sheet_export.py --include sujato,html,reference --exclude comment mn50 mn50.tsv`

[example-tsv.zip](https://github.com/suttacentral/suttacentral/files/8031303/example-tsv.zip)

sn1.19.tsv is a very short single text, sn1.1.tsv is a "subdivision" of many texts, mn50.tsv is a longer single text. Of course the full books are going to be about 50x longer.
