### ISSUE TITLE
Info not present on root texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2378]
Root texts are lacking the required metadata that is displayed as "Info" in the toolbar.

![Screenshot from 2022-01-23 17-10-57](https://user-images.githubusercontent.com/6112010/150667029-7256a498-04d1-46b8-a0ee-28bc6263c864.png)

This applies to those root texts that are also segmented in Bilara.

The metadata Info is extracted from `_publication.json` but there are no root texts there, only translations.

I have created an entry for the mahasangiti root text in `_publication.json`. It is scpub64.

https://github.com/suttacentral/bilara-data/blob/published/_publication.json

Not all the fields are exactly suitable. It has "translation description", etc. Still, I did it the best I could. maybe?

- alter the field names so they apply to root as well?
- make a separate file for root texts?

Anyway, the Info field does not automagically appear. Let's make it work!

One thing to bear in mind, the Info applies to the entire Tipitaka, not just to a single volume.

**Comment by ihongda** [comment]
There is currently no need to modify _publication.json, I have modified a small amount of front-end code to adapt to the changes.
