### ISSUE TITLE
social media preview appears broken

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2379]
![Screenshot from 2022-01-23 17-15-02](https://user-images.githubusercontent.com/6112010/150667099-a1c94557-cdfe-4d55-b62b-0b8b143b0c6a.png)

**Comment by ihongda** [comment]
Facebook and Twitter looks normal, maybe discouse.suttacentral.net has been updated recently?

**Comment by thesunshade** [comment]
This is a duplicate of the larger https://github.com/suttacentral/suttacentral/issues/1486
