### ISSUE TITLE
Fragment URLs involving `/subjects` display erratic behavior.

### ISSUE THREAD

**Issue by mikez** [suttacentral/suttacentral#2380]
#### Description:
Fragment URLs involving [/subjects](https://suttacentral.net/subjects) display erratic behavior. 

#### Steps to reproduce:
* Visit https://suttacentral.net/subjects
* Click on any `See Recollections, ten` link.

or

* Visit https://suttacentral.net/subjects?lang=en#recollections

or

* Visit https://suttacentral.net/subjects#recollections

#### Expected behaviour:

* Jump to #recollections.

#### Observed behaviour:

* Sometimes jumps to top of page. Console error: `TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector')`
* Sometimes does nothing.
* Sometimes removes fragment.
* Sometimes jumps to correct section.

**Comment by mikez** [comment]
Possibly related to #2372.

**Comment by sujato** [comment]
Thanks, we'll fix this, calling @ihongda
