### ISSUE TITLE
EBook Data API

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#2400]
We want to make available the data required for generating ebooks via a data API, that leverages ArangoDB.

This will be a public facing data API.

We will need multiple API endpoints, something like:

1. Get a list of publications
2. Get the details of a publication
3. Get the editions for a publication (perhaps combined with above)
4. Get the data for a publication/edition

**Comment by alple** [comment]
Pulling together knowledge of the publishing script and configuration/publication files that are available I'll propose an API response that should give us flexibility in creating publications artifacts.

# Considerations
When thinking about publishing I'm seeing 3 cases:
1. Publishing only one concrete edition
2. Publishing publication in all its defined formats
3. Refreshing all available publications

Is it safe to assume that we would like to have all three options available? If yes then the API should ingest and recognize if it's an edition or publication id - the publication script will have no way of knowing if it's one or the other unless we hardcode some conditions for it, but it seems less flexible.
If we want to have an option of refreshing all the publications, from the server we would need another endpoint returning just a list of available publications.

# Response
Example API response:
```
GET "http://localhost/api/ebook_data?uid=pub_or_edition_id"

[
  {
    "config": {
      // All the data or only important parts from _publication-v2.json
      // ...
      "text_uid": "thag",
      "translation_title": "Verses of the Senior Monks",
      "translation_subtitle": "An approachable translation of the Theragāthā",
      "root_title": "Theragāthā",
      // All the data or only important parts from given edition.json
      // ...
      "volumes": [
        {
          "frontmatter": [
            "titlepage",  // if we could treat that as key/uid, then we can find that in a given `volumes` data key
            "copyright",
            "toc",
            "/matter/foreword.html",
            "/matter/introduction.html",
            "/matter/acknowledgements.html"
          ],
          "mainmatter": [
            "mn"
          ],
          "endmatter": [
            "index",
            "notes",
            "author_bio"
          ]
        }
      ]
    },
    "data": {
      "volumes": [
        {
          "titlepage": {
            "type": "blurb",  // The processor used to transform the data before sewing it into the publication/book
            "content": {...}  // The data of a given sub-matter
          },
          "copyright": {
            "type": "html",
            "content": [...] // The data type [array|list] send here should be always the same and tied with the type - like `blurb` should always get for example array
          }
          // ...
        }
      ]
    }
  },
  {
    "config": {...},
    "data": {...}
  }
  // ...
]

```
That way we have data gathering on the bilara server-side - editors can get all the configuration and preparation done there - and publishing script will be 'dummy' and take care only of piecing and formatting it all together based on data and the type of data it receives.

If we send a request for a single edition id we will receive a list of one `config` and `data` for that given edition. If we send a request for publication id we will receive a list of editions.

**Comment by sujato** [comment]
> When thinking about publishing I'm seeing 3 cases:
> 
>     1. Publishing only one concrete edition
> 
>     2. Publishing publication in all its defined formats
> 
>     3. Refreshing all available publications
> 
> 
> Is it safe to assume that we would like to have all three options available? 

It's really only 2 & 3. Once a given translation is deemed ready for "publication", it would be made available in multiple formats AKA editions.

**Comment by blake-sc** [comment]
I think for now I'll focus the API on returning the data for a single edition. Let's not worry about sending the same data repeatedly, the queries are pretty fast (less than a second for a full nikaya, often much less if ArangoDB has freshly accessed those regions) and the internet isn't running out of bits yet.

That means the API endpoint will simply return the data for a single edition. Call it multiple times to get the data for all editions. Other endpoints will return a list of publications, a list of editions in a publication.

**Comment by alple** [comment]
ok. Given that we will have publication id, what endpoints should we call to get editions details and data for them?

**Comment by blake-sc** [comment]
Working on it.

One big question: at the moment I have an API endpoint that returns the edition config, like:
<details>
<summary>Click to expand</summary>

```
{
    "edition": {
      "_key": "mn-en-sujato_scpub3-ed2-paperback_2021-04-24.json",
      "_id": "publication_editions/mn-en-sujato_scpub3-ed2-paperback_2021-04-24.json",
      "_rev": "_dt6c4W2---",
      "publication_number": "scpub3",
      "text_uid": "mn",
      "edition_number": "2",
      "isbn": "abcdefg",
      "cip": "wxyz",
      "publication_type": "paperback",
      "format": "tex",
      "creator": "lualatex",
      "output": "pdf",
      "page_size": "6in, 9in",
      "cover_image": "./matter/img/paperback_cover.jpg",
      "main_toc_depth": "all",
      "secondary_toc": false,
      "number_of_volumes": 3,
      "sources": {
        "main_text": "translation-en-sujato",
        "notes": "comment-en-sujato",
        "reference": "reference",
        "markup": "html"
      },
      "volumes": [
        {
          "frontmatter": [
            "titlepage",
            "copyright",
            "toc",
            "./matter/foreword.html",
            "./matter/introduction.html",
            "./matter/acknowledgements.html"
          ],
          "mainmatter": [
            "mn-mulapannasa"
          ],
          "endmatter": [
            "index",
            "notes",
            "creator_bio"
          ]
        },
        {
          "frontmatter": [
            "titlepage",
            "copyright",
            "toc"
          ],
          "mainmatter": [
            "mn-majjhimapannasa"
          ],
          "endmatter": [
            "index",
            "notes",
            "creator_bio"
          ]
        },
        {
          "frontmatter": [
            "titlepage",
            "copyright",
            "toc"
          ],
          "mainmatter": [
            "mn-uparipannasa"
          ],
          "endmatter": [
            "index",
            "notes",
            "creator_bio"
          ]
        }
      ],
      "working_dir": "/opt/sc/sc-flask/sc-data/sc_bilara_data/_publication/en/sujato/editions",
      "edition_id": "mn-en-sujato_scpub3-ed2-paperback_2021-04-24"
    },
    "publication": {
      "creation_process": "Primary source was the digital Mahāsaṅgīti edition of the Pali Tipiṭaka. Translated from the Pali, with reference to several English translations, especially those of Bhikkhu Bodhi.",
      "creator_github_handle": "sujato",
      "creator_name": "Bhikkhu Sujato",
      "creator_uid": "sujato",
      "editions_url": "",
      "first_published": "2018",
      "is_published": true,
      "license_abbreviation": "CC0",
      "license_statement": "This translation is an expression of an ancient spiritual text that has been passed down by the Buddhist tradition for the benefit of all sentient beings. It is dedicated to the public domain via Creative Commons Zero (CC0). You are encouraged to copy, reproduce, adapt, alter, or otherwise make use of this translation. The translator respectfully requests that any use be in accordance with the values and principles of the Buddhist community.",
      "license_type": "Creative Commons Zero",
      "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "publication_number": "scpub3",
      "publication_status": "Completed, revision is ongoing.",
      "root_lang_iso": "pli",
      "root_lang_name": "Pali",
      "root_title": "Majjhimanikāya",
      "source_url": "https://github.com/suttacentral/bilara-data/tree/master/translation/en/sujato/sutta/mn",
      "text_description": "This translation was part of a project to translate the four Pali Nikāyas with the following aims: plain, approachable English; consistent terminology; accurate rendition of the Pali; free of copyright. It was made during 2016–2018 while Bhikkhu Sujato was staying in Qimei, Taiwan.",
      "text_uid": "mn",
      "translation_lang_iso": "en",
      "translation_lang_name": "English",
      "translation_subtitle": "A lucid translation of the Majjhima Nikāya",
      "translation_title": "Middle Discourses"
    }
  }
```
</details>

Then there is a very important question: is it better to "populate" this with the data making a giant JSON blob, or is it better to make a smaller separate API endpoints. The reason to make a separate API endpoints would be to make them more precisely defined and focused. It's a bit hard when it's easiest to say "this endpoint does everything and returns a giant blob of complex JSON".
