### ISSUE TITLE
Serve range suttaplexes per-sutta

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2409]
This complements the recent addition of serving range suttas per sutta.

https://github.com/suttacentral/suttacentral/issues/2296

This applies to the text, but what about the suttaplex?

There are places where it makes sense to kink to a suttaplex rather than a text. For example, in our static pages, references point to the bare suttaplex URL (/dhp123) rather than the text (/dhp123/en/sujato). This is because the static pages are translatable, and updating all references for all languages is difficult.

Let us add the same functionality for suttaplexes as we do for texts. This applies to all the texts affected by issue #2296. 

Since Suttaplexes are complicated, let's try to keep this change to the minimum. The main purpose of these is to make it easier to get to one text in different languages. So let's focus on that.

- Currently, the range-suttaplex is found on each individual sutta. Eg. https://suttacentral.net/dhp1/en/sujato, the suttaplex in the toolbar is for dhp1-20. **DON’T CHANGE**
- The individual suttaplex does not need to have parallels or even the nerdy row.
- Just have the title and the list of translations and texts.

Something like this!

>## Dhammapada 1
>**5 translations** in your chosen language
>- Bhikkhu Sujato *English & Pāli*
>- Bhante Suddhāso *English & Pāli*
>- Bhikkhu Ānandajoti *English 2017*
>- Ācāriya Buddharakkhita *English 1985*
>- Peter Feldmeier *English 2013*
>
>**1 edition** of the root text
>- Mahāsaṅgīti Tipiṭaka Buddhavasse 2500 Pāli
>
>**24 translations** in other modern languages

**Comment by ihongda** [comment]
> https://staging.suttacentral.net/an1.75?view=normal
> https://staging.suttacentral.net/ud4.3?view=normal
> https://staging.suttacentral.netsnp2.2?view=normal
> https://staging.suttacentral.net/an5.1?view=normal
> 
> They work correctly on production, so it must be a new bug.
> 
> 

It looks normal, it should be caused by the difference between the dev configuration and the production configuration of nginx
