### ISSUE TITLE
Realace `url-parse` with URL API?

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2413]
The README for `url-parse` recommends using the URL API instead:

>url-parse was created in 2014 when the WHATWG URL API was not available in Node.js and the URL interface was supported only in some browsers. Today this is no longer true. The URL interface is available in all supported Node.js release lines and basically all browsers. Consider using it for better security and accuracy.

The URL API and URLSearchParams are now in 95% of browsers:

https://caniuse.com/?search=url

Shall we replace it? Fewer dependencies is always good!

**Comment by ihongda** [comment]
I noticed URLSearchParams while working on PR2399, it looks perfect and should be a replacement for url-parse.
