### ISSUE TITLE
error when executing "make run-production-env" due to missing make target "rebuild-all"

### ISSUE THREAD

**Issue by falko-strenzke** [suttacentral/suttacentral#2422]
#### Description:

building as described at https://github.com/suttacentral/suttacentral under "Deploying" leads to an error.

The make target `rebuild-all` seems to be missing from `Makefile`

#### Steps to reproduce:

I just now checked out the code `commit 5eef2040f64b275d10c7f7e88104d65288e0804b`  and followed the manual under "Deploying", namely
```
$ git clone git@github.com:suttacentral/suttacentral.git
$ cd suttacentral
$ git checkout production
$ make prepare-host
$ make run-production-env
```
 and received from the last command
```
make[1]: Leaving directory '/home/falko/lib/suttacentral'
make[1]: Entering directory '/home/falko/lib/suttacentral'
make[1]: *** No rule to make target 'rebuild-all'.  Stop.
make[1]: Leaving directory '/home/falko/lib/suttacentral'
make: *** [Makefile:124: run-production-env] Error 2
```

#### Expected behaviour:
The build process should run through without an error.

**Comment by sujato** [comment]
Are you able to execute `make run-dev`?

**Comment by falko-strenzke** [comment]
Thank you for the quick reply, Bhante. 

When I run that I get:
```
┌─(~/lib/suttacentral)────────────────────────────────────(falko@fsl13:pts/2)─┐
└─(10:15:06 on production)──> make run-dev                  2 ↵ ──(Sat,Mar26)─┘
ERROR: Network nginx-proxy declared as external, but could not be found. Please create the network manually using `docker network create nginx-proxy` and try again.
make: *** [Makefile:27: run-dev] Error 1
```

**Comment by sujato** [comment]
I'm no expert, I just follow the instructions, but I think you need to go back to the "development" page on the wiki, and ignore "deployment". Go from the beginning, see if that works. If not, we'll have to invoke the powers of blake.
