### ISSUE TITLE
duplicate de blurbs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2441]
I thought we had fixed this, but apparently not.

```
   17: Load blurbs from sc_bilara_data
Duplicate key value：pli-tv-bu-vb-as1_de
Duplicate key value：pli-tv-bu-vb-as2_de
Duplicate key value：pli-tv-bu-vb-as3_de
Duplicate key value：pli-tv-bu-vb-as4_de
Duplicate key value：pli-tv-bu-vb-as5_de
Duplicate key value：pli-tv-bu-vb-as6_de
Duplicate key value：pli-tv-bu-vb-as7_de
Duplicate key value：pli-tv-bu-vb-as_de
Duplicate key value：pli-tv-bu-vb-ay1_de
Duplicate key value：pli-tv-bu-vb-ay2_de
Duplicate key value：pli-tv-bu-vb-ay_de
Duplicate key value：snp-atthakavagga_de
Duplicate key value：snp-culavagga_de
Duplicate key value：snp-mahavagga_de
Duplicate key value：snp-parayanavagga_de
Duplicate key value：snp-uragavagga_de
Duplicate key value：pli-tv-bu-vb-sk69_de
Duplicate key value：pli-tv-bu-vb-sk_de
9140 blurbs added or updated
```

**Comment by thesunshade** [comment]
@sabbamitta do you know if this was ever resolved? I realize the error is happening on the code side of things, but perhaps you are aware.

**Comment by sabbamitta** [comment]
I actually don't know what this is about. Where does this error appear? What do I need to do or where do I need to look in order to see it?

**Comment by thesunshade** [comment]
I'm not sure exactly. I think it may happen in the build process when the data in `bilara-data` is imported into `sc-data`. I just thought you might have been aware of any fix.

No problem. I think you can ignore.

**Comment by sabbamitta** [comment]
I am not even aware of the problem, sorry. But it seems to affect specifically some German things, which does of course make me curious to learn what it is about.

**Comment by thesunshade** [comment]
So, I'm guessing that when the files are being built to be used on the actual website, some how something is being combined so that there are duplicate keys for segments. As you know, the segments are made up of keys (e.g. `pli-tv-bu-vb-as1_de`) and then the values (i.e. the translations). In a single json file (and I guess in the whole site) there can't be more than one occurrence of a key, because then the software would not know which one to use. 

So if you wanted to research it, You would want to search in all your blurb files to see if you can find the above keys more than once. From there we would need to figure out which one is the correct one and I believe delete the other.

I went back and looked at the log from when I created a local version of the site last week and found a similar error:
```
   22: Load blurbs from sc_bilara_data
Duplicate key value：pli-tv-bu-vb-sk69_de
Duplicate key value：pli-tv-bu-vb-sk_de
Duplicate key value：pli-tv-bu-vb-as1_de
Duplicate key value：pli-tv-bu-vb-as2_de
Duplicate key value：pli-tv-bu-vb-as3_de
Duplicate key value：pli-tv-bu-vb-as4_de
Duplicate key value：pli-tv-bu-vb-as5_de
Duplicate key value：pli-tv-bu-vb-as6_de
Duplicate key value：pli-tv-bu-vb-as7_de
Duplicate key value：pli-tv-bu-vb-as_de
Duplicate key value：pli-tv-bu-vb-ay1_de
Duplicate key value：pli-tv-bu-vb-ay2_de
Duplicate key value：pli-tv-bu-vb-ay_de
Duplicate key value：snp-atthakavagga_de
Duplicate key value：snp-culavagga_de
Duplicate key value：snp-mahavagga_de
Duplicate key value：snp-parayanavagga_de
Duplicate key value：snp-uragavagga_de
12737 blurbs added or updated
```

**Comment by sabbamitta** [comment]
Thanks, I will look into it.

**Comment by thesunshade** [comment]
@sabbamitta I think I may have figured this out. Do you have any idea what theses circled files are?
<img width="913" alt="2024-03-03 17_48_59-C__GitHub_bilara-data_translation_de_blurb_pli-tv-bu-pm-blurbs_translation-de-bl" src="https://github.com/suttacentral/suttacentral/assets/82448383/2afe704b-a24c-47ee-87c9-ae50cd0a6766">

I doubt it you can see them through Bilara. 

They are here on github: https://github.com/suttacentral/bilara-data/tree/published/translation/de/blurb

**Comment by sabbamitta** [comment]
Aaahhh! Thank you for finding this!

No, I can only see those files in Bilara that don't have `-blurb` after `de` in their name. It seems the ones you found are just remnants of the older form in which they were coded. The blurb files used to be all this way in the early days of Bilara!

I think when I make changes in Bilara this will only ever affect the newer files.

![Screenshot from 2024-03-03 08-14-07](https://github.com/suttacentral/suttacentral/assets/43345786/ed88752a-87aa-4a30-a804-477ee6f182d8)

You can see that the file without the `-blurb` ending had its last edit 2 days ago, whereas the one with the `-blurb` ending was last edited 2 years ago. Although I am pretty sure I didn't change this particular blurb file two days ago, all files of the folder are nevertheless included in my publish pull request, as I do bulk publishing to save Carmi some work. So the Nilakkhana script just goes over them all and makes its automatic changes, which is probably what has happened 2 days ago.

I believe that all files with the older format that have `-blurb` after `de` in their name can be deleted. They are ghosts. :ghost:

**Comment by thesunshade** [comment]
Excellent! @ihongda can you confirm this is what's going on and maybe delete the unneeded files?

**Comment by sabbamitta** [comment]
I am not sure when this switch in file naming has happened, it's even possible that it was still before @ihongda joined the team.

**Comment by ihongda** [comment]
It looks like they only exist in the published branch, I have deleted them, thank you @thesunshade @sabbamitta 🙏🏼

**Comment by thesunshade** [comment]
Great! I did a `make load-data` on my local build and I no longer see this problem. 

But now there is a new error. Since it looks different I will close this and reference https://github.com/suttacentral/suttacentral/issues/3064
