### ISSUE TITLE
Web: editions page

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2444]
Add a page with URL `/editions`.

This contains a list of all projects for which we have publication editions.

- each edition lives in a card, pretty similar to the nav cards
- content of card has class names that are the same as publication.json.
- the `publication_blurb` comes from the editions config
- also have a "download all" area. Currently this just has static links to Github.
- Include a picture of the books.
- link on the header area like the nav cards

Attached is mockup with primitive styling. Import styles from nav cards or something, I'll take care of CSS details.

[editions.zip](https://github.com/suttacentral/suttacentral/files/8548722/editions.zip)

**Comment by thesunshade** [comment]
I think this was finished long ago. I'll close for now.
