### ISSUE TITLE
normalize trailing spaces as soon as possible

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2454]
The rule is:

- always have a space at the end of a segment
- EXCEPT if a segment ends in em-dash (—)

I have encountered a case where the spacing is correct on the website, but incorrect in the standalone HTML for publications. I could just fix it in the data, but i want to ensure that this problem does not occur in the future.

See mn6:16.2 in bilara-data:

https://github.com/suttacentral/bilara-data/blob/published/translation/en/sujato/sutta/mn/mn6_translation-en-sujato.json

It ends without a space: `greed”,",`

When the file is processed and sent to sc-data, it still lacks a trailing space: 
`greed”,",`

https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/en/sujato/sutta/mn/mn6_translation-en-sujato.json

When on the website, it does have a space: `greed”, </span>`

https://suttacentral.net/mn6/en/sujato?layout=plain&reference=none&notes=none&highlight=false&script=latin

So there must be some processing that normalizes the spaces in between sc-data and the website.

However, in the standalone HTML produced for the publications project there is no space: `greed”,and`

I know we implemented this at some point, but I forgot the details. 

What should happen is that the text spacing is normalized as *soon as possible*. Ideally, in the browser when the user submits a string on Bilara. If not, then in unpublished. At the very latest, when promoting from unpublished to published.

The texts in bilara-data/published should be publishable, which means they definitely should not have this kind of issue.

But it seems the normalization is happening much later, between sc-data and the front end, which naturally results in this kind of issue.

- **Identify where the trailing spaces are normalized, and shift that as early as possible in the text processing chain**

**Comment by ihongda** [comment]
>I know we implemented this at some point, but I forgot the details.

After inspection, when segmented text is loaded in sc-text-bilara.js (segmented text page), spaces will be added according to the rules:

- always have a space at the end of a segment
- EXCEPT if a segment ends in em-dash (—)
