### ISSUE TITLE
back button broken

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2455]
Back button on SC doesn't always work. See:

https://discourse.suttacentral.net/t/suttacentral-2021-bug-reports-here/19609/189

I cannot reproduce this bug, so maybe it is on iOS?

However I do encounter the following:

- [X] Back button in nav cards does work
- [x] From suttaplex list back to nav cards does not work 
       (/pitaka/sutta/long/dn --> /dn-silakkhandhavagga)
- [X] From text back to suttaplex list does work

**Comment by thesunshade** [comment]
I have also had back button problems. When it happens again, I will see if I can get it to reproduce. I use FF on desktop.
