### ISSUE TITLE
Segment links take you to the wrong segment in suttas with ranges such as AN2.11-20, etc.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2459]
#### Description:
I believe that clicking on a SC id in a sutta should put the id as an anchor in the url so it can be shared.

#### Steps to reproduce:
1. Go to https://suttacentral.net/an2.21-31/en/sujato?layout=plain&reference=none&notes=none&highlight=true&script=latin
2. Find sutta 21
3. Click on the first id in sutta 22
![image](https://user-images.githubusercontent.com/82448383/170805069-10169118-ea20-4b5c-b760-8e6f31d3157f.png)

#### Expected behaviour:
The anchor for that segment should be added to the url and that id should turn brown. Instead, the first occurance of similar id is added to url. In this case the url becomes
`https://suttacentral.net/an2.21-31/en/sujato?layout=plain&reference=none&notes=none&highlight=true&script=latin#1.1`
![image](https://user-images.githubusercontent.com/82448383/170805159-37583f4c-b678-4670-9ea7-30df36690d1a.png)

**Comment by thesunshade** [comment]
This is still broken.

**Comment by ihongda** [comment]
This is indeed a problem. e.g. `1.1` this anchor exists in many suttas.

**Comment by firepick1** [comment]
There are possible solutions:
1) renumber the ranged suttas, or
2) change the segment link hash ids to the full JSON key (e.g., "#an2.20:1.2"
3) let grass grow over it and just allow people to read the sutta to find a quoted segment

**Comment by sabbamitta** [comment]
Thank you for addressing this! I'd give my vote for option #2.
