### ISSUE TITLE
site pages update: bad links in the indexes

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2482]
Fix errors and update the site pages in Bilara.

https://discourse.suttacentral.net/t/keep-making-us-happy-tell-us-about-mistakes-and-typos/24120/60

**Comment by thesunshade** [comment]
@sabbamitta Do you know if this was ever resolved?

**Comment by sabbamitta** [comment]
Oh no this has never been resolved, and I am not sure if there are thoughts to ever resolve it. There are so many errors in these indexes that a really BIG revision would be required, and I understood that this is not intended. The idea is rather that new indexes should be built from scratch at some point—not sure whether still in my lifetime, still in the lifetime of this solar system, or at what point … (given the available resources …)

**Comment by thesunshade** [comment]
Oh, sorry, I missed the heading "Index of Names" at the top. 🤦‍♂️

I totally understand/appreciate/respect the notion of just waiting to add a new index. but I think I may go through and update these since I believe it is very straightforward. But it wouldn't be in service of the goal of eventually translating the indexes. That may never be reached with the current docs.

**Comment by sabbamitta** [comment]
Thank you for this! I have already done quite some work in preparation, testing many many links and collecting all the errors. In one of the indexes that I had already started translating without being aware of the problem I have even inserted working links in the German version (but I need to find out which one exactly that was, it's already a while back).

So I'll go find my lists of link errors and post them here for you.

(But probably not now; tomorrow or in the coming days.)

**Comment by sabbamitta** [comment]
My collection of wrong links is found here: https://discourse.suttacentral.net/t/discussion-for-bilara-users/23803/119?u=sabbamitta

It seems I have fixed them in the German version already :muscle: :smiley: I've obviously done the index of similes with fixes and translated the index of names without fixes (when I did this I wasn't aware yet of the wrong link problem and didn't test the links; they are however a multitude of the number of links in the simile index).

Related issue: https://github.com/suttacentral/suttacentral/issues/2656

**Comment by thesunshade** [comment]
I have updated all of these. They won't appear on the site for a few days, but I will close this for now.

Feel free to reopen if more bad links are discovered.
