### ISSUE TITLE
errors in some Vinaya range texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2483]
Go here:

https://suttacentral.net/pli-tv-bi-vb-pd?view=normal

First of all, you'll see that the formatting for the acronym in the suttaplex is buggy, the second one is:

>Pli Tv Bi Vb –pd2–8

It should be:

>Bi Pd 2–8

Now if we open the text page:

https://suttacentral.net/pli-tv-bi-vb-pd2-8/en/brahmali?layout=plain&reference=none&notes=none&highlight=true&script=latin

At the bottom the PREV button works, but the NEXT leads to Pli Tv Bi Vb Pd 2, which doesn't exist. (The remaining rules in this set only exist as parallels.) It should go to here:

https://suttacentral.net/pli-tv-bi-vb-sk1-75/en/brahmali

Now, the suttaplex for this has the same problem with the acronym:

>Pli Tv Bi Vb –sk1–75

should be

>Bi Sk 1–75

And again:

>Pli Tv Bi Vb –as1–7

should be

>Bi Vb 1–7

And in each case the PREV/NEXT also doesn't work properly. The correct sequence is:

- pli-tv-bi-vb-pd2-8
- pli-tv-bi-vb-sk1-75
- pli-tv-bi-vb-as1-7 || finish here

In the bu-vb we also have:

> Pli Tv Bu Vb –as1–7

should be

>Bu As 1–7

And the prev/next should finish here.

**Comment by ihongda** [comment]
>Pli Tv Bi Vb –pd2–8

It should be:

>Pli Tv Bi Vb Pd 2–8

According to the latest rules, `pli-tv-bi-vb` in `super_extra_info.json` is acronym as `Bi`, so the new acronym for `pli-tv-bi-vb-pd2-8` after conversion is equal to `Bi –pd2–8`..

**Comment by ihongda** [comment]
> At the bottom the PREV button works, but the NEXT leads to Pli Tv Bi Vb Pd 2, which doesn't exist. (The remaining rules in this set only exist as parallels.) It should go to here:

The data of PREV and NEXT comes from the `tree` data. If it is not in the order of the tree file, we need to hardcode or create a special `tree` to define these special cases.

**Comment by sujato** [comment]
>According to the latest rules, pli-tv-bi-vb in super_extra_info.json is acronym as Bi, so the new acronym for pli-tv-bi-vb-pd2-8 after conversion is equal to Bi –pd2–8

No, the new version should be Bi Pd 2–8. I'll update the original issue.

>The data of PREV and NEXT comes from the tree data. If it is not in the order of the tree file, we need to hardcode or create a special tree to define these special cases.

Hmm. Let me think …

Ok, how about this.

In such cases, we have:

- suttaplex? --- yes, for the parallels
- text? --- no
- navigation? --- incorrect

Let's add some logic to the navigation:

- *if* there is no text (eg. `/pli-tv-bi-vb-pd2/en/brahmali` does not exist) 
- *then* go to the plain suttaplex view `/pli-tv-bi-vb-pd2/`

This would be a helpful general practice anyway. 

In addition:

- we can finally move ahead with #913 (which has been outstanding since April 2018!) 
- I can add blurbs for the empty texts, so that anyone who arrives there knows what is happening.

**Comment by ihongda** [comment]
Thanks Bhante @sujato

**Comment by sujato** [comment]
I'm working on a more systematic proposal, I will make a separate issue. For now, just get the acronyms right, don't worry about the navigation.
