### ISSUE TITLE
create `empty-leaf.json`?

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2489]
There are a number of cases where texts exist only in theory, without any actual content. For example, many of the bhikkhuni rules are not found, but are assumed to be the same as the bhikkhu rules. Nonetheless, we have them in our system because they can still have parallels.

It would be handy to have a list of such texts. 

These could be stored as a single json array in `sc-data`. 

They can be used, for example, in the creation of the suttaplexes for these texts: leave out text and translation, and have only parallels.

This might also be used for publications, and maybe elsewhere.

**Comment by ihongda** [comment]
This issue looks similar to https://github.com/suttacentral/suttacentral/issues/2525 ?

**Comment by sujato** [comment]
Indeed yes, close it
