### ISSUE TITLE
remaining bugs in standalone html and epub

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2496]
## 🐛 nesting ToC lists

- [x] Ensure ToC lists nest properly. Nested lists must be included in the `<li>`. 

This is a regression, I think:

```
<li>foo</li>
    <ul><li> bar
     …
    </li></ul>
<li>
```
should be

```
<li>foo
    <ul><li> bar
     …
    </li></ul></li>
<li>
```

***
## 🐛 pretty-printing, ugly output

- [x] Fix improper spacing due to pretty-printing:

```
<dd>
Aggregates (
<a class="ref" href="https://suttacentral.net/sn22">SN 22</a>
)
</dd>
```

similarly:

```
<dt>
Keen (
<i lang="pi" translate="no">ātāpī</i>
)
</dt>
```

Do not spend much time on this. Make sure the priorities are in order:

- It is ***absolutely essential*** that pretty-printing does not affect the content in any way.
- It is ***nice to have*** the source code readable.

Without hesitation, sacrifice readability for:

- getting content right
- finishing this and moving on

## 🐛 Vinaya body ID is malformed

- [x] `<body id="pli tv bu vb">` should be `<body id="pli-tv-vi">`

##  🐛 Publication URL

- [x] add Publication URL to #2375 

Do when the web interface is ready.

## ❓ add UID to SN main-toc

- [x] In SN, main-toc should include the samyutta number

## ❓ use `<br>` for verses

- [x] use `<br>` tag to define verse lines, instead of spans.

We wrap lines of verse in `<span class='verse-line'>`. This is so we can get the different displays using `grid` on the web. 

```
<p>
<span class='verse-line'>Here is my line of verse</span>
<span class='verse-line'>it is neither verbose nor terse</span>
<span class='verse-line'>it could be better but could be worse</span>
<span class='verse-line'>anyway it's not a deadly curse.</span>
</p>
```

This is irrelevant for us. And it has a cost: it means verses will only display sanely when there is CSS. It is also hard to transform to LaTeX. 

Traditionally, lines of verse end with `<br>` tag. 

```
<p>
Here is my line of verse <br>
it is neither verbose nor terse <br>
it could be better but could be worse <br>
anyway it's not a deadly curse.
</p>
```

Note that the *last line* of verse does not contain `<br>`. In other words, `<br></p>` must never occur.

**Comment by iseekk** [comment]
Related branch: https://github.com/suttacentral/publications/tree/2496-remaining-bugs
