### ISSUE TITLE
create more concise acronyms for Vinaya

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2497]
See also: https://github.com/suttacentral/suttacentral/issues/2483

The Vinaya acronyms are long and clumsy:

- Pli Tv Bi Vb Pd 2–8

This is because they need to disambiguate across the different Vinayas. But in fact only the UIDs need to be unambiguous. For the acronyms, it's not an issue, as you always know where you are anyway.

Typically the acronyms have the form:

- language (`pli`)
- school (`tv`)
- bhikkhu or bhikkhuni (`bi` or `bu`)
- vibhanga or patimokkha (`vb` or `pm`)
- rule class (`pd`)
- number

Of these, the language, school, and patimokkha/vibhanga can go. All we need is

- Bi Pd 2–8

**Comment by thesunshade** [comment]
Absolutely agree. Thanks for doing this.

**Comment by sujato** [comment]
I have made these changes in `super_extra_info.json` and (perhaps redundantly) in `text_extra_info.json`. 

Running the site locally, they all work fine.
