### ISSUE TITLE
individual suttas split from ranges have wrong content

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2499]
We allow in certain cases that a sutta can be presented as a range, as well as the individual suttas. 

The range:

https://suttacentral.net/an1.394-574/en/sujato?layout=plain&reference=none&notes=asterisk&highlight=false&script=latin#sc394.1

- [x]  stray span

The first sutta in this range includes an extra span. This has incorrect markup in the browser, in that it is not included in an `<article>`. However the bilara-data/html is correct.

![Screenshot from 2022-07-29 10-07-31](https://user-images.githubusercontent.com/6112010/181657177-230c7bc3-30f6-42ff-93d2-595dcddffa25.png)

- [ ] repeated content

The next sutta should be different, but in fact has the same content, including the same stray span.

https://suttacentral.net/an1.395/en/sujato?layout=plain&reference=none&notes=asterisk&highlight=false&script=latin

**Comment by ihongda** [comment]
![深度截图_选择区域_20220811213714](https://user-images.githubusercontent.com/4037966/184146197-3ade28e7-2736-4e58-aa16-408e89f2d406.png)

A curly brace is missing here, I have fixed.
