### ISSUE TITLE
Developer environment on MacOS - setting ElasticSearch ends with an error

### ISSUE THREAD

**Issue by degregar** [suttacentral/suttacentral#2518]
#### Description:

When I try to run `make prepare-host` on MacOS I get an error:
```
make prepare-host
Since ElasticSearch 5.0 you have to change 'vm.max_map_count' to at least 262144 on the host machine, even when using Docker.
In order to do that I'm going to ask you for your sudo password
sudo sysctl -w vm.max_map_count=262144
sysctl: unknown oid 'vm.max_map_count'
make: *** [prepare-host] Error 1
```

This prevents from installing further dependencies `cd client && npm install`.

#### Expected behaviour:
I'm not sure how this should work; I've never worked with ElasticSearch before, I don't know if that's an issue (with max map count) on MacOS, but we could handle the error, showing some message that we could not set the `vm.max_map_count` and continue the script to allow to perform the following steps.

**Comment by ihongda** [comment]
Hi @degregar 
Please refer to the following:
https://stackoverflow.com/questions/41192680/update-max-map-count-for-elasticsearch-docker-container-mac-host

**Comment by degregar** [comment]
@ihongda 

I don't find it useful.

I was trying to set up the development environment using instructions from `README.md` file:
```
# Development
## 1. Server

### 1.1 Running the project
0. Install [docker](https://docs.docker.com/engine/installation/) and [docker-compose](https://docs.docker.com/compose/install/).
1. Clone the repo `git clone git@github.com:suttacentral/suttacentral.git`.
2. Cd into the repo `cd suttacentral`.
3. run `make prepare-host` in order to make some small adjustment on the host machine so that we can run ElasticSearch.
4.  * 1st time run: run `make run-preview-env` - Build images, load data, index-elasticsearch and more.
	* normal run: run `make run-dev`.
```

I'm stuck at the step 3.

The instructions from the link you've sent don't work. I try to use the `screen ...` command, pressing enter and then `sysctl ...` command but it returns the same output as previously.

I'm not sure how important it is to set it, but it seems rather unimportant at this stage.

I've tried to run `make run-preview-env` to see if that makes any difference, but it failed with an error `E: Package 'google-chrome-stable' has no installation candidate`.

So I'm stuck now and don't know how to proceed with setting the environment up. I think the process might be out-of-date and I'm not sure who is maintaining it.

**Comment by ihongda** [comment]
@degregar 
I don't have a mac and there is no way to check
You can also consider pulling the relevant container directly from docker hub
https://hub.docker.com/r/paccakkha/suttacentral

**Comment by ihongda** [comment]
Or execute the following commands to create containers separately:

docker-compose build sc-flask
docker-compose build sc-nginx
docker-compose build sc-swagger
docker-compose build sc-arangodb
docker-compose build sc-frontend
docker-compose build sc-elasticsearch
docker-compose build sc-chrome-headless

**Comment by sujato** [comment]
Just a tip: elasticsearch is marked for removal, we will replace it as soon as we get the opportunity. So unless you need search for your local install, you don't need it.

**Comment by sujato** [comment]
elastic is now deprecated, I'll close this issue.
