### ISSUE TITLE
Add Jataka numbers to the top level navigation

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2523]
Go here:

https://suttacentral.net/pitaka/sutta/minor/kn/ja/ja-ekakanipata

You'll see we have the Jataka numbers per-vagga.

But go back up a level:

https://suttacentral.net/pitaka/sutta/minor/kn/ja

And there's no numbers. It makes it hard to navigate!

We should add the Jataka numbers to the nerdy row at the top level, eg.

>**The Book of the Ones**
Ja 1–150
>
>**The Book of the Twos**
Ja 151–250

And so on.

**Comment by ihongda** [comment]
It has been processed and will be pushed in the next update :smile:
