### ISSUE TITLE
Enhancing the information for backend-developers

### ISSUE THREAD

**Issue by eineruntervielen** [suttacentral/suttacentral#2531]
## Summary
Unfortunately I did not find any information regarding the current version of python in the README.md or in the server package.

## Enhancement
It would be nice to have this information in a small README.md or even better in a `.python-version` file. 
When using multiple versions of Python on a machine, `pyenv` is a popular choice for managing those. There it is common that a `.python-version` file is present in the `src` directory.

This file only contains the current version and nothing else.

Further information: https://realpython.com/intro-to-pyenv/#specifying-your-python-version

**Comment by sujato** [comment]
Good idea, thanks.

**Comment by eineruntervielen** [comment]
I'd have a few more ideas regarding the server that are going into the same direction (code documentation, strong typing, etc.) but I don't know if those are welcome.

**Comment by sujato** [comment]
Most definitely so. You know how it is, there are always so many things, it's easy to overlook stuff. We're very happy for helpful suggestions!

**Comment by eineruntervielen** [comment]
If I find something, I'll just open a new enhancement issue. If there are any topics you could use some help with, i'd love to help out at any time.

**Comment by sujato** [comment]
Well thanks. You're most welcome to check through our issues, although best check with us before proceeding, because they might be stale.

**Comment by thesunshade** [comment]
@buddhist-uni, I wonder if this is something you and or I should/could work on as we are learning about the back-end operations.

**Comment by khemarato** [comment]
@thesunshade Yeah, we should definitely document as we go. I'll go ahead and update the README with my takeaways from our architecture discussion with HongDa. But I don't think we need this issue to track it, so maybe just close?

**Comment by thesunshade** [comment]
Right. 

I don't know if it is worth it to add to the readme that `make` may not be installed. I guess it's supposed to be commonly installed by default? Unlike docker which is never? Any way, I seem to remember the problems I had with it were not as straight forward as error messages saying "You don't have make installed.

But I don't know how many people will be as clueless as me who are trying to build a local site. Maybe we could have a wiki page for setting up using WSL?

You are right, we don't need this issue. I will close for now.
