### ISSUE TITLE
Acronyms showing null

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2533]
In the parallels tables, the acronyms sometimes show `null`.

![Screenshot from 2022-10-15 07-21-30](https://user-images.githubusercontent.com/6112010/195936377-fe43f2ad-82d6-496f-89cb-a94a97be5fbc.png)

I believe this started happening after we used the new method for acronyms.

**Comment by ihongda** [comment]
The reason for this problem is that the `acro` field of uid_expansion.json is modified to `acronym`, but the corresponding backend code is not modified, will fix this problem today.

**Comment by ihongda** [comment]
This problem has been resolved, 
The reason is that the backend code of the `Production` server has not been updated recently, only the data has been updated, resulting in unexpected results.
