### ISSUE TITLE
Handling segment IDs in range texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2543]
Normally segment IDs are abstracted from the full sutta ID and presented with only the segment number, i.e. that which comes after the `:`. So for `mn2:3.2` the segment id would be `3.2`.

This works fine in normal suttas, but breaks in range suttas.

Consider:

https://suttacentral.net/an1.454/en/sujato?layout=plain&reference=main&notes=none&highlight=false&script=latin#1.1

For which the HTML is:

```
  "an1.447:1.0": "<article id='an1.447-454'><h2 class='sutta-title'>{}</h2>",
  "an1.447:1.1": "<p>{}",
  "an1.448:1.1": "{}",
  "an1.449:1.1": "{}",
  "an1.450:1.1": "{}",
  "an1.451:1.1": "{}",
  "an1.452:1.1": "{}",
  "an1.453:1.1": "{}",
  "an1.454:1.1": "{}</p></article>",
```

We have a series of segments all with id `1.1`, which is invalid HTML, and not helpful to the user.

The meaningful numbers here are the sutta numbers. We should rather have IDs of `447`, `448` and so on.

But how to do this in a robust way?

**Comment by ihongda** [comment]
I have modified this. If it is range sutta, then the sc ref id will be changed from the original `1.1` to a format similar to `an2.12_1.1` on the frontend.

![image](https://github.com/suttacentral/suttacentral/assets/4037966/8efe8813-0fee-4d60-873f-4857fdee6c6d)
