### ISSUE TITLE
Showing the data dump date of third party texts

### ISSUE THREAD

**Issue by yapcheahshen** [suttacentral/suttacentral#2549]
![image](https://user-images.githubusercontent.com/1085366/202830584-dd811813-592d-4ea2-9440-7321c5e18cf7.png)

Vimutti is mistranslated to "聖戒解脫"  in the previous version of Chuang works,
and he fixed it on 2022/10/02 .
it would be nice if SC shows the timestamp of data dumps.

**Comment by sujato** [comment]
Hi, can you help me out by giving the exact characters that need to be found + replaced? It would be nice if there was an unambiguous string.

Also as far as timestamps go, I agree, but it's not a priority. Meanwhile all that can be found on Github.

https://github.com/suttacentral/sc-data/tree/master/html_text/zh/pli/sutta/an/an4

**Comment by thesunshade** [comment]
@yapcheahshen Are you able to provide any assistance on this issue?

**Comment by thesunshade** [comment]
I'm going to close this issue for now since Bhante has indicated it's not a priority and an alternative solution (looking on git) exists.
