### ISSUE TITLE
Fix chapter links in German Vinaya texts

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/suttacentral#2560]
Chapter links in German legacy Vinaya texts like for example `https://suttacentral.net/pli-tv-kd1/de/maitrimurti-traetow?reference=main&highlight=true#mt1-336` don't link to the respective chapter, but to the top of the page.

I think the issue is due to wrong coding.

![Screenshot from 2022-11-25 09-00-56](https://user-images.githubusercontent.com/43345786/203986531-8abb2f5c-8941-4ec5-892d-2037c77975c4.png)

The link in the section number has `#mt1-336`, while in the [HTML file](https://github.com/suttacentral/sc-data/blob/master/html_text/de/pli/vinaya/pli-tv-kd/pli-tv-kd1.html) it says `id='mt1~336'`. I.e. hyphen `-` versus tilde `~`. This can probably not match.

So either in the HTML files, tildes have to be replaced by hyphens, or in the links, hyphens have to be replaced by tildes.

**Comment by sujato** [comment]
Okay, best use hyphen in IDs, we never have tilde there.

**Comment by sabbamitta** [comment]
I guess there are people who could automate this for all texts. For me it would be manual work, so I'd like to defer it to someone more knowledgeable in coding.

**Comment by ihongda** [comment]
This issue appears to have been resolved, so it will be closed.
