### ISSUE TITLE
acronyms in KN are mostly wrong on staging

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2584]
In the Suttaplex on staging, the acronyms are mostly wrong. In KN:

kp = Kp not K
dhp = Dhp not Dh

and so on. They are correct on the live site, so there must be some regression.

**Comment by ihongda** [comment]
This problem appears to be resolved :smile:

**Comment by sujato** [comment]
Indeed it is fixed on staging and production, although it is still current on the local search branch. Anyway, let's just make sure it doesn't regress.
