### ISSUE TITLE
a chronology of the Dīghanikāya

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2598]
- dn7: quoted in dn6
- dn6: Nagita is attendant; Sunakkhatta has been ordained 3 nearly years
- dn24: Sunakkhatta disrobes

- dn1: indefinite mid-period (Buddhism is well-known, sutta is quoted elsewhere)
- dn9: indefinite midperiod (Buddhism is well-known, this is before AN 6.60)
- dn8: indefinite mid-period (Vinaya ordination rules for probation)

- dn13: before dn3, as Pokkharasāti is still teaching Brahmanism (?) not really certain
- dn3: Pokkharasāti introduced, takes refuge; Bimbisara alive
- dn4: Pokkharasāti has already taken refuge; Bimbisara alive
- dn5: Pokkharasāti has already taken refuge; Bimbisara alive
- dn2: Ajatasattu
- dn16: parinibbana
- dn10: not long after parinibbana, discussion with Subha Todeyyaputta, who is in mn99 where Pokkharasāti has not taken refuge.

***

Todeyya was a supporter of Ramaputta (an4.187). The Buddha stayed in his mango grove. There were many Todeyya nrahmins (a school?). A Todeyya is in the parayana (snp5.10). He was said to have come from Tudigama, but that town seems to only exist to give him a name.

Subha, Todeyya's son, goes for refuge on three separate occasions, once before Pokkharasati's conversion, and once after the Parinibbana, On all three occasions he begins with mere polite conversation, not bowing.

**Comment by thesunshade** [comment]
I'm unclear what this is. Is it related to any problem or feature on this repo?

**Comment by sujato** [comment]
Ha ha no just some notes, no idea why I put it here. 

FWIW I was trying to place the chronology of the major DN texts, especially the major brahmin conversions starting with Pokkharasadi. From contextual evidence, it is clear that a very large number, possibly the majority, of major suttas stem from the Buddha's final years. I suspect that Pokkarasadi's conversion, and consequently the conversion of other major brahmanical figures, also dates from this time. Since posting this there's some more evidence from MN, and I think the conclusion is likely. If that is the case, it means that the conversion of senior brahmins—who one would expect to be cautious about such things—happened late in the Buddha's career. This also has various knock-on effects allowing us to identify other texts from this period as well.
