### ISSUE TITLE
"share this sutta" is broken

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2599]
On the suttaplex, we have a little button that helps to be able to share or cite a particular sutta. This has been there since the jQuery version of the site! It's currently broken, and I don't know for how long. Probably we changed the API and forgot to update it.

Go to https://suttacentral.net/sn1.19?view=normal

parallels --> share icon 

- [X] **copy link**

```
https://suttacentral.net/sn1.19
```

Ok, fine.

- [x] **copy table**

```
<!DOCTYPE>
<html>
<head>
  <title>sn1.19 Kuṭikāsutta</title>
</head>
<body>
<table>
  <caption>Kuṭikāsutta</caption>
</table>
</body>
</html>
```

That's not right. It should have all the main info for the suttaplex in a table form, including parallels. The easiest way would simply be to use the same code as we have in the "Table view". 

(When we originally did this, for some reason we made the table into a full HTML document, but that's probably a bad idea. The main use case for this is to paste it into another web page or document, so just the `<table>` is plenty good enough.)

```
<table>
            <tbody>
              <!--?lit$9717818965$--><!---->
                  <tr>
                    <td class="sutta_uid">
                      <a class="uid" href="/sn1.19/pli/ms"><!--?lit$9717818965$-->SN 1.19<!--?lit$9717818965$--></a>
                    </td>
                    <td class="sutta_title"><!--?lit$9717818965$-->Kuṭikāsutta</td>
                    <td class="parallels">
                      <!--?lit$9717818965$--><!---->
                          <!--?lit$9717818965$--><a class="uid" href="/sa-2.168/lzh/taisho"><!--?lit$9717818965$-->SA2 168<!--?lit$9717818965$--></a>,
                        <!----><!---->
                          <!--?lit$9717818965$-->
                                <a class="uid" href="/sa584/lzh/taisho"><!--?lit$9717818965$-->SA 584<!--?lit$9717818965$--></a>
                              
                        <!---->
                    </td>
                  </tr>
                <!---->
            </tbody>
          </table>
```

Ok that would be fine. (If we could strip out the Lit comments it would be even better!)

- [ ] **cite**

This is mainly useful for students, they can quickly grab a citation and paste it as a footnote.

```
Retrieved from https://suttacentral.net/sn1.19?view=normal on Sun Jan 29 2023 10:03:22 GMT+1100 (Australian Eastern Daylight Time).
```

This should have a full entry for the text and parallels. Something like.

```
SN 1.19 Kuṭikāsutta, “Little Hut” (PTS (1st ed) 1.8, PTS (2nd ed) 1.17–1.18). Parallels: SA2 168 手杻 (T ii 436b02), SA 584 手杻 (T ii 155b05). Retrieved from https://suttacentral.net/sn1.19 on Sun Jan 29 2023 10:03:22 GMT+1100 (Australian Eastern Daylight Time). 
```

- use the same URL as was already in the "copy link".
- Put the translated name in “quote marks”.
- Put the vol/page info in (brackets).

**Comment by sujato** [comment]
The "cite" is still not working properly. It gives a list of all the PTS vol-page numbers, which makes it unusable. Here is a small example from SN 1.1:

```
Parallels for SN 1.1 Crossing the Flood  ( PTS (1st ed) 1.1): SA2 180 (T ii 438c12); SA 1267 (T ii 348b07); Sag#13
Parallels for SN 1.1#2 Crossing the Flood  ( PTS (1st ed) 1.1): Sag#5.3; SF 105#1545.2 (Mette 1981: 133–151); SN 2.18#6 (PTS (1st ed) SN i 54); Mnd 15#165 ( PTS 402, PTS 403, PTS 404, PTS 405, PTS 406, PTS 407,PTS 408, PTS 409, PTS 410, PTS 411, PTS 412, PTS 413, PTS 414, PTS 415,PTS 416, PTS 417, PTS 418, PTS 419, PTS 420, PTS 421, PTS 422, PTS 423, PTS 424, PTS 425, PTS 426, PTS 427, PTS 428, PTS 429, PTS 430, PTS 431, PTS 432, PTS 433, PTS 434, PTS 435, PTS 436, PTS 437, PTS 438, PTS 439, PTS 440, PTS 441, PTS 442, PTS 443, PTS 444)
Retrieved from https://suttacentral.net/sn1-nalavagga?view=dense on Fri Apr 28 2023 08:08:12 GMT+1000 (Australian Eastern Standard Time).
```

Also, take off the `?view=dense`

It should be:

```
Parallels for SN 1.1 Crossing the Flood  ( PTS (1st ed) 1.1): SA2 180 (T ii 438c12); SA 1267 (T ii 348b07); Sag#13
Parallels for SN 1.1#2 Crossing the Flood  ( PTS (1st ed) 1.1): Sag#5.3; SF 105#1545.2 (Mette 1981: 133–151); SN 2.18#6 (PTS (1st ed) SN i 54); Mnd 15#165 
Retrieved from https://suttacentral.net/sn1-nalavagga on Fri Apr 28 2023 08:08:12 GMT+1000 (Australian Eastern Standard Time).
```

**Comment by ihongda** [comment]
> The "cite" is still not working properly. It gives a list of all the PTS vol-page numbers, which makes it unusable. Here is a small example from SN 1.1:
> 
> ```
> Parallels for SN 1.1 Crossing the Flood  ( PTS (1st ed) 1.1): SA2 180 (T ii 438c12); SA 1267 (T ii 348b07); Sag#13
> Parallels for SN 1.1#2 Crossing the Flood  ( PTS (1st ed) 1.1): Sag#5.3; SF 105#1545.2 (Mette 1981: 133–151); SN 2.18#6 (PTS (1st ed) SN i 54); Mnd 15#165 ( PTS 402, PTS 403, PTS 404, PTS 405, PTS 406, PTS 407,PTS 408, PTS 409, PTS 410, PTS 411, PTS 412, PTS 413, PTS 414, PTS 415,PTS 416, PTS 417, PTS 418, PTS 419, PTS 420, PTS 421, PTS 422, PTS 423, PTS 424, PTS 425, PTS 426, PTS 427, PTS 428, PTS 429, PTS 430, PTS 431, PTS 432, PTS 433, PTS 434, PTS 435, PTS 436, PTS 437, PTS 438, PTS 439, PTS 440, PTS 441, PTS 442, PTS 443, PTS 444)
> Retrieved from https://suttacentral.net/sn1-nalavagga?view=dense on Fri Apr 28 2023 08:08:12 GMT+1000 (Australian Eastern Standard Time).
> ```
> 
> Also, take off the `?view=dense`
> 
> It should be:
> 
> ```
> Parallels for SN 1.1 Crossing the Flood  ( PTS (1st ed) 1.1): SA2 180 (T ii 438c12); SA 1267 (T ii 348b07); Sag#13
> Parallels for SN 1.1#2 Crossing the Flood  ( PTS (1st ed) 1.1): Sag#5.3; SF 105#1545.2 (Mette 1981: 133–151); SN 2.18#6 (PTS (1st ed) SN i 54); Mnd 15#165 
> Retrieved from https://suttacentral.net/sn1-nalavagga on Fri Apr 28 2023 08:08:12 GMT+1000 (Australian Eastern Standard Time).
> ```

Bhante @sujato  what is the logic of truncation here?

**Comment by sujato** [comment]
The logic is that it should include **only** the information that is visible in the suttaplex parallels. In the example:

https://suttacentral.net/sn1.1?view=dense

We just use the same data that is in the `parallel-item-nerdy-row`. For some reason, currently it adds a bunch of extra references that list every page in the range.

**Comment by ihongda** [comment]
It is processed in the parallels of suttaplex, such as pts 1 pts 2 pts 3, will be formatted as PTS 1-3, so I also formatted them in the share menu
