### ISSUE TITLE
fix ToC in sn-guide essay

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2601]
See here: https://suttacentral.net/sn-guide-sujato?lang=en

![Screenshot from 2023-02-14 17-12-05](https://user-images.githubusercontent.com/6112010/218654276-8b20563d-4623-4681-95d4-88f49c909540.png)

Item number 5 is incorrect. It should be “The Book of the Sense Fields”.

It seems the item was left off the ToC for some reason. Unfortunately, all the segments in the essays are strict increments, so if we just insert a segment we have to change all the other numbers. That is, unless we add a point number.

I think that is what I did at some point, making it `sn-guide-sujato:6.1`. But I can't find anywhere that number exists!

So I'm not sure how to fix this, but the best way would be to make sure that this essay, including all markup, localization, and translation files, was updated with the segment numbers incremented.

I don't really care if we use a point number or just increment everything, so long as it works.

**Comment by ihongda** [comment]
I think that is what I did at some point, making it sn-guide-sujato:6.1. But I can't find anywhere that number exists!:
---
related pr:
https://github.com/suttacentral/suttacentral/commit/464bc0537eea3f051a55cf9493dadfce0d2f8a23

I've submitted the fix code and the localization files for other languages need to be modified accordingly.
https://github.com/suttacentral/suttacentral/pull/2603
