### ISSUE TITLE
display search results for other languages if there are no results in user languages

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2613]
Normally you get results in your language, as defined in the top sheet. But what if your search explicitly indicates that you want results in another language?

Currently if I search for `author:sabbamitta Katze` it tells me there are 7 results, but nothing is displayed. But the fact that I have defined an author and searched in German says that I want results in German, regardless of what it says on my "language" settings.

The language filter is useful if results are present in multiple languages. So if I search for "buddha" I should only get results in my language. But if I search for a German word or author, I must be looking for German results.

So how to deal with this?

How about this logic:

- look for results in languages as defined in settings
- if there are no results there, look in all languages
- if there are results, display them

In addition, show the user a notice:

>We found no results in the languages in your search language settings. But we did find results in `{german}`, `{french}`, `{saarlandisch}`, so here they are. If you want to search in these languages, add them via the “languages” icon in the toolbar.

This can be added  simply as an `<aside>` directly after `.search-result-head`. In this case, probably replace the existing `<aside>` so there is only one hint at a time. Maybe we can add other hints as well.

**Comment by thesunshade** [comment]
@ihongda, it looks like this is no longer implemented. Was that done on purpose?

If it was an accident, we can re-open, but I don't think it's a priority.
