### ISSUE TITLE
Search inconsistencies

### ISSUE THREAD

**Issue by ayya-vimala** [suttacentral/suttacentral#2621]
Please forgive me if this is not the right place for this issue. It's a bit hard on a phone!

The search returns some unexpected data i.e. not all possible matches and counting is a bit counter-intuitive. Also case sensitivities are problematic.

Go to search and type in:

In: sn dana

Returns 0 results due to my phone capitalizing the first letter.

in:sn dana 

Returns one match (sn1.33 in pali) and tells me there are 71 results. 

I see it says 71 results in all languages but not the language I selected. So that would be the reason. So it would be more logical to say that only one match is found with current filter and language settings. Still, I'd expect more matches in the pali texts than just 1.

**Comment by ihongda** [comment]
@ayya-vimala Venerable Vimala, 
thank you for your feedback. I have been adjusting and fixing bugs in search these days, and I will fix them as soon as possible.: pray:

**Comment by ihongda** [comment]
Arangosearch's full-text search uses words to search, so such as `vedanaṁ`, although it contains `dana`, will not be matched in the full-text search。

If use arangodb's identity analyzer to index the content of sutta, most of them will exceed the allowed limit.

I'm looking for any other suitable way.

**Comment by delightedbydhamma** [comment]
Similar enough to Venerable Vimala's that I won't start a new issue. 
Please forgive me if this is in the wrong place.

in:MN returns nothing
in:mn returns suttas both in MN and Mnd

**Comment by ihongda** [comment]
Venerable @ayya-vimala 
Venerable @delightedbydhamma 

The relevant fixes have been deployed to `[staging](https://staging.suttacentral.net)`, please try it out when you have time.

Due to indexing all segmented texts, the number of database records increased from approximately 80,000 to approximately 800,000. As a result, the search speed has decreased and I am thinking of ways to improve it.
