### ISSUE TITLE
Searching for "firefly" "fire-fly" and "fire fly" should return the same results.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2622]
#### Steps to reproduce:

* search for "firefly" "fire-fly" and "fire fly"

#### Expected behaviour:

Results should be identical each time, but they are not. 

OK, so I *think* the results should be the same each time. At least I can't imagine that someone would ever expect the results to be different.

#### Example results:

![image](https://user-images.githubusercontent.com/82448383/224405027-105da941-0585-41ea-934d-9a651f2f8e86.png)

For the two below, the items returned are the same, however the text previews are missing on one. But that is probably a completely different issue.

![image](https://user-images.githubusercontent.com/82448383/224405089-dae97ec4-200e-4ac4-a729-e42622c207fc.png)

![image](https://user-images.githubusercontent.com/82448383/224405151-f35d6612-4829-46c9-9f15-178e300890c3.png)

**Comment by ihongda** [comment]
Thanks @thesunshade This problem has been fixed :smile:

**Comment by thesunshade** [comment]
Thanks!!

**Comment by ihongda** [comment]
It will be deployed to staging.suttacentral.net later. :smile:

**Comment by ihongda** [comment]
Hey @thesunshade The fix has been deployed to [staging](https://staging.suttacentral.net), please check when you have time.

**Comment by thesunshade** [comment]
When I search for firefly I get MN79 and 80 translated by Bhante Sujato. When I search for fire-fly (or fire fly) I get those two suttas translated by IB Horner. 

Honestly I don't know if it is reasonable to expect that firefly and fire fly return identical results. (meaning that both Bhante Sujato's and Horner's should return) But I do. ¯\\\_(ツ)_/¯

**Comment by ihongda** [comment]
> When I search for firefly I get MN79 and 80 translated by Bhante Sujato. When I search for fire-fly (or fire fly) I get those two suttas translated by IB Horner.
> 
> Honestly I don't know if it is reasonable to expect that firefly and fire fly return identical results. (meaning that both Bhante Sujato's and Horner's should return) But I do. ¯\_(ツ)_/¯

Hey @thesunshade , I solved this problem in another way, please try it when you have time:
[staging.suttacentral.net](https://staging.suttacentral.net)

**Comment by sujato** [comment]
Tested this and it works!
