### ISSUE TITLE
filter to search by reference number

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2625]
Let people search by reference. This is similar to the volpage search, it lets people look things up by traditional reference systems. In this case, any reference key would return the appropriate results.

What might this be useful for? Well, the `reference` files include counts of verses which are labelled `vns` (verse number SuttaCentral) and `vnp` (verse number PTS). (Mostly these are the same, but in a few cases the verse count is different.) People want to look up the exact verse result. In other cases, they might want to check a reference found in another edition of the Tipitaka.

Note that the references are not necessarily unique in the canon, as sometimes they are scoped to specific books. Eg. verse count is per book. If there are multiple results, show them all.

If possible, let people just use the reference key:

- `vns12` gives everything that has `vns12`.
- etc.

If we cannot get it working using just the bare reference, then add the prefix `ref:` to make it more explicit.

- `ref:vns12`

**Comment by thesunshade** [comment]
Ooh, I just found an undocumented feature!

https://suttacentral.net/search?query=ref:vns12 works.

Even https://suttacentral.net/search?query=ref:cck9.1 works.

Is this actually fully functioning? How to narrow it to a book? E.e. `in:pv ref:vns360` doesn't work. Neither does `ref:pv.vns360`

@buddhist-uni FYI
