### ISSUE TITLE
make sure front end always uses en-dash for number ranges

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2651]
go here: https://suttacentral.net/pitaka/sutta/minor/kn/ja

We see ID number ranges of the form: Ja 464-473. This uses a hyphen to separate the numbers, it should be an en-dash: Ja 464–473.

This is correct sometimes, eg. here:

https://suttacentral.net/pitaka/sutta/minor/kn/ja/ja-terasakanipata

and here:

https://suttacentral.net/ja-ambavagga?view=normal

**Comment by ihongda** [comment]
The child range mainly comes from this file, https://github.com/suttacentral/sc-data/blob/master/structure/child_range.json,
let me check if I can modify this file directly.
