### ISSUE TITLE
Start and end of lines are not visible

### ISSUE THREAD

**Issue by mjhopkins** [suttacentral/suttacentral#2652]
The box containing the text is wider than the displayed area. This means that it's not possible to see the start and end of every line, even with scrolling or zooming. I have attached a screenshot that demonstrates the issue.

Platform: Android
Browser: Chrome 

![Screenshot_20230501-164014~2](https://user-images.githubusercontent.com/2715128/235418255-e10e6655-8949-45e3-a7d1-745462fa19c6.png)

**Comment by Branzz** [comment]
This has also happened to me on android Firefox. For now, one can enable Desktop Mode

**Comment by ihongda** [comment]
Hey @Branzz , thank you for you feedback, I will check it 🙏🏼

**Comment by ihongda** [comment]
Hey @Branzz , This bug has been fixed, thanks 🙏🏼
