### ISSUE TITLE
add badges on suttaplex for "aligned" and "annotated"

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2655]
On the suttaplex it is not immediately obvious which suttas are "aligned", (i.e. root and translation segments aligned via Bilara), except by the fact that it has translation language + root language mentioned.

Nor is there any indication of where notes AKA annotations are available.

Let's solve these by putting a badge on the suttaplex to indicate these things. 

Something like this.

![badge-mockup](https://user-images.githubusercontent.com/6112010/235815044-e27611ca-d3e2-4665-8856-5e64502e64be.png)

**Comment by sujato** [comment]
Running the latest master locally, there's still check marks on `legacy` badges. The point of the check mark is to indicate the presence of an extra functionality, which is lacking in legacy texts, so no checkmark.

![Screenshot from 2023-05-16 17-08-44](https://github.com/suttacentral/suttacentral/assets/6112010/706c8b1d-8ed8-44fa-ac90-ff56d45f4de6)

Also we should clean up the code for this. I suggest making a separate badge for each thing, so if we need to target them for styles or functionality we can. We may want to add more in future.

Something like this, but this is just pseudo-code for demonstration:

```
    :host([badge='annotated']) {
      color: var(--sc-secondary-text-color);
      border: 1px solid var(--sc-border-color)
    }

    :host([badge='annotated']):before {
      content: "✓ ";
      color: var(--sc-primary-accent-color);
    }

    :host([badge='aligned']) {
      color: var(--sc-secondary-text-color);
      border: 1px solid var(--sc-border-color)
    }

    :host([badge='aligned']):before {
      content: "✓ ";
      color: var(--sc-primary-accent-color);
    }

    :host([badge='legacy']) {
      color: var(--sc-secondary-text-color);
      border: 1px solid var(--sc-border-color)
    }
```

**Comment by ihongda** [comment]
We can use the original text attribute to customize, for example

```
    :host([text='aligned']):before {
      content: "✓ ";
      color: var(--sc-primary-accent-color);
    }

    :host([text='annotated']):before {
      content: "✓ ";
      color: var(--sc-primary-accent-color);
    }
```
