### ISSUE TITLE
Option to show segment number link

### ISSUE THREAD

**Issue by vwkd** [suttacentral/suttacentral#2680]
#### User story

An option to show the segment number link would be helpful. Currently, there doesn't seem to be an option or I haven't found it yet.

Though I've found a workaround. Opening the URL without query parameters and with the section number as fragement shows the segment number links, e.g. https://suttacentral.net/dn1/en/sujato#1.1.1

<img width="753" alt="segment number links" src="https://github.com/suttacentral/suttacentral/assets/33468089/922705c0-b990-49bc-8a68-c2326c94e774">

#### Feature description

A option somewhere (maybe in "Views"?) to show the segment number link.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by ihongda** [comment]
![screenshot_2024-01-04_18-26-06](https://github.com/suttacentral/suttacentral/assets/4037966/a30b9e50-fe9c-4914-9e02-27a54bd4883d)

Hey @vwkd 
Hi, here you can display the relevant segment numbers and links. 🙏🏼

**Comment by vwkd** [comment]
Great, had indeed missed that. Thanks!
