### ISSUE TITLE
Search results don't seem to be added to browser history

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2713]
#### Steps to reproduce:

1. Start from the home page
2. Click search icon
3. type "parents"
4. on results page, the search query is not included in the history/url
5. click on the first sutta result
6. click the back button
7. end up nowhere (specifically https://suttacentral.net/search?lang=en)

#### Expected behaviour:

The search result page should be part of the browser history. Hitting the back button after looking at a sutta from the search results page should take you back to that same search result.

**Comment by sujato** [comment]
Indeed it should, thanks for noting this.

**Comment by thesunshade** [comment]
It looks like this is working now. I'm closing.
