### ISSUE TITLE
Remove obsolete items from the i18n file and correct errors

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2732]
- [x] [possibly remove tool tips from site](https://github.com/suttacentral/suttacentral/issues/2732#issuecomment-1913050557)

## Not being used?

I believe the following are no longer used in the interface:

```
  "interface:downloads": "Downloads",
  "interface:downloadsTitle": "Downloads",
```

```
dictionary:rememberSettings
dictionary:rememberSettingsDescription
dictionary:rememberSettingsDisabled
dictionary:rememberSettingsEnabled
interface:aNewBeginning
interface:aNewBeginningTitle
interface:browseTooltip
dictionary:onlyWorks
```

## Errors?
This just seems wrong.
```
"error:pageNoFound": "Page No Found",
```
I'm not sure if this is even being used.

There are two different spellings, 
Acknowledgments and 
Acknowledgements
```
"interface:acknowledgments": "Acknowledgments",
"interface:acknowledgmentsTitle": "Acknowledgements",
"footer:acknowledgments": "Acknowledgements",
```

**Comment by thesunshade** [comment]
I'm also suggesting that we remove 
```
"suttaplex:blurb": "Blurb",
```
from the interface. It's just a tool tip and doesn't really provide users much value. Also, it's a strange new English word that 1) people may not know the meaning and 2) it's very hard for translators to translate.

This would actually need to be removed from the code of the site before it is removed from the interface file.

**Comment by ihongda** [comment]
The relevant key value has been deleted 😄

**Comment by thesunshade** [comment]
So have they all been deleted from the other language files as well? I'm beginning to see what a complicated thing this i18n is.

**Comment by ihongda** [comment]
> So have they all been deleted from the other language files as well? I'm beginning to see what a complicated thing this i18n is.

Yes, they have been deleted in the unpublished branch, but I will also check in the published branch.

**Comment by thesunshade** [comment]
@sujato, do you know if these lines actually need to be internationalized?
```
"interface:metaDescriptionText": "Early Buddhist texts and modern translations. Suttas (sutras) from the Tipitaka (Tripitaka) in Pali, Chinese, Sanskrit, and Tibetan with the Buddha's teachings on mindfulness, insight, wisdom, and meditation.",
  "interface:metaKeywords": "Buddha, Buddhism, Buddhist, sutta, sutra, tipitaka, tripitaka, wisdom, teaching, mindfulness, meditation, scripture, canon, Pali, Sanskrit, Tibetan, Chinese, insight, vipassana",
```

They aren't displayed on the site, and any scraper is not going to have access to the non-English page anyway, will they?

I just ran this link (https://suttacentral.net/dn16/de/sabbamitta?lang=no&layout=plain&reference=none&notes=none&highlight=false&script=latin) through the opengraph checker (https://www.opengraph.xyz/url/https%3A%2F%2Fsuttacentral.net%2Fdn16%2Fde%2Fsabbamitta%3Flang%3Dno%26layout%3Dplain%26reference%3Dnone%26notes%3Dnone%26highlight%3Dfalse%26script%3Dlatin) And only the English text appears.

I'm just trying to keep the i18n to what is actually needed.

**Comment by thesunshade** [comment]
I think we should stop adding `title` tool tips to the site. 

1. They don't aid in accessibility
2. They aren't usable on touch/mobile
3. They have to be internationalized

For example, all of these things on the home page have tool tips but they don't even add good information to the experience:

![Image](https://github.com/suttacentral/suttacentral/assets/82448383/7d116f70-feff-4c20-96a4-5f3baaa8a6e2)

Bhante @Sujato, what do you think? Vens @sabbamitta, @buddhist-uni?

**Comment by khemarato** [comment]
Yeah. The element's plain text should be enough.

**Comment by sabbamitta** [comment]
Yes, I agree.
