### ISSUE TITLE
Clean up language names in interface

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2744]
#### Description:

There are some languages in the interface list that are not capitalized or are not in their own language script.

# these aren’t capitalized:

* hrvatski: Croatian
* slovenčina: Slovak
* ру́сский язы́к: Russian

Should be 
* Hrvatski: Croatian
* Slovenčina: Slovak
* Русский : Russian (язы́к means language and we don't seem to include that usually)

# Languages not in own script

* Arabic --> اَلْعَرَبِيَّةُ‎
* Farsi --> فارسی
* Hebrew --> עִבְֿרִיתּ
* Bengali --> বাংলা

**Comment by thesunshade** [comment]
I just noticed that the issues above are also found on the language page here: https://suttacentral.net/languages?lang=en

Does that somehow need to be rebuilt? It appears that the individual language pages also have the issue:
![2024-01-06 11_11_40-SuttaCentral—languages-detail — Mozilla Firefox](https://github.com/suttacentral/suttacentral/assets/82448383/0487196f-9d6c-49a6-b761-a899b78a390d)

**Comment by ihongda** [comment]
@thesunshade  This issue should have been resolved after reloading the language data.

**Comment by thesunshade** [comment]
It appears this is resolved so I am going to close.
