### ISSUE TITLE
instant search remaining bugs

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2750]
- [x] Get rid of js messing with tab order in search results. We must serve *only plain, well-structured HTML in search results*. That means links must be `<a>` tags. We should always structure the HTML properly and trust the browser. No js in search results!
- [x] The context cues are not implemented properly. The idea is that `in:mn` should only show when you are *in mn*. Otherwise they just take up space. But this is just an enhancement, it is not necessary. For now, let's take out all suggested filters except `in:ebt`.
- [x] We don't need to keep results limited to seven: try having maximum 20 results.
- [x] Dark theme is not yet implemented. I will do this, but it will take a couple of days. 

Now let's look at the different results for texts (i.e. suttas) and nodes (i.e. vaggas, etc., or anything that is not a text).

- [x] Show an `open_book` icon for text results, and a `network_node` icon for nodes.
    - I have implemented the `open_book` icon. I have also added `network_node` icon to `sc-icon.js`. Use this for any instant search results that are *not* texts.
- [x] Don't add `/lang/author` to node URLs. If I search for `vagga` then click on the first result I get: `https://staging.suttacentral.net/snp-mahavagga/en/sujato?lang=en`. This is not a valid URL.  Take off `/en/sujato` and it is correct. This means `/lang/author` is only added to texts. Here is a summary:

| type of result  | has `lang/author` | icon |
| ------------- | ------------- | ------------- |
| text  |  ✅ yes | `open_book` |
| node  | ❎ no | `network_node` |

**Comment by ihongda** [comment]
Bhante, can you send me these two icons: `open_book`, `network_node` ？

**Comment by ihongda** [comment]
> Show an open_book icon for text results, and a network_node icon for nodes.
> I have implemented the open_book icon. I have also added network_node icon to sc-icon.js. Use this for any instant search results that are not texts.

For the time being, only the open_book icon is used, because to determine whether it is a leaf or a branch, each item needs to request information from the server, which will have a great impact on the loading speed.

**Comment by sujato** [comment]
Adding one more to the list:

- [x] **Use `ebs` filter instead of `ebt`.**

Currently results use `ebt` filter. This gives results for all Early Buddhist Texts. The problem is, a large number of those texts are Vinayas in Chinese, which are very obscure and hardly anyone reads. We should prioritize Sutta texts for these results. Instant search should aim to cover 90% of people's immediate needs, not all of them.

To do this, introduce a new search filter, `ebs`, i.e. "Early Buddhist Suttas". This is equivalent to :

```
in:dn da mn ma sn sa sa-2 sa-3 an ea ea-2 kp iti ud snp dhp thig thag sf
```

This filter applies to:

- it can be used on full text search just like any other, and should be added to the "filters" list
- it is the default suggested filter for the instant search.

**Comment by sujato** [comment]
> > Show an open_book icon for text results, and a network_node icon for nodes.
> > I have implemented the open_book icon. I have also added network_node icon to sc-icon.js. Use this for any instant search results that are not texts.
> 
> For the time being, only the open_book icon is used, because to determine whether it is a leaf or a branch, each item needs to request information from the server, which will have a great impact on the loading speed.

Can't we use a regex on the URL?  

- use `network_node` icon UNLESS
- matches `\.net/.*/.*\?`, then use `open_book`.

**Comment by sujato** [comment]
The "stop js messing with tabindex" was marked as done, but it hasn't changed, at least not on staging.

Are we looking at the same thing?

[Screencast from 2023-09-15 16-38-38.webm](https://github.com/suttacentral/suttacentral/assets/6112010/481d8d41-46af-4cc8-8500-0c95ef8f5328)

This is not acceptable, it is confusing and janky for the user, and adds needless complexity. Just use `<a>` tags and let the browser worry about tabbing.

**Comment by sujato** [comment]
Another minor bug:

```
<span class="search-filter">in:in:ebt</span>
```

- [x] should be

```
<span class="search-filter">in:ebt</span>
```

**Comment by sujato** [comment]
One more:

We need a search prompt in the main text field. Currently we have two search options:

- main text field = search in all texts
- filter prompt = search in ebt (to be changed to ebs)

But in the first case there is no indication what is meant. It should have "Search in all texts". 

- [x] make search label descriptive

**Comment by ihongda** [comment]
> The "stop js messing with tabindex" was marked as done, but it hasn't changed, at least not on staging.
> 
> Are we looking at the same thing?
> 
>  Screencast.from.2023-09-15.16-38-38.webm 
> This is not acceptable, it is confusing and janky for the user, and adds needless complexity. Just use `<a>` tags and let the browser worry about tabbing.

I just checked and it's my problem. I only removed the code that responds to keyboard events and forgot to remove the code that responds to mouse events.

**Comment by ihongda** [comment]
> > > Show an open_book icon for text results, and a network_node icon for nodes.
> > > I have implemented the open_book icon. I have also added network_node icon to sc-icon.js. Use this for any instant search results that are not texts.
> > 
> > 
> > For the time being, only the open_book icon is used, because to determine whether it is a leaf or a branch, each item needs to request information from the server, which will have a great impact on the loading speed.
> 
> Can't we use a regex on the URL?
> 
> * use `network_node` icon UNLESS
> * matches `\.net/.*/.*\?`, then use `open_book`.

The URL is generated by getting data from the server when the user clicks it, so this method won't work.

**Comment by ihongda** [comment]
Orama data of `ebs` is about 1.5MB
