### ISSUE TITLE
Voice - playlist of suttas in order?

### ISSUE THREAD

**Issue by mxmilkiib** [suttacentral/suttacentral#2762]
#### User story

Going to the Voice site, or the main site itself, and being able to click once for the Voice system to read out the selected/current sections set of suttas.

#### Feature description
Playlisting multiple entries to be read out.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by thesunshade** [comment]
@sabbamitta (I don't know K.L.'s gitHub name), I just noticed this fairly recent issue. Should it perhaps be moved to the Voice repository?

**Comment by sabbamitta** [comment]
@firepick1 have you seen this issue? We have the possibility for playlists in the old Voice (soon to be deprecated). In the new Voice we can have a list of suttas on a search card, then to open individual sutta cards for each of them. But we don't have so far a way to have a playlist *from SC*.

@mxmilkiib could you please describe your use case in a bit more detail?

**Comment by mxmilkiib** [comment]
I want to be able to listen to all the suttas in order.

**Comment by sabbamitta** [comment]
Okay, please let us continue the discussion [on the D&D forum](https://discourse.suttacentral.net/t/listen-to-suttas-in-order-on-sc-voice/32675) as this is easier to read for the visually disabled. In case we come to a particular feature to work on, we can then come back here.

**Comment by firepick1** [comment]
:wave: Hello @mxmilkiib! Thanks for your suggestion. Please join us on the D&D forum, where I posted my own reason for sutta playlists. Would love to hear your story. :pray:

**Comment by thesunshade** [comment]
I'm going to close this for now. Perhaps if it is still necessary after the D&D discussion someone could start a new issue on the SCVoice repository.
