### ISSUE TITLE
delete .search-result-head, add content to toolbar

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2818]
Currently we have the `.search-result-head` at the top of the search results.

![Screenshot from 2023-10-27 17-55-11](https://github.com/suttacentral/suttacentral/assets/6112010/3d7b7d74-9c59-40f1-9e87-39719f2b8af1)

This

- takes up vertical space
- adds visual noise

Notice that the toolbar just says "Search: dhamma" which is less informative. Let's add the content to the toolbar instead.

![Screenshot from 2023-10-27 18-00-53](https://github.com/suttacentral/suttacentral/assets/6112010/efa9da54-f9b0-4f03-8d18-f50239bf0e11)

**Comment by ihongda** [comment]
Bhante, The modification has been submitted to PR: 
https://github.com/suttacentral/suttacentral/pull/2817
