### ISSUE TITLE
Print Stylesheet cutting off on bottoms of pages

### ISSUE THREAD

**Issue by delightedbydhamma** [suttacentral/suttacentral#2823]
#### Description:
When printing from the site the last line gets half cut off and then is reprinted on the next page, also half cut off. This seems to be consistent on many printers. Can we update the print css file to fix this?

#### Steps to reproduce:
Printing from Safari or Chrome. See attached PDF for example
* [include links were possible]

#### Expected behaviour:
Show all line in printed document

#### Screenshots:
[Thag 20-1.pdf](https://github.com/suttacentral/suttacentral/files/13197080/Thag.20-1.pdf)

**Comment by ihongda** [comment]
Ven. @delightedbydhamma 
I tried the same sutta and exported it to PDF and it didn't reproduce the problem:
[cd.pdf](https://github.com/suttacentral/suttacentral/files/13601319/cd.pdf)

I also set it to line by line, but the color of the root text font looks different from the file you exported.

**Comment by delightedbydhamma** [comment]
🤔 interesting. I am travelling until Tuesday but I will try and do more tests when I am back at the monastery and see what is happening

**Comment by thesunshade** [comment]
@delightedbydhamma Do you know if this has been resolved?

**Comment by delightedbydhamma** [comment]
Seems to be ok for Chrome now, but still present in Safari :)

**Comment by thesunshade** [comment]
I've never used Safari. Is this kind of par for the course?

@ihongda are we even officially trying to support Safari? Of course it would be good have it working.

**Comment by delightedbydhamma** [comment]
If I try and print this page it's fine!
Safari is the default browser for Mac and has the second highest market share after chrome according to https://gs.statcounter.com (this seems to combine iOS and MacOS)

**Comment by thesunshade** [comment]
> If I try and print this page it's fine!

So the issue is resolved? Meaning that on screen the print preview looks wrong but it prints fine?

**Comment by delightedbydhamma** [comment]
No. Sorry I wasn't clear.
 If I try and print THIS page it's fine (ie github). 
If I try and print a page from SC I have the issue flagged above.

My response was that it is not that Safari can't follow print stylesheets, but that it has a problem with the SC print stylesheet.

**Comment by thesunshade** [comment]
OK, so I checked in the `suttacentral/suttacentral` repo and could only find four print styles for the whole site. One is just for maps, another for something called `\client\elements\text\sc-text-stepper.js`. Another is just for the footer, but it only has `display: none`

`\client\elements\styles\sc-site-layout-styles.js` looks the most promising but it only has this:

```css
 @media print {
    #universal_toolbar,
    #title,
    #site_footer {
      display: none;
    }
  }
```

So my completely uneducated conclusion is that Safari may have a problem with SuttaCentral pages, but it's not because of SuttaCentral's print style sheet. There simply isn't one.

I don't know how to move forward on this. I'm assuming that Safari users will always have a second browser installed so that when they run into problems like this they can do what they need to do.

@delightedbydhamma do you have any suggestions?

**Comment by delightedbydhamma** [comment]
[Google](https://www.bennadel.com/blog/851-fixing-divs-that-cause-content-truncation-when-printing.htm) tells me that we need to do 
`<style type="text/css" media="print">

		.container {
			display: inline ;
			}

	</style>`

Tested and works in Safari.
Doesn't break anything obvious in Chrome

**Comment by thesunshade** [comment]
@ihongda are you able to test this?

**Comment by ihongda** [comment]
@thesunshade Got it, I'll find a Safari to test it out.

**Comment by thesunshade** [comment]
Wondering if there was any resolution to this. Since we are playing with Apple things these days.

**Comment by delightedbydhamma** [comment]
It seems good for me now :)

**Comment by thesunshade** [comment]
Thanks for following up!
