### ISSUE TITLE
If site search returns nothing, Display a link to the forum.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2831]
#### User story

Someone does a search for `Emotional Intelligence`.
https://staging.suttacentral.net/search?query=Emotional%20Intelligence

They get zero results:

<img width=400 src="https://github.com/suttacentral/suttacentral/assets/82448383/58819593-3920-4980-8498-25b7bd6a1f99">

It would be nice to direct them to the discussion forum to search for what they are looking for and/or post a question.

#### Feature description

The screen for no results might look like this:

<img width=400 src="https://github.com/suttacentral/suttacentral/assets/82448383/36f4f735-1617-48b9-a754-f5136d91c36c">

The first link could include the unsuccessful search term:

> https://discourse.suttacentral.net/search?q=Emotional%20Intelligence

The second link could just be to the home page of the forum.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
Yes, good idea.
