### ISSUE TITLE
#Breadcrumbs Nav not displaying (correctly) in IOS15 on iPhone

### ISSUE THREAD

**Issue by delightedbydhamma** [suttacentral/suttacentral#2840]
#### Description:
When viewing a sutta on iOS15 on an iphoneXE  #breadCrumb nav has no background color showing.

#### Steps to reproduce:

Hooking up my phone to the inspector in Safari, I can make it look how I think it should by adding a background color to  <nav>. For my testing I did: `background: orange;`

if I change `display:flex;` to `display:block;` then things are a bit less squishy.

without these fixes there are 1 or 2 black arrows which mean nothing at the top of the screen, which are the dividers in the breadcrumbs.

It still seems the breadcrumb box is extending off of the left of the screen.... something to do with the `display` of `nav .breadcrumbs-wrapper ul`

#### Screenshots:
![IMG_0662](https://github.com/suttacentral/suttacentral/assets/105905254/4921f45e-7ad7-4dba-a67e-a1e9d119bc62)
![IMG_0661](https://github.com/suttacentral/suttacentral/assets/105905254/7a13a0fa-fd66-4d08-8534-ffdd888c0e4d)
![IMG_0660](https://github.com/suttacentral/suttacentral/assets/105905254/04f3d03f-8665-49f2-936b-4bf9b1bad2d8)

My tweaks
with `background:orange;`
![IMG_0669](https://github.com/suttacentral/suttacentral/assets/105905254/0702a095-52cb-4a7d-ba92-05313502509e)

with `display:block`
![IMG_0668](https://github.com/suttacentral/suttacentral/assets/105905254/ebf43d1d-c973-4332-9eeb-ed7f2e751974)

Let me know if I can be of any more help :)

**Comment by ihongda** [comment]
@delightedbydhamma  Thanks for your feedback, I will follow up 🙏🏼

**Comment by thesunshade** [comment]
@delightedbydhamma Can you confirm if this is working yet?

**Comment by delightedbydhamma** [comment]
I'm sorry to report this is definitely not working.
There are a LOT of formatting issues on iphone XE including the one noted above.
The breadcrumbs are now invisible (no background with black arrows >)

![IMG_0723](https://github.com/suttacentral/suttacentral/assets/105905254/acb43092-ceb0-4abe-a0fd-0c6a6903482f)
![IMG_0722](https://github.com/suttacentral/suttacentral/assets/105905254/dd1f0930-a0d0-4227-bd8d-6f9503ec6bbc)
![IMG_0721](https://github.com/suttacentral/suttacentral/assets/105905254/f1dc5acf-cd08-4591-a414-aabd301f7f90)

**Comment by thesunshade** [comment]
@delightedbydhamma Wow. That's kind of a disaster. 

Do you mean iPhone SE? I guess there is only Safari on the iphones, eh? Also assume you have done a hard refresh.

**Comment by delightedbydhamma** [comment]
Yes, sorry. iPhone SE
All browsers on ios are just pretty skins of safari/webkit.
I will check tomorrow how the site looks on iOS on iPad, but from memory the larger screen is more forgiving.

**Comment by thesunshade** [comment]
It looks, though, that whole css files are missing, which is odd.

**Comment by thesunshade** [comment]
This looks related to https://github.com/suttacentral/suttacentral/issues/2898

**Comment by delightedbydhamma** [comment]
I agree. 
Though, my experience is that this is only a bug on iOS safari and not safari for MacOS

**Comment by delightedbydhamma** [comment]
Good news. iOS 17.4.x seems to have fixed this problem

**Comment by thesunshade** [comment]
Excellent! Thanks for following up.
