### ISSUE TITLE
Parallels dropdown does not display correctly on Mac Safari

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2898]
Using Safari on Mac, on the text page view, the Parallels button opens an overlay that does not render properly.

![a1e07bb62b53470ec5a0e102abc868283d0b5fde_2_966x750](https://github.com/suttacentral/suttacentral/assets/6112010/73a3ccfc-5a3f-458a-98cf-61c03cdc00ec)

![df4983c5dd4255d786d879085d7b0b3a6436521e_2_1380x716](https://github.com/suttacentral/suttacentral/assets/6112010/bcdbd28e-c96b-4049-bfb7-38aa60ae3ac2)

We should test that all the dropdowns (contents, info, views, parallels) work correctly on all versions of Safari. Also test the dropdown on the navigation and search views.

**Comment by ihongda** [comment]
This problem may occur in a specific version of Safari. It does not seem to have this problem in the latest version 17. I will find other versions to test it.

**Comment by thesunshade** [comment]
Bhante, what version of Safari are you using? I also tested in an emulator for 17 and it was fine. Of course the emulator may not be accurate.

Are you still having this problem?

**Comment by thesunshade** [comment]
This looks related to https://github.com/suttacentral/suttacentral/issues/2840

**Comment by delightedbydhamma** [comment]
> Bhante, what version of Safari are you using? I also tested in an emulator for 17 and it was fine. Of course the emulator may not be accurate.

iOS 17.4 seems to behave as expected. I can no longer reproduce this issue either. 
It's not my bug to check off, but I think we can squish it.
