### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#2904]
#### Description:
I'm trying to set up a local version of the site with `make run-dev`. However, I'm unable to load the Tipitaka section of the site (see screenshot) and get the following error in the console `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`. 

#### Steps to reproduce:
1. `DOCKER_DEFAULT_PLATFORM=linux/amd64 make run-preview-env`
2. `make run-dev`
3. Open browser to http://localhost:3000/

#### Expected behaviour:
See links to the Tipitaka

#### Screenshots:
<img width="1727" alt="image" src="https://github.com/suttacentral/suttacentral/assets/4453276/e8dfae36-8dba-4f26-8c53-7f58c2916f90">

I'm also using a mac m2 chip to build so I had to modify some build flags but I was able to do so successfully. Let me know if it's worth adding instructions so Mac users can contribute more easily.

**Comment by ihongda** [comment]
Hi @ishaanv 
You can access `http://localhost/?lang=en` directly without adding a port. 🙏🏼

**Comment by ghost** [comment]
That worked, thanks! Happy to make a PR to include this in the readme as well as instructions for running on mac arm64 chips if you think it's a good idea.
