### ISSUE TITLE
client dependencies fail to install due to version conflict

### ISSUE THREAD

**Issue by gambhiro** [suttacentral/suttacentral#2910]
#### Description:

CC @ihongda

As @ishaanv also noted [on the commit](https://github.com/suttacentral/suttacentral/commit/bb0a5bcb01f54dadd455d8c5aa89932df7106bf1#r134787185), the vite and vite-plugin-babel versions are incompatible in `client/package.json`:

    "vite": "5.0.8",
    "vite-plugin-babel": "1.1.3",
    
This causes `make run-preview-env` fail with a dependency resolution error.

`vite-plugin-babel` currently specifies`"vite": "^2.7.0 || ^3.0.0 || ^4.0.0"`, so the last compatible version is:

    "vite": "4.5.1",

#### Steps to reproduce:

Fresh clone, `make prepare-host`, `make run-preview-env`.

#### Expected behaviour:

`make run-preview-env` should complete without errors.

**Comment by ihongda** [comment]
Thanks @gambhiro @ishaanv 🙏🏼 
I have adjusted the vite version.
