### ISSUE TITLE
span.acronym for Saṁyuttanikāya and Aṅguttaranikāya

### ISSUE THREAD

**Issue by renaldoaluska** [suttacentral/suttacentral#2925]
sukhī hontu,

"span.acronym" that I address here refers to that "DN 1-13", "DN 14-23", etc. label 
(https://suttacentral.net/pitaka/sutta/long/dn):

<img width="947" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/1f625c69-860c-432d-91da-4c57258892f6">

it is very helpful for beginner readers that aren't familiar with the structure of the nikāyas.
but, there is no such label on the Saṁyuttanikāya page (https://suttacentral.net/pitaka/sutta/linked/sn):

<img width="941" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/1e2abb1b-eb71-435a-a261-8f69eaccec6f">

is it possible to also add something like "SN 1-11", "SN 12-21", etc. (span.acronym) to the Saṁyuttanikāya page?
umm... and for Aṅguttaranikāya, I know that the nikāya's structure is a bit different here but..

![image](https://github.com/suttacentral/suttacentral/assets/21968935/20732547-f039-4316-a763-237a2d0a143b)

for example here (https://suttacentral.net/pitaka/sutta/numbered/an/an3), is it possible to also add the span.acronym? something like "AN 3.1-50", "AN 3.51-102", etc.. the same applies to AN 2, 4, 5, 6, and so on.

thanks.

**Comment by renaldoaluska** [comment]
update: after checking a glimpse of:
https://github.com/suttacentral/suttacentral/blob/b5f8a2e0317935d213dcb2407b71fb942038aa6d/client/elements/navigation/sc-navigation.js#L156

I think I should've posted this on `sc-data` instead (not sure).
I assume that adding the `id `to https://github.com/suttacentral/sc-data/blob/383dc90d3920c34256fc4ae60940aed9bc741f9b/structure/child_range.json would automatically show the `span.acronym`.

https://github.com/suttacentral/sc-data/blob/383dc90d3920c34256fc4ae60940aed9bc741f9b/structure/README.md?plain=1#L20

**Comment by ihongda** [comment]
@renaldoaluska Thanks for the suggestion, I'll check it out and see how to do it. 🙏🏼

**Comment by ihongda** [comment]
@renaldoaluska Hi, I have made corresponding improvements and published them on the staging server. You can try it out.

https://staging.suttacentral.net/?lang=en?v=20240109

**Comment by renaldoaluska** [comment]
hi, thanks for the response. 

for consistency, on Saṁyuttanikāya (https://staging.suttacentral.net/pitaka/sutta/linked/sn?lang=en), I think just "SN 1-11", "SN 12-21", etc. is enough. it will go better with the flow.

flow 1:
<img width="478" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/a7704fb2-9bb5-476c-952f-0f751a4c405b">

flow 2:
<img width="478" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/2c34c6a9-c1ea-4035-b3f0-df25967982f0">

flow 3:
<img width="478" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/11e3b8ce-1989-41cc-bba7-f163c2af66fe">

flow 4:
<img width="478" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/d242c81a-337a-454f-8df4-04f77cc97f67">

today, I also notice that it can also be applied to the Khuddakanikāya 😄 

- Itivuttaka (https://staging.suttacentral.net/pitaka/sutta/minor/kn/iti?lang=en)
- Vimānavatthu (https://staging.suttacentral.net/pitaka/sutta/minor/kn/vv?lang=en)
- Cariyāpiṭaka (https://staging.suttacentral.net/pitaka/sutta/minor/kn/cp?lang=en)
- Netti (https://staging.suttacentral.net/pitaka/sutta/minor/kn/ne?lang=en)

thanks so much!!

**Comment by renaldoaluska** [comment]
umm.. this one is kind of unrelated but... i also notice that there's an existing responsive issue; probably related to the span.acronym.

<img width="478" alt="image" src="https://github.com/suttacentral/suttacentral/assets/21968935/55ce55fe-6131-4d3e-828d-63768f2dd51d"/>

**Comment by thesunshade** [comment]
It looks like the original issue has been resolved.

If you are still having the responsiveness problem, could you create a new issue?

Thanks @renaldoaluska !

**Comment by renaldoaluska** [comment]
it still isn't resolved for  itivuttaka, vimana, and netti. but sure thanks!! about the responsiveness issue, i'll look forward to it.

**Comment by thesunshade** [comment]
Oh, sorry. I see now that this is resolved for some of the levels but not all. 

Thanks for your comment. I will reopen!

**Comment by ihongda** [comment]
Thanks @renaldoaluska @thesunshade 
I will reorganize it today.

**Comment by ihongda** [comment]
Hey @renaldoaluska 
I have modified the relevant files and pushed them to staging

https://staging.suttacentral.net/pitaka/sutta/linked/sn?lang=en&v=20240226
https://staging.suttacentral.net/pitaka/sutta/minor/kn/ne?lang=en&v=20240226
https://staging.suttacentral.net/pitaka/sutta/minor/kn/vv?lang=en&v=20240226
https://staging.suttacentral.net/pitaka/sutta/minor/kn/cp?lang=en&v=20240226
https://staging.suttacentral.net/pitaka/sutta/minor/kn/iti?lang=en&v=20240226

**Comment by thesunshade** [comment]
@renaldoaluska, you may need to do a hard refresh to see the update.

@ihongda this looks great to me. It's a small detail, but it's really useful, especially to people less familiar with the suttas. Thank you!

**Comment by ihongda** [comment]
> umm.. this one is kind of unrelated but... i also notice that there's an existing responsive issue; probably related to the span.acronym.
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/21968935/296426938-55ce55fe-6131-4d3e-828d-63768f2dd51d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTM3MTYsIm5iZiI6MTcwOTAxMzQxNiwicGF0aCI6Ii8yMTk2ODkzNS8yOTY0MjY5MzgtNTVjZTU1ZmUtNjEzMS00ZDNlLTgyOGQtNjM3NjhmMmRkNTFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1NTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NGZhMTQ3Yzc5NjMzZWM0MTAyYzc3ZDg5NmU1MjA0OGQyMzBiNDhjMGI3ZGZlODIzMDA5ODdjMjBkYjlmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbFMX72WbYnPDh93oVehZrg2rKwZZ_tCk1DtgHmcQ8E">

This problem has also been fixed 🙏🏼 

![screenshot_2024-02-27_14-56-12](https://github.com/suttacentral/suttacentral/assets/4037966/55ab002b-bae8-4486-9586-91990f8c88fb)

**Comment by thesunshade** [comment]
Thank you @renaldoaluska for bringing up these two issues. And thank you to HongDa for fixing them!
