### ISSUE TITLE
Filters should be possible at any place in search string

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2932]
Currently, filters are only parsed when they appear at the beginning of a search string.

## User Story

Say someone does a search for `meditation`. Of course they get too many results, so they think, "Hmm, why don't I limit my search to the Samyutta Nikaya."

So they add `in:sn` to the end of their search string to get `meditation in:sn`. It's normal to add things to the end when something is already in the search field, but also one may have the natural language thought, "I want to look for all occurances of the word `meditation in:sn`". However they get no results because it should have been entered as `in:sn meditation`.

## Expected behaviour

Filters should be parsed no matter where they exist in the search string. This also includes `author` filters. For example, `in:dn meditation author:sujato` fails but `in:dn author:sujato meditation` does not.

**Comment by thesunshade** [comment]
https://github.com/suttacentral/suttacentral/issues/2623 may also relate to this.

**Comment by mtnadi** [comment]
I've got it working https://github.com/mtnadi/suttacentral/tree/nadi-issue-2932, however before I open a PR, it only handles `in:` and `author:`.  I ran `make test-server` fine.

Do we want it to do more first?  Are there other tests to run?

**Comment by thesunshade** [comment]
Oh wow! Thanks.

The `volpage` and `ref` don't need to be combined with anything else. I don't have much experience using `title`.

I think that `in` and `author` are the only ones that really need it.

**Comment by mtnadi** [comment]
Okay, that's good (for now!) as `title` seems to have more issues around it...!  Shall open PR for now.

**Comment by thesunshade** [comment]
This is working live on the site now. 

Thanks so much for this!!!
