### ISSUE TITLE
Add `for:` filter to search— body, title, note

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2967]
#### User story
Larry remembers reading something about the chronology of texts in a footnote and wants to search for it. He adds `for:note` to his search and it looks for his keyword in all footnotes.

Samadhī wants to look for titles that contain "love" and "benefit". She searches for `for:title love AND benefit` and it looks for titles that contain the words  "love" and "benefit"

#### Feature description

A new filter type would be added, `for:`. It would have the following three options:

* `for:body`
* `for:title`
* `for:note`

Currently the `title:` filter seems to work with only a single keyword, so Samadhī would be out of luck.

I think that the default search should be for only body and title.

It appears that currently search does not support searching in footnotes. I tested this by searching for "chronology" in English texts. There is a footnote in DN1 that contains this word, but nothing was returned.

The `for:note` could be used for people trying to search for variants in the manuscripts as well

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by khemarato** [comment]
Hmmm  The syntax other search engines usually use for this is more like `title:"Honey Ball"` This is already how other fields on SC (such as author, language, etc) are searched and it allows for combining different fields in one query

**Comment by thesunshade** [comment]
> This is already how other fields on SC (such as author, language, etc) are searched

Really? `author:"sujato suddhaso" moat` gives me no results.

https://suttacentral.net/search?query=author:%22sujato%20suddhaso%22%20moat

Also, we have discussed using quote marks to indicate a literal string.

**Comment by khemarato** [comment]
Yeah, quotes don't work right now (which I'd consider a separate bug) but `author:sujato moat` currently does what you'd expect. Point being, if you're searching within a particular field, it should be `field:value` not `for:field value` which is ambiguous / harder to parse

**Comment by thesunshade** [comment]
Well, they are different, though. `author` only has a set number of values. And each document only has a single author. So any list of authors is necessarily going to be `OR`. 

But within the current `title:` filter, one would presume that they any keywords in something like `title:"value1 value2"` is going to be `AND`.

But elsewhere we are talking about things in quotation marks being literal strings. So I don't think it's good to have quotation marks indicate literal strings in one case and a list of `AND`ed values somewhere else.

One advantage of having `title:"vlaue1 value2"` is that you could use it in combination with `body:"value3 value4"`. But honestly that seems like overkill. That's why I liked the method of determining what part of a document the whole search applied to.

Can you suggest method for `title:` that avoided using quotation marks?

**Comment by khemarato** [comment]
Yes `title:"Ways of Developing"` should be a literal string because it's in quotes. I agree. For Anding, use ANDs: `title:root AND title:arguments` no?

**Comment by thesunshade** [comment]
OK, that makes sense. However I believe we are leaning towards all unquoted things being `AND`ed. So shouldn't it be `title:root title:arguments`?

But at this point it's not possible to use identical filters with different values.

In https://github.com/suttacentral/suttacentral/issues/2969 I'm trying to work out a way to string values together. But for `in:` and `author:` this is going to need to be an `OR`.

BTW, what do folks think about these upper case operators? I find them impractical. I'm assuming "and" "or" and "not" are generally ignored in searches? Maybe not "not".

I swear I'm not trying to make things more complicated than they need to be. And of course I don't want them to be either.

**Comment by khemarato** [comment]
Yeah, on that larger point, typically sites will develop a sophisticated query language and then build [an interface on top of it](https://www.google.com/advanced_search) that does the query building for the medium-savvy users who want those features but can't remember the syntax

**Comment by thesunshade** [comment]
I'm going to close this as unplanned. Hopefully someone else will come up with a better solution to the problem.
