### ISSUE TITLE
Change `author:` fiter to `by:`

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2970]
With this I'm not proposing any functional change. I think it would be beneficial for a few reasons:

* It's easier for everyone to type
* It's easier for non-English speakers
* It takes up less space in the urls.
* Authorship is kind of an odd thing with EBTs. Using `by` would fit the English phrase of "translations by so and so" as well as "manuscripts created by such and such organization"

**Comment by thesunshade** [comment]
This does create a small problem with the command `list authors`. 

My idea is that the `list` command should be available for all filters and the parameter should always be the exact text of the filter. For example
```
list by
list in
list for
```

**Comment by khemarato** [comment]
There should be an overlap period where both are supported for a while before deprecating `author`  Agreed that a warning would be nice during that period, informing people about the change

**Comment by thesunshade** [comment]
I guess my thought is that it's still early enough in the life of the new search that there may not be a lot of people using the author filter. So supporting both makes the code more complicated (I'm assuming) and that just has to be uncoded later. Since I hope we will have error reporting anyway, I thought that would be a simpler solution.

**Comment by ihongda** [comment]
The relevant changes have been pushed to Production.
