### ISSUE TITLE
In legacy texts, spans prevent finding literal strings that include spans.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2990]
#### Description:

If a text html includes span tags, they will prevent search from finding literal strings that "span" the span. For example a search for `precipitation in a womb` (because at the moment this is a literal string search) returns nothing.

If you just search for `precipitation` You will get Bhikkhu Bodhi's [translation of MN9](https://suttacentral.net/mn9/en/bodhi). The reason is the span tags I believe:

```
The birth of beings in the various orders of beings, their coming to birth, 
precipitation <span class="add">in a womb</span>, generation, 
manifestation of the aggregates, obtaining the bases for contact—
this is called birth.
```

**However...** If you search for `in:mn womb` you get no results for MN9. So maybe the text in the `add` class is not being searched at all?

**Comment by thesunshade** [comment]
So I found in `Collection: text_contents > Document: 4100946` That in `content` the spans and their contents have been stripped out. So if that is what search is using, then it explains the behaviour.

@ihongda Do you think this is the cause of the problem? Is it possible to strip the html of the span but not the content?

**Comment by ihongda** [comment]
Bhante @thesunshade Let me check :)

**Comment by ihongda** [comment]
The content contained in <span class='add'></span> is excluded during indexing. I browsed some text contained in .add, most of which are similar to notes. @thesunshade

**Comment by thesunshade** [comment]
> most of which are similar to notes.

This really depends on the translator/translation. Unfortunately the `add` class refers to anything at all not strictly included in the root manuscript including headings. In the Japanese legacy texts the translator has made extensive use of both text added to make the sentence sound natural (which is the way `add` is used in the Bhante Bodhi texts) *as well as* to add things we would normally consider notes. 

It's kind of a mess, since text added to make the sentence sound natural probably should have never been marked up in the first place. Bilara doesn't even allow for this. And *that kind of text* should definitely be indexed. However the note type text probably should not. 

I'll close this for now, but perhaps Bhante @sujato has some thoughts.
