### ISSUE TITLE
Author name link in License on bilara translations info take you to the home page.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2995]
#### Description:
Author name link in License on bilara translations info take you to the home page.

#### Steps to reproduce:

* Go to https://suttacentral.net/dn1/en/sujato
* Click on the (i) dot.
* Click on the link `Bhikkhu Sujato` in the License area

You are taken to the home page

#### Expected behaviour:

I would have expected to be sent to some author page for Bhante Sujato. But as is it seems like a bug.

#### Screenshots:

Here's the link I'm talking about. 

![image](https://github.com/suttacentral/suttacentral/assets/82448383/45a16f20-9986-48ca-ae82-2eef336b5624)

**Comment by thesunshade** [comment]
OK, so this is hard coded into the localization file. Strange:

```
  "publication:licenseDescription": "To the extent possible under law, <a rel='dct:publisher' href='https://suttacentral.net/'><span property='dct:title'>{authorName}</span></a> has waived all copyright and related or neighboring rights to <cite property='dct:title'>{translationTitle}</cite>. This work is published from <span property='vcard:Country' datatype='dct:ISO3166' content='AU' about='https://suttacentral.net/licensing'>Australia</span>.",
```

I may just make a pr and remove all of those. Unless there is a real plan to add in a variable that would link it to an author page. But since I don't think author pages exist and it will have to be redone anyway, I may just do.

https://github.com/suttacentral/bilara-data/blob/64163779edfbafe8b868196756965b3674064413/root/en/site/publication_root-en-site.json#L22

**Comment by ccronje** [comment]
There seem to be plans for adding bios:
https://github.com/suttacentral/suttacentral/issues/2356
https://github.com/suttacentral/suttacentral/issues/2467

**Comment by thesunshade** [comment]
My thinking was that the files I modified will eventually have to be modified again (even without my PR) in order to build a link to the bio pages. So in the mean time my fix would stop unexpected behaviour.

I fully understand it's a very minor problem. It just happened to be a minor problem that I thought I could fix, lol.

I think I'm going to close my issue, https://github.com/suttacentral/suttacentral/issues/2467 since it's really a duplicate of Bhantes. 

Thanks!

**Comment by thesunshade** [comment]
Done!
