### ISSUE TITLE
Some search excerpts are out of order on database SERP page

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2996]
#### Description:
If more than one excerpt is shown for a search result, one would expect them to be shown in the same order they are in the text itself. However sometimes they aren't. It's not a big problem, but it's odd.

#### Steps to reproduce:

* Search for `in:sn feelings` https://staging.suttacentral.net/search?query=author:sujato%20in:sn%20feelings

If you look down the list you will find *some* excerpts that are out of order. E.g. 

![Image](https://github.com/suttacentral/suttacentral/assets/82448383/f31254be-077e-4661-9ab0-883630b3764f)

![Image](https://github.com/suttacentral/suttacentral/assets/82448383/8dd716a8-906b-449a-91eb-b9520e1758cb)

#### Expected behaviour:

Excerpts should always be sorted in the order they appear in the text.

**Comment by thesunshade** [comment]
There is still a small glitch, @ihongda.

https://suttacentral.net/search?query=author:sujato%20in:sn%20feelings

![image](https://github.com/suttacentral/suttacentral/assets/82448383/8524beda-a79e-4f60-8130-2dd895ea638e)

Of course this is very minor, but if you think it can be fixed, perhaps you could take a look.

**Comment by thesunshade** [comment]
Also
https://suttacentral.net/search?query=in:vinaya%20author:brahmali%20feeling

![image](https://github.com/suttacentral/suttacentral/assets/82448383/13bc9f38-e800-47c3-89fd-6db632e84757)

**Comment by ihongda** [comment]
This is an interesting question. Mathematically, 1.12 is smaller than 1.5, but in the `sc` segmented number, 1.5 is smaller than 1.12. I need to adjust the corresponding code.

**Comment by thesunshade** [comment]
Ooooh. It's obvious now that you point it out. I was thinking maybe it was just sorting strictly by alphanumeric order.

**Comment by thesunshade** [comment]
Fixed! Thanks so much
