### ISSUE TITLE
Issues with some Myanmar(Burmese) menu text displays

### ISSUE THREAD

**Issue by amaung** [suttacentral/suttacentral#2999]
#### Description:
Myanmar words are wider and taller compare to Roman letters and some menu items are not displayed nicely. This problem happens in quite a few places. Some section titles appear to be much bigger than the text in the paragraph. Smaller font size, wider textbox, with shorter text should solve the problems.

#### Steps to reproduce:

*set your site language to `my`*

https://suttacentral.net/dn?view=dense&lang=my (top of the texts for "spacing" and "table" are touching the icons)

https://suttacentral.net/dn1/my/pmt?lang=my&reference=none&highlight=false (text for "contents", "info", "views", "parallels" are overlapping with the icons)

https://suttacentral.net/offline?lang=my (to show the issue with the title text with large font size compare the paragraph text)

* [include links were possible]

#### Expected behaviour:
Myanmar texts tend to be longer compare to the same Eng text. I think smaller font size with wider textbox and with shortened Myanmar text (still need to work on it) should have the texts displayed nicely.

#### Screenshots:
![image](https://github.com/suttacentral/suttacentral/assets/60203873/27211f0f-11dc-401c-8306-e3768c531b25)
![image](https://github.com/suttacentral/suttacentral/assets/60203873/02f71bfa-d43e-402e-8c7a-603de5801396)
![image](https://github.com/suttacentral/suttacentral/assets/60203873/9b5c8361-0957-4722-bf1d-8505a7367408)

**Comment by thesunshade** [comment]
Thank you so much for posting this. I happened to find what looks like a language specific CSS file called `sc-typography-i18n-styles.js` but I'm not sure how to do anything there that would help.

**Comment by amaung** [comment]
Let me also look into the "sc-typography-i18n-styles.js" file.

**Comment by amaung** [comment]
Can you point me to where that file is?

**Comment by thesunshade** [comment]
Sorry. It's here: https://github.com/suttacentral/suttacentral/blob/master/client/elements/styles/sc-typography-i18n-styles.js

BTW, Github has a great search for finding files:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/716bb24a-cc38-4349-b1ad-6f248471bda1)

**Comment by ihongda** [comment]
Hi @amaung 
I made some changes and when the language is Myanmar(Burmese) the button text is fixed at 6px, they look like this:
![image](https://github.com/suttacentral/suttacentral/assets/4037966/db50a62f-0b6e-4113-a548-fd3014e247b9)

This looks smaller, but if it is adjusted to 8px, the text of some buttons will cover the icon.

**Comment by thesunshade** [comment]
I'm seeing overlap on the TOC icon, but perhaps that is unavoidable with the label being that long.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/cecd5697-2bbd-4d08-8d78-9666ebc48704)

**Comment by amaung** [comment]
Hi,
Thank you so much for fixing the problem. It now looks good except for the long text you mentioned. I will reduce the text. It is hard to do direct translation from English and in a short text.
I am not sure I entered about another issue in Github. Some of the heading texts are oversized compare to the body text. Although it is not a major problem it will be nice to see the Burmese header text font size reduced. The following is for Using SuttaCentreal offline page.




Regards,
-Auz Maung    On Tuesday, April 9, 2024 at 03:09:21 PM PDT, thesunshade ***@***.***> wrote:  
 
 


I'm seeing overlap on the TOC icon, but perhaps that is unavoidable with the label being that long.

image.png (view on web)

**Comment by thesunshade** [comment]
> Although it is not a major problem it will be nice to see the Burmese header text font size reduced.

I think since you replied by email your image was not posted.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/b33c80fc-9846-4645-b601-e52b473adf53)

I think this is really a matter of aestetics. You can see that the Myanmar letters do match with the English letters in the heading. In general all the h1 level headings on SuttaCentral are quite large. In the case of  mixed alphabets like this I don't think we  would want the Myanmar letters smaller than the English letters.

**Comment by amaung** [comment]
Since it is not an error, it will be fine to keep it as is.
