### ISSUE TITLE
Headings need `word-break: break-word` to prevent forced wide pages

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3004]
#### Description:

Some title text is so large that it won't fit on a small screen. Instead of the words breaking and wrapping (or even getting a horizontal scroll bar) they keep their full width and force left justified text off the screen, etc.

All that is necessary is `word-break: break-word`.

Of course having soft hyphens in all of these long titles would be ideal. But for now it is impossible to read these pages on mobile and this change would fix that for now.

#### Steps to reproduce:

* https://suttacentral.net/tha-ap392/pli/ms?lang=en&layout=sidebyside&reference=none&notes=asterisk&highlight=false&script=latin#msdiv67

![image](https://github.com/suttacentral/suttacentral/assets/82448383/8da77c42-72d0-4deb-b3cf-f10a294699dd)

#### Expected behaviour:
Titles should break and wrap:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/3a28a577-e7d3-451d-856d-d5daabe11e14)

**Comment by thesunshade** [comment]
@buddhist-uni, Have you never run into this? I know you use mobile a lot.

**Comment by khemarato** [comment]
Yes  Not very often but sometimes 😁
