### ISSUE TITLE
Instant search is no longer instant enough

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3011]
#### Description:
This is all from Bhante Sujato:

> 
> 1) One thing I am noticing, the instant search is no longer instant. Like, I type in mn1 I should get a list of all suttas with that in them before I type the next number, then it should filter down.
> 
> It used to do this, but now I type in mn1, nothing happens, I then type the next number mn18 and it waits a second then shows me results. It’s not a cache or network thing, it happens persistently. I literally type the ID, then count “one thousand and one” and then the results appear. It’s too slow, it should be an imperceptible lag, that’s why it’s called “instant”.
> 
> Not sure why this is so, but we need to fix it. My guess would be that either a bug has crept in or that complexity or too much data is causing the delay. If the latter, then we should focus on getting the relevant results instantly and lazy-loading other things.
> 
> Is anyone else having the same problem?
> 
> 2) Relatedly, when the results do appear, the overlay janks: this is a CSS bug. It needs to define the absolute height of elements first so they don’t create jank when appearing.
>

**Comment by ihongda** [comment]
There was an improvement before, because generally speaking, it is meaningless to search for only two English letters, so the current practice is to search only for 3 letters or more.
@sujato @thesunshade 


Fixing this problem is easy, just delete a few lines of code.
