### ISSUE TITLE
Chapters should not return in title results because they are not texts

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3020]
#### Description:

Chapter titles are being matched in database search but they have no text. You can't do anything with them or go to the chapter even.

#### Steps to reproduce:

* Search [`greed`](https://suttacentral.net/search?query=greed)

Notice the title cards on the right. It appears that they are untranslated. It also appears that there is no manuscript. The only way to get to that chapter is by clicking on the share button and then copy pasting the link into a new tab.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/7aafb795-866f-4062-bd9c-32da874debb0)

I can see the utility of including Samyutta top level chapters in results. however they have to be clickable in some way. 

* [`unknowable`](https://suttacentral.net/search?query=unknowable)

![image](https://github.com/suttacentral/suttacentral/assets/82448383/68c8f97d-b3c7-40bb-997d-5f8fe9b55569)

But it's still not clickable.

For all other books, the chapter results are kind of useless since many chapter titles are meaninglesss (like numbers in An or Thig/Thag) or they are simply the name of the first sutta in the chapter.

**Comment by thesunshade** [comment]
@buddhist-uni and @sabbamitta, I'm always curious to hear your thoughts.

**Comment by sabbamitta** [comment]
>It appears that they are untranslated.

I am not sure what these cards on your pictures represent. They seem to show suttas from the AN tens, elevens, and twos, but all suttas of these books are translated into English; there are no untranslated texts.

Also, the IDs look strange to me. It says `AN 10-10` which is no valid ID anywhere, and similarly for the others.

**Comment by thesunshade** [comment]
> I am not sure what these cards on your pictures represent

If you click on the share button on the first card and copy the link, you get https://suttacentral.net/an10-ragapeyyala. If you go there you will see it is a whole chapter.

**Comment by sabbamitta** [comment]
Hmm, interesting, I didn't know I can have chapter pages like this. (And all these suttas are translated into English.)

But in this case the ID `AN 10-10` is even more misleading. It suggests (to me) it may have something to do with `AN10.10`, but it's in fact `AN10.237-746`.

And, btw, when I type "greed" in the search field, I see totally different results in the right column altogether.

**Comment by sabbamitta** [comment]
![Screenshot from 2024-02-21 20-27-42](https://github.com/suttacentral/suttacentral/assets/43345786/bc02afd7-914f-4938-a880-d6eef41eceaf)

**Comment by sabbamitta** [comment]
Only two results in the right column.

**Comment by thesunshade** [comment]
> I see totally different results in the right column altogether.

Yeah, this is a strange one. It's unrelated to this issue. [There is a bug](https://github.com/suttacentral/suttacentral/issues/2985) that always searches titles as partial matches. Those two at the top of your title results are because there is a partial match. They are in the English results as well, at the very bottom.
![image](https://github.com/suttacentral/suttacentral/assets/82448383/e9332a1c-6991-4071-9d69-6e01ec76780f)

**Comment by thesunshade** [comment]
@sabbamitta, If you search [`Gier`](https://suttacentral.net/search?query=Gier) you get something similar to what I got in English.

**Comment by sabbamitta** [comment]
Indeed, I do. But I don't understand why searching for "greed" doesn't give me similar results. English is included in my search languages just as German. Why are they treated differently? When I do use SC search, I might just as likely search for English terms than for German; or French or other languages I do understand (the latter ones perhaps not *quite* as likely).

(Probably not relevant to this particular issue, though.)

**Comment by thesunshade** [comment]
> (Probably not relevant to this particular issue, though.)

It's not from what I can tell. I was also surprised to see that different results were returned. I will bring it up with Hongda.

**Comment by thesunshade** [comment]
Done by @hongda!
