### ISSUE TITLE
Document Language list does not update on SERP when settings change

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3029]
#### Description:

When viewing the SERP you can see a list of the document languages that will be included in the search. However when you change these options using the language button/overlay, the list does not change.

![2024-02-24 08_04_59-401 results for cat search_inSelectedLanguage — Mozilla Firefox](https://github.com/suttacentral/suttacentral/assets/82448383/c7209247-df07-41fb-84a3-3982fa486623)

#### Steps to reproduce:

* Run a search, eg [`cat`](https://suttacentral.net/search?query=cat)
* Click on the document languages button
* Select a new language
* Click on the document languages button to close the overlay
* The language list under the input field is unchanged. If you trigger another search, then the new language will be included and will then appear in the list.

#### Expected behaviour:

Changing the document languages should change the list of included document languages immediately under the search input box.

**Comment by thesunshade** [comment]
This is not working in some cases. For example if you 

1. click on the search icon at the top of any page.
1. Then click on the globe icon to change the document languages.
1. Then change the document language.
1. Then click on the search icon at the very top of the page.

Original document language is still shown.

https://github.com/suttacentral/suttacentral/assets/82448383/faa09dc7-1892-4b0c-941b-103836d31807

**Comment by ihongda** [comment]
Bhante, I have fixed this bug and pushed it to `Staging`. @thesunshade

**Comment by thesunshade** [comment]
Thanks! It looks like it is working now.
