### ISSUE TITLE
Add a search button to the input field on SERP

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3030]
#### User story

Clarence is a very mouse oriented user. He is looking at a SERP and types in a new term. The search icon/button that was in the instant search is no longer there and he is unsure how to trigger a new search. 

#### Feature description

Add a search button to the input field that allows a user to trigger a new search (like there is on the instant search)

This would also solve https://github.com/suttacentral/suttacentral/issues/2954 where it is impossible currently to trigger a new search when document language settings are changed.

Here is a proposed mockup from https://github.com/suttacentral/suttacentral/issues/3028:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/b8059240-78f6-4b1f-8daf-8fcfb690e54c)

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

- [ ] https://github.com/suttacentral/suttacentral/issues/3028 should probably be done first so that there isn't double work in the design
- [ ] The new icon should work in dark theme as well

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by khemarato** [comment]
I agree, there should definitely be a button for clicky people :)

**Comment by thesunshade** [comment]
I am closing https://github.com/suttacentral/suttacentral/issues/2954 because if this issue is implemented, then that issue is moot. However you may still want to check it out.

**Comment by thesunshade** [comment]
On my local install, there is a problem with this.

An ongoing issue is that if the user changes their document search languages it is impossible to trigger a new search by typing enter. I thought that having a search button would fix that. 

### To reproduce
* search for boat
* now click on the languages overlay and add and or remove some languages.
* close the overlay
* click the new search button

For me, nothing happens. I also cannot hit enter and trigger a new search. Do you know why that is? Is it some kind of protection to prevent the user from triggering thousands of searches in case their enter key gets stuck?

**Comment by thesunshade** [comment]
Looks like this is working now so i will close.

Thanks!
