### ISSUE TITLE
`volpage:` search is returning lots of wrong and unnecessary results

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3032]
When a user searches for `volpage:DN ii 4` there is only a *single link to this* in the entire canon. However now it is returning hundreds of links that are completely wrong. For example, [` volpage:DN ii 4`](https://suttacentral.net/search?query=volpage:DN%20ii%204) gives this:

![Image](https://github.com/suttacentral/suttacentral/assets/82448383/2eb157a4-c0f3-45db-899d-c6fefa8ff96a)

I can see absolutely no reason at all to be returning:

* results not in the Digha Nikaya
* more than the link directly before or after the actual link the person searched for, if even that.

I don't understand why when the user searches for an actual reference why they are getting all these wrong ones. Basically it appears that it is returning everything matching just `ii 4` in every single collection and additionally *all* the references in whatever text the real match is found.

**Comment by thesunshade** [comment]
Here is another example. Ud comes in a single volume. Here is a search: https://suttacentral.net/search?query=volpage:ud%2059

And here are the results:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/7e42fb52-eb15-432b-aac3-f8e8c528f472)

It's strange for many reasons:
* Ud 5.9 and Ud 5.10 are duplicated and they give no clickable references. 
* In the row 

|Ud 5.6 | With Soṇa | PTS Ud 57 | pts-vp-pli57, pts-vp-pli58, pts-vp-pli59,|
|-- | -- | -- | --|

What is going on? I just want a way to get to exactly where I want to go, which is PTS Ud 59. But the only way I get there is if I recognize that I should click on `pts-vp-pli59`

**Comment by ihongda** [comment]
![screenshot_2024-02-28_09-52-48](https://github.com/suttacentral/suttacentral/assets/4037966/62e4395d-3165-4ee7-bad8-941aa1acad33)

**Comment by thesunshade** [comment]
Great! I think that is good enough for now.

Thanks
