### ISSUE TITLE
Instant search should be prioritizing actual matches over typo suggestions

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3033]
#### Description:

DISCLAIMER: I have never liked the algolia typo match feature. If it were up to me it would be removed. Or at the very least it should only give typo suggested results if there are no actual results.

Currently there is no priority given to actual matches of search terms over typo suggestions. So for example in instant search for `moats` The first result is `goats`, the second is `moats` and the third and fourth is `mats`. 

#### Steps to reproduce:

* Search for `moats` in instant search

![2024-02-25 15_27_34-](https://github.com/suttacentral/suttacentral/assets/82448383/dbf68b60-0da5-4944-bd72-7440b5b64a96)

#### Expected behaviour:

- If there are actual matches they should always be returned before any typo-matches.
- Consider not returning typo-matches if there is a real match since it would be clear to the user they have made a typo because the results they are getting would clearly not be what they are expecting.

I believe in Google, typo suggestions are made very explicitly and rarely when the user searches for a real word. I don't know if this is possible.

**Comment by ihongda** [comment]
This is not a problem with Algolia, but when sorting, I sorted the name type data at the front and the text content at the back. I have turned off this sorting rule.
