### ISSUE TITLE
Currency drop down on form on donate-now page drops up and hides behind header

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3044]
#### Description:

On FireFox Currency dropdown on form on donate-now page drops up and hides behind header. On Edge and Chrome it also drops up, but it stays above header.

#### Steps to reproduce:

* open FireFox
* go to https://suttacentral.net/donate-now
* Click on currency drop down

![image](https://github.com/suttacentral/suttacentral/assets/82448383/7555b958-7b64-4be1-bb9a-e05231002c81)

This is what it looks like on Chrome. Not hidden.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/821e924f-a221-4bf4-ba48-0c8e19e718e8)

I realize that you usually only want to support Chrome, but since this is a donation page I thought you might be more concerned.

**Comment by thesunshade** [comment]
@ihongda I just noticed that now the currency dropdown is no longer attached to its place in the form:


https://github.com/suttacentral/suttacentral/assets/82448383/2d10e911-b858-41c1-821c-0e269a93e6ad

**Comment by ihongda** [comment]
Confirm that the problem exists in firefox.

**Comment by thesunshade** [comment]
Now in Firefox the dropdown is not hidden behind other elements.

The detaching behaviour is only in Firefox.

**Comment by ihongda** [comment]
@thesunshade  Bhante, I have upgraded the Material design components to latest version , this problem seem to be fixed.

I'll close this issue first, if this problem still exists, please reopen it 🙏🏼
