### ISSUE TITLE
make UI for using Dictionaries more directly?

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3049]
This idea was given in https://github.com/suttacentral/suttacentral/issues/2383.

I'm not sure what Bhante had in mind. Currently dictionary results come up in an ordinary search. They take you to a dedication definition page, e.g. https://suttacentral.net/define/dhamma?lang=en

It makes sense that if someone is just looking up words then it would be nice for them to not have to go through the main search page every time to get to the full definition page.

**Comment by sujato** [comment]
Yes, I didn't have a really clear goal in mind.

But again, I think this is basically rendered irrelevant by the DPD. Better to let a specialist website handle it. What we could do is give more prominence to them. I discussed this with Ven Bodhirasa, and he agreed that they need proper URLs for  queries, which they now have!

https://dpdict.net/?q=dhamma

Let me make a new issue for this and tag you in on it.
