### ISSUE TITLE
pull in results from CPD? (http://pali.hum.ku.dk/cpd/search.html)

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3050]
This idea was given in https://github.com/suttacentral/suttacentral/issues/2383.

I'm not sure what Bhante had in mind for this, so I can't write more.

**Comment by sujato** [comment]
Thanks for re-upping, but basically I was just wondering whether we could use the CPD data to complement our dictionaries. But now with DPD it's not necessary. 

In fact if I were to contemplate a change—which I'm not, but if I were—it'd be to get rid of other Pali dictionaries and just use DPD. Ultimately, SC is not a dictionary site, they are just a complement for the main content. But anyway, for now we can keep them.
