### ISSUE TITLE
Highlighted Pali search keywords are missing diacritics on the full database search result page

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3077]
#### Description:
Highlighted Pali search keywords are missing diacritics on the full database search result page

#### Steps to reproduce:

* With `Pali` as a document language selected
* Search for `rupa`

#### Expected behaviour:

Highlighted search keywords should have the actual Pali diacritics. Instead they are stripped out:
![560d6b8c0bc3fb0522e5ce30a610c10e62d7c82d](https://github.com/suttacentral/suttacentral/assets/82448383/f418e63a-0f06-4e24-8da9-4d6346152870)

Dictionary results are highlighted correctly.

This is **not** a problem in the Algolia search: 
![image](https://github.com/suttacentral/suttacentral/assets/82448383/acc925ef-d646-416d-a1b4-89e0f994a694)

**Comment by thesunshade** [comment]
Might be related to https://github.com/suttacentral/suttacentral/issues/2975

**Comment by ihongda** [comment]
Hey @thesunshade @buddhist-uni 
Is there any relevant Python library that can handle this problem? For example, if you enter `rupe`, you can get a list of possible Pali words, such as `rūpe`.

I currently normalized the keywords and content before searching, but this will cause the problem pointed out in this issue.

**Comment by thesunshade** [comment]
Oh… Now I see what is happening. I'm so blind that I didn't notice that *all* the Pali diacritics have been stripped out of the excerpts shown on the SERP page, not just those of the matching search term. That's not good. We should never be showing that normalized source text to users.

For the purposes of searching, yes, the content should be normalized (I think). However for the purpose of displaying excerpts, we should be showing the actual excerpt text, not a normalized version. I rarely do Pali searches so I never noticed what was happening. 

I don't think the solution is to have access to a list of real Pali words that would match a normalized keyword. Instead the search can work the way it does now, but instead of showing normalized result excerpts, it needs to show the actual segments. Then there just needs to be a way to insert the highlighting based on the normalized text, but done on the real text.

@buddhist-uni ?

**Comment by ihongda** [comment]
The original search results have diacritics, but when the user enters a word without diacritics, the relevant results with diacritics can be searched in arangosearch, but when processing the highlighting, python The search itself does not seem to support such a search method, that is, searching for `rupa`, `rūpa` cannot be matched. I'm making some changes to see if that solves the problem.

**Comment by ihongda** [comment]
I'm trying Arangosearch's highlighting feature, hoping it can solve this problem.

**Comment by thesunshade** [comment]
Looks like this is working now. Thanks!!
