### ISSUE TITLE
If no document languages are selected, then explicitly search in all documents

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3110]
#### Description:

Currently when no document languages are selected, there is no indication this is the case, and the scope of the search results are unclear.

#### Steps to reproduce:

* uncheck all languages in the search languages options page
* search for "moat"

There is no indication of what document languages are being searched:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/7f5285b3-5fc3-4436-841e-44b404e480ed)

#### Expected behaviour:

There should be some indicator that all document languages are being searched. Such as:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/22bd5dc5-7703-4c81-ba68-8c638e7012cd)

*_However:_* Even though all languages are being searched, the actual settings should not change, meaning that all the languages should not get ticked. The logic would be that having no languages ticked is equivalent to all languages being ticked.

**Comment by thesunshade** [comment]
@buddhist-uni per the gitter discussion.

**Comment by thesunshade** [comment]
This is somewhat related to this issue: https://github.com/suttacentral/suttacentral/issues/3111

Also wanted to see if @sabbamitta or @firepick1 had thoughts on either issue.

**Comment by sabbamitta** [comment]
See my comment [here](https://github.com/suttacentral/suttacentral/issues/3111#issuecomment-2033672732).

**Comment by sujato** [comment]
Seems reasonable, is this still outstanding?

**Comment by thesunshade** [comment]
Yes, afaik.

**Comment by ihongda** [comment]
This issue has been fixed and pushed to the production server. 
This issue will be closed.
