### ISSUE TITLE
If there are no search results on SERP, check to see if user's site language and search document language match

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3111]
#### User story

Ven. Khema is searching for "moat". However they have somehow got their search document language set to French. 

Search doesn't know what language "moat" is in, but it does know there are no results in French, and it also knows that Khema's site language is set to English. So instead of just returning no results, it offers some suggestions and a one click option to add Khema's site language to the search document languages and re-run the search:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/1b4d97dc-377e-42ef-84c3-263616968348)

Clicking on that link would produce this result:
(note that a new language has been added to their settings and the search has been re-run)

![image](https://github.com/suttacentral/suttacentral/assets/82448383/f6729da4-515f-43e3-9944-81ccc774ea05)

#### Feature description

If there are no results, check to see if the user's site language is included in the list of search document languages. If it is not, provide a link to add that document language and re-rerun the search.

If there are no results and no root language are selected in the search document languages, then suggest (without a link) to add root languages to the search  document languages.

*Also*, the option to one-click-add root languages could be offered if **no** root languages are already selected. Clicking on one of those links would add the root language to the user's settings and the search would be re-run.
![image](https://github.com/suttacentral/suttacentral/assets/82448383/16d46158-7b32-4199-8b51-658c39523070)

#### There is yet another situation…

Say Ven. Khema suddenly wants to search for some German words, but forgets to add it to their search documents languages. They get this:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/42cc3261-3edd-4423-a6af-ee9afc8fa8ed)

In this case, their site language doesn't help (they are looking for German terms but their site language is English) and they already have at least one root language selected. They could be given an additional suggestion *in general* to add more document languages:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/1aa0d2ec-da87-4a02-a142-6f946fa6e3ba)

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by thesunshade** [comment]
@buddhist-uni , @sabbamitta , @firepick1 per the discussion on gitter.

Did I capture all the situations we discussed? Does it seem useful and/or necessary?

**Comment by sabbamitta** [comment]
Why so complicated? I would suggest the following much simpler solution:
- user should have at least one document language for search ticked
- the default, if they don't actively go to language settings, should be to have the site language selected (this is more useful than having *all* languages selected)
- it is impossible to untick the only selected language without ticking another one
- if a search returns no result, independent of languages selected, along with the message "no result" the user sees a hint "try searching in another language", maybe with a one click option to go to the language selection; this way they are shown that language selection for search is possible, something not everybody would think of naturally, especially users with little internet experience

**Comment by sabbamitta** [comment]
BTW, what does SERP stand for?

**Comment by thesunshade** [comment]
> BTW, what does SERP stand for?

Search Engine Result Page. 

> user should have at least one document language for search ticked
> it is impossible to untick the only selected language without ticking another one

This is very hard to enforce. Currently there are two interfaces for selecting document languages. One is an overlay which you access from being on the SERP. The other is this page: https://suttacentral.net/search-options. For the overlay, you could make it so that you couldn't close it until you selected at least one option. However I don't know how it would be to prevent the closing of the page unless you have at least one ticked.

I don't like the experience of having to have two languages ticked just to be able to untick one. It would require an error message when you tried unchecking the last remaining option. And now the list of languages is so large that just having an error message at the top of the interface wouldn't work.

> the default, if they don't actively go to language settings, should be to have the site language selected (this is more useful than having all languages selected)

I agree completely, however this just deals with default behaviour. Currently the default (meaning the user has never been to the settings) is to select English and all the source languages. I believe we are trying to change that, but there are bugs. In any case, this issue is about time after a "fresh" start up of the site.

I also agree that it's good to keep things simple, however I also like to make things as useful as possible, so it's a balance.

Of course I am very open to all ideas.

**Comment by sabbamitta** [comment]
>>user should have at least one document language for search ticked
    it is impossible to untick the only selected language without ticking another one

>This is very hard to enforce.

Is it? We have it in Voice (the user has to select at least *one* language in which the text is shown, and if they try to untick the last option, this simply doesn't work). Karl didn't seem to find this hard to implement.

>I don't like the experience of having to have two languages ticked just to be able to untick one.

Why would you want to have no language selected? If you want to untick one, this is usually because you want something else, not because you want nothing. :thinking: 

>I agree completely, however this just deals with default behaviour.

I am proposing it because this would make sure that at least one language *is* in fact selected, and if the user searches in another one, they would be prompted that they should have a look at the language selection. However, I can't say anything as to the technical challenges. It seems to be already hard to get the site to open in the user's browser language by default—which to my mind would be by magnitudes more important.

**Comment by thesunshade** [comment]
> Why would you want to have no language selected? If you want to untick one, this is usually because you want something else, not because you want nothing.

True, but if I try to uncheck a language and it won't let me and it doesn't tell me why it won't let me, then that's confusing. If I want to change from German to English, I shouldn't have to select German before I select English. Just my opinion.

Any way, you are really talking about https://github.com/suttacentral/suttacentral/issues/3110 aren't you? I realize they overlap a bit, but the "having no languages selected" falls under that issue.

**Comment by sabbamitta** [comment]
Yes, they do overlap, to me they can't really be separated. Just keep the link to the other issue here, so the connection is visible.

**Comment by sujato** [comment]
Just to check where we are on this, is this still in need of attention?

**Comment by thesunshade** [comment]
It's still not finished, if this is still desired.

**Comment by ihongda** [comment]
This issue has been fixed and pushed to the production server. 
This issue will be closed.
