### ISSUE TITLE
`in:sn` search filter should only list those texts in the selected languages

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3162]
#### Description:

It is possible to use the `in:` filter with no search keywords. For example `in:sn`. This will list all of the suttas in the SN. However, it does not limit the results to just those document languages you have selected. For example:
![2024-05-07 08_13_31-](https://github.com/suttacentral/suttacentral/assets/82448383/e4b889a6-090b-4ebc-b8a3-027dc0b99c13)

It is very similar to the `list authors` problem now fixed https://github.com/suttacentral/suttacentral/issues/2971

#### Steps to reproduce:

* Select English as your document language for the search
* search for `in:sn` with no other keyword

You will then see every single SN text regardless of language

#### Expected behaviour:

When you do a bare search using `in:`, it should only list documents in the chosen languages

**Comment by sujato** [comment]
Yes, this should always be the case, you should never get results outside of your selected languages.
