### ISSUE TITLE
`list` + language code search filter should list all documents in chosen language

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3163]
#### User story

Fatma wants to share a list of all of the Türkçe translations on Sutta Central with their friend. Currently there is no way to do that.

This issue has come up from time to time on the forum.

#### Feature description

Similar to the `list authors` ~and `in:xxx`, `list all` would give a list of all the suttas that matched the user's selected language(s)~ `list` and a language code would list all the texts on SC for that language.

So the search string `list tr` would list all the Turkish texts on the site.

There should be four columns: Sutta ID, Name (which should really be change to "Title"), Author, and Language. This is just like the results for `in:xxx`, e.g [in:kp](https://suttacentral.net/search?query=in:kp)

It's true that the list could be long. But this is also the case with the `in:xxx` and bare `author:sujato` filter. It would really be up to the user to decide if the search is useful for their purpose.

### Multiple languages?
I would say no. If you want multiple languages, so multiple searches.

Related issues: 
* https://github.com/suttacentral/suttacentral/issues/2971
* https://github.com/suttacentral/suttacentral/issues/3162

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by Pinpin123456** [comment]
Dear @thesunshade, thank you for raising this issue. Dear @ihongda, it would be highly beneficial to have a list of the suttas that are translated into spesific language. This will allow users ot easily identify the suttas that are available in their language.

**Comment by sujato** [comment]
Thanks for the suggestion, I agree it's a good idea. 

I'm not sure that `list all` is transparent though. Instead, how about `lang:ko` to list all Korean translations?

**Comment by thesunshade** [comment]
> how about `lang:ko` to list all Korean translations?

That would be better for sharing a search with someone else. However it complicates things a bit.

Usually we depend on the options selected by the user in the overlay to decide what text languages to show. Would you expect `lang:ko` to over-ride the user settings? So basically any time a `lang` filter was in the search string it would search exclusively `ko`? Could you use it in combination with other filters and search terms? 

Could you have multiple languages? `lang:ko AND lang:pli` even if permitted won't give the user texts from Korean and Pali as the normal use of "and" would expect, but instead it would give nothing.

Do you see what I mean? @khemarato, @sabbamitta thoughts?

**Comment by sabbamitta** [comment]
To me, `lang:ko` seems to make more sense than `list all`.

And the reason why `lang:ko AND lang:pli` gives no result, is it because we only have non-Pali texts translated into Korean?

**Comment by thesunshade** [comment]
> And the reason why `lang:ko AND lang:pli` gives no result, is it because we only have non-Pali texts translated into Korean?

No! You have fallen back into the wrong mental model of what language means when it comes to search. Honestly I can never keep it straight in my mind. Texts can only ever have *one language*. A text is never Pali AND German. If you want to return both you would have to search for Pali OR German. 

If you are looking for Pali scriptures translated into German, then you need to select a Pali _collection_ (Which is currently not possible to do completely) and set your language to German.

> To me, lang:ko seems to make more sense than list all.

In isolation I would agree. However until now we haven't let people specify language in the search string, only in the check box settings. I'm not sure how that new filter should interact with the settings. Should it add to the settings or over-ride them?

**Comment by sabbamitta** [comment]
>Should it add to the settings or over-ride them?

Hmm … I am just thinking of the example that I am asked questions by translators into other languages about the use of Bilara etc. Perhaps in that context I want to check what translations exist in their language. So in that case, I would like that a search for `lang:ko` overrides my own setting, but just for this one search, and does not change it.

Does that make sense?

I mean, in principle I can always go to the repository and find it out there, and that's not difficult for someone used to look there.

**Comment by thesunshade** [comment]
> Does that make sense?

Perfect sense. My original proposal for `list all` is really not good because it requires the person who gets the link (if we are talking about sharing, which I think we should) to have the specific language (and _only_ that specific language) selected.

So how about this… Instead of taking `in:sn` as our model we take `list author` as the pattern. So to list all of the Korean texts we have `list ko`. Because that is explicitly what we are trying to do.

**Comment by thesunshade** [comment]
Bhante @sujato I have changed the original issue. What do you think about `list` + a language code. I 100% agree that `list all` is bad.

We could even have `list languages` to list all the language codes like we do with the authors.

**Comment by sujato** [comment]
Yeah, that sounds better, let's see if we can make that work.
