### ISSUE TITLE
ripple bounding bug for prev/next buttons

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3179]
In some cases, clicking the prev/next buttons at the bottom of a sutta creates, in addition to the ripple on the button, an unwanted ripple higher up on the page. 

![Screenshot from 2024-05-24 09-32-21](https://github.com/suttacentral/suttacentral/assets/6112010/07ed439e-5704-4178-9ba4-91e5bd49580c)

make sure the ripple is properly bounded so it appears only on the button itself.

**Comment by ihongda** [comment]
This bug has been fixed.
