### ISSUE TITLE
Coding for Publication date needs attention

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3183]
If I understand correctly, the publication date for a sutta is pulled from the footer data. I just noticed that in https://suttacentral.net/mn100/es/catalan-jose, this is the footer:

```
<footer>
<p>Traducido por <span class='author'>Pablo Catalán</span> y <span class='author'>Dhamma José</span> a partir de las siguientes fuentes:</p>
<p>Bhikkhu Ñanamoli y Bhikkhu Bodhi (<span class='publication-date'>1995</span>) “Sangarava Sutta: To Sangarava” en The Middle Length Discourses of the Buddha—A Translation of the Majjhima Nikaya . Boston, Wisdom Publications. Págs. 819–822.</p>
<p>La sección 39 está tomada de la traducción del MN 4 del mismo libro (sección 31).</p>
<p>Prepared for SuttaCentral by <span class='editor'>Bhikkhu Sujato</span>.</p>
</footer>
```

The date, 1995, that is marked with the `class='publication-date'` is actually the publication date of the source of the text that was translated, not the date of the Spanish translation.

I'm guessing this is not a one off.

I'm making this issue just so the problem is recorded some where. I'm not sure the extent of the problem. 

For the author, it appears to be the `meta` tag in the head that provides the actual author data:
```
<meta name='author' content='Pablo Catalán, Dhamma José'>
```

It seems odd that we are pulling publication data (publication date)  from a span class instead of from a meta tag.

I'm not sure how to best address this, and it may not even belong as an issue here.

**Comment by sujato** [comment]
>It seems odd that we are pulling publication data (publication date) from a span class instead of from a meta tag.

Yeah, that's just how it evolved, the metadata for legacy texts has always been very loose due to the variety of sources.

Anyway, in this case I have removed the existing publication date.
