### ISSUE TITLE
Paper-badge not updating at the right time

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#32]
Basically, the problem and the hack are described here:

https://github.com/PolymerElements/paper-badge/issues/66

I have not found another way to do it yet then to set a TimeOut on it. The problem is caused by the iron-resize-behaviour firing at the wrong time: it should fire when the entire page is loaded, not just the toolbar. So the badge appears 256 px too far to the right.

You will have to play around with the correct time for the setTimeOut. I have 1000 locally and that works OK.

**Comment by SamaneriVimala** [comment]
I think this one can be closed as the bug is fixed.
