### ISSUE TITLE
Segmented Bilara texts should always take priority over legacy texts in suttaplex

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3214]
As you can see here:

![Screenshot from 2024-07-12 16-47-37](https://github.com/user-attachments/assets/c9dd9eaa-e34a-4245-815d-313f2452620c)

The compact view of the suttaplexes for Mil displays the old Rhys Davids translation by default. However we have a new John Kelly aligned translation which you can see when expanding the suttaplex:

![Screenshot from 2024-07-12 16-48-32](https://github.com/user-attachments/assets/db604a3a-d418-4c72-8bae-abdb813cdef9)

The new translations should always take precedence. 

- display Bilara translations in compact view
- put them at the top of the list in expanded view

**Comment by thesunshade** [comment]
I'd go all the way and say that 130 year old translations should be removed once Bilara translations are available. I don't think SC needs to be a museum. The RD translations are available elsewhere.
