### ISSUE TITLE
In comments, THA Ap and THI Ap should be Tha Ap and Thi Ap

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3220]
Capitalization for `tha-ap` and `thi-ap` in the comments is incorrect.

![Screenshot from 2024-07-17 07-52-36](https://github.com/user-attachments/assets/43026f1c-0123-4e50-93dc-d1dd23001628)

It should be:

- `tha-ap` --> Tha Ap
- `thi-ap` --> Thi Ap

**Comment by ihongda** [comment]
Bhante, I have fixed this bug.
