### ISSUE TITLE
individual suttaplex display is broken for stub Vinaya rules

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3231]
There are some Vinaya rules for which we only have a stub, i.e. there is a title, a list of parallels, but no text. 

In such cases the display of the individual text suttaplex is broken.

Comapre Bi c 96, which is not a stub:

https://suttacentral.net/pli-tv-bi-vb-pc96?view=normal&lang=en

With Bi Pc 97, which is a stub:

https://suttacentral.net/pli-tv-bi-vb-pc97?view=normal&lang=en

We should display the same suttaplex as is found in the navigation.

**Comment by ihongda** [comment]
This problem have been fixed.
