### ISSUE TITLE
Final item of breadcrumbs should always be plain text

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3235]
Currently the final item of breadcrumbs is a link that does not go anywhere. Worse, on text pages, clicking it adds a `>` icon, while at the same time making the title on the toolbar disappear. 

The final item in breadcrumbs should always be plain text.

- no link
- no hover state, ripple, or click state
- no `>` added after on text pages
- nothing happens when you do anything!

**Comment by thesunshade** [comment]
~~It was suggested by someone at some point that clicking on the final item should take you to the suttaplex page for that sutta. I don't know if that's ideal or even a good idea. But logically the suttaplex page does kind of sit between an actual translation and the next higher level in the trail.~~

~~As it is, there is currently no way for the user to get a link to the individual suttaplex page for the sutta being viewed.~~

~~I'm not saying it should be that way, but I just wanted to point out what had been suggested in the past. I agree that the current situation is not good.~~

Never mind. I see you have already addressed this [here](https://discourse.suttacentral.net/t/make-a-rainbow-fall-at-our-feet-tell-us-about-our-mistakes-typos-and-other-oversights/29204/462) 

And it is indeed possible to get a link to the suttaplex this way:
![image](https://github.com/user-attachments/assets/9a7c060d-a5e6-4900-b092-7717de62477f)
