### ISSUE TITLE
where we have results of Pali words, link to DPD on web

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#3246]
Digital Pali Dictionary has rapidly outpaced any other Pali dictionary and should be the standard Pali dictionary for SC going forward. 

One way we can do this is by adding links to DPD in relevant places. 

I'm thinking two places:

- search results
- pali lookup

Maybe there's more?

But the basic idea would be simply to add something like:

```
<a href='https://dpdict.net/?q=dhamma'>**dhamma** in Digital Pali Dictionary</a>
```

**Comment by thesunshade** [comment]
Just a quick mockup Bhante @sujato …

So something like this for Pali lookup:

![image](https://github.com/user-attachments/assets/d7aa2f27-a1fa-482e-9bb9-410eda0ef5e6)

And this for search result:
![image](https://github.com/user-attachments/assets/0a370486-e792-476c-9c34-488084b9c6c9)

And maybe this for the dictionary results page:

![image](https://github.com/user-attachments/assets/37f7005d-9481-4923-8f3e-f3968f4c1f24)

**Comment by thesunshade** [comment]
Do we need to specify Digital Pali Dictionary _online_? Or is it enough for people to just see where it is they end up once they are there?

**Comment by sujato** [comment]
Yes, no need to specify "online". 

Those look good, except I wouldn't put it in the dictionary box on the search results page, it's too much. Just on the main dictionary result page is fine.

**Comment by ihongda** [comment]
Thanks @sujato @thesunshade 

![image](https://github.com/user-attachments/assets/4c84fa2b-a745-41ad-b8df-899c3f19842f)

I also made a prototype.
