### ISSUE TITLE
Keep ref id in url when switching to root or alternative translation.

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#3289]
#### User story
Pat is reading an aligned translation. They want to start reading in the root-only text. To go to the same place they have to remember the current segment number, select the root from parallels interface, search for the segment number. Doesn't have to be that hard.

Kelly is reading an aligned text in German. They want to check out the English translation. They have to go through the same process as Pat.

#### Feature description
With this feature, Pat and Kelly would be able to click on the segment number in the aligned text they were reading, go to the root text or a different translation and be taken automatically to the same segment on the page.

In the future when there is a literal/word by word aligned translation this will be even more useful.

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):
There would need to be some way for clicking on a link to the root or an alternate translation of the same text to remember the segment id in the url and then put it back there once on the new text. Or move to the new text by simply changing the language/author and not touch the rest of the url.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by thesunshade** [comment]
@sabbamitta or @khemarato, any thoughts on this?

**Comment by sabbamitta** [comment]
I second your proposal.

Although for the second user story, they can simply go to Dhammaregen or SC-Voice, where they can view three languages together in aligned texts. :slightly_smiling_face:
