### ISSUE TITLE
Add PTS 2nd images

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#700]
Right now text images are PTS 1st edition. It would be better to have PTS 2nd edition so this involves:

1. scanning and optimizing images
2. uploading images
3. changing js in frontend to show images

**Comment by thesunshade** [comment]
I'm going to go out on a limb and close this since I don't think SuttaCentral hosts *any* PTS scans any more.

Apologies, Bhante @sujato if I'm mistaken.
