### ISSUE TITLE
English translation Therigatha

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#707]
Ayya Kathrin will code Rhys-Davids translation of the Therigatha and also Thanissaro.
Files to be sent to her.

**Comment by SamaneriVimala** [comment]
Everything sent to Kathrin for coding today.

**Comment by SamaneriVimala** [comment]
Uploaded Davids translation.

**Comment by SamaneriVimala** [comment]
Thanissaro / Hecker/Khema also done.

**Comment by sujato** [comment]
Looks good.
