### ISSUE TITLE
Service worker loads "old" cache #2

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#763]
Updated 26/11/18: users are served stale version of the page if they have previously visited it.

---------------

Original ticket Creator:
krzysztof.wozniak

Not dependent on the browser

When the site is cached one on subsequent visits the user is being served with the old version.

Comments:
 
07/Mar/18 11:35 AM
krzysztof.wozniak
I rise again this bug because it looks like this problem still occurs on production environment.

**Comment by Bosmanfrx** [comment]
I suppose this bug will become deprecated with our upgrade to webpack. More info:
https://developers.google.com/web/tools/workbox/guides/precache-files/webpack
