### ISSUE TITLE
Infinite loop when searching if server responds with 500 error

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#765]
Original ticket Creator:
blake.walsh

How to reproduce (developer environment):* Make a search query, verify that the results return as expected.* Now stop the elasticsearch container with `make stop-elasticsearch`* Make a new search query, the site will show a spinner, but by going to the network tab of inspect it can be seen the browser keeps sending more requests, increasing the offset with each request, as if it is looking for more results.

*Expected Behaviour:*

When the server fails to respond, the client should display an error stating that the search could not be completed and to try again later.

Jira ID: SUCE-640
Jira Creation Date: 14/Mar/18 10:28 AM
Jira Epic: 
Jira Priority: High
Jira Status (at import): To Do

Comments:

**Comment by Aminah-SC** [comment]
Hi @blake-sc, is this still an issue or can it be closed?
