### ISSUE TITLE
Error on search page

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#766]
Original ticket Creator:
ayya.vimala

Search for 'mn12'
Then search for 'rat'
It tries to load the suttaplex for rat but cannot find it.

Jira ID: SUCE-658
Jira Creation Date: 23/Mar/18 3:14 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Screenshot from 2018-03-23 08-13-10.pnghttps://suttacentral.stxnext.pl/secure/attachment/11100/Screenshot+from+2018-03-23+08-13-10.png

Comments:

**Comment by Aminah-SC** [comment]
![2018-03-23t08-13-10](https://user-images.githubusercontent.com/36522678/37881911-f7709f98-3095-11e8-9833-72ef7e4836b6.jpg)
