### ISSUE TITLE
[iOS Safari old] - Tab switching don't work

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#767]
Original ticket Creator:
hubert.dworczynski

On older versions of mobile Safari (<6), the anchor tags (<a>) over the tabs are not positioned correctly, and consequently the user cannot switch between tabs.

Jira ID: SUCE-659
Jira Creation Date: 23/Mar/18 3:15 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by Bosmanfrx** [comment]
I think we shouldn't support browsers that are this old. According to this table: https://caniuse.com/usage-table
Safari market share is negligible. Pretty much no one uses these versions. In fact, Apple stopped shipping Xcode simulators with such old iOS version. Creating workarounds for older versions of browsers complicates the code and hinders development. It can also create hard-to-track bugs for users of new versions.

**Comment by Aminah-SC** [comment]
May be resolved with tab elements so leave for now.
