### ISSUE TITLE
(iOS) problem renedering homepage

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#769]
Original ticket Creator:
ayya.vimala

If I browse to the SC homepage (via entering the URL) the first time the page loads it leaves a large gap between #tabscontainer (the horizontal menu) and the following horizontal element. It’s approximately the height of my browser window (100vh). The gap is #FFF not the off white you have selected for the design.

Additionally, if I scroll the top section (everything above and including the horizontal menu) flickers. However, if I then refresh my browser window, the page loads as I believe it should be rendered with ‘The wisdom of the Buddha has been preserved in a vast ocean of ancient texts.’ sitting around 145px (on desktop) below the horizontal menu.

This occurs both on my desktop Safari 11.03 and on my older iOS version (10.3).

If it’s helpful I can reproduce it and capture things from the inspector. (Ven. Passana)

Jira ID: SUCE-657
Jira Creation Date: 21/Mar/18 11:14 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): In Progress

Comments:
 
23/Mar/18 11:56 AM;hubert.dworczynski;This sounds oddly similar to our MS Edge problems. Weird.

I downloaded a virtual device with iOS 10.3 and couldn't reproduce this. Could Ven. Passana maybe try if the issue occurs in incognito mode now?

The error report is in general very well written and detailed, but could he please also provide errors from the console (if there are any) and a screenshot of the network tab, if possible?

**Comment by Bosmanfrx** [comment]
Could not reproduce
