### ISSUE TITLE
Pali lookup not working in highlighted texts

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#770]
Original ticket Creator:
ayya.vimala

https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/173?u=vimala

Jira ID: SUCE-652
Jira Creation Date: 20/Mar/18 12:43 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Comments:
 
21/Mar/18 10:44 PM;ayya.vimala;This is a strange issue. Once the two sections (English & Pali) are put into the wrapper for highlighting, they loose their paper-tooltips. I cannot determine why.

**Comment by Bosmanfrx** [comment]
Could not reproduce
