### ISSUE TITLE
6.Numbering at some of menu levels

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#771]
Original ticket Creator:
malgorzata.maksimczyk

6.Numbering at some of menu levels (example: Samyutta)

The purpose of this is to cater for texts that organize their material in "dotted" numbers, i.e. other than straight increment. For example, SN 1.1, AN 4.45, and so on. In such cases it is useful to see the initial number in the menu.

Currently this is implemented in SN and AN, but missing elsewhere.* AC.7** Implementing numbering logic for Samyutta (add number in front of text: 1.) or other sub-menus chosen*** make just simple logic 1,2,3,4,5, etc. for defined levels:*** {color:#d04437}which levels need numbering: Sujato will provide {color}list{color:#d04437} {color}

Jira ID: SUCE-344
Jira Creation Date: 24/Nov/17 1:50 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): In Progress

Comments:
 
22/Dec/17 12:42 AM;sujato.bhikkhu;Here I will make a list of levels that need numbering. This is not comprehensive, I will add to it.
 -Samyutta Nikaya, per samyutta (done)-
 -Anguttara Nikaya, per nipata (done)-
 Udana, per vagga
 -Sutta Nipata, per vagga-
 Theragatha, Therigatha, per nipata.
 -Patisambhidamagga, per vagga-
 Milinda, per section and vagga. Unusually, this text uses a triple numbering system, i.e. 3.1.1, 3.1.2 … (second vagga) 3.2.1, 3.2.1 and so on.
 -Patna Dharmapada-
 -Gandhari Dharmapada-
 Udanavarga (vaggas should be in sidebar, as per Patna and Gandhari)
 Avadanasataka: *numbers should be removed*
 san-lo-bi-vb-nidana-vagga1: *number should be removed*
22/Jan/18 12:20 PM
malgorzata.maksimczyk
needs back end data update

**Comment by SamaneriVimala** [comment]
@sujato - I'm looking at this. It's a rather old ticket so I want to update a few things:

**Those that need numbering per vagga/nipata in the sidebar:**

- Udana, per vagga
- Sutta Nipata, per vagga - _Looks like this is already done._
- Theragatha, Therigatha, per nipata - _is this still needed when the vaggas are numbered? Same for Itivuttaka and Jataka?_
- Patisambhidamagga, per vagga- _Seems like this is already done._
- Milinda, per section and vagga. Unusually, this text uses a triple numbering system, i.e. 3.1.1, 3.1.2 … (second vagga) 3.2.1, 3.2.1 and so on.

**Numbers to remove:**
- Avadanasataka - _Are you sure this should not be per vagga like `1-10 Prathamo Vargah`, etc.?_
- san-lo-bi-vb-nidana-vagga1

**Subject to ticket re Dharmapadas.:**
- Patna Dharmapada-
- Gandhari Dharmapada-
- Udanavarga (vaggas should be in sidebar, as per Patna and Gandhari)

**Comment by SamaneriVimala** [comment]
With regards to numbering, in the Vinaya texts the menu sometimes lists numbers if not all rules are available, but this is not always consistent. Do we actually want this? F.i. san-sarv-bi-vb, there is only one SS rule and several PC rules, but only the PC rules have numbers in the sidebar and the SS rule doesn't.
What is the best way to deal with this? I think we might as well remove numbers from the sidebar for vinaya-rules.

**Comment by sujato** [comment]
>Theragatha, Therigatha, per nipata - is this still needed when the vaggas are numbered? Same for Itivuttaka and Jataka?

Itivuttaka and Jataka do *not* have nipata numbers. This is because they are referenced with a simple increment within the collection (eg Iti 1, Iti 2, Ja 56, Ja 57). Thag/thig are referenced by nipata + sutta (eg Thag 3.4, Thig 2.3) which is why they need the numbers at the nipata level.

>Avadanasataka - Are you sure this should not be per vagga like 1-10 Prathamo Vargah, etc.?

You're right, this can be left as-is.

>I think we might as well remove numbers from the sidebar for vinaya-rules.

I agree, we can remove numbers from sidebar for Vinaya rules.

**Comment by SamaneriVimala** [comment]
All done. Have a look if they are all OK now.
