### ISSUE TITLE
iPhone display of suttaplex not working properly

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#773]
Original ticket Creator:
ayya.vimala

See for details:
https://discourse.suttacentral.net/t/safari-should-be-working-now/8815/5?u=vimala

Jira ID: SUCE-650
Jira Creation Date: 20/Mar/18 1:58 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Comments:

**Comment by Bosmanfrx** [comment]
Will be deprecated with new suttaplex design
