### ISSUE TITLE
twitter/fb descriptions to show blurbs

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#775]
Original ticket Creator:
ayya.vimalaJira ID: SUCE-627
Jira Creation Date: 09/Mar/18 1:10 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Screenshot from 2018-03-12 13-15-33.png
https://suttacentral.stxnext.pl/secure/attachment/11012/Screenshot+from+2018-03-12+13-15-33.png
12/Mar/18 3:20 PM
krzysztof.wozniak
Screenshot from 2018-03-12 16-18-47.png
https://suttacentral.stxnext.pl/secure/attachment/11010/Screenshot+from+2018-03-12+16-18-47.png
12/Mar/18 3:20 PMkrzysztof.wozniak

Comments:
 
https://suttacentral.stxnext.pl/secure/attachment/11014/Screenshot+from+2018-03-13+15-05-59.png
14/Mar/18 4:21 PM
krzysztof.wozniak
Screenshot from 2018-03-14 17-19-16.png
https://suttacentral.stxnext.pl/secure/attachment/11018/Screenshot+from+2018-03-14+17-19-16.png
14/Mar/18 4:21 PM
krzysztof.wozniak
Screenshot from 2018-03-14 17-19-54.png
https://suttacentral.stxnext.pl/secure/attachment/11019/Screenshot+from+2018-03-14+17-19-54.png0|i001ho:o12/Mar/18 3:21 PM;krzysztof.wozniak;Seems like doesn't work as expected for:

[https://staging.suttacentral.net/dn1/en/sujato] 

 

!Screenshot from 2018-03-12 16-18-47.png|thumbnail!!Screenshot from 2018-03-12 16-19-03.png|thumbnail!
12/Mar/18 8:19 PM;ayya.vimala;This is weird. In the head of that same link on staging I have this:

 !Screenshot from 2018-03-12 13-15-33.png|thumbnail! 

So the descriptions are definately there. It also has the correct twitter & og titles.

But even weirder: when I click on View Page Source, it tells me the site is down! But the site just works!
On the main site there is not issue with that.
43172.5875
krzysztof.wozniak
!Screenshot from 2018-03-13 15-05-38.png|thumbnail! !Screenshot from 2018-03-13 15-05-59.png|thumbnail!
14/Mar/18 4:08 PM;ayya.vimala;Please try again [~krzysztof.wozniak]. If this doesn't work I have no more clues on what to do
:(
14/Mar/18 4:21 PM;krzysztof.wozniak;[~ayya.vimala] for URL: [https://staging.suttacentral.net/dn1/en/sujato] 

!Screenshot from 2018-03-14 17-19-54.png|thumbnail!!Screenshot from 2018-03-14 17-19-16.png|thumbnail!
43173.6902777778
ayya.vimala
I give up. I think the only way to do this is through python.

**Comment by SamaneriVimala** [comment]
Everything is now updated in the Frontend in index.html, including the title-element. BUT it will not show up in social media. So best to have this done in the backend.

**Comment by sujato** [comment]
Also note we have to make the discourse onebox work.

**Comment by Aminah-SC** [comment]
Hi @blake-sc, I'm not 100% sure if I imagined it :-/ but did you report this as completed a couple of meetings ago? Can the ticket be closed?

**Comment by SamaneriVimala** [comment]
This has been done.
