### ISSUE TITLE
PWA: Fallback to available cached resource if resource in page language not available

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#776]
Original ticket Creator:
hubert.dworczynski

*Problem:*

As a user, I want to use the site offline in one language (eg. Spanish), but have the UI in English. If I choose Spanish on the offline page, it'll download the sidebar menu and the suttaplexes in Spanish.

Later, when I go offline, and my main website language is English, the site will try to download the menu/suttaplexes in English and fail (because the UI is in English).
*Solution*

Modify the service worker code, so that it:   1. Parses every request URL and applies custom logic for the localized resources (menu and suttaplexes).   2. If a request from one of the two previously mentioned categories fails, use the Cache API to find the same cached URL in a different language (with English as highest priority).

*Expected Behaviour:*

If I cache the suttaplexes in Spanish, but my website UI is in English, after I go offline I should get the suttaplexes in Spanish (if English is not also cached).

Jira ID: SUCE-597
Jira Creation Date: 02/Mar/18 2:48 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Comments:

**Comment by Aminah-SC** [comment]
This us a UI issue
