### ISSUE TITLE
Error 0 when page content is not cached

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#781]
Original ticket Creator:
krzysztof.wozniak

*Steps to reproduce:*

* Go to [https://next.suttacentral.net/offline] 
* Cache page in Polish language (its faster to download)
* Go to the not caches sutta page

*Current behaviour:*

Error 0

*Expected behaviour:*

We should give more specific error information like "Connection error"

*Screenshot:*

![781](https://user-images.githubusercontent.com/36522678/49436644-80625480-f7b1-11e8-989a-f15d8fddbcc9.jpg)

**Comment by janlat** [comment]
Was fixed here: https://github.com/suttacentral/suttacentral/commit/ed1c03f32cf29dc8a6ff5613f5767ed2ed217394#diff-1ab099882a2a26365c0757807b669fd2R91
