### ISSUE TITLE
[iOS Safari] Backlight of the translation menu covers menu with share functionalities

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#784]
Original ticket Creator:
krzysztof.wozniak

Occurs on iOS Safari

*Steps to reproduce:*# Go to the sutta plex list# Click on the dropdown menu with translations# Next click on the Share functionalities icon

*Current behaviour:*

*Expected behaviour:*

Share functionalities menu should be over the backlight.

Jira ID: SUCE-603
Jira Creation Date: 05/Mar/18 3:59 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

IMG_0019.PNGhttps://suttacentral.stxnext.pl/secure/attachment/11002/IMG_0019.PNG

Comments:

**Comment by Bosmanfrx** [comment]
Will be deprecated with new suttaplex design
