### ISSUE TITLE
[iOS Safari] Parallel counter is out of box

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#786]
Original ticket Creator:
krzysztof.wozniak

Occurs on iOS Safari

*Steps to reproduce:*# Go to the random sutta view# Click to expander icon# Take a look on parallel counter on sutta view page

*Current behaviour:*

Parallel counter is out of box.

*Expected behaviour:*

Parallel counter should be inside the box.

Jira ID: SUCE-601
Jira Creation Date: 05/Mar/18 3:46 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

IMG_0020.PNGhttps://suttacentral.stxnext.pl/secure/attachment/11000/IMG_0020.PNG

Comments:

**Comment by Bosmanfrx** [comment]
Will be deprecated with new suttaplex design
