### ISSUE TITLE
Localization on sc-text not working

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#792]
Original ticket Creator:
ayya.vimala

`localization/elements/sc-text` is used in several different files.
For instance in sc-text-page-selector. But the localization does not work and the element returns null.

Jira ID: SUCE-576
Jira Creation Date: 25/Feb/18 11:19 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Comments:

**Comment by SamaneriVimala** [comment]
The only place where this is used and not working has to do with the description tag in the header of text files which is now set to default English only. 

But this is low priority. I cannot figure it out but it also does not matter very much, especially since it only deals with non-english description element in head, which will be overwritten any way by issue 775. This is something that me and Kuba both spent ages on, only to come to the conclusion that this is best done in the backend by Blake and not in the frontend by us. So now we only have it in the frontend and although it looks good when you do "inspect element", FB, twitter, discourse etc are not picking it up so it is basically useless.

So I would wait to see see when issue 775 is done if this is still an issue then. I'm pretty sure it's not.

**Comment by Aminah-SC** [comment]
Does #1031 have any bearing on this?

**Comment by SamaneriVimala** [comment]
No, #1031 is about the process to start having localization for the whole site.
This issue here has to do with a certain polymer element in the front end that is working everywhere except for some strange reason, not on that one page. However, it is not important because it is only used to generate meta-tags and not for any visible text and I think Blake might have found a way around that already. So keep it very low priority and I will have a look at it after 6 months or so to see if it is still necessary to solve this.
