### ISSUE TITLE
Numbering of zeroth level segments in vagga-length texts is wack

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#805]
Original ticket Creator:
sujato.bhikkhu

Our convention with numbering is that when we follow the existing paragraph or section numbers we subdivide them to make our segment numbers, so that eg. "section 1" becomes segment 1.1, segment 1.2, segment 1.3, etc.

In cases that fall outside this, especially when numbering the `<h1>` headings and associated stuff, we should use zeroth level, i.e. 0.1, 0.2, 0.3, etc.

However in the AN 1s and 2s, where we collect the suttas into vaggas, the zeroth level after the first on in the vagga is ignored. The heading numbers of the included suttas carry on from the previous sutta. Thus the heading for AN 1.4 is:

msgctxt "an1.1-10:3.1.4"
msgid "4"
msgstr "4"

Thus it is numbered as the fourth segment of paragraph one of AN 1.3. But it should be

msgctxt "an1.1-10:4.0.1"
msgid "4"
msgstr "4"

I.e. the first segment of the zeroth level of AN 1.4.

Jira ID: SUCE-562
Jira Creation Date: 19/Feb/18 9:50 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by SamaneriVimala** [comment]
This issue seems outdated ...
