### ISSUE TITLE
If site fails, offer redirect to old site

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#807]
link to #1197

Add Safari redirect if needed after testing re #1280.

Original ticket Creator:
sujato.bhikkhu

Despite our best intentions, it's likely that a small number of user agents will be bamboozled by the new site and fail to render. We shouldn't spend too much time catering for legacy systems and browsers. Rather, we should try to detect if the site fails, and offer a redirect to the old site at legacy.suttacentral.net.

**Comment by Aminah-SC** [comment]
Linked with #1197
