### ISSUE TITLE
3.Cache strategy with order keeping

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#821]
Original ticket Creator:
malgorzata.maksimczyk

 
*User story / Story Level*

As a user interested in offline functionality

I want to know to have the capability to choose certain collection/s to be cached in one chosen by me user language.

So that I can read them offline
*User story result will be developed after story 1, 2 & 3 ( SUCE-414, SUCE-437,  SUCE-438)*
*Acceptance Criteria* 
*Story 3: Cache strategy with order keeping*# AC.1.Implement caching model per user choice with following order:** stop default caching model when memory size will end up so a user can have cached sidebar menu from top till some moment (depending memory size limit)# AC.2.Sidebar menu:** Collection/s view chosen by user is displayed on top of key-value cached elements# AC.3.Sutta Plex:** All sutta plex view is displayed under chosen cached Collection (on top of key-value elements);
without parallels, unless displayed in step 1 /MVP epic (key values)# AC.4. Sutta View - download one sutta view in user language chosen** download default translation  - what is default:*** pick up segmented as a priority*** if more than one sutta marked as segmented, then pick up first one segmented,*** if no segmented then pick up first legacy text;
*Expected results* for *testing (story 3)*: end-stage caching model working - keeping order on sidebar menu and displaying correct content on sidebar menu, sutta plex and sutta view
*Technical subtasks (implementation details)*# Core task # AC test - as per testing approach agreed: https://suttacentral.stxnext.pl/browse/SUCE-97  or PWA capabilities per browser

Jira ID: SUCE-438
Jira Creation Date: 05/Jan/18 11:18 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Ticket Link (Cloners):

SUCE-414
Ticket Link (Relates):

Comments:

**Comment by SamaneriVimala** [comment]
What does this mean exactly?

**Comment by sujato** [comment]
Yes, it's a bit unclear. I would suggest delete it, then we can re-evaluate the PWA situation in a month or two, observing how it's used and how easy/hard it is to do stuff, then set out a new roadmap.
