### ISSUE TITLE
[Mobile] Search Box scale the hamburger to the tiny size

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#824]
Original ticket Creator:
krzysztof.wozniak

Occurs on mobile devices

*Steps to reproduce:*

Go to random page where lotus icon is visible (for example: [https://next.suttacentral.net/dn] )

Click on search icon in navigation bar

*Current behaviour:*

Search Box scale the hamburger to the tiny size

*Expected behaviour:*

Because search field covers icons on the right side (discourse, vert menu) my idea is to cover all icons in top navigator when search fields is expanded, including lotus and hamburger icons.

Jira ID: SUCE-529
Jira Creation Date: 07/Feb/18 1:58 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

Screenshot_20180207-134827.pnghttps://suttacentral.stxnext.pl/secure/attachment/10804/Screenshot_20180207-134827.png

Comments:

**Comment by sujato** [comment]
I can still see the lotus and forum icons.

**Comment by SamaneriVimala** [comment]
The lotus icon is there but it is not in tiny size but normal size once you open the search box. This is how it should be I think.
I cannot see the forum icon: on my Android that disappears when you open the search box. You have to close the search box to see the forum and other icons again.
