### ISSUE TITLE
[FireFox] Previous/Next navigation bar is not at the bottom of the page when text if short

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#825]
Original ticket Creator:
krzysztof.wozniak

Occurs on FireFox Nightly version

*Steps to reproduce:*

Go to Suttaview which contains short text inside (for example: [https://next.suttacentral.net/sn1.2/pl/gabryszewski] )

*Current behaviour:*

Previous/Next navigation bar starts where texts ends. In some cases this bar is in the middle of the page.

*Expected behaviour:*

Previous/Next navigation bar should be "glued" to the bottom of the page no matter how short text is it.

Screenshot:

![screenshot from 2018-02-07 11-46-26](https://user-images.githubusercontent.com/36522678/49727338-e5adbe00-fc67-11e8-88ef-92b3ee20bb34.png)

**Comment by sujato** [comment]
Note this bug still applies and is **not** limited to Firefox, but also occurs in Chrome.

https://staging.suttacentral.net/sn56.5/en/sujato
