### ISSUE TITLE
Images on static pages shouls be responsive

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#828]
Original ticket Creator:
krzysztof.wozniak

Occurs on each browser on low resolution.

*Steps to reproduce:*

Go to [https://next.suttacentral.net/introduction] 

Open page on mobile device (or resize browser window to the low resolution)

*Current behaviour:*

Images are not responsive. Horizontal scrollbar appears.
!Screenshot (1).png!
*Expeted behaviour:*

All images should be responsive.

Jira ID: SUCE-508
Jira Creation Date: 02/Feb/18 3:54 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

Screenshot (1).pnghttps://suttacentral.stxnext.pl/secure/attachment/10786/Screenshot+%281%29.png

Comments:

**Comment by SamaneriVimala** [comment]
Is this still valid? They seem to be responsive to me ...

**Comment by sujato** [comment]
Agreed, they look fine.
