### ISSUE TITLE
Toast notifications are not centered

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#834]
Original ticket Creator:
krzysztof.wozniak

Occurs on all devices and browsers.

*Steps to reproduce:*# Go to Dotations page and make successfull/unsuccessfull payment# Take a look on toast notification

*Current behaviour:*

Toast notification is not centered.

*Expected behaviour:*

Toast notification should be centered in content page (likewise settings popup on SuttaView, excluding side menu)

Currently toast notifications are on:* Donation* Vertical menu (Copy link, Copy table, Cite)

Have on mind that all available toast in each place in the application should be centered.

Jira ID: SUCE-267
Jira Creation Date: 20/Oct/17 1:35 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

Screenshot_100.png
https://suttacentral.stxnext.pl/secure/attachment/10719/Screenshot_100.png
16/Jan/18 11:36 AM
krzysztof.wozniak
Screenshot_101.png
https://suttacentral.stxnext.pl/secure/attachment/10718/Screenshot_101.png
20/Oct/17 1:33 PMkrzysztof.wozniak

Comments:
SUCE-274 

Impediment
0|i0001j:etzznx23/Oct/17 12:18 PM;sujato.bhikkhu;Yes, but this is an enhancement, not a breaking issue.
23/Oct/17 1:12 PM;krzysztof.wozniak;Confirmed on daily meeting, we can amend this in free time.
16/Jan/18 11:35 AM;krzysztof.wozniak;We should rethink one again this ticket because of possibility to hide left menu. At the moment all toasts are centered to the content page, excluding left menu.

 

!Screenshot_100.png|thumbnail! !Screenshot_101.png|thumbnail!

**Comment by Aminah-SC** [comment]
Toasts doesn't have to be centred.
