### ISSUE TITLE
Icon tooltips should not be displayed on touch screens

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#845]
Original ticket Creator:
krzysztof.wozniak

*Steps to reproduce:*
- got to any text page
- click on the the icons at the top of the page. 

(this concerns the three icons on the any text page). 

Notice: This refers to each tooltip which are implemented into icon (gear, information icon, expanders, search

*Current behaviour:*

After click there is properly action of element (for example expanded list of parallels) AND tooltip which appears only once, every next click does not turn on tooltip.

*Expected behaviour:*

We should have it so that long click displays the tooltips on touch screen and short clicks should perform the actions (as per material design: https://material.io/design/components/tooltips.html#placement).

**Comment by sujato** [comment]
Let's leave this for upgrade to MWC.
