### ISSUE TITLE
Expanding/collapsing subcategories in side menu

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#857]
Original ticket Creator:
krzysztof.wozniak

Seems to occur only on Firefox browser.

Verified on Chrome, Safari and mobile devices (Android/iOS)

*Steps to reproduce:*# Try to expand or collapse subcategories in side menu.

*Current behaviour:*

User is not able to expand or collapse subcategories. 

*Expected behaviour:*

User should be able to expand or collapse subcategories in side menu.

Jira ID: SUCE-212
Jira Creation Date: 29/Sep/17 1:46 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

Comments:
 
23/Oct/17 9:53 AM
malgorzata.maksimczyk
that bug the best should be fixed with sidebar menu implementation
23/Oct/17 12:20 PM;sujato.bhikkhu;This bug should be deleted, we will reimplement the sidebar anyway.

**Comment by Aminah-SC** [comment]
This seems to be an outdated issue; all appears to be working.
