### ISSUE TITLE
Ripple on the expander

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#864]
Original ticket Creator:
malgorzata.maksimczyk

Sujato finding:
"Okay, so one extremely critical bug remains. Well alright, maybe not _extremely_ critical. The ripple on the expander is z-indexed above the badge. But the expander sits _on_ the material, while the badge is on the layer above, so the ripple should be behind it."

connected with story SUCE-269

Jira ID: SUCE-287
Jira Creation Date: 30/Oct/17 3:02 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Bugs

Badge bug.pnghttps://suttacentral.stxnext.pl/secure/attachment/10338/Badge+bug.png

Comments:
30/Oct/17 3:02 PM malgorzata.maksimczyk
During Daily 30 October it was decided that we can leave this bug for later (future if time will allow) as fix will be hard to implement.

**Comment by sujato** [comment]
Close due to current non-existence.
