### ISSUE TITLE
[Blake] Rebuild PO files

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#871]
Original ticket Creator:
blake.walsh

Sujato has delivered a single 26mb text file containing all translations concatenated (for ease of search replace and such).* Break back down into individual po files based on msgctx* Place those new po files into proper directory structure* Split segments as indicated, creating new segments with new msgctx

Jira ID: SUCE-113
Jira Creation Date: 11/Sep/17 11:33 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by Aminah-SC** [comment]
Hi @blake-sc / @SamaneriVimala would I be right in thinking this issue can be closed now?
