### ISSUE TITLE
Make search view endless scroll use exact element height values instead of approximations

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#872]
Original ticket Creator:
hubert.dworczynski

sc-page-search.html currently uses the height of the first element as reference for search result item size, but elements can differ in height.

Fix/enhancement:

When a new element is added to the list, we should add its height to a variable and use that in shouldLoadMoreItems().

Jira ID: SUCE-139
Jira Creation Date: 14/Sep/17 10:52 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by Aminah-SC** [comment]
Does this belong as an issue under the #883 epic?

**Comment by SamaneriVimala** [comment]
No, the #883 is about the possibility to search more accurately and is a backend issue.
This here is a front-end issue to do with Polymer. Maybe we can leave it for Hubert :-)

**Comment by Aminah-SC** [comment]
Iron lists to be deprecated, so this issue is no longer relevant.
