### ISSUE TITLE
SUTTA PLEX LIST ENHANCEMENT - animations

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#876]
Original ticket Creator:
malgorzata.maksimczyk

*Need improvement**  Blurb showing animation is not displaying properly currently - defined at Sprint # 2 review
*When - Agreed with Sujato:** it is moved as future improvement after PWA functionality (to consider there);
*Why*

To fix that in Sprint # 3 would be time consuming Polymer element change (we decided to concentrate first on online and PWA functionalities)
*Additionaly consider:*

Ref. [https://discourse.suttacentral.net/t/next-2do-for-the-front-end/6060] 

The animation of the suttaplex when it expands is currently not perfect. It “lifts” and expands vertically. But in MD the motion should always be realistic, so _if_ it is to lift, it should expand horizontally too, and zoom slightly, like lifting a piece of paper. On the other hand, maybe it’s better to keep it simple and not have it lift at all, just expand vertically

Jira ID: SUCE-162
Jira Creation Date: 20/Sep/17 12:55 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by SamaneriVimala** [comment]
@sujato is this issue stil valid?

**Comment by sujato** [comment]
No, delete it.
