### ISSUE TITLE
eBOOK

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#878]
Original ticket Creator:
malgorzata.maksimczyk

eBOOK functionality implementation -  improvement identified during initial workshop ([https://docs.google.com/spreadsheets/d/1fitjwTdypc8K5vG5mp9XVLz7g-GH-r9BrqjSrmOaZhU/edit#gid=1553072797)] :

Jira ID: SUCE-179
Jira Creation Date: 22/Sep/17 1:21 PM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): To Do

Comments:

**Comment by Aminah-SC** [comment]
Supplanted by #960.
