### ISSUE TITLE
Incorrect display of carousel texts

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#882]
Original ticket Creator:
krzysztof.wozniak

Its possible to reproduce on Chrome while changing resolution or on Safari browser. Probably problem occurs also on other browsers.

*Steps to reproduce:*

Go to the home page and observe The Buddha's words. (mostly on Safari, on Chrome sometimes occurs while changing window size)

*Current behaviour:*

*Expected behaviour:*

Quotations should be displayed correctly in the carousel, at the middle.

*Screenshots:*

![882 1](https://user-images.githubusercontent.com/36522678/49436979-637a5100-f7b2-11e8-8fb6-597154ed0b20.jpg)

![882 2](https://user-images.githubusercontent.com/36522678/49436980-637a5100-f7b2-11e8-9a41-6bebfeb2a268.jpg)

*Comments:*

14/Jan/18 2:35 AM;sujato.bhikkhu;Can confirm, this widget is a little flaky; not it applies to the "Why we read" as well. However, it mostly works okay, so treat it as low priority. Not necessary before launch.
43138.5902777778
krzysztof.wozniak
Problem still occurs with higher frequency. It's visible on almost each browser.

**Comment by sujato** [comment]
This is still current:

https://discourse.suttacentral.net/t/please-report-any-errors-or-typos/9548/196

**Comment by sujato** [comment]
Seems to be fixed with the LitElement upgrade.
