### ISSUE TITLE
[FireFox&Safari] Tooltip from Pali lookup not always disappear

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#889]
Varrious bugs with Pali lookup on FF.

Original ticket Creator:
krzysztof.wozniak

Occurs on FireFox and Safari browsers

*Steps to reproduce:*# Go to the segmented text and turn on Pali lookup (for example: [http://localhost/dn1/en/sujato])# Move cursor through the text

*Current behaviour:*

Tooltip not always disappear. Sometimes we need to move again curon on selected work to make it disappear.

Sometimes tool tips does not appear at all. 

*Expected behaviour:*

Tooltip should hide when current word lose target.

Tooltips should appear on hover and disappear when current word lose target.

Jira ID: SUCE-384
Jira Creation Date: 12/Dec/17 10:25 AM
Jira Epic: 
Jira Priority: Lowest
Jira Status (at import): Bugs

2017_12_12_11_16_13_318.mp4https://suttacentral.stxnext.pl/secure/attachment/10510/2017_12_12_11_16_13_318.mp4

Comments:
 
Current Kanban Board

14/Jan/18 1:01 AM;sujato.bhikkhu;I can't reproduce this bug in FF, it seems fine to me. I will move this low priority, not necessary to fix before launch.

**Comment by sujato** [comment]
I'm closing this issue, assume that upgrade to MWC will fix.
