### ISSUE TITLE
Pali Speak text to speech tts for proper names

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#895]
Readers sometimes have no idea how to pronounce Pali/Sanskrit names. It would be nice to have a TTS widget that could be clicked to pronounce the name.

To do this, we'd need two things:

1. Markup in the text to identify Pali terms
2. Something to pronounce the words

The first one would be reasonably doable on the back end, Blake made something some years ago that would check the words in a text against the native dictionary for that language, and spit out a list of words not in the language. (This can also be used to add diacriticals, which is what we did at the time.) Then we can add `<i lang="pli">Pali<//i>` to the markup and we're good to go. If it could be done nicely on the fly in the front end, even better.

Okay, then as to pronouncing the words, we can use either human speech or machine TTS. As the list of proper names and technical terms is just a few thousand words, it's probably best to simply record them all. 

If we want to go the machine route, Yuttadhammo has made a nice Pali TTS app:

https://play.google.com/store/apps/details?id=org.sirimangalo.palispeak

This could be used to read Pali texts, or, usefully, to pronounce Pali/Sanskrit names.

**Comment by blake-sc** [comment]
With machine-speaking one thing is that you could do exaggerated pronunciation rather than attempting natural speech pronunciation - so literally just stringing together syllable sounds with a small gap in between rather than blending the transitions. For pali this would work well as a pronunciation guide.

**Comment by sujato** [comment]
Maybe, although I think natural speech is always best. But anyway, it'd be worth checking out Yuttadhammo's app, see what it does.

**Comment by sujato** [comment]
remove this, let Voice handle it.
