### ISSUE TITLE
Print CSS needs some tweaks

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#897]
We need some tweaks to the print CSS for text pages. 

Generally speaking we should aim for a minimal sane PDF output. It shouldn't be too fancy, and shouldn't rely on too many changes from the main styles. 

It should be tested on the different evergreen browsers. They all handle the output differently. It's not important that they be totally consistent, so long as it is reasonable in each case. Don't worry about old browsers/MS.

Things to look at:

- ensure top toolbar is display:none
- ensure background is white 100% and print is black 100%.
- Make all text black.
- remove (i), gear, and expander icons.
- prev/next links should not be printed.
- ensure page break is handled in a sane way without loss of text: When downloading or printing texts as PDF, the first lines of the second and subsequent pages are missing because the header overlays them. See for instance:
[https://app.zenhub.com/files/89286697/e22cbac2-fe95-4ae9-a474-24f85b7a2ee2/download](https://app.zenhub.com/files/89286697/e22cbac2-fe95-4ae9-a474-24f85b7a2ee2/download)

**Comment by thiago-silva** [comment]
Hi Bhante,

It seems a little buggy too. Some examples from the print dialog in chrome Version 65.0.3325.181 (Official Build) (64-bit) / MacOS Sierra 10.12.6.

The one below has "None" for "View original text with translation" settings.  The other two are set to "line by line".

<img width="568" alt="screen shot 2018-04-17 at 5 49 16 pm" src="https://user-images.githubusercontent.com/1530771/38896160-4fea2278-4268-11e8-9a95-77e3e526369a.png">

---

<img width="535" alt="screen shot 2018-04-17 at 5 56 42 pm" src="https://user-images.githubusercontent.com/1530771/38896454-2264d932-4269-11e8-9021-c7ab270c1494.png">

---


<img width="1052" alt="screen shot 2018-04-17 at 6 01 56 pm" src="https://user-images.githubusercontent.com/1530771/38896571-72504954-4269-11e8-928c-0e32fc663dbe.png">

**Comment by sujato** [comment]
Thanks, we'll bear this in mind when we get around to this bug.

**Comment by sujato** [comment]
Note these issues supplied by user Harsha. Some text is missing especially on page break.

[MN109_ The Longer Discourse on the Full-Moon night — Bhikkhu Sujato.pdf](https://github.com/suttacentral/suttacentral/files/1934116/MN109_.The.Longer.Discourse.on.the.Full-Moon.night.Bhikkhu.Sujato.pdf)
