### ISSUE TITLE
Check redirect links from old vinaya links.

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#899]
Following on from https://discourse.suttacentral.net/t/building-a-map/8951/13

The Vinaya links that mention pi-tv-… etc and not pli-tv- … appear to be broken

**Comment by SamaneriVimala** [comment]
I found the error with the links on that map: You use links to the old parallels-pages without the language code in there. The redirect only works for files that had a language code. I will change that.
