### ISSUE TITLE
Add parallels for Nakatani's 1987 Udanavarga de Subasi

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#902]
Following on from #890 

> Verses with other numbers: I have not used the numbers between brackets at all but the fat numbers at the end of each verse. So verse 232 would be `<a class="uvs" id="18.16"></a>`
The numbers between square brackets are "renvoient aux stances correspondantes dans l'Udiinavarga, édition Bernhard" so these are corresponding verses and are only of concern to me, who will take care of adding the parallels after these texts have been uploaded. (can you make a separate ticket for me for that, connected to this one?

**Comment by SamaneriVimala** [comment]
All done. Bhante @sujato, do you want me to put these things in your column or just close straight away?
