### ISSUE TITLE
Check new University of Oslo translations

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#904]
From: https://discourse.suttacentral.net/t/some-new-translations-for-sc/8551

>There’s also various interesting things at the U Oslo site. I haven’t checked it in a while, and there seem to be some new things.
>
>https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=23
>
>This appears to be the Sanskrit Dīrghāgama with a German translation:
>
>https://www2.hf.uio.no/polyglotta/index.php?page=volume&vid=4173
>
>The text is segmented, so is potentially a candidate for Pootle. But I haven’t investigated it closely. The licensing situation is a little vague, but it appears to allow reuse.
>
>The same site also has a large series of sections from the Mulasarvastivada Vinaya, but I don’t think there’s any translations.

**Comment by sujato** [comment]
I have checked the site, there doesn't appear to be anything useful for C at the moment. The DA text referred to above seems to be only a couple of lines.
