### ISSUE TITLE
Discuss & Discover mobile device CSS

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#905]
CSS of D&D MD Theme on mobile devices is very bad and renders it nearly unusable. Also the CSS for desktop needs some tweeks.

**Comment by Aminah-SC** [comment]
Bhante @sujato, can perhaps one of those desktop tweeks be to reduce the display width. I have to use [Too Wide](https://addons.mozilla.org/en-US/firefox/addon/too-wide/) Firefox add-on to protect my delicate little sense and have threads more centred than uncomfortably off to the left.

**Comment by SamaneriVimala** [comment]
Nearly a year ago now! I've deleted the MD theme and installed another simple accessibility theme with our color schemes. Maybe this issue can be scrapped ...
