### ISSUE TITLE
Table of contents for texts with internal heading structure

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#914]
## Discussion

Certain texts, especially the longer texts in DN, the Khandhakas, and similar places, have structured headings. In the legacy SC, we used to extract the `<hX>` tags and construct a ToC. You can see this if you go to https://legacy.suttacentral.net/pi/dn1, open the sidebar, and look under "Navigation". 

This is one of the few areas where there is an actual regression on the new site. This was not a choice, we simply didn't look at this issue. 

## New feature

1. Add ToC to all texts that have an internal `<hX>` structure.
2. Use the same structure, style, and markup as we currently use on certain static pages, eg. https://suttacentral.net/methodology 
3. Use just `<h2>`. (Don't add `<h3>` to `<h6>`)

#### Added value:

Improve navigation in long texts.

#### Acceptance criteria:

Check especially:

https://staging.suttacentral.net/dn16/en/sujato
https://staging.suttacentral.net/pli-tv-kd1/pli/ms 
https://staging.suttacentral.net/patthana1.2/pli/ms (this one has down to h6, check that they are not added.)

#### Performance criteria:

Creating ToC should not significantly impact page load.

#### Method of demonstrating completion:

Show ToC working on relevant pages.

#### Pre milestone planning check:
- [x] Small enough to completed in a milestone.
- [x] Dependencies marked
- [x] No external dependencies block the PBI from being completed.
- [x] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
This has been created and pushed live. However currenly the ToC is generated above the main sutta heading. It should appear immediately after the main sutta heading.

In other words, `<sc-nav-contents>` should appear after `<div class="hgroup">`.

**Comment by ihongda** [comment]
![Peek 2019-09-17 22-43](https://user-images.githubusercontent.com/4037966/65052148-af426380-d99c-11e9-8102-ff8d347f9a2d.gif)

**Comment by sujato** [comment]
This looks good but it is still not on staging @blake-sc @ihongda it is imperative that changes are made live on staging IMMEDIATELY. Fixes cannot be left to just rot.
