### ISSUE TITLE
In Home page epigraphs carousel, the ID of the sutta doesn't always match up with the text

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#916]
When you click on the button in the quotation carousel, it takes you to a suttaplex. That should be the suttaplex for the sutta from which the quote was taken. However, this is not always the case.

**Comment by SamaneriVimala** [comment]
I cannot recreate this locally.

**Comment by AlfredConlan** [comment]
Same here. I can see it happening on the live site, but the local seems to work fine.

**Comment by SamaneriVimala** [comment]
No, I can see it on the live site too. Sometimes it also gives a blank field but the button is working. It has to do with the blurb being one behind the button-text on slower systems. It is difficult to reproduce locally because there your system responds faster. So keep this.

**Comment by SamaneriVimala** [comment]
I think it works now ... On staging. Also does not give a blank field any more (at least for me) and has the correct uid.

**Comment by SamaneriVimala** [comment]
Although the epigraph uid now seems to point to the right place, the box is still empty on first load. So I'm taking this issue back to look at that.

**Comment by Aminah-SC** [comment]
In handover notes, Ven Vimila mentioned not having time to fix the caroussel bring empty when the page first loads, so the issue needs to be reassigned.

**Comment by sujato** [comment]
I cannot reproduce this any more, closing.
