### ISSUE TITLE
Add full text of Mills translation for snp

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#919]
In the old site, we didn't use the Mills translation for all of snp, as Anandajoti's is more reliable. But now we can, and should, add the full text.

Most of the Mills translation is there already, we just need to add the Parayanavagga. Here is the raw HTML which is to be adapted for SC.

[snp-chapter5-tobeaddedtoSC.zip](https://github.com/suttacentral/suttacentral/files/2883598/snp-chapter5-tobeaddedtoSC.zip)

**Comment by SamaneriVimala** [comment]
@sujato if you give me the text I can ask Ayya Kathrin to code this.
