### ISSUE TITLE
Add "0" badge for suttas that have no parallel

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#928]
In a couple of cases, people have asked how to find parallels on SC. We had thought this was pretty clear, as there is a badge displaying the numer on the suttaplex. However it turns out that in both such cases, the suttas they were referring to had no parallels. In the old site, you could see a column for parallels with an empty cell, so it was clear. Now there's nothing, and it seems this is tripping people up.

The obvious solution is to put a badge on every suttaplex that lacks parallels, displaying the number "0" and with the title attribute "This text has no recorded parallels."

**Comment by SamaneriVimala** [comment]
I have done this but left the dropdown arrow. Do you want that to be made invisible?

**Comment by sujato** [comment]
Oh, yes, the expander should not appear.

**Comment by SamaneriVimala** [comment]
I had some thoughts about that but not sure what to do. The badge has to be attached to the expander, otherwise it does not appear

**Comment by SamaneriVimala** [comment]
Done that. Just a little bit strange with the badge hanging in mid-air.

**Comment by sujato** [comment]
I've pulled it but can't see the badges. Maybe I have to do make-preview-env?
