### ISSUE TITLE
Sidebar navigation fix for segmented texts

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#935]
The Sidebar does not always represent the full text. This happens in several cases like AN3 (The Tatiyapannasaka finishes with the Mangala Vagga at AN 3.155. However the nipata continues to 352, all of which is included in the Tatiyapannasaka.) and also other places in AN and SN.

What needs to be done is:

* [ ] Check the entire menu and submenu in the sidebar to make sure that all suttas are represented
* [ ] Make changes in structure where needed

**Comment by sujato** [comment]
Another case noted [on Discourse](https://discourse.suttacentral.net/t/report-bugs-for-the-new-site-here-bug/8605/260)

**Comment by sujato** [comment]
There are still substantial issues with this .I am checking the version on staging. In the Ones, for example, see `an1-atthana`. 

- The titles of the suttas don't reflect the ID ranges. For example in `an1-nivaranappahanavagga` the range is 11-20 but the title (apparently randomly) says "12".
- In the Ones and Twos, the sutta numbers don't appear in the sidebar, unlike the Threes and above.

**Comment by SamaneriVimala** [comment]
First of all, please check staging in incognito.
I cannot see anything wrong with the sidebar menu and suttaplex card (it uses the right suttaplex UID). The titles are derived from your pootle files and are part of a different ticket (I know we talked about this several months back and we decided to wait funtil all the Pootle files are correctly uploaded). If there is no ticket for this, please make one but this is not the same as the sidebar.

> In the Ones and Twos, the sutta numbers don't appear in the sidebar, unlike the Threes and above.
No, in the Threes and above there are sub-sub-menus and the numbers appear there. The numbers don't appear in the sub-menu. But I can add that if you want.

**Comment by SamaneriVimala** [comment]
Now updated as discussed for AN1, AN2, SN49, SN50, SN53 so please have a look.

**Comment by sujato** [comment]
All looks good to me.
