### ISSUE TITLE
Error in display of parallel

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#940]
One parallel gets listed 100s of times:

https://discourse.suttacentral.net/t/buddhas-biography-in-the-discourse-to-prince-bodhi-parallels-and-translations/9187

**Comment by SamaneriVimala** [comment]
I've deleted this parallel but there are also others with ranges and at some point these will have to be looked at.

**Comment by sujato** [comment]
Should we make a ticket for that?

**Comment by SamaneriVimala** [comment]
Maybe, yes. But it might be good to do it after everything is uploaded and the menu done properly.
