### ISSUE TITLE
Correct numbering for certain AN texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#947]
A few of the abbreviated texts in AN need a little adjustment in their numbering. In some cases texts that are ranges are mistakenly identified as single suttas. They should be corrected as follows.

- an10.229 --> an10.229-232
- an10.233 --> an10.233-236
- an10.240 --> an10.240-266
- an10.267 --> an10.267-746
- an9.113 --> an9.113-432
- an8.148 --> an8.148-627
- an7.645 --> an 7.645-1124
- an6.170 --> an6.170-649
- an4.304 --> an4.304-783

And it's not just AN, so we should ad to this:

- sn12.93 --> sn12.93-213

**Comment by SamaneriVimala** [comment]
These are all done in the menu.

**Comment by SamaneriVimala** [comment]
- sn39.1 --> sn39.15

**Comment by sujato** [comment]
I think the first one in the list above should be:

- sn39.1 --> sn39.1-15

And the third:

- sn48.147 --> sn48.147-158

**Comment by SamaneriVimala** [comment]
Yes, you are right and I actually had that correct in the menu. The menu has been uploaded yesterday, also to Staging.

**Comment by SamaneriVimala** [comment]
an7.618 --> an7.618-644

**Comment by SamaneriVimala** [comment]
I cannot see the changes???
I still get the errors:
:root:Text uids do not match menu uids for (en): an4.304, an6.170, an7.618, an7.645, an8.148, an9.113, an10.229, an10.233, an10.240, an10.267, sn12.93, sn48.137, sn48.147, sn50.67
:root:Text uids do not match menu uids for (pli): an4.304, an6.170, an7.618, an7.645, an8.148, an9.113, an10.229, an10.233, an10.240, an10.267, sn12.93, sn48.137, sn48.147, sn50.67

**Comment by sujato** [comment]
They're correct in the menu/suttaplex, but the texts don't match up. I thought I had done this, but now I can't find any trace. @blake-sc , do you remember anything about this? Maybe I just dreamed it in a fever.

If you check say https://suttacentral.net/an10.229/en/sujato The text is there, with some bugs. But the numbering has not been adjusted in the files. It looks like we need to fix the numbering in the PO files for all these.

**Comment by SamaneriVimala** [comment]
We have adjusted the menu, but not the filenames of the texts itself in Pootle. When that is done, these will automatically propegate through. So it is just the filenames in Pootle that need updating.

**Comment by sujato** [comment]
Okay, well, do you want to do that or should I?

**Comment by sujato** [comment]
@blake-sc can you make the changes in these files?
