### ISSUE TITLE
Add search or dictionary term to page <title> so it appears in the tab

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#954]
Currently on search results pages, we just have the generic `<title>SuttaCentral — Search results</title>`. It would be better to make this more informative. 

`<title>Search: cat</title>`

Similarly, on the Dictionary pages we have: `<title>SuttaCentral — Dictionary results</title>`. Let's change this to.

`<title>Define: cat</title>`

Use "Define" rather than "definitions" or "dictionary" because it's shorter and thus more useful in tabs.

Currently on these pages the same field appears both in the `<title>` element and the toolbar title. This raises the question whether we should change them both so that they stay the same, or leave the toolbar as is. I don't think this is hugely important one way or the other. So whatever is easiest is fine.

**Comment by SamaneriVimala** [comment]
You were looking at the old version of the site. This changed with the last upgrade.
What we have is `SuttaCentral—Search results for cat` and `SuttaCentral—Pali Dictionary results for cat`
(apart from the fact that cats don't appear in the pali dictionary but you get the idea)
Does that need changing to the shorter form you have above?

**Comment by sujato** [comment]
Yes, use the short form. Curently in a browser tab you can basically only see "SuttaCentral—sear…". The point is to make these more informative for a user who has multiple tabs open.

**Comment by SamaneriVimala** [comment]
Done.
