### ISSUE TITLE
Provide UI for EPUBs on Downloads page

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#960]
Update taken from [SuttaCentral Upgrade Roadmap 2018: Polymer 3+](https://github.com/suttacentral/suttacentral/issues/1091):

## EPUB download UI

The UI should be a simple list of links on the Downloads page. It should be the first item on the page. 

Show a date when last updated. This is useful because it lets the user know if they have the latest version or not. So it should only be updated if there is an actual change in the files. I am not sure, however, if this information is available to the front end. If not, then just omit it for now, and we'll add at a later time.

```
<h2>Download EPUBs</h2>
<p>The latest version of key translations on SuttaCentral.</p>
<ul>
<li><a><cite class="text-translated">Long Discourses</cite> (<cite class="text-root">Dīgha Nikāya</cite>), <span class="author">Bhikkhu Sujato</span></a> <span class="update-date">Updated [[date]]</span></li>
<li><a><cite class="text-translated">Middle Discourses</cite> (<cite class="text-root">Majjhima Nikāya</cite>), <span class="author">Bhikkhu Sujato</span></a> <span class="update-date">Updated [[date]]</span></li>
<li><a><cite class="text-translated">Linked Discourses</cite> (<cite class="text-root">Saṁyutta Nikāya</cite>), <span class="author">Bhikkhu Sujato</span></a> <span class="update-date">Updated [[date]]</span></li>
<li><a><cite class="text-translated">Numbered Discourses</cite> (<cite class="text-root">Aṅguttara Nikāya</cite>), <span class="author">Bhikkhu Sujato</span></a> <span class="update-date">Updated [[date]]</span></li>
<li><a><cite class="text-translated">Verses of the Senior Monks</cite> (<cite class="text-root">Theragāthā</cite>), <span class="author">Bhikkhu Sujato</span></a> <span class="update-date">Updated [[date]]</span></li>
<li><a><cite class="text-translated">Verses of the Senior Nuns</cite> (<cite class="text-root">Therīgāthā</cite>), <span class="author">Bhikkhu Sujato</span></a></li>
</ul>
```

## Acceptance criteria

- Correctly generate HTML on Downloads page.
- Links for each item download the EPUB for the correct text.
- Use full names for translator, original language title, and translated title.
- Texts update from the latest version on Git.
- The above list is automatically updated from the appropriate Git repo: @blake-sc to advise.
- Show the latest update when changes were made. If there are no changes, leave the old date. (If this data is not available, omit this for now.)

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by olastor** [comment]
Hello,
Have you considered using [pandoc](https://pandoc.org/)? It's is pretty good at converting HTML to LaTeX or PDF. I've made myself a pdf of the whole german SN using a quickly written [helper script](https://gist.github.com/olastor/ad6d15dd721fd0c931997520e20d387a) for merging the concerning html files from sc-data into one html file and then ran

``
pandoc -o sn_de.pdf --pdf-engine=xelatex --toc book.html
``

It gave some font warnings, but I think most of the output looks fine:
[sn_de.pdf](https://github.com/suttacentral/suttacentral/files/2612570/sn_de.pdf)

For converting to pdf, it requires all the necessary latex packages installed. For only converting to latex, you can change it to something like `pandoc -o sn_de.text -t latex --toc book.html`

Don't know how far you are with creating latex files, but maybe this helps.

**Comment by sujato** [comment]
Thanks Olaster. We haven't used pandoc yet, as it is a general tool and we don't know if it's necessary for our very specific use case. It's generally speaking not to hard to transform HTML to LaTeX, so long as you know exactly what to expect. We can tell it directly how to handle some non-standard things like verse formats. 

You can see here a recent test of producing the DN as a single PDF file via LaTeX. Plenty of rough edges still, but on the whole it works okay.


[dntest1.pdf](https://github.com/suttacentral/suttacentral/files/2617898/dntest1.pdf)

**Comment by sujato** [comment]
The publication date has been deferred, as we should introduce proper version numbering. Apart from that this issue is complete.
