### ISSUE TITLE
Titles of AN texts display incorrectly

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#967]
AN texts in English often only show numbers or ranges of numbers but the system gets confused if there is more than one H1 tag in there.

* [x] Make sure only the first h1 tag is used

* [x] If there are only numbers, let it use the root text

**Comment by sujato** [comment]
I don't really know how to test this, I need specific IDs to check.

**Comment by SamaneriVimala** [comment]
It was what we discussed last week. The AN texts often showed just numbers in the suttaplex. Now it shows the root title instead if there are only numbers.

**Comment by SamaneriVimala** [comment]
This works for me locally, but not on staging. I've asked Blake why.
You have to do `make run-preview-env` to see it because it has to reload the database and recalculate the titles.

**Comment by sujato** [comment]
It's still inconsistent, sometimes it uses numbers, sometimes vagga titles in the Ones.

**Comment by SamaneriVimala** [comment]
Something seems to have changed. I'm taking this ticket back to have a look at it.

**Comment by SamaneriVimala** [comment]
Something changed in the last pootle update in that a hidden character has appeared in the title. I've filtered that out now so after reload that should be fine.
