### ISSUE TITLE
Bhikkhu and Bhikkhuni Parivara parallels

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#975]
Somehow make sure the parallels look halfway decent rather than just the uid.

**Comment by sujato** [comment]
They still have just the uid. This should be expanded to the full name, eg. #pj1 --> Pārājika 1

**Comment by SamaneriVimala** [comment]
It won't be expanded but it is hardcoded in the parallels.json file. I can do a regex to change all the codes to their full word.

**Comment by SamaneriVimala** [comment]
Done now
