### ISSUE TITLE
Replace "immersion" with "samādhi" in Pali texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#976]
At some point the translation "immersion" has gotten into 29 segments of the Pali text. Ouch! We need to remove immersion and replace with samādhi in the PO files.

**Comment by blake-sc** [comment]
This is fixed on production now

**Comment by sujato** [comment]
It's still in Pootle:

https://pootle.suttacentral.net/en/translate/#search=immersion&sfields=source

**Comment by Aminah-SC** [comment]
Hi @blake-sc / @sujato, I think I've seen 'samādhi' when reading some suttas recently, can this issue be closed now?

**Comment by sujato** [comment]
No, I'm still seeing it in Pootle.

**Comment by Aminah-SC** [comment]
Yeah, whoops, sorry! I had seen 'samādhi' (eg. an11.12), trouble is I was only scanning, so didn't see that it's used in 'immersed in samādhi' and that 'immersion' is also used separately.
