### ISSUE TITLE
Improve handling of reference numbers

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#996]
## General principles

We must be clear, consistent, and reliable in how we handle alternate numbering systems, to avoid confusion and complication for users and ourselves.

We maintain multiple overlapping hierarchies in our system, but this is mainly for the purpose of backwards compatibility. The Mahasangiti edition, for example, includes several sets of references. We have added others. But as far as what is used by us and presented to users, we should try to use as few sets of numbers as possible.

**Only display references when it is of benefit to users.**

An example of a case where keeping multiple systems is useful for a user this would be the Sutta Nipāta, where texts are commonly referenced both by verse number and by sutta number.

## Inherited numbering and "first class" numbering

"Inherited" numbers are the referencing systems that SC has inherited from our sources. 

- **Pali**: These include the references found in the Pali Text Society edition (`pts`), those from the Mahasangiti edition, etc, and in the case of the majjhima Nikaya, the Nyanamoli numbers.
-  **Sanskrit** and **Tibetan**: Different numbering systems for each edition.
- **Chinese**: the Taisho numbering.

We select one of these numbering systems and use as the "first class" numbers on SuttaCentral. Currently this is not done elegantly, and the purpose of this epic is to improve this system.

**Clearly define and consistently implement "first class" numbers.** #1055

## Current behavior

Currently we display both `sc` numbers and either `pts-cs` or `nya` numbers when viewing these texts. 

The meaning of the `sc` numbers is confused. In the unsegmented view, they are the Mahasangiti paragraph numbers. But in the segmented view, the `sc` numbers suddenly change and stand for the legacy `pts` or `nya` numbers. This is very bad! It must be changed.

**Make sure segment views on DN, MN, and Vinaya are labelled `pts-cs` and `nya`, not `sc`.**

There is also a bug where multiple sets of reference may have unprefixed IDs. 

**Ensure only first class references have unprefixed IDs.**

**Comment by SamaneriVimala** [comment]
The parallels references are to the SC numbers only. So when you click on a parallel, it highlights that section of sc-numbers.

**Comment by sujato** [comment]
Oh I know, we've discussed this in the past. The parallels should be changed to use the first class numbers.

**Comment by SamaneriVimala** [comment]
That's a lot of work!

**Comment by sujato** [comment]
I know, right! I don't say it lightly, but it has to be done. Otherwise we end up maintaining two systems forever, and it just doesn't make sense. I'm hoping that when we have time, we can look at it carefully and figure out a way to programmatically switch from one set of numbers to the other. 

In DN and MN, a quick check shows around 756 items that match the regex `dn|mn\d+#\d`. So it's a lot, but not an impossible amount, even if we end up having to check the entries by hand.

**Comment by SamaneriVimala** [comment]
I see your point but let's leave this until after the vassa. I would rather hardcode the correct parallel-numbers rather than having the system having to figure out if one reference is to an old SC number or to a new pts-cs number: that is bound to start creating problems. The parallels.json file has to be consistent and best to have the whole file consistent with the actual numbers rather than use the old system in the parallels.json file and than programmically convert numbers to the new system in the frontend.

The MN and DN will be less problematic than the AN and SN. Due to various trials in the last few months, there are errors in the parallels.json file and I still have to go over references for AN and SN to weed them out.

**Comment by sujato** [comment]
Close this epic, future development of references is in bilara-data.
